### PR TITLE
FRONTEND WITH FRAMEWORK: Angular -> How to Create a Component using Angular CLI?

### PR DESCRIPTION
**Pull request by RIYANSHGARG**
<hr>

## Description 📜

I have Written about Angular Components, how to create component using Angular CLI and files that get created by it.
Fixes # <531> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>
Screenshot (100)

### CODE REVIEW

**Review by anandhu720 — APPROVED** [review]

**Review by mukeshmjn — APPROVED** [review]
Very Well Explained @RIYANSHGARG .Good Job mate!

**Comment by RIYANSHGARG** [comment]
Hey! can you please add GWOC21 label also ?

**Comment by anandhu720** [comment]
@RIYANSHGARG this pr is already merged bro,also labels are just for find pr faster.I don't think it is nessecery.

**Comment by mukeshmjn** [comment]
Added @RIYANSHGARG  :) ..No worries, @anandhu720 its fine!

**Pull request merged**
