### PR TITLE
ML 3.2: k-means Clustering (A)

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜
k means clustering algo, Steps
Elbow method
Disadavantages
Applications
Fixes # <4109> 

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
Audio content:
k means clustering algo, Steps
Elbow method
Disadavantages
Applications

@abhisheks008 , @geeythree please review on this

**Review by geeythree — CHANGES_REQUESTED** [review]
Few points are not clear : 

- [ ] Steps in k-means algorithm
- [ ] Elbow method (its used for determining the number of clusters)
- [ ] Steps in elbow method and why its useful in k-means
- [ ] Elaborate Outliers 

These are few good resources for your reference :
- https://www.youtube.com/watch?v=4b5d3muPQmA
- https://www.youtube.com/watch?v=QXOkPvFM6NU

If you need any help, kindly let us know

**Comment by ron352** [comment]
@geeythree  please check it now :D

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@ron352 everything looks fine enough. Just a small change in the file name is required, as the prefix of the file name will be, `ML_3_2_....`

**Comment by ron352** [comment]
Renamed.

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
Merged @ron352 🎉

**Pull request merged**
