### PR TITLE
Front end: CSS Button styling

### LINKED ISSUE #252: Front-end : CSS Button Styling

### PR DESCRIPTION
**Pull request by KhafiaAyyub**
<hr>

## Description 📜
Documentation of CSS button styling. Explained CSS property such as color, padding, transitions, border etc with examples.
Fixes #252  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by KhafiaAyyub** [comment]
Hey @ghulamyazdani  , you are requested to review and let me know if any changes needed.

**Comment by ghulamyazdani** [comment]
Hey @KhafiaAyyub you have to make a separate folder for your particular topic and put your markdown and content in that file only.

**Comment by KhafiaAyyub** [comment]
@ghulamyazdani  Please check ,done with the changes .

**Comment by ghulamyazdani** [comment]
LGTM 🥳 
Your work is commendable!

**Pull request merged**
