### PR TITLE
Data Science with Python: Hyperparameter Tuning #372

### PR DESCRIPTION
**Pull request by imedusa**
<hr>

## Description 📜

I have made the folder containing the importance of different hyperparameters in neural networks, how to monitor them, and tune them. The .ipynb notebook contains a demo for the user to run the model and compare the results. I have also added additional resources relating to hyperparameter tuning. 

Fixes : #372

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by imedusa** [comment]
@prathimacode-hub please take a look at my PR, thank you.

**Comment by DhruvBajaj01** [comment]
The files are under the process of reviewing.

**Comment by imedusa** [comment]
@DhruvBajaj01 noted, thank you.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The issue contribution should be under "/Machine Learning/Tutorials/Hyperparameter Tuning
The project file name should be in snake case : hyperparameter_tuning.ipynb
In README.md, it needs more information. Add what hyperparameter tuning is, how it's derived, how it works, features, advantages and usage of it, applications, conclusion. Instead of just adding screenshots, you can explain each screenshot of what it does.
Add short intro in your .iynb file before you get into code implementation and what's the final outcome you go from your issue at the end.
Add up the respective datasets used in "DS Datasets" in "Machine Learning" folder and resources referred in "DS Resources" in "Machine Learning" folder

Kindly work on it. @Sakalya100

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. your way of explaining things is fab. Amazing work put up. Kudos to your start. ✨👏@imedusa

**Comment by imedusa** [comment]
Thanks a lot @prathimacode-hub ma'am!😄

**Review by DhruvBajaj01 — COMMENTED** [review]
Reviewed! Great work

**Review by DhruvBajaj01 — COMMENTED** [review]
Great work!

**Pull request merged**
