### PR TITLE
Algorithms and Flowcharts In C Programming Language

### LINKED ISSUE #2339: Algorithms and Flowcharts In C Programming Language
### Description

- What is an Algorithm?
- Characteristics of an Algorithm?
- How to design an Algorithm?
- What is a Flowchart?
- What is DFD(Data Flow Diagram)?
- Some examples of Flowcharts

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜
I have prepared a documentation on:

Algorithms and Flowcharts In C Programming Language

- [x] What is an Algorithm?
- [x] Characteristics of an Algorithm?
- [x] How to design an Algorithm?
- [x] What is a Flowchart?
- [x] What is DFD(Data Flow Diagram)?
- [x] Some examples of Flowcharts

Hope you learn and applyyy! 💯 

Fixes #2339

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by vasu-1 — APPROVED** [review]
Good @ikavyajain 
@Suvraneel Please review and merge this PR :))

**Comment by Suvraneel** [comment]
image
@ikavyajain

**Comment by ikavyajain** [comment]
These were simple algorithm steps Sir, and flowchart image was downloaded
because in md file I wouldn’t have made the flowchart. It was just to refer

**Comment by Suvraneel** [comment]
> These were simple algorithm steps Sir, and flowchart image was downloaded because in md file I wouldn’t have made the flowchart. It was just to refer

The text is all ............

I havent even compared the flowchart image

**Comment by ikavyajain** [comment]
Okay will work on this too

**Pull request closed without merging**
