### PR TITLE
C_CPP : CSS Animation in document

### PR DESCRIPTION
**Pull request by Pranshu321**
<hr>

## Description 📜

In this, I deeply explain about the animation what is the different properties of the animation which are important for implementing animation.
Issue Number Closed : #7328

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
Add some videos to show the output animation.

**Comment by kashishahuja2002** [comment]
> Add some videos to show the output animation.

Update as per the requested changes or close the PR please.

**Comment by Pranshu321** [comment]
> Add some videos to show the output animation.

how I add animations, I am not able to figure it out.

**Comment by kashishahuja2002** [comment]
> how I add animations, I am not able to figure it out.

Just record a video while showing the output.

**Comment by Pranshu321** [comment]
@kashishahuja2002  mam I figure out that it is already merged. So I am closing this, I apologized for my mistake.

**Pull request closed without merging**
