### PR TITLE
Create Opensource 5.40: Explain everything related to KEDA

### LINKED ISSUE #676: OpenSource : 5.40 Explain everything related to `KEDA`
### Description :

- **Explain everything related to `KEDA`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by PrachiDoshi2170**
This documentation consist of the basic of KEDA

<hr>

## Description 📜

Added the document for the PR review. Please also include relevant motivation and context. 
Fixes #676 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [x] Open Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Please rename the file to `5.40_Explain_everything_related_to_KEDA.md ` and also please add reference links in the bottom of this file.

**Comment by PrachiDoshi2170** [comment]
After I add the changes should I create a new branch and add a pull request
or should I just commit the changes to the same branch

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Update your fork repo @PrachiDoshi2170   and put your doc under `CNCF_projects`

**Comment by Aryamanz29** [comment]
> After I add the changes should I create a new branch and add a pull request or should I just commit the changes to the same 

You don't need to create PR for new changes, Just add commits and push to that same branch

**Comment by PrachiDoshi2170** [comment]
> Update your fork repo @PrachiDoshi2170 and put your doc under `CNCF_projects`

How do I do that, should I directly create a new file under the folder CNCF projects and add the pull request there?

**Comment by PrachiDoshi2170** [comment]
> Update your fork repo @PrachiDoshi2170 and put your doc under `CNCF_projects`

How do I do that, should I directly create a new file under the folder CNCF projects and add the pull request there?

**Comment by Aryamanz29** [comment]
> > Update your fork repo @PrachiDoshi2170 and put your doc under `CNCF_projects`
> 
> How do I do that, should I directly create a new file under the folder CNCF projects and add the pull request there?

Hmm, Just create a new PR after updating your repo & put your doc under `CNCF_projects` with the name `5.40_KEDA.md`

**Comment by PrachiDoshi2170** [comment]
Done

**Review by Aryamanz29 — APPROVED** [review]
- I have updated you fork and resolved conflicts
LGTM Now @PrachiDoshi2170 
Thanks for contributing 🎉🎉

**Pull request merged**
