### PR TITLE
Python: 3.1 What is type conversion?

### LINKED ISSUE #340: Python: 3.1 What is type conversion?
### Description :
What is type conversion in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by priyanshuc4423**
<hr>

## Description 📜
Python: 3.1 What is type conversion? explained different type of type conversion and gave examples for it b
Fixes #340 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by priyanshuc4423** [comment]
@adityabisoi  please have a look

**Comment by adityabisoi** [comment]
Include index in `Python/README`

**Comment by priyanshuc4423** [comment]
> Include index in `Python/README`

Done

**Comment by adityabisoi** [comment]
Two points are appearing on the same line in README. Double-check your code before pushing.

**Comment by priyanshuc4423** [comment]
Done

> Two points are appearing on the same line in README. Double-check your code before pushing.

done

**Comment by priyanshuc4423** [comment]
> Two points are appearing on the same line in README. Double-check your code before pushing.

Done

**Pull request merged**
