### PR TITLE
Python: Loops- while loop

### LINKED ISSUE #557: Python: Loops- while loop
### Description :
What is `while` loop in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by naveeramesh**
<hr>

## Description 📜

I had fixed the issue for while loop in python 
Fixes #557 

<hr>

## Type of change 📝
- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊
- [x] Python
<hr>

## Checklist ✅
- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by kalyanirb12** [comment]
I would like to contribute through documentation.

**Comment by naveeramesh** [comment]
@kumarankm can you validate my pr

**Comment by kumarankm** [comment]
> @kumarankm can you validate my pr

@ankurg132 is a mentor for you

**Review by ankurg132 — APPROVED** [review]
Looks good to me, the Readme has a merge conflict that the supervisors can look upon

**Comment by SouravKr2001** [comment]
Plz assign it to me

**Comment by ankurg132** [comment]
Hey @SouravKr2001 , the issue related to this PR is open for video contributions, you can comment if you're interested for that at #557. Also @naveeramesh can you also resolve the merge conflicts so that the supervisors can merge this one.

**Comment by naveeramesh** [comment]
> Hey @SouravKr2001 , the issue related to this PR is open for video contributions, you can comment if you're interested for that at #557. Also @naveeramesh can you also resolve the merge conflicts so that the supervisors can merge this one.

resolved @ankurg132

**Comment by ankurg132** [comment]
Looks good, @adityabisoi you can merge this one!

**Pull request merged**
