### PR TITLE
Data Science with Python : An Introduction to Scientific Python

### LINKED ISSUE #1837: Data Science with Python : An Introduction to Scientific Python
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about An Introduction to Scientific Python. Tutorial to An Introduction to Scientific Python and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Programming

Mentors Assigned : Aishani Singh / Peehu Saxena

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜
I have added one readme file about brief introduction Scientific python, features , applications, environment and one ipnyb file about multiple algorithm code
Fixes #1837

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
Tasks I have done:

**1.  Readme files :** 
Contents: 
Introduction
Features
Environment Setup
SciPy Subpackages
Topics covered in ipnyb file
Applications
Resources
Conclusion

**2. Ipnyb file: code snippet and snapshot with explanation:**

Please check and let me know if any changes needed 👍 

@prathimacode-hub 
@aishani_singh
@peehu saxena

**Comment by PeehuSaxena** [comment]
Looks great to me ...

**Comment by ron352** [comment]
@PeehuSaxena Thanks! When it will be merged?

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Fab work. Great going. 🙌👌@ron352

**Comment by ron352** [comment]
Thanks @prathimacode-hub

**Pull request merged**
