### PR TITLE
Python: What are Errors and its types

### LINKED ISSUE #713: Python:What are errors and its types?
**Description:**
Explain What are Errors in Python and its types ?
@
**Note :**
Changes should be made inside the Python/ directory & Python branch.
Issue only for GWOC'21 contributors.
Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.
In the PR, keep this issue's title as your PR's title.

Must follow: Contributing  Guidelines  and Code of Conduct

### PR DESCRIPTION
**Pull request by shaurya24sri**
<hr>

## Description 📜
Python What are Error and its Types

Fixes #713

<hr>

## Type of change 📝

- [ ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Python

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by shaurya24sri** [comment]
@Randrita .Please Review my PR

**Review by Randrita — CHANGES_REQUESTED** [review]
@shaurya24sri can you please add the reference of that table? also if you want you can add one line about try and except block.

**Comment by shaurya24sri** [comment]
@ Randrita Reference of the table  means?. Can you explain a bit more
Like I have created the table on my own so there is no reference that I can provide.

**Review by Randrita — APPROVED** [review]
looks okay @adityabisoi can be merged!

**Pull request merged**
