### PR TITLE
tollbooth_in_cpp

### LINKED ISSUE #7961: [Create New Issue]: tollbooth program
### Description

tollbooth program in cpp

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Sharayu1071**
tollbooth management project in C++.

<hr>

## Description 📜

this program helps to manage tollbooths.
Fixes #7961 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Do add i/p and o/p at last and also update the respective md files with their directories.

**Comment by Sharayu1071** [comment]
Okay

**Comment by Sharayu1071** [comment]
Hey @deeqakkk , I have added an output image with i/p at last but  I'm unable to find the proper directory for this. cause this PR comes under the minor management project in CPP. can you plz suggest in which directory this PR comes under?

**Review by apeksha235 — COMMENTED** [review]
@Sharayu1071 Add this file under Competitive programming directory for now

**Comment by Sharayu1071** [comment]
Okay

**Comment by Sharayu1071** [comment]
hey @apeksha235 & @deeqakkk , now it is correct or not?

**Comment by Suvraneel** [comment]
@Sharayu1071  LGTM ❤️  Nice work
Btw we've moved all projects to a new separate directory
So, this is where your contribution resides :
https://github.com/girlscript/winter-of-contributing/tree/C_CPP/C_CPP/Projects%20in%20C_C%2B%2B

**Comment by Sharayu1071** [comment]
Okay

**Pull request merged**
