### PR TITLE
What is python interpreter

### LINKED ISSUE #79: Python: 1.7 What is python interpreter
### Description :
What is a Python interpreter, and how does it work?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by roopali-1**
<hr>

## Description 📜

In this i try to explain what is Python Interpreter 
Fixes #79 (#1001)

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x ] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
Can you please add few more lines on the python interpreter?  Specially can you explain the diagram as well? I am sharing an example with you.

"To begin, it examines the script's statements and verifies that the syntax is proper. As soon as the source code is compiled, it creates bytecode, an intermediate, platform-independent version of your programme. Once the code has been shipped, it will be executed by the Python Virtual Machine, which executes the code you've written at its most basic level."

**change your branch to python as well.**

**Comment by roopali-1** [comment]
@prathimacode-hub mam please review this PR .

**Comment by prathimacode-hub** [comment]
@roopali-1, I can't see your name tagged to this issue and assigned to you over issue number.

**Pull request closed without merging**
