### PR TITLE
added video about Substitution method

### LINKED ISSUE #484: DSA 1.2.2.3 Algorithms: Recurrence Relations
## Description
How can you solve recurrences using Substitution Method? Discuss the approach and provide examples.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by harshithatnbr**
<hr>

## Description 📜

added video about Substitution method. I have made a markup file which contains the video (google drive link). 
Fixes #484

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
[title](https://drive.google.com/file/d/1P-c5SE0ngegzPbjEoO3zL5oD5XieEUP3/view?usp=sharing)
click image for video

<hr>

### CODE REVIEW

**Review by harshsri28 — CHANGES_REQUESTED** [review]
You have to commit in DSA branch as you are commiting in main branch.

**Comment by harshithatnbr** [comment]
@harshsri28  ok thanks . Can you let me know how to do this??

**Comment by harshsri28** [comment]
> @harshsri28 ok thanks . Can you let me know how to do this??

Fork the repo , then select DSA branch(by default main will be selected) , then go to DSA folder, then add your file in respective section

oie_oEPHSTRBPbbs

**Comment by harshithatnbr** [comment]
I forked DSA branch .I have added my file in DSA branch. But when I made PR it is committed to main branch. So should I make another PR for DSA branch??

**Comment by harshsri28** [comment]
At the time of  pull request change branch from main to dsa.

**Comment by harshithatnbr** [comment]
I have changed as you said!!

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by nimisha-yadav — APPROVED** [review]
Congrats on getting your PR merged!

**Comment by harshithatnbr** [comment]
> Congrats on getting your PR merged!

Thanks @nimisha-yadav. ☺️ This is my first successful PR in GWOC🥳

**Pull request merged**
