### PR TITLE
Data Science with Python : Dealing with Categorical Columns #2403

### LINKED ISSUE #2403: Data Science with Python : Dealing with Categorical Columns
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about working on Dealing with Categorical Columns. Tutorial to Dealing with Categorical Columns and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Peehu Saxena / Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜
Made a video presentation on the topic of Dealing with categorical columns

Fixes #2403 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you evaluate the PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Changes to be done 👍 

README can be elaborated.
Keep your project repo as "Dealing with Categorical Columns"

Kindly work on it. @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam i have made the changes can you please evaluate the PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Also explain the purpose and why it's useful while working on solutions. @ashish-reddy-20-08

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Your dedication is worth appreciating. Great job. Keep going. 👌🎇@ashish-reddy-20-08

**Review by DhruvBajaj01 — COMMENTED** [review]
Reviewed!

**Pull request merged**
