### PR TITLE
Frontend web development html css js

### PR DESCRIPTION
**Pull request by hrshita-kshyp**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise, Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations, and regular explanatory films are all possibilities, etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by hrshita-kshyp** [comment]
@Knighthawk-Leo please review this PR for issue #7708

**Comment by 2024-SANDHYA** [comment]
Almost 77% of Palgiazrized 

image

**Comment by hrshita-kshyp** [comment]
Can't I add credits? I saw in some merged repo they added credits @2024-SANDHYA 
I took help of the first website

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Can't I add credits? I saw in some merged repo they added credits @2024-SANDHYA I took help of the first website

What'll be the use of that if you've copy-pasted only, we can refer to that site rather than this repo. Getting my point? Plagiarized content won't be accepted in any form, no matter if you add links or not. Take reference but don't copy-paste.

**Pull request closed without merging**
