### PR TITLE
Data types in C

### PR DESCRIPTION
**Pull request by shreyarai05**
<hr>

## Description 📜

I briefly explained data types and have included a doc file for better understanding with  numerous example and all.
Fixes # 1295 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Docmentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ChetasShree** [comment]
@shreyarai05 ,pls submit in .md file ,not doc file

**Comment by shreyarai05** [comment]
How to do that?I am not understanding it.

**Comment by shreyarai05** [comment]
Moreover my issue no. Was 1295

**Comment by ChetasShree** [comment]
@shreyarai05 , when u make a file for CPP,u write an extension of .cpp, similarly, for a .md file, u have to save it with the extension of .md

**Comment by shreyarai05** [comment]
Okay

**Comment by shreyarai05** [comment]
But i have cloned the repo on and then put my doc file from local machine.
How would I create a md file on my local machine??

**Comment by Suvraneel** [comment]
@shreyarai05 You can use any IDE/text editor : VS Code, Sublime, Notepad++ even normal notepad

Also, 
image
Pull from girlscript/C_CPP

**Comment by shreyarai05** [comment]
Okay sure

**Comment by Saviour1001** [comment]
Here is a [video](https://drive.google.com/file/d/1MT427pPKeay_pXGNNuE4kMJj0xRkn6G-/view?usp=sharing) explaining the complete workflow. Hopefully it clears all your doubts !

**Comment by ChetasShree** [comment]
@shreyarai05 pls check the syntax of .md file and make changes accordingly.
Hope this helps : https://guides.github.com/features/mastering-markdown/

**Comment by shreyarai05** [comment]
Is not there any shortcut method of making a md file? Will I have to edit
all this line by line???

**Comment by Saviour1001** [comment]
Markdown is a file type just like a txt , docx. Just copy all the content in a markdown file and you are good to go. I consider you should have a look at the merged PRs of CPP domain and you will get a better idea.

**Comment by Saviour1001** [comment]
Great work on the content @shreyarai05 just add the file into the correct place now, you could add this file in introduction to C, rather than creating a new folder called datatype in C.

**Comment by Suvraneel** [comment]
@shreyarai05  Awesome ❤️  Merging 🚀

**Comment by shreyarai05** [comment]
What is this workflow run?? I am getting constant notif as workflow run
failed.

**Comment by Saviour1001** [comment]
@shreyarai05 You can ignore those notifications, it's related to the various bots which we have added to the repo. Sorry for the inconvenience.

**Pull request merged**
