### PR TITLE
Added document of Pair in C++ STL #855

### LINKED ISSUE #855: Pair in C++ STL
<hr>

## Description 📜

I want to add documentation of Pair in C++ STL.

<hr>

## Domain of Contribution 📊

- [x] C/CPP
<hr>

### PR DESCRIPTION
**Pull request by Perpetual-Incantation**
<hr>

## Description 📜

Added document of Pair in C++ STL.
Fixes #855  

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [x] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Saviour1001** [comment]
The file is not correctly placed, you can place it in the Data Structures folder in CPP. And pairs has a lot of functions, try to give more examples. Try showcasing some powerful data structures, such as Pair of Vectors etc.

**Comment by Perpetual-Incantation** [comment]
@Saviour1001 Please check, I have edited the code.

**Comment by Saviour1001** [comment]
image
We just want the Pair file, you have created 2 Pair files and one competitive one. Kindly remove those in this PR.

**Comment by Saviour1001** [comment]
image
It still has 2 files, this is a CPP PR thus you can only add files of this domain. Don't add Competitive Programming files in this PR. If you want to contribute in multiple domains at the same time you should learn Branching in Git, using branches you would be able to store different data in different branches and make multiple PRs.

**Comment by Perpetual-Incantation** [comment]
@Saviour1001 Please review my code.

**Comment by Saviour1001** [comment]
The content is great but could you just place it correctly. We have a [Data Structures](https://github.com/girlscript/winter-of-contributing/tree/C_CPP/C_CPP/Data%20Structures) folder already, place it there. Make a subfolder for Pairs and place your content there.

**Comment by Saviour1001** [comment]
Perfect @Perpetual-Incantation ! 🎉

**Pull request merged**
