### PR TITLE
Largest Arithmetic Subarray

### LINKED ISSUE #2305: DSA : Longest Arithmetic Subarray
### Description

A has an array of N non-negative integers. A wants to calculate maximum length of contiguous arithmetic subarray.

Arithmetic Subarray is an array that contains at least two integers and the difference between consecutive integers are equal. For example  [9,10] , [3,3,3] and [9,7,5,3] arithmetic arrays.

Input: No. of test cases T
          integer no N
          array A[]
 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by priyanka001tech**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2305 

# Longest Arithmetic Subarray

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by priyanka001tech** [comment]
@nimisha-yadav can you please review my work once

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Discuss about time complexity and space complexity

**Comment by nimisha-yadav** [comment]
Also @priyanka001tech, do send in your full name and DSA Batch number

**Comment by priyanka001tech** [comment]
> Discuss about time complexity and space complexity

Okk sir I'll do that.

**Comment by priyanka001tech** [comment]
> Also @priyanka001tech, do send in your full name and DSA Batch number

Yes ma'am 
Name: Priyanka Kothari
DSA Batch no: 1

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by sneha-nitdgp — APPROVED** [review]

**Comment by sneha-nitdgp** [comment]
Good.

**Comment by priyanka001tech** [comment]
> LGTM

When the pull request is going to merge??

**Review by nimisha-yadav — CHANGES_REQUESTED** [review]
LGTM. Just do the following changes and you're good to go. 
Update fork
Put your file in Standard Problems folder in Array
Rename it 1.1.5_Largest_Arithmetic_Subarray.md

**Comment by priyanka001tech** [comment]
> LGTM. Just do the following changes and you're good to go. Update fork Put your file in Standard Problems folder in Array Rename it 1.1.5_Largest_Arithmetic_Subarray.md

Ok ma'am I'll do it

**Comment by priyanka001tech** [comment]
@nimisha-yadav ma'am please review this

**Review by nimisha-yadav — APPROVED** [review]

**Pull request merged**
