### PR TITLE
C_CPP : Structure in C++

### LINKED ISSUE #1623: C_CPP : Structure in C++
<hr>

## Description 📜

This documentation will explain Structure in C++

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by ankushsingh24**
<hr>

## Description 📜
I've completed my issue work , I raised an issue on the topic Structure in C++.

This documentation will explain Structure in C++ :

1. It is a beginner friendly documentation of Structure includes structure C++ code with proper comments ahead.
2. Used images to visualize structure very well.
3. Explained functions involved in Structure in the C++ code.

Fixes #1623 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
### Very good, except a few things, please change them and we're free to approve and merge.

- move the directory of /Diagram to /Structure in C++
- change the name of Structure in C++/structure.md to readme.md
- change the first line of Procedural Structures/Structure/readme.md to **Structure in C/C++**

**Comment by vasu-1** [comment]
@Suvraneel Now , we can merge this branch !

**Comment by vasu-1** [comment]
Hey ! @ankushsingh24  Please create the new branch for this deque work ..!
You have to change the branch for each issue !

@Suvraneel Please see this , he has also done same thing earlier !

**Comment by ankushsingh24** [comment]
> Hey ! @ankushsingh24 Please create the new branch for this deque work ..!
> You have to change the branch for each issue !
> 
> @Suvraneel Please see this , he has also done same thing earlier !

@vasu-1 actually it was accidently deleted, so I've added now
suggest me some changes if it's still there

**Review by Suvraneel — APPROVED** [review]

**Comment by Suvraneel** [comment]
@vasu-1 okay okay... I'm telling him

**Pull request merged**
