### PR TITLE
Data Science with Python : Dimensionality Reduction

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
Name-Bhaswati Roy   
Domain-Data Science with Python 
Batch-19  
Serial No-787 
Issue Number-464
Contribution-Dimensionality Reduction

<hr>

## Description 📜

Created a documentation on the topic Dimensionality Reduction (Section-Machine Learning, Domain-Data Science with Python)
Issue  : #464

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The issue contribution should be under /Machine Learning/Tutorials/Dimensionality Reduction
Add a README.md file. You can find the things you can add up in Project structure document
The project file name should be in snake case : dimensionality_reduction.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Dimensionality Reduction"
Add up the respective datasets used in "DS Datasets" in "Machine Learning" folder and resources referred in "DS Resources" in "Machine Learning" folder
Even .ipynb file needs more detailing. Check on to it. Add short intro, how it works using test cases and final outcome of it

Kindly work on it.

**Comment by BhaswatiRoy** [comment]
> Changes to be done 👍
> 
> The issue contribution should be under /Machine Learning/Tutorials/Dimensionality Reduction
> Add a README.md file. You can find the things you can add up in Project structure document
> The project file name should be in snake case : dimensionality_reduction.ipynb
> If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Dimensionality Reduction"
> Add up the respective datasets used in "DS Datasets" in "Machine Learning" folder and resources referred in "DS Resources" in "Machine Learning" folder
> Even .ipynb file needs more detailing. Check on to it. Add short intro, how it works using test cases and final outcome of it
> 
> Kindly work on it.

yaah sure will send it in proper format asap

**Comment by prathimacode-hub** [comment]
Are changes done? @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
@prathimacode-hub I created a new pr of this and you've already merged that. https://github.com/girlscript/winter-of-contributing/pull/2278

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub I created a new pr of this and you've already merged that. This one-> #2278

k, thanks for notifying. I can now close this PR. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> > @prathimacode-hub I created a new pr of this and you've already merged that. This one-> #2278
> 
> k, thanks for notifying. I can now close this PR. @BhaswatiRoy

sure thanks

**Pull request closed without merging**
