### PR TITLE
Create Part_4_Introduction_to_Figma_Creating_Grids.md

### LINKED ISSUE #183: Introduction to Figma Part 4 - Creating Grids
In this we need a documentation or a video tutorial showing how to work with grids in Figma .Grids are very useful for interface design but can also be invaluable for creating icons. 

 

Note :
Folder Structure should be UI_UX/Introduction_to_Figma/Part_4  & changes should be made to  UI_UX branch.
Issue only for GWOC'21 contributors.
In the PR, keep this issue's title as your PR's title.
Must Follow : [Contributing Guidelines ](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)& [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing

### PR DESCRIPTION
**Pull request by LegendSumeet**
<hr>

## Description 📜

Introduction to Figma Part 4 - Creating Grids
Fixes #183  

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by LegendSumeet** [comment]
done ready to merge @Debasmita-01

**Comment by LegendSumeet** [comment]
@Debasmita-01

**Review by LegendSumeet — COMMENTED** [review]
@Debasmita-01 review it mam

**Comment by Debasmita-01** [comment]
merging this

**Pull request merged**
