### PR TITLE
Middle element of array in C, Fibonacci Series without recursion in C

### LINKED ISSUE #1729: Middle Element of an Array
<hr>

## Description 📜
A C program where user can find the middle elements of a "n" size array.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by amelia2802**
<hr>

## Description 📜
Fixed issue "Middle element of array" by adding a relevant code in C, where user can find the middle elements of an n size array.

Fixes #1729 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@amelia2802 add the readme to the Arrays folder as well

**Comment by amelia2802** [comment]
@apeksha235 Done!

**Comment by amelia2802** [comment]
<hr>

## Description 📜
Fixed issue "Fibonacci Series in C without recursion" by adding a relevant code in C, where the user can find the Fibonacci series of n number.
Fixes  #1924 

<hr>

## Type of change 📝




- [x] Documentation (Content Creation in the form of codes or tutorials)


<hr>

## Domain of Contribution 📊



- [x] C/CPP


<hr>

## Checklist ✅



- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>




<hr>

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@amelia2802 Please make a PR for one issue only

**Comment by amelia2802** [comment]
@apeksha235 Can you guide me on how to separate this two now? Because when I try to make a pull request on the issue 1924 it shows me this pull request page & I can't see the "create new pull request option".

**Comment by vasu-1** [comment]
Hey please delete or close this pr..

**Comment by vasu-1** [comment]
And make two individual PRs for different issues.

**Pull request closed without merging**
