### PR TITLE
Python Numpy

### LINKED ISSUE #2995: Python Numpy
### Description
NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.<br>
NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

### Domain

Python_Domain

### Type of Contribution

Audio, Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by mridu-pant**
<hr>

## Description 📜

Audio for Python Numpy module along with a presentation. 
Fixes #2995 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nayakaj** [comment]
@adityabisoi  plz assign me for video contribution

**Comment by adityabisoi** [comment]
plz tag a mentor for review

**Comment by mridu-pant** [comment]
@hritikksingh please review the pr

**Comment by hritikksingh** [comment]
@mridu-pant your Audio file is great.
The presentation is great.
But the readme seems to be too short, can you add few lines to it, it was supposed to be a readme but it rather looks like clickme because only one link is there. Can you try merging the presentation to readme? Because I don't find presentation.md use there.

**Comment by mridu-pant** [comment]
Alright I'll do that.

**Comment by mridu-pant** [comment]
@hritikksingh is it ok now?

**Comment by hritikksingh** [comment]
Yes all good.
@adityabisoi this can be merged.

**Comment by adityabisoi** [comment]
@mridu-pant Can you make a new PR removing all the documentation so that only audio contribution is retained?

**Comment by mridu-pant** [comment]
Done @adityabisoi 
Link to new PR- https://github.com/girlscript/winter-of-contributing/pull/7828

**Pull request merged**
