### PR TITLE
JSON

### LINKED ISSUE #1882: JS: JSON  Tutorial
### I will discuss what is JSON and how to use it?
```
Topics/8.JSON
```

### Domain

JavaScript

### Type of Contribution

- [x] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by yellowberard**
<hr>

## Description 📜

A brief description about JSON
Fixes #1882

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by yellowberard** [comment]
I have updated the PR #5376. 
@2024-SANDHYA Please review my PR

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
This is not in the MD format


image

**Comment by yellowberard** [comment]
@2024-SANDHYA done the required changes

**Comment by 2024-SANDHYA** [comment]
88% Plagiarized. Will not accept this.

image

**Comment by yellowberard** [comment]
Can I make a video about this topic??

**Comment by 2024-SANDHYA** [comment]
> Can I make a video about this topic??

No, only 1 week is left. Work on the documentation part itself.

**Comment by yellowberard** [comment]
Okay

**Pull request closed without merging**
