### PR TITLE
DSA: Bit Manipulation

### PR DESCRIPTION
**Pull request by mridul8920**
<hr>

## Description 📜

 I have added important code solution for Bit Manipulation topic which is always considered as an under rated topic and student miss it and lose marks. 

Language->C++

Contribution type-> Documentation

#6476
<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [X] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Muskan-creator** [comment]
Make your PR in girlscript:DSA branch not main branch @mridul8920

**Comment by mridul8920** [comment]
Okay I will do it. I am contributing for the first time so maybe i did a
mistake somewhere.
Thank you

**Comment by mridul8920** [comment]
> Make your PR in girlscript:DSA branch not main branch @mridul8920

I have changed the branch kindly review my PR

**Comment by nimisha-yadav** [comment]
@mridul8920 Commit changes to DSA branch in your fork as well. Once it shows 1 file changed instead of 728, then that would be the correct way.

**Pull request closed without merging**
