### PR TITLE
Why_Python

### LINKED ISSUE #3128: Why to choose python as a programming language?
### Description

This will give the information about:
1)The python capabilities in our today's world.
2)Scope of Python.
3)Major Uses of Python and more. 

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by achsahxavier**
<hr>

## Description 📜

Here, I explained why to choose Python as a programming language. I also explained its uses and advantages in audio format along with ppt containing relevant information.
Fixes #3128

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by achsahxavier** [comment]
@queenish001
Please review this and tell me if any change is to be
made.
Thank you.

**Review by queenish001 — CHANGES_REQUESTED** [review]
Nice Work on the Explanation!

Just one change that needs to be done: Change this file name from `Why to choose Python as a programming language_ (1).md` to `README.md`

**Comment by achsahxavier** [comment]
@queenish001 
A file with that name already exists there, what should I do now?

**Comment by queenish001** [comment]
Okay then, This README would be for Documentation.
What you can do is:-
1. Make a folder inside Why_Python folder `Why_Python_Audio`
2. Inside that Folder add Your file and rename it to `README.md`

**Comment by achsahxavier** [comment]
@queenish001 
Please check and tell if it is done or not.

**Review by queenish001 — APPROVED** [review]
Approved 🦋

@adityabisoi

**Comment by achsahxavier** [comment]
> Approved 🦋
> 
> @adityabisoi 

Thank you :)

**Pull request merged**
