### PR TITLE
Update 04.0 Overview of Android-Manifest file.md

### LINKED ISSUE #516: Android-Kotlin : 04.0 Overview of Android-Manifest file
## Description :
* Give a brief overview of **AndroidManifest.xml** file.
*  Required documentation or video.

* Changes should be made in **Android_Development/Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
> Supervisor @rahulsain

### PR DESCRIPTION
**Pull request by Parth-001-git**
<hr>

## Description 📜

In this repository, you will get to know about the android manifest.
Fixes #516

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [x] Android Dev (Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by Parth-001-git** [comment]
@rahulsain  Made the necessary changes.

**Review by sitamadex11 — CHANGES_REQUESTED** [review]
Nice work. just cut the audio in 3:19 - 3:25 duration. there exist a voice break. The remaining are just awesome.

**Comment by rahulsain** [comment]
> @rahulsain Made the necessary changes.

If you are changing the file in your drive, just update the file(by using the same name as it was in your drive) don't create a new one in your drive (so that the link will remain same)

**Comment by Parth-001-git** [comment]
@Rahul sain  I am unable to change,I have to give a fresh link or is 
it's ok?

**Comment by rahulsain** [comment]
> @rahul sain I am unable to change,I have to give a fresh link or is it's ok?

its ok for now, dont change the link

**Comment by rahulsain** [comment]
Why it is not playing now?
image

**Comment by Parth-001-git** [comment]
Because you told me to edit that's why I was in the process.

**Comment by Parth-001-git** [comment]
I have a fresh link .

**Comment by rahulsain** [comment]
Ok give me the new link, i will update

**Comment by Parth-001-git** [comment]
Ok

**Comment by Parth-001-git** [comment]
https://drive.google.com/drive/folders/17xiDUKNDhDx7RMNA93BipaVexiU4NtWG?usp=sharing

**Comment by Parth-001-git** [comment]
Working?

**Comment by rahulsain** [comment]
> https://drive.google.com/drive/folders/17xiDUKNDhDx7RMNA93BipaVexiU4NtWG?usp=sharing

give me the link of the audio file not the folder

**Comment by Parth-001-git** [comment]
https://drive.google.com/file/d/1dh_0NpEwBMhJ86accW0Uz9aHjVuEzxLd/view?usp=sharing

**Comment by Parth-001-git** [comment]
Now?

**Comment by rahulsain** [comment]
updated

**Pull request merged**
