### PR TITLE
ML 3.7 : BIRCH (A)

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜
birch algo.applications,cf
Fixes # <4120> 

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
@Isha307 @abhisheks008 please review on this

**Comment by abhisheks008** [comment]
Just a small change there, `ML_3_7_....` this will be the initial for the file name @ron352

**Comment by ron352** [comment]
Changed

**Comment by abhisheks008** [comment]
PR merged @ron352

**Pull request merged**
