### PR TITLE
ML 1.1 : Variables, Range, Population Distribution, Sample Distribution (A)

### PR DESCRIPTION
**Pull request by SathiyaEthi**
<hr>

## Description 📜

Added audio for ML 1.1 : Variables, Range, Population Distribution, Sample Distribution (A)

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
**Changes Requested @SathiyaEthi **
Please follow the demo folder or others contribution on how to provide your drive link using the thumbnail.

**Comment by SathiyaEthi** [comment]
@abhisheks008 , Updated thumbnail. Kindly review.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@SathiyaEthi thumbnail is not visible.

**Comment by SathiyaEthi** [comment]
@abhisheks008 , Updated again with correct thumbnail. Kindly review.

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
PR approved 🎉

**Pull request merged**
