### PR TITLE
Infix To Postfix in C

### LINKED ISSUE #7351: Infix To Postfix Using Array in C
### Description

To Convert Infix Expression To Postfix Expression In C :)

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜

I have prepared a documentation on:
To Convert Infix Expression To Postfix Expression using Stack Data Structure In C :)

Hope you learn from it 👍 

Fixes #7351  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Kavya, the code looks good.
Do add a few input-output at the end of your code.

**Comment by ikavyajain** [comment]
Okay sir

**Comment by ikavyajain** [comment]
@deeqakkk sir,
I have made the required changes. Please have a look :)

**Review by deeqakkk — APPROVED** [review]
@Suvraneel its looks good to be merged, do mention things if something need to be changed .

**Comment by Suvraneel** [comment]
@Saviour1001  Already implemented in C++ [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Data%20Structures/Stack/infixToPostfix.md) 

This one's in C, works too right?

**Comment by ikavyajain** [comment]
@Suvraneel Kindly check on this once :)

**Pull request merged**
