### PR TITLE
WebDevlopment: JS objects

### LINKED ISSUE #213: JavaScript
* Functions and Scope
* Objects and Arrays 

I am raising the issue after going through the <a href="https://docs.google.com/document/d/1OK3bL6ue5PMxpRP-6y7Xl91MMJ8NTMa6V3FzXxJxU9E/edit">Google spreadsheet</a> and I want to work on this issue.

Note- In the spreadsheet **functions and scope** are mentioned two times.

### PR DESCRIPTION
**Pull request by helper-uttam**
<hr>

## Description 📜
Adding about JavaScript Objects via documentation.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #213 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by helper-uttam** [comment]
@paramsiddharth  There is one more PR for the same  #815 . I had already completed the documentation part, and more peoples are working on the same. 
I didn't understood this 😥?

**Comment by paramsiddharth** [comment]
> @paramsiddharth There is one more PR for the same #815 . I had already completed the documentation part, and more peoples are working on the same.
> I didn't understood this 😥?

No no! 😅 There's been a confusion here. JavaScript and FEWD are two different domains with coinciding topics. The other PR is for JS, this is for FEWD. So there is no clash. 😊 Don't worry. Your PR is eligible to be reviewed and merged by FEWD supervisors and mentors.

**Comment by Ayan-thecodeking** [comment]
@helper-uttam @paramsiddharth PR has conflicts ...pls do resolve that

**Comment by helper-uttam** [comment]
@paramsiddharth  can you tell me what is causing these conflicts? I'm not able to get it, what wrong am I doing😥

**Pull request closed without merging**
