### PR TITLE
Competitive Programming :: Graphs :: CSES Counting Rooms (Documentation)

### LINKED ISSUE #1892: Competitive Programming : : Graphs : : CSES Counting Rooms (Documentation)
### Description

I'd like to make a detailed document outlining how to approach CSES typical dfs on-grid problems.

### Domain

Competitive Programming

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by shreeshjha**
<hr>

## Description 📜

Implemented the CSES Counting Rooms problem solution in C++, complete with a thorough explanation.
Fixes #1892 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Competitive Programming
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ravireddy07** [comment]
This PR can't be merged, Because you're targeting or making PR to main branch. You should make PR to `Competitive_Programming ` branch. raise another PR pointing to `Competitive_Programming ` branch. @shreeshjha

**Comment by shreeshjha** [comment]
@ravireddy07  Thanks for pointing it out to me will make sure to do that.

**Comment by ravireddy07** [comment]
Update your branch with current `Competitive_Programming` changes and include your contribution file only. @shreeshjha

**Comment by shreeshjha** [comment]
I'll be creating a new pull request with mentioned changes so will be closing this pr.

**Pull request closed without merging**
