### PR TITLE
Data Science with Python : Introduction to Unsupervised Learning

### PR DESCRIPTION
**Pull request by Robinrai2612**
<hr>

## Description 📜

I have worked on the issue "Introduction to Unsupervised learning" in which I have explained the detailed information about the unsupervised learning. Fixes issue #428 
<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [x] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Saviour1001** [comment]
Just removing the unnecessary tags. From next time just keep the domain name you are contributing to in the PR description. Its mentioned in the comments. 
You can ask the mentors of your domain to review this PR now!

**Comment by BasuDevTyagi10** [comment]
/assign
I would like to work on this issue.
Name: Basudev Tyagi
Batch: Data Science with Python Batch-13
Type: Documentation

**Comment by Robinrai2612** [comment]
@prathimacode-hub please review my issue.

**Comment by prathimacode-hub** [comment]
Kindly follow the project structure provided. @Robinrai2612

**Pull request closed without merging**
