### PR TITLE
DSA 3.2 Greedy Algorithms-Readme 

### LINKED ISSUE #5900: DSA 3.2 Greedy Algorithms - Readme
## Description
Contribute to the readme file of 3.2 Greedy Algorithms
**Important: Do not use assign command for this issue.**

## Task
- [ ] Documentation

## Note

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by nisha855**
<hr>

## Description 📜

Added Readme file of Greedy Algorithms
Fixes #5900

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Add some images , example

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Add sample code for 1-2 standard problems.

**Comment by nisha855** [comment]
Please review @harshsri28 @sneha-nitdgp have done the required changes

**Review by harshsri28 — CHANGES_REQUESTED** [review]
format your code, rest is looking fine

**Comment by nisha855** [comment]
@harshsri28 Done

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by harshsri28 — APPROVED** [review]
LGTM

**Comment by nisha855** [comment]
@nimisha-yadav The changes are approved

**Review by nimisha-yadav — COMMENTED** [review]
@nisha855 update your fork and name the file as README.md itself

**Comment by nisha855** [comment]
@nimisha-yadav I'm unable to rename it. It says-A file with the same name already exists. Please choose a different name and try again.

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav I'm unable to rename it. It says-A file with the same name already exists. Please choose a different name and try again.

Like I said, update your fork and then try. I've removed the original file so it won't be an issue anymore.

**Comment by nisha855** [comment]
Okay, done @nimisha-yadav

**Pull request merged**
