### PR TITLE
Create Folder CSS Selector and Pseudo Selector

### LINKED ISSUE #986: Selectors and Pseudo-selectors in CSS
<hr>

## Description 📜

I'll be adding documentation about selectors and pseudo-selectors in CSS.

## Domain of Contribution 📊

 Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by brassgolem-25**
<hr>

## Description 📜

I have added a readme file covering points as follows:
- Selectors in CSS
- Pseudo Selectors in CSS
with concise and enunciate example.

Fixes #986 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by brassgolem-25** [comment]
@sifa123 please check this PR. If there's any changes i need to do.

**Comment by brassgolem-25** [comment]
@praveenscience @code-reaper08 please do check this PR.

**Comment by brassgolem-25** [comment]
Hey @SnehaKumari3 this is not issue assignment place, it's a PR. Pls go to issue section and create one and work on it!!!

**Review by sifa123 — COMMENTED** [review]
Looks good to me!

**Comment by brassgolem-25** [comment]
So, @sifa123 , can it be merged now?!

**Pull request merged**
