### PR TITLE
Data Science with Python : Normalization & Standardization

### PR DESCRIPTION
**Pull request by pankaj-Makhijani**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Explained about feature scaling, different scaling techniques, Normalization, standardization, Code Implementation [Issue #471 ]

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by pankaj-Makhijani** [comment]
Hello mam @prathimacode-hub , Please review my Pull request.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

In README.md, add purpose, why its used, features, advantages, applications, overall summary, conclusion
Change your title to README.md
In .ipynb file, give short intro about topic before getting into code directly and final outcomes at the end.

**Comment by pankaj-Makhijani** [comment]
Hello @prathimacode-hub, I have made the requested changes.

**Review by prathimacode-hub — APPROVED** [review]
This was an amazing start. Congrats on your first PR. Your PR is appproved. Well done. 🎉👏 @pankaj-Makhijani

**Pull request merged**
