### PR TITLE
Android-Kotlin: 01.1 Requirement of Version Control System 

### LINKED ISSUE #453: Android-Kotlin : 01.1 Requirement of Version Control System
## Description :
*  Give a brief description stating the need of Version Control System.
* Also describe about Git and GitHub.
*  Required documentation, audio, or video.

## References :
https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control
https://guides.github.com/activities/hello-world/

* Changes should be made in Android_Development/Kotlin/ directory under Android_Development_With_Kotlin branch.
* You have to push your PR to the Android_Development_With_Kotlin branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.

> Supervisor @rahulsain

### PR DESCRIPTION
**Pull request by Asmit2952**
<hr>

## Description 📜

Gave a brief description stating the need of Version Control System. Also described about git and GitHub 
Fixes #453 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Asmit2952** [comment]
Mentors I tried squashing commits, but it was giving me error, can you please squash and merge from you side?

**Comment by sitamadex11** [comment]
@Asmit2952 you can try https://www.youtube.com/watch?v=V5KrD7CmO4o this tutorial. Coz it will be easier for you to squash rather than mentor.

**Comment by Asmit2952** [comment]
> @Asmit2952 you can try https://www.youtube.com/watch?v=V5KrD7CmO4o this tutorial. Coz it will be easier for you to squash rather than mentor.

I referred to that video and the "Merge branch 'Android_Development..." isn't visible in my git rebase command. Only the "Added info about VCS" is visible. So I can't squash commit that.

**Comment by Asmit2952** [comment]
Can someone review it please? so that I can contribute more

**Comment by rahulsain** [comment]
Please follow this type of file structure
`winter-of-contributing\Android_Development_with_Kotlin\Topic Name\subtopic markdown file`

**Comment by Asmit2952** [comment]
> Please follow this type of file structure
> `winter-of-contributing\Android_Development_with_Kotlin\Topic Name\subtopic markdown file`
> 
> so it would be
> `winter-of-contributing\Android_Development_with_Kotlin\01 Version Control System\01.1 Requirement of Version Control System.md`

Ok sure, I'll  change it.

**Comment by sitamadex11** [comment]
> > @Asmit2952 you can try https://www.youtube.com/watch?v=V5KrD7CmO4o this tutorial. Coz it will be easier for you to squash rather than mentor.
> 
> I referred to that video and the "Merge branch 'Android_Development..." isn't visible in my git rebase command. Only the "Added info about VCS" is visible. So I am not able to squash commit that.
> The other 3 commits are made by the supervisors.
> 
> picture
> 
> Edit: I even tried squashing on GitHub desktop, still not possible.

ok, no issue mate,  then leave it like that.

**Comment by sitamadex11** [comment]
> > Please follow this type of file structure
> > `winter-of-contributing\Android_Development_with_Kotlin\Topic Name\subtopic markdown file`
> > so it would be
> > `winter-of-contributing\Android_Development_with_Kotlin\01 Version Control System\01.1 Requirement of Version Control System.md`
> 
> Ok sure, I'll change it.

Please change it accordingly. Then we will approve your PR.

**Comment by Asmit2952** [comment]
@rahulsain I made changes as requested, please review this PR.

**Review by rahulsain — APPROVED** [review]

**Pull request merged**
