### PR TITLE
Data Science with Python : Machine Learning and Types

### LINKED ISSUE #5660: Data Science with Python : Machine Learning and Types
### Description

Welcome to 'DSWP' Team, good to see you here

you will give an overview of Machine learning and its types and applications

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : @Kareem-negm / @DhruvBajaj01

Start from: you can use this [notebook ](https://www.kaggle.com/kareem3egm/learn-machine-learning-faster-1)to give you a sample overview 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Hritik157**
<hr>

## Description 📜

An overview of Machine learning and its types and applications also codes of some examples 
Fixes #5660

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub plz review my pr sorry for so much delay....my laptop had some battery issue so I was unable to work on the assigned issue

Hmm, I understand when it's with respect to laptop. I can relate myself here which I had faced few days ago. That's Ok. @Hritik157

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your files aren't opening up and don't use multiple .ipynb files. Do it in single .ipynb file where you demonstrate all the types of algorithms you are showcasing.
For README.md, have you referred any references, if so mention it. @Hritik157

**Comment by Hritik157** [comment]
1. Added References
2. Algorithms examples in a single .ipynb file, probably the files will now open

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Exception work and finest PR. Great job done. Keep going. ✨✔@Hritik157

**Pull request merged**
