### PR TITLE
C_CPP: Throwing Exception from Functions

### LINKED ISSUE #5189: C_CPP: Throwing Exception From Functions
### Description

Description

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by 124015001**
<hr>

## Description 📜

Explained how exceptions are thrown with the help of functions. Also, performed two programs as examples on the same.
Fixes #5189 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
Good&unique content and explanation !

**Comment by 124015001** [comment]
@vasu-1 But she is asking for irrelevant changes, which is not at all needed.

**Comment by vasu-1** [comment]
For Bold Text use this `**Note**`
Give heading to the code !

@124015001

**Comment by vasu-1** [comment]
> What heading should I give to the code? I didn't get that.

e.g.

` ###Example `

**Comment by 124015001** [comment]
@kashishahuja2002 @vasu-1 See if it looks fine now?

**Pull request merged**
