### PR TITLE
FrontEnd : CSS : Transition and transformation (D) - Part 1 (only contains Transforms)

### LINKED ISSUE #1061: FrontEnd : CSS : Transition and transformation (D)
<hr>

## Description 📜

Documentation on Transitions and transformations used in CSS
<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by RC2208**
<hr>

## Description 📜

CSS transforms code and documentation with examples.  Will create a 2nd PR for CSS transitions after this because the documentation is too long. Thus total of 2 PR's in this issue.
Fixes #1061

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by RC2208** [comment]
Please don't close the issue since I need to make another pr in the same issue. Just merge this one if everything is alright!

**Comment by RC2208** [comment]
https://github.com/girlscript/winter-of-contributing/pull/2606
Here's the Part 2 of the pr

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
You need to explain more @RC2208, and examples will be really good to include.

**Comment by RC2208** [comment]
> You need to explain more @RC2208, and examples will be really good to include.

Hi! I have done the required changes and added more example images. The readme file was just the summary of both pdfs.... @code-reaper08

**Review by code-reaper08 — APPROVED** [review]
Looks good 😄

**Pull request merged**
