### PR TITLE
ML 2.13 : Implement Naive Bayes without using any standard ML library like scikit-learn or more. (D)

### LINKED ISSUE #2803: ML 2.13 : Implement Naive Bayes without using any standard ML library like scikit-learn or more. (D)
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Implement Naive Bayes without using any standard ML library like scikit-learn or more_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
-  Dataset to be used : **IRIS DATASET**. (No other datasets will be entertained.)

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Coding in .ipynb file, show the implementation)
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by hrugved06**
<hr>

## Description 📜

Documentation and Code explaining Naive Bayes without using any fancy libraries like scikit-learn
Fixes #2803 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Use Iris Dataset instead of Titanic Dataset, and provide a cell in the notebook, where you have to explain about the dataset and its parameters. @hrugved06

**Comment by abhisheks008** [comment]
@hrugved06 Please do the needful changes otherwise this PR can not be merged.

**Comment by hrugved06** [comment]
> @hrugved06 Please do the needful changes otherwise this PR can not be merged.

Yes I'm on it but I'm facing some issue in the GIT so I'm trying to solve that

**Comment by hrugved06** [comment]
Hello @abhisheks008, I have done the required changes and created a new pull request #3236 as I had some issues in my GIT and I did resolve that. Please have a look at the new PR

**Pull request closed without merging**
