### PR TITLE
Importing_packages.md

### LINKED ISSUE #2447: Java 13.3: Importing Packages
<hr>

## Description 📜

Add audio, documentation and video regarding the Need of Java.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `Importing Packages`  folder which is inside the `Packages` folder present in the `Java` main folder. If the folder is not present, create the folder with this exact name. The documentation file can be in the .md/.py/.ipynb format. Audio should be in .mp3 format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 Note:
 - You are required to comment with \assign CONTENT_TYPE, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned. 
- Issues will be assigned on the basis of first come first serve.

### PR DESCRIPTION
**Pull request by rishitajain01**
documentation added.
fixes #2447

<hr>

## Description 📜

I have added documentation for the topic importing packages in java
Fixes #2447 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by garvitraj** [comment]
@AkMo3 have a look at it l1 review is okay

**Review by AkMo3 — APPROVED** [review]

**Comment by rishitajain01** [comment]
@garvitraj @AkMo3  Sir can you please add hacktoberfest-accepted label to it?...Is this necessary for PR to be counted in the fest?

**Comment by rishitajain01** [comment]
@AkMo3  Sir please add hacktoberfest-accepted label to it?...Is this necessary for PR to be counted in the fest?

**Comment by AkMo3** [comment]
@rishitajain01 I guess it is too late to add the label now.

**Comment by rishitajain01** [comment]
okay..no problem

**Pull request merged**
