### PR TITLE
[C/CPP]: Implementation of Queue in C Programming

### PR DESCRIPTION
**Pull request by motasimmakki**
<hr>

## Description 📜

Here is the Implementation in Queue Data Structure in C programming language.
Fixes # 3504

<hr>

## Type of change 📝
- [X] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

Screenshot (659)

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@motasimmakki Please make a different branch for different issues and remember to fetch and merge upstream with the C_CPP branch

**Comment by motasimmakki** [comment]
> @motasimmakki Please make a different branch for different issues and remember to fetch and merge upstream with the C_CPP branch

I made the new branch only in my local as C_CPP to contribute to this domain, and fetch and merged upstream also, but don't know in the PR how it showing that my branch is 113 commits ahead of the original one, whereas I only made a single commit for my contribution.
Kindly help.

**Comment by apeksha235** [comment]
@motasimmakki 
- Once you are in the C_CPP branch of your forked repo, fetch upstream
image

- After which it'll be shown that your branch is even
image

You'll have to close this PR and try again

**Comment by motasimmakki** [comment]
> @motasimmakki
> 
> * Once you are in the C_CPP branch of your forked repo, fetch upstream
>   image
> * After which it'll be shown that your branch is even
>   image
> 
> You'll have to close this PR and try again

@apeksha235 
The problem that I'm facing is that only, it is not showing after fetching and merging also that "the branch is even with GWOC", I have to make the separate PR that I understand, but how can I deal with this one.

Screenshot (663)

Kindly help.

**Comment by Saviour1001** [comment]
Closing this PR as you haven't updated your repo, Update your repo, add your changes and then generate a new PR.

**Comment by motasimmakki** [comment]
> Closing this PR as you haven't updated your repo, Update your repo, add your changes, and then generate a new PR.

How do I make my branch even with the upstream branch, I also did the fetch and merged upstream.

**Comment by Saviour1001** [comment]
@motasimmakki ping me on discord

**Comment by motasimmakki** [comment]
> @motasimmakki ping me on discord

just sent you a request!

**Pull request closed without merging**
