### PR TITLE
C_CPP : Maps in C

### LINKED ISSUE #904: C_CPP : Maps in C
<hr>

## Description 📜

Maps in C 
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

- Documentation

### PR DESCRIPTION
**Pull request by a-rcane**
<hr>

## Description 📜

Issue #904 :  Maps in C
Desc : Making a map implementation in C using struct and hashtable.

Fixes #904  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by motasimmakki** [comment]
Assign this to me.
Motasim (C/CPP Batch-01)

**Comment by ChetasShree** [comment]
amazing work @a-rcane !!
@Saviour1001 @Suvraneel pls review this PR and merge it :)
Thank you

**Comment by a-rcane** [comment]
@ChetasShree Thank you :)

**Comment by Saviour1001** [comment]
Didn't know how to code maps in C. Great work @a-rcane ! :tada:

**Pull request merged**
