### PR TITLE
Python: 2.3 Installing development & debugging software #339{video tutorial}

### PR DESCRIPTION
**Pull request by Cyber-Prajwal**
<hr>

## Description 📜

My assignment was to create a video tutorial for installing development & debugging software for python programming. 
issue : #339
I have created a folder  at the required domain address i.e., 'winter-of-contributing/Python/Installing_Software/ '
There I have created a folder named 'Installing_development_&_debugging_software_{VIDEO TUTORIAL}'
Within the folder, I have further created a 'README.md' file which contains a link to the video tutorial on youtube and also a brief text summary of what the video contains with screenshots as well for better understanding.

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilities etc)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

# what my changes will look like when merged

#screenshots of my repo 
Screenshot (367)

Screenshot (368)

#  ['Able merge without any issues' screenshot below ]

Screenshot (366)
<hr>

### CODE REVIEW

**Comment by adityabisoi** [comment]
Can you update the index?

**Comment by Cyber-Prajwal** [comment]
@adityabisoi 
Not sure how 
plus the upstream has updated and for some reason I am not able to fetch the changes ..please guide

**Comment by Cyber-Prajwal** [comment]
> Can you update the index?

@adityabisoi
I have updated index in readme please confirm is everything ok now ??

**Comment by adityabisoi** [comment]
You need to place in `Learning path` in README also

**Comment by Cyber-Prajwal** [comment]
> You need to place in `Learning path` in README also

@adityabisoi 
Done

**Comment by ankurg132** [comment]
@adityabisoi looks good to me!

**Pull request merged**
