### PR TITLE
added Coroutines.md

### LINKED ISSUE #881: Android-Kotlin : 02.6 Coroutines in Kotlin
I want to make documentation on this topic. Kindly assign this to me @rahulsain .
Tanushree here ! (from Batch 1 : Android-Dev-Kotlin)

### PR DESCRIPTION
**Pull request by Tanushree-coder**
<hr>

## Description 📜

Added Documentation for Coroutines in Kotlin
Fixes #881 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Kotlin)
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by rahulsain** [comment]
Please follow the PR template

**Comment by Tanushree-coder** [comment]
> Please follow the PR template

should I make another PR ?

**Comment by rahulsain** [comment]
> > Please follow the PR template
> 
> should I make another PR ?

No, just edit the PR description

**Comment by rahulsain** [comment]
Revert this latest commit
no cpp file allowed

**Comment by rahulsain** [comment]
> > > Please follow the PR template
> > 
> > 
> > should I make another PR ?
> 
> No, just edit the PR description

do this, then I will review

**Comment by Tanushree-coder** [comment]
> > > > Please follow the PR template
> > > 
> > > 
> > > should I make another PR ?
> > 
> > 
> > No, just edit the PR description
> 
> do this, then I will review

Sir, I'm not getting the template

**Comment by rahulsain** [comment]
`<hr>

## Description 📜

Added Documentation for Loops in Kotlin
Fixes #491 

<hr>

## Type of change 📝



- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊



- [x] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅



- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>
`

**Comment by Tanushree-coder** [comment]
> `
> 
> ## Description 📜
> Added Documentation for Loops in Kotlin
> Fixes #491
> 
> ## Type of change 📝
> * [ ]  Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
> * [ ]  Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
> * [x]  Documentation (Content Creation in the form of codes or tutorials)
> * [ ]  Other (If you choose other, Please mention changes below)
> 
> ## Domain of Contribution 📊
> * [x]  Android Dev (Flutter, Java, Kotlin)
> * [ ]  Backend Dev (Java, .NET, Python)
> * [ ]  C/CPP
> * [ ]  Competitive Programming
> * [ ]  Cyber Security
> * [ ]  DSA
> * [ ]  Database
> * [ ]  Datascience with Python
> * [ ]  Datascience with R
> * [ ]  Frontend Dev (HTML, CSS, JS)
> * [ ]  Frontend Dev (React, Angular, Vue)
> * [ ]  Golang
> * [ ]  Interview Prep
> * [ ]  Java
> * [ ]  JavaScript
> * [ ]  MERN
> * [ ]  Machine Learning
> * [ ]  Open Source
> * [ ]  Python
> * [ ]  Rust
> * [ ]  Statistics
> * [ ]  UI/UX
> 
> ## Checklist ✅
> * [x]  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
> * [x]  I have performed a self-review of my own code or work.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  My changes generates no new warnings.
> * [x]  I'm GWOC'21 contributor
> 
> `

Thanks! I've edited now.

**Pull request merged**
