### PR TITLE
ML 1.5 : Probability Distributions (Gaussian, Standard, Poisson) (A) #608

### PR DESCRIPTION
**Pull request by Pratyaksha-047**
<hr>

## Description 📜

Audio file explaining Probability Distributions (Gaussian, Standard, Poisson).

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please check out the Demo folder to understand how to contribute your audio contents.
Also provide the issue number while making the PR.
The PR name should be same as the issue name.
File name needs to be changed as, `ML_1_5_Probability Distributions (Gaussian, Standard, Poisson)_(A).md`

@Pratyaksha-047

**Comment by abhisheks008** [comment]
put the audio file link in correct manner, check out the Demo folder for more help @Pratyaksha-047

**Comment by Pratyaksha-047** [comment]
> put the audio file link in correct manner, check out the Demo folder for more help @Pratyaksha-047

Could you please tell me where to find this Demo folder. I can't seem to locate it.

**Comment by abhisheks008** [comment]
https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Demo

@Pratyaksha-047

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@Pratyaksha-047 one small change needed. Please rename the .md file name as, `ML_1_5_Probability Distributions(Gaussian,Standard,Poisson)_(A).md`

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
PR Merged @Pratyaksha-047 🎉

**Pull request merged**
