### PR TITLE
[JS] Topic : Labels and 'continue' 

### LINKED ISSUE #2629: JS: Labels and 'continue'
### Description

<li> Write about label statements.
<li> Write about break & continue statements.
<li> Tell about label statement using break and continue.
<li> Give Examples & Syntax of each.

### Domain

JavaScript

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by AbhinandanAdhikari**
<hr>

## Description 📜

Created documentation for JS Labels and 'continue'.
Fixes #2629

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AbhinandanAdhikari** [comment]
@paramsiddharth @dakshsethi @Creatoon @s4-2 Supervisor & Mentors! Please review this pull request.

**Review by paramsiddharth — APPROVED** [review]

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Comment by AbhinandanAdhikari** [comment]
@Creatoon @s4-2 Mentors! Please review

**Review by s4-2 — APPROVED** [review]
Looks good to me:)

**Pull request merged**
