### PR TITLE
1.1.5.4 Arrays: Standard Problems (Problem 4)

### LINKED ISSUE #1242: DSA 1.1.5.4 Arrays: Standard Problems (Problem 4)
## Description
Find the longest common subsequence in the 2 given sequences.

## Task
- [x] Documentation
- [x] Audio
- [x] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by saketsagarsingh**
<hr>

## Description 📜

Find the longest common subsequence in the 2 given sequences.
Fixes #1242

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] DS#A

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by saketsagarsingh** [comment]
Please Review my PR

**Comment by saketsagarsingh** [comment]
@goelesha please approve this PR

**Review by goelesha — CHANGES_REQUESTED** [review]
@saketsagarsingh Pls add time and space complexity and references at the end.

**Comment by saketsagarsingh** [comment]
@goelesha made changes kindly please merge it if all's well.

**Review by goelesha — COMMENTED** [review]
@saketsagarsingh Add the file inside arrays folder.

**Comment by nimisha-yadav** [comment]
@saketsagarsingh Please do the changes asap.

**Pull request closed without merging**
