### PR TITLE
CSS Gradients, Box Shadow and Text Shadow

### LINKED ISSUE #2376: CSS Gradients, Box Shadow and Text Shadow
### Description

Here I will be explaining CSS gradients, Box Shadow and Text Shadow, and add examples of some designs related to them.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by srijanishere**
<hr>

## Description 📜

A well-defined documentation for understanding of CSS gradients, box shadow and text shadow. Provided along with syntax and live examples
Fixes #2376 

<hr>

## Type of change 📝

- [ ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Yes screenshots of each example has been included in README.md
<hr>

### CODE REVIEW

**Comment by iamsunil25** [comment]
@praveenscience  can you assign me this issue?

**Review by code-reaper08 — APPROVED** [review]
Looks super cool @srijanishere 👏 
Nice work.

**Comment by code-reaper08** [comment]
> @praveenscience can you assign me this issue?

You need to get assigned in the **issues**, and not in **PR**.

**Comment by srijanishere** [comment]
> Looks super cool @srijanishere 👏
> Nice work.

Thanks a lot! I hope to keep contributing more.

**Pull request merged**
