### PR TITLE
C/CPP : Linear and Binary Search Documentation

### LINKED ISSUE #1145: C_CPP : Linear and Binary Search Documentation
<hr>

## Description 📜

I'll provide documentation for linear and binary searches in an array.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by areenoverclouds**
<hr>

## Description 📜

Added documentation on Linear and Binary Search Algorithms.
Domain: C/CPP
Format: Documentation
Fixes #1145

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by dishagupta2413** [comment]
I want to contribute to it.

**Comment by ChetasShree** [comment]
@dishagupta2413 u have to create your own issue and can't claim any issue from the PR section

**Comment by ChetasShree** [comment]
Amazing work @areenoverclouds !!
@Suvraneel @Saviour1001 pls check this PR :)
Thank you

**Comment by areenoverclouds** [comment]
> Amazing work @areenoverclouds !! @Suvraneel @Saviour1001 pls check this PR :) Thank you

Thank you :)

**Pull request merged**
