### PR TITLE
Creating a binary tree using linked list

### LINKED ISSUE #8469: Creation of Binary Tree using Linked List
### Description

Description

### Domain

C/C++

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by pinpan123**
<hr>

## Description 📜

C program to create a binary tree using linked list. I have demonstrated **two approaches**. Fixes  #8469

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Review by Suvraneel — CHANGES_REQUESTED** [review]
@pinpan123 
Finally, you've put it in a directory 
image

but you can NOT make your own folder...
Follow the roadmap & put your contribution in the appropriate directory...
In this case `C_CPP/Data Structures/LinkedList/`

**Comment by pinpan123** [comment]
okay

**Comment by pinpan123** [comment]
Done sir

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Needs documentation... Not just code

**Comment by pinpan123** [comment]
Updated

**Review by Suvraneel — CHANGES_REQUESTED** [review]
image

1. Pdf file not supported
2. Markdown (.md) formatting incorrect 
Read [here](https://www.markdownguide.org/cheat-sheet/)
3. Delete Duplicate file

**Comment by pinpan123** [comment]
Did the corrections

**Comment by Suvraneel** [comment]
@pinpan123  LGTM ❤️  🚀  :octocat: 

PS - Observe the changes... See the readme... Thats how we use it as an index to all our files...
I hope you've learnt something new from this PR regarding opensource stds 😄 

There's a lot more, left to learn (eg, conflicts that I've solved for you ) here :
image
All the best

**Comment by pinpan123** [comment]
Yes Sir, i definitely learned a ton of new things in this entire process. I am glad that you could provide me suggestions for improvement throughout. That helped me a lot and I am grateful for all the learnings. Thank you for that and for finally merging it!

**Pull request merged**
