### PR TITLE
Python _Socket_Module

### LINKED ISSUE #3746: PYTHON Socket Module
### Description

Understanding the socket module in python and writing a simple client-server program

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by shaurya24sri**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #3746

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by kumarankm** [comment]
@shaurya24sri  Use proper folder naming eg: Python_Socket_Module

**Comment by shaurya24sri** [comment]
OK I will change

**Comment by kumarankm** [comment]
Give a short note on the socket module in the main folder( i.e on python socket folder as readme in there was empty)

**Comment by shaurya24sri** [comment]
ok

**Comment by shaurya24sri** [comment]
@kumarankm i have updated

**Review by kumarankm — APPROVED** [review]
Looks good 👍🏻 
You can merge this pr @adityabisoi

**Pull request merged**
