### PR TITLE
Frontend web development react angular vue - Using Vue.js with CDN

### LINKED ISSUE #523: FRONTEND WITH FRAMEWORK: VueJS-1.2 => Introduction to VueJS using CDN
Contributors are required to include an Introduction of VueJS using CDN, which should cover questions like :-
What is VueJS CDN?
How to install VueJS with this?
A basic code, showing an implementation of VueJS with CDN .
etc....

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

### PR DESCRIPTION
**Pull request by Safwan310**
<hr>

## Description 📜

Added a file that explains how to use Vue.js with a CDN.
Fixes #523

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by SourabhSaraswat-191939** [comment]
Hi @Safwan310,
Looks good. But there are some corrections.
1) Explain the code a bit which you mentioned as an example. So that it will be good for a learner to get an idea. How it is working.
2) The image which you attached to show the output of the code is looking like a subtext of the upper heading. So, please change the image, you can attach an image in which this output is shown in the browser.

**Review by anandhu720 — CHANGES_REQUESTED** [review]
Some changes are required.Changes are mentioned by @SourabhSaraswat-191939 .
If you have any doubts contact @SourabhSaraswat-191939

**Review by anandhu720 — CHANGES_REQUESTED** [review]
image link is not attached correctly.
 is correct I think
Please cross check it

**Comment by Safwan310** [comment]
> image link is not attached correctly.
> `` is correct I think
> Please cross check it

But it works.... Anyway I will edit this line

**Review by anandhu720 — COMMENTED** [review]
Good work, need one more review from @SourabhSaraswat-191939 after that we can merge

**Review by anandhu720 — APPROVED** [review]

**Comment by SourabhSaraswat-191939** [comment]
> Good work, need one more review from @SourabhSaraswat-191939 after that we can merge

LGTM 👍🏻 
We can merge it.

**Pull request merged**
