### PR TITLE
Create Stack Operations

### LINKED ISSUE #7136: DSA 4.1.2 Implementation of Stacks - Audio/Video
## Description
Discuss in detail the implementation of Stacks in Java, Python, and C++

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [ ] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by Bhavika2210**
<hr>

## Description 📜

Here I am adding the drive link to the audio of explaining stack operations in mp3 format. I have explained keeping the CPP framework in mind 
Fixes #7136 
The details of the audio are as follows:
- Explaining what a stack data structure is though practical example
- Talked about the operations possible on stack when implemented by an Array
- Discussed about accessing the data elements through only one pointer, i.e Top
- Discussed in detail about the possible operations: push(), pop(), peek(), display().
<hr>

 Addition  of Audio 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by nimisha-yadav — COMMENTED** [review]
@Bhavika2210 push changes to GWOC DSA branch. And add some description about the topic in the readme

**Comment by Bhavika2210** [comment]
> @Bhavika2210 push changes to GWOC DSA branch. And add some description about the topic in the readme

Hi , can you confirm if I have made the necessary changes and if its reflecting

**Comment by nimisha-yadav** [comment]
> > @Bhavika2210 push changes to GWOC DSA branch. And add some description about the topic in the readme
> 
> Hi , can you confirm if I have made the necessary changes and if its reflecting

Not yet, you can check it for yourself as well. See on top, it should be ```girlscript : DSA``` instead of ```girlscript : main```

**Comment by nimisha-yadav** [comment]
Please do the changes asap. Let us know if you face any issue.

**Comment by Bhavika2210** [comment]
> Please do the changes asap. Let us know if you face any issue.

@nimisha-yadav i have done it can you please confirm.

**Pull request closed without merging**
