### PR TITLE
Issue #1105: Video content for Need of Java

### LINKED ISSUE #1105: Java 1.1: Need of Java
<hr>

## Description 📜

Add audio, documentation and video regarding the **Need of Java**.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `History of Java` folder. If the folder is not present, create the folder with this exact name. The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by Aman-Deshpande**
<hr>

## Description 📜

In this video we learn about need of Java and its Advantages
Fixes #1105

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AkMo3** [comment]
@garvitraj Please start the review process

**Comment by garvitraj** [comment]
@Aman-Deshpande good content for first 2 min instead of displaying a constant screen just use some presentation to show the stuff you are speaking
rest I like the delivery and content @AkMo3 pls watch the video once

**Comment by Aman-Deshpande** [comment]
Ok sir. Will consider the suggestions and deliver the video in a day or two

**Comment by Aman-Deshpande** [comment]
Sir I have updated the new video. Plz check and review

**Review by garvitraj — APPROVED** [review]
good work @Aman-Deshpande

**Comment by Aman-Deshpande** [comment]
@garvitraj can i now start working on the method overriding video which I was assigned a days ago

**Comment by garvitraj** [comment]
> @garvitraj can i now start working on the method overriding video which I was assigned a days ago

yes

**Pull request merged**
