### PR TITLE
DSA : Added Disjoint Set Union

### LINKED ISSUE #1164: Competitive Programming : Disjoint Set Union
<hr>

## Description 📜

Would like to add the documentation for Disjoint Set Union (Trees - Data Structures) 
Can you please assign me for this issue?
Thanks 

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming
- [x] DSA
- [x] Open Source

<hr>

### PR DESCRIPTION
**Pull request by hariketsheth**
<hr>

## Description 📜
- Added Documentation for Disjoint Set Union (Under Union Find)
- Added all the Coding Problems available for the same concept 
Fixes #1164 

Can you review this, @nimisha-yadav. Thank you !

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image
image

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Hi @hariketsheth, if you're in DSA, please send in your DSA batch number while creating issues/PRs. I don't see your name in the DSA contributor list so do send in your serial number in the list for future issues/PRs.

Assuming you're in DSA then as we have mentioned, contributors can only create issues/PRs for topics mentioned in the [Week Agenda](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA#roadmap-overview-of-code-structure) and for the initial week it is Array and Analysis of Algorithms. You may save this documentation for upcoming weeks. For now, feel free to create issues pertaining to Week 1 topics provided they have not been covered already, check [DSA Label](https://github.com/girlscript/winter-of-contributing/labels/DSA). I'm closing this PR for now, but do not hesitate to reach out in case of any doubt, all the best :)

**Comment by nimisha-yadav** [comment]
Also, your documentation was really structured and well-compiled, good work on that. Save this and it would definitely be considered once we work on this topic in the upcoming weeks!

**Comment by hariketsheth** [comment]
> Hi @hariketsheth, if you're in DSA, please send in your DSA batch number while creating issues/PRs. I don't see your name in the DSA contributor list so do send in your serial number in the list for future issues/PRs.
> 
> Assuming you're in DSA then as we have mentioned, contributors can only create issues/PRs for topics mentioned in the [Week Agenda](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA#roadmap-overview-of-code-structure) and for the initial week it is Array and Analysis of Algorithms. You may save this documentation for upcoming weeks. For now, feel free to create issues pertaining to Week 1 topics provided they have not been covered already, check [DSA Label](https://github.com/girlscript/winter-of-contributing/labels/DSA). I'm closing this PR for now, but do not hesitate to reach out in case of any doubt, all the best :)

Ohh I will follow the Agenda, I missed to check that out. 
Also, I am not in the DSA batch but I am really interested to contribute to DSA alongwith my actual batches. So, is it possible for me to contribute in DSA ?

**Comment by nimisha-yadav** [comment]
> 
> Ohh I will follow the Agenda, I missed to check that out.
> Also, I am not in the DSA batch but I am really interested to contribute to DSA alongwith my actual batches. So, is it possible for me to contribute in DSA ?

In that case, I'm afraid you can't contribute to DSA. Feel free to fill up the form in server ann channel if you're facing any issue regarding domains.

**Pull request closed without merging**
