### PR TITLE
Create FrontEnd : HTML Forms.md

### LINKED ISSUE #529: Front_End: HTML Forms
<h1>HTML Forms</h1>

- Creating HTML forms with HTML/CSS

<h3>Description</h3> 

- Forms Attributes
- Forms Elements
- Input Types
- Input Attributes
- Input Forms Attributes

### PR DESCRIPTION
**Pull request by GenMech**
<hr>

## HTML Forms📜

I have a good hold in Front End and got this issue and made a well documented file on HTML Forms. 
Fixes #529 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by GenMech** [comment]
@ghulamyazdani @code-reaper08  Pls have a look on this and let me know if there is any changes or it's good to go.

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Great job 👏 
Till now it's good, but you can make it more awesome by adding more attributes.
You now have only,

1. radio
2. submit
3. reset
4. Password
5. checkbox

You can add more like date, email to name a few.

**Comment by GenMech** [comment]
> Great job 👏
> Till now it's good, but you can make it more awesome by adding more attributes.
> You now have only,
> 
> 1. radio
> 2. submit
> 3. reset
> 4. Password
> 5. checkbox
> 
> You can add more like date, email to name a few.

Ok I am adding them too

**Comment by GenMech** [comment]
I have added more attributes and also added Select elements attribute @code-reaper08

**Comment by GenMech** [comment]
@code-reaper08

**Review by code-reaper08 — COMMENTED** [review]
Hello it looks nice now 👏 
You could also take your time to add more content. Since this would later become a fantastic learning material, where thousands of people are gonna refer to your documentation.

You could add much more topics. If you need any help, hop into Discord.

**Comment by GenMech** [comment]
@praveenscience Sir i have got some branching issue pls look at this PR and merge it if it is good to go.

**Comment by GenMech** [comment]
@code-reaper08 @sifa123 Why my file is deleted 😥

**Pull request merged**
