### PR TITLE
Create CSS Rules and Readme File

### LINKED ISSUE #2313: CSS general rule
### Description

I'll be adding documentation about rule's one should follow for css.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by brassgolem-25**
<hr>

## Description 📜

In this PR, i have committed/resolved some basic rules for css 
- How to add CSS
- Colors
- Typography/Font
- Selectors
- and !important tag
Fixes #2313 

<hr>

## Type of change 📝

 - [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
 - [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
 - [ ] Other (If you choose other, Please mention changes below)

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ]  Android Dev #(Java)
- [ ]  Android Dev #(Kotlin)
- [ ]  Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ]  Backend Dev #(Python)
- [ ]  C/#CPP
- [ ]  Competitive #Programming
- [ ]  Cyber #Security
- [ ]  DS#A
- [ ]  Data#base
- [ ]  Datascience with #Python
- [ ]  Datascience with #R
- [x]  Frontend Dev HTML/CSS/JS
- [ ]  Frontend Dev #React/Angular/Vue
- [ ]  Go#lang
- [ ]  Interview #Prep
- [ ]  Java_#Domain
- [ ]  Java#Script
- [ ]  ME#RN
- [ ]  Machine #Learning
- [ ]  Open #Source
- [ ]  Python_#Domain
- [ ]  Ru#st
- [ ]  Statis#tics
- [ ]  UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by brassgolem-25** [comment]
@sifa123 Please check this PR, Any feedback is highly appreciated!

**Comment by brassgolem-25** [comment]
@code-reaper08 @praveenscience please do check it !!

**Review by himanshu007-creator — APPROVED** [review]

**Comment by brassgolem-25** [comment]
@praveenscience i have updated the template please have a look ?!

**Comment by brassgolem-25** [comment]
@code-reaper08 hey it'been almost a week since this pr is opened and as i mentioned if there's any feedback to improve i'll work on it. Do check this

**Review by code-reaper08 — APPROVED** [review]
LGTM ✨

**Pull request merged**
