### PR TITLE
Issue #3256 

### LINKED ISSUE #3256: DSA 1.2.2.2 Algorithms: Lower and Upper bounds - Audio/Video
## Description
Discuss Asymptotic Notations. What are Lower and Upper bounds? Describe their usages.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by shahhilag**
<hr>

## Description 📜

I have covered the following topics in detail in the video file:
<ol>
<li>What are Asymptotic Notations</li>
<li>What is the use of asymptotic notations</li>
<li>A world without Asymptotic Notations</li>
<li>Major Asymptotic Notations</li>
<li>Big O(Upper Bound)</li>
<li>Omega(Lower Bound)</li>
<li>Theta Notation</li>
</ol>

Fixes #3256 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by shahhilag** [comment]
@nimisha-yadav  please review this new pull request

**Review by nimisha-yadav — APPROVED** [review]
Looks good. The video is very well created, with crisp and clear explanation - covering all the important sub-topics. Great work. Also, you can name your md file as readme only.
@sneha-nitdgp @harshsri28 is the PR fine by you?

**Comment by shahhilag** [comment]
Thankyou very much @nimisha-yadav mam.
I have made the filename changes.

**Review by harshsri28 — APPROVED** [review]
LGTM

**Comment by shahhilag** [comment]
Thankyou @harshsri28 sir

**Comment by nimisha-yadav** [comment]
Congrats on getting your PR merged! Happy first contribution, many more to come :')

**Comment by shahhilag** [comment]
Thabkyou very much.

**Pull request merged**
