### PR TITLE
Added the Documentation for Multimap and Unordered multimap

### PR DESCRIPTION
**Pull request by sujal2048**
<hr>

## Description 📜

Multimap is an associative container that contains a sorted list of key-value pairs, while permitting multiple entries with the same key. Sorting is done according to the comparison function Compare, applied to the keys.
Fixes  <2610> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
@sujal2048 
- you must have to put your content into respective directories !!
- like in this case your contribution can goes ` /C_CPP/Data Structures/Standard Template Library/ ` here.
- make a file name Map and put your content there
- revert all things that you have done in this Pr
- Plagiarism Detected from some sources..try to use your own words. try to restructure/rephrase some sentences a little bit
- Most important use some markdown formatting .. [link](https://www.markdownguide.org/basic-syntax/)

Hope it will make sense to you !

**Review by Suvraneel — CHANGES_REQUESTED** [review]
+1 to @vasu-1  Do it

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@sujal2048 Please add a md file and not a txt file and make use of the markdown formatting as suggested by @vasu-1

**Comment by Suvraneel** [comment]
image

Plagiarised from here :  https://www.geeksforgeeks.org/mapat-c-stl/

**Pull request closed without merging**
