### PR TITLE
Infix to Postfix using stack in C++ #6945

### PR DESCRIPTION
**Pull request by Narotam-singh**
<hr>

## Description 📜

I have written documentation on converting Infix expression to Postfix expression using Stack in C++. 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Narotam-singh** [comment]
@Saviour1001 Kindly review the PR.

**Review by vasu-1 — CHANGES_REQUESTED** [review]
This stuff is already there in main repo.you can watch it [here ](https://github.com/girlscript/winter-of-contributing/tree/C_CPP/C_CPP/Data%20Structures/Stack/Infix%2C%20Prefix%20%26%20Postfix%20(Application%20of%20Stack))

- kindly close this pr and respective issue.

**Comment by Narotam-singh** [comment]
But those files are about the evaluation of infix, postfix and prefix expression.
My code is about converting infix to postfix

**Comment by vasu-1** [comment]
ohk ohk 😅
i didn't see that thing ! sorry for this !

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please add your file link into respective readme file !
Happy Diwali 😃

**Comment by Narotam-singh** [comment]
Kindly review @vasu-1

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image

Rephrase the sentences for avoiding the plagiarisms !

**Review by vasu-1 — CHANGES_REQUESTED** [review]
There is also merge conflict !
That must be resolved first!

**Comment by vasu-1** [comment]
for this merge conflict ::  revert back your last commit(Readme updation's commit) and then fetch the repo and then again edit the readme !

**Comment by Narotam-singh** [comment]
Can you tell how to revert

**Comment by Narotam-singh** [comment]
Shall I close this PR and Open a new PR?

**Comment by Saviour1001** [comment]
Resolved the merge conflicts. Do the other changes asked above and this PR is good to merge

**Comment by Narotam-singh** [comment]
I have already made the changes in "changed" commit

**Comment by Narotam-singh** [comment]
@Saviour1001 @vasu-1 Kindly review

**Comment by vasu-1** [comment]
👍🏻

**Pull request merged**
