### PR TITLE
Added Documentation for Balanced Parenthesis Problem for Multiple Parenthesis

### LINKED ISSUE #8093: [Create New Issue]: Balanced Parenthesis problem for multiple Parenthesis
### Description

I'll be implementing the code and pseudo code for Balanced Parenthesis problem for Multiple brackets

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #8093 

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] DSA

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav Please review my PR

**Review by nimisha-yadav — COMMENTED** [review]
Add your file in [this folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/4.1%20Stacks/15.%20Balanced%20Parenthesis%20in%20Expression) as its README.md

**Comment by VaibhavMalik4187** [comment]
> Add your file in [this folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/4.1%20Stacks/15.%20Balanced%20Parenthesis%20in%20Expression) as its README.md

Done

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav Can you please review it now?

**Comment by nimisha-yadav** [comment]
There's no file change

**Comment by VaibhavMalik4187** [comment]
> There's no file change

Sorrry for such a mistake, now I have fixed it, can you review it now?

**Review by nimisha-yadav — APPROVED** [review]

**Comment by VaibhavMalik4187** [comment]
Thanks for merging my PR and being active this late

**Comment by nimisha-yadav** [comment]
@VaibhavMalik4187 If you're looking to contribute more, feel free to take up these two problems:
4. Array Implementation of Stacks
5. Implement stack using 2 queues

We're looking to fill up these topics and would appreciate if any contributor can take them up :)

**Comment by nimisha-yadav** [comment]
> Thanks for merging my PR and being active this late

No worries, thanks for contributing :)

**Comment by VaibhavMalik4187** [comment]
> @VaibhavMalik4187 If you're looking to contribute more, feel free to take up these two problems: 4. Array Implementation of Stacks 5. Implement stack using 2 queues
> 
> We're looking to fill up these topics and would appreciate if any contributor can take them up :)

I would be more than happy to get assigned to these topics, you assign these topics to me right away, I'll create the documentation very soon

**Comment by nimisha-yadav** [comment]
> I would be more than happy to get assigned to these topics, you assign these topics to me right away, I'll create the documentation very soon

That's great to hear. The folder with same serial no. are already there, you may create the issues, and add the file in those folders. We review and merge :)

**Comment by VaibhavMalik4187** [comment]
> > I would be more than happy to get assigned to these topics, you assign these topics to me right away, I'll create the documentation very soon
> 
> That's great to hear. The folder with same serial no. are already there, you may create the issues, and add the file in those folders. We will review and merge :)

I got you :)

**Pull request merged**
