### PR TITLE
Data Science with Python : Contrast Stretching using Matplotlib #7362

### LINKED ISSUE #7362: Data Science with Python : Contrast Stretching using Matplotlib
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know on how to use and implement Contrast Stretching using Matplotlib.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Computer Vision

Mentors Assigned : Aishanu Singh | Ankit Kumar

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Jinal4502**
<hr>

## Description 📜

I have added the complete documentation tutorial on 'Contrast Stretching Using Matplotlib' alongwith its implementation in jupyter-notebook.
Fixes #7362

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add how it works, why its necessary, advantages of applying it and conclusion. Its been said using Matplotlib but how its useful isn't mentioned in README.md. Yes, change the file name to README.md
In .ipynb, add short intro at start of the file, add appropriate comments along with text to get good understanding of the code operations and overall summary at the end.
Since it's Computer Vision issue, add your visualizations and image screenshots in "Images" folder
Also "requirements.txt" file, where in list of libraries used in this issue are added.

@Jinal4502

**Comment by Jinal4502** [comment]
@prathimacode-hub, ma'am I have done all the changes you mentioned. First I have changed the name of readme.txt to README.txt, alongwith it, I have added the necessity and advantages of matplotlib and also added the conclusion. I also created folder named Images in which there are output images. I have also added requirements.txt file. And lastly, I have also added introduction, summary and more comments for better explanation in the .ipynb file. Please check it, thank you!

**Comment by prathimacode-hub** [comment]
I couldn't find the changes that's been done at .ipynb file. Hope its pushed correctly. Check it. @Jinal4502

**Comment by Jinal4502** [comment]
@prathimacode-hub, ma'am, I have again replaced the .ipynb file with the updated one, can you please check it now, thank you!

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. Keep it up. 👌👏@Jinal4502

**Pull request merged**
