### PR TITLE
Booleans in Python

### PR DESCRIPTION
**Pull request by pinpan123**
<hr>

## Description 📜

This is a video presentation to illustrate Boolean data type in Python. I have covered the following topics in the video:
Overview

- The Boolean type
- Evaluating variables and expressions
- Integers and Floats as Boolean expressions
- Boolean Arithmetic (With operators and their examples)

A Google Drive link to view the video is provided. https://drive.google.com/file/d/1U9qd_qhHize1AEBv4a24_vSmIIslJbwI/view?usp=sharing

Fixes issue #971

<hr>

## Type of change 📝

- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by kumarankm** [comment]
Use folder name as Boolean_in_Python

**Comment by kumarankm** [comment]
And give a short introduction about video in that readme filrr

**Comment by pinpan123** [comment]
Done!

**Comment by kumarankm** [comment]
I said to create folder named ```Boolean_in_Python``` and inside that add file in readme with a short intro about video and video link

**Comment by pinpan123** [comment]
I created new PR.Please check:
https://github.com/girlscript/winter-of-contributing/pull/8554

**Pull request closed without merging**
