### PR TITLE
search an element in an array #2495

### LINKED ISSUE #2495: search an elemennt in an array
### Description

using dsa solving problem search an element in an array.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ShivaniAgarwal2001**
<hr>

## Description 📜

Explained different types of Searching Algorithm with Algorithm their example.
Concluded, **Binary Search Algorithm** is best among all searching Algorithms.

Fixes #2495

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS
- [x] JavaScript_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by kashishahuja2002** [comment]
No updates for long, make changes or close the PR. @ShivaniAgarwal2001 

Please close this PR, @praveenscience

**Comment by ShivaniAgarwal2001** [comment]
> No updates for long, make changes or close the PR. @ShivaniAgarwal2001 
> 
> Please close this PR, @praveenscience 

I will update it by tomorrow.

**Comment by kashishahuja2002** [comment]
> > No updates for long, make changes or close the PR. @ShivaniAgarwal2001
> > Please close this PR, @praveenscience
> 
> I will update it by tomorrow.

Okay

**Comment by kashishahuja2002** [comment]
> I will update it by tomorrow.

No updates yet, please close this PR. @praveenscience

**Pull request closed without merging**
