### PR TITLE
Data Science with Python : Movie Recommendation Systems #1939

### LINKED ISSUE #1939: Data Science with Python : Movie Recommendation Systems
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Movie Recommendation Systems. Tutorial to Movie Recommendation Systems and how it's applied using code snippets.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Dhruv Bajaj / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜

Made a video presentation on the topic of movie recommendation system.
Fixes #1939 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor.
<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you please evaluate the PR mam.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

Add conclusion and final summary in README.md
According to issue, sample code of movie recommendation system should also be addressed.

Kindly work on it. @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam can you please evaluate my PR , I made the changes.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Keep blazing high. I highly appreciate your efforts. This is one of the curated PR and to the point. Amazing work done. 🙌✨ @ashish-reddy-20-08

**Pull request merged**
