### PR TITLE
Frontend With Framework: VueJS-1.5 => Installing Vue-DevTools

### LINKED ISSUE #618: FRONTEND WITH FRAMEWORK: VueJS-1.5 => Installing Vue-DevTools
Contributors are required to include a procedure to Install Vue-DevTools, which should cover questions like:-
What is Vue-DevTools?
Why it is needed?
How to install it?
How to open Vue-DevTools in the browser? (you can make GIF, which shows how to open this)
etc....

**And also mention that we will learn, how to use it further in the upcoming topics.**

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

### PR DESCRIPTION
**Pull request by Saurabh-crypto16**
<hr>

## Description 📜

VueJS-1.5 => Installing Vue-DevTools
What is Vue-DevTools?
Why it is needed?
How to install it?
How to open Vue-DevTools in the browser?
Fixes #618

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Saurabh-crypto16** [comment]
@the-pro

**Review by anandhu720 — COMMENTED** [review]
guys we have told you many times please add Frontend With Framework before main heading.Please follow this order.Because we are searching PR using this keyword

**Comment by Saurabh-crypto16** [comment]
> guys we have told you many times please add Frontend With Framework before main heading.Please follow this order.Because we are searching PR using this keyword

Done, sorry for the inconvenience

**Comment by SourabhSaraswat-191939** [comment]
Looks good,
1) Please change your file name. Make it simple as per indexing in roadmap like -> "Installing Vue-Devtools.md".
2) You can add commands for windows users to open developer tools in the bracket of mac command " Cmd-Alt-i "

**Review by anandhu720 — CHANGES_REQUESTED** [review]
please add changes suggested by @SourabhSaraswat-191939

**Comment by Saurabh-crypto16** [comment]
@anandhu720 and @SourabhSaraswat-191939 please check the changes

**Review by anandhu720 — COMMENTED** [review]
It is fine for me, we can megre it if it is okey for  @SourabhSaraswat-191939 also

**Review by anandhu720 — APPROVED** [review]
great

**Pull request merged**
