### PR TITLE
Added the documentation

### LINKED ISSUE #2729: How to Ace Online Assessments
### Description

**Description**

1. How Assessments are planned?  
2. What types of tests are there?  
3. What are Prerequisite knowledge and requirements? 

**Domain** 
_Interview Preparation_ 

**Type of Contribution**
_Documentation, Video_ 

 **Code of conduct** 
- [ ]   I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

Interview Prep

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by whatmansi**
<hr>

## Description 📜

Added the documentation part to the topic "How to Ace Online Assessments."

It contains these sub topics -
How Assessments are planned?
Why Assessments are planned?
What types of tests are there?
What are Prerequisite knowledge and requirements?
Tips to ace online assessments
 
Fixes #2729

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [X] Interview Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by syedareehaquasar** [comment]
Please add tips how to ace the online assessment as heading says so!

**Comment by syedareehaquasar** [comment]
Also changed first heading how these assessments are planned to why are these planned.

**Comment by syedareehaquasar** [comment]
In tips you can cover practicing, breaking sentence to points, sites one can refer! Also add issue u are solving no. in description of pr fixes #....

Great effort let's merge it soon!

**Comment by whatmansi** [comment]
Is it alright now?

**Comment by syedareehaquasar** [comment]
add .md to file name (suffix for markup support)

**Comment by syedareehaquasar** [comment]
Looks good to me. Please add references if u have used any and also add some sites that can be used for practicing!

**Comment by syedareehaquasar** [comment]
Let's merge this today!

**Pull request merged**
