### PR TITLE
Operations in Binary Tree

### LINKED ISSUE #7376: Operations in Binary Tree
### Description

I have prepared a documentation on Operations in Binary Tree which includes:
- Inserting an element into a Binary Tree
- Deleting an element from a Binary Tree
- To traverse through the Binary Tree in INORDER
- To count the number of nodes in the Binary Tree
- To find the height of the Binary Tree
- To traverse tree in LEVEL ORDER
- To search a value in the Binary Tree

Hope you learn from the documentation :)

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜

I have prepared a documentation on Operations in Binary Tree which includes:
- Inserting an element into a Binary Tree
- Deleting an element from a Binary Tree
- To traverse through the Binary Tree in INORDER
- To count the number of nodes in the Binary Tree
- To find the height of the Binary Tree
- To traverse tree in LEVEL ORDER
- To search a value in the Binary Tree

Hope you learn from the documentation :)

Fixes #7376  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Kavya, your content is good.
But do mention websites as a reference section to avoid the plagiarism thing 
image

**Comment by ikavyajain** [comment]
I’ll edit the code sir

**Comment by ikavyajain** [comment]
@deeqakkk Made the required changes! :)
According to me the code has no faults, no plagiarism :(
It was just that some sentences that we commonly use in our codes were creating such a problem! :)
Kindly have a look :)

**Comment by ikavyajain** [comment]
@Suvraneel Please have a look :)

**Comment by Suvraneel** [comment]
@deeqakkk

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Kavya, your content has exact similarities with these two websites, either mention these websites as a reference section or try to explain things in your own words.

**Comment by ikavyajain** [comment]
Okay

**Comment by ikavyajain** [comment]
@deeqakkk added a referral site for code. You can check

**Comment by Suvraneel** [comment]
@ikavyajain  Still wont do ... Too much percentage...
image

**Comment by ikavyajain** [comment]
@Suvraneel is it okay ?

**Comment by Suvraneel** [comment]
@ikavyajain  Still needs documentation... Code se pehle

**Pull request closed without merging**
