### PR TITLE
Data Science with Python : Ensemble Methods

### LINKED ISSUE #427: Ensemble Methods
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Ensemble Methods. Tutorial to Ensemble Methods and how it's applied.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Shivang Dubey / Yash Goel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by nakshatra-garg**
<hr>
@prathimacode-hub

## Description 📜

I've created documentation for ensemble methods in python and explained multiple algorithms with code examples alongwith comments.
Fixes #427

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nakshatra-garg** [comment]
Please Review @prathimacode-hub

**Review by prathimacode-hub — COMMENTED** [review]
This PR is currently under reviewing process. @nakshatra-garg

**Comment by prathimacode-hub** [comment]
Changes to be done 👍 

- The issue contribution should be under "/Machine Learning/Tutorials/Ensemble Methods
- Elaborate your README file. It needs more detailing. You can find the things you can add up in Project structure document
- The project file name should be in snake case : ensemble_methods.ipynb
- If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Emsemble Methods"

You had done a good representation of Ensemble methods, but it lacks detailing. Kindly work on it, especially README.md file. 

@nakshatra-garg

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

- The issue contribution should be under "/Machine Learning/Tutorials/Ensemble Methods
- Elaborate your README file. It needs more detailing. You can find the things you can add up in Project structure document
- The project file name should be in snake case : ensemble_methods.ipynb
- If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Emsemble Methods"

You had done a good representation of Ensemble methods, but it lacks detailing. Kindly work on it, especially README.md file. 

@nakshatra-garg

**Review by nakshatra-garg — COMMENTED** [review]
I've made the requested changes @prathimacode-hub.
Kindly check.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add advantages, applications and conclusion in your README.md file. If you had referred any resources add them in "DS Resources". @nakshatra-garg

**Comment by nakshatra-garg** [comment]
I've made the requested changes. But, I had to open a new pull request #1912 Because there was some conflict in the current one and I couldn't solve it so I had to fork again and open a new pull request. I hope you'll understand.
Please review #1912

**Pull request closed without merging**
