### PR TITLE
In main Frontend_Web_Development is missing & I add in Programming Fundamentals of Javascript

### LINKED ISSUE #2472: Frontend_Web_Development is missing or archieved from GWOC.
### Description

From the GWOC, Frontend_Web_Development is missing or archived.
I have a forked copy of it, from where I work on JavaScript Fundamental and I add about the Script Tag.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Sin-Sumit**
<hr>

## Description 📜
Programming Fundamentals in JavaScript, add all about the first basic tag i.e., script tag.  

Fixes #2472

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generates no new warnings.
- [ X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by sifa123** [comment]
Hey, I think the GWOC team will merge ours into the main. So far, we should continue contributing to our branch and when time comes, Gaurav or his team will work on this. What do you say @code-reaper08 @praveenscience ?

**Comment by code-reaper08** [comment]
> Hey, I think the GWOC team will merge ours into the main. So far, we should continue contributing to our branch and when time comes, Gaurav or his team will work on this. What do you say @code-reaper08 @praveenscience ?

Exactly @sifa123 , we at the moment don't need to worry about `main` branch.
@Sin-Sumit Just have your contributions on FEWD, the domain branches will be merged later by **GWoC team**.

**Fun Fact :** This can't even be merged by us (we are not authorized to do so) 🤣

**Comment by Sin-Sumit** [comment]
I got scared when I unable to find FEWD.

**Comment by Sin-Sumit** [comment]
Hey, @sifa123 @code-reaper08 Now, I'm unable to create PR. Github only showing the view last PR i.e., this PR only, not able to create new PR.

**Comment by Sin-Sumit** [comment]
@sifa Please Make a Review of this PR.

**Comment by Sin-Sumit** [comment]
@sifa123 @code-reaper08  I'm facing a problem, Github is not creating a new PR for this FEWD branch, it shows only view the last PR i.e., this PR#2471. I think on merging this PR, I will be able to create a new PR.

**Review by sifa123 — APPROVED** [review]
Well explained 🥳

**Comment by Sin-Sumit** [comment]
Thank You

**Pull request merged**
