### PR TITLE
C/CPP  : Nested Loops documentation

### PR DESCRIPTION
**Pull request by pranjalambesh**
Nested loops in C/CPP

<hr>

## Description 📜

In this document nested loops are briefly explained and discussed. . This documentation contains definition , syntax or format , Flow of code and Few examples on nested loops.

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Pranjal, the use of .md file is preferred, so plz change .txt to .md with proper tags.

**Comment by pranjalambesh** [comment]
Ok thanks

**Comment by vasu-1** [comment]
Another thing is your file should go here `/C_CPP/Fundamentals/Looping Control Structure or Statements/`

**Comment by pranjalambesh** [comment]
> Another thing is your file should go here `/C_CPP/Fundamentals/Looping Control Structure or Statements/`

can you please elaborate

**Comment by vasu-1** [comment]
currently, you have made your file in the `/C_CPP/c++14/` folder.
but you should make your file in this `/C_CPP/Fundamentals/Looping Control Structure or Statements/` folder.

**Comment by vasu-1** [comment]
so change your file path .!!!
i hope it will make sense to you

**Comment by pranjalambesh** [comment]
> so change your file path .!!! i hope it will make sense to you

yeah thanks

**Review by pranjalambesh — COMMENTED** [review]
changed the path of file

**Review by Suvraneel — CHANGES_REQUESTED** [review]
- Update readme with relative link
- Run a formatter on this

**Comment by Suvraneel** [comment]
@vasu-1  Nice review btw

**Comment by vasu-1** [comment]
@pranjalambesh 
Please do some markdown formatting 
so documentation can look nice !

see this [link](https://www.markdownguide.org/basic-syntax/) if you are not knowing markdown formatting.

**Comment by pranjalambesh** [comment]
> * Update readme with relative link
> * Run a formatter on this

I have updated with formatting can you please check it and explain what I have to do with readme.md file

**Comment by pranjalambesh** [comment]
> @pranjalambesh 
> 
> Please do some markdown formatting 
> 
> so documentation can look nice !
> 
> 
> 
> see this [link](https://www.markdownguide.org/basic-syntax/) if you are not knowing markdown formatting.

.

**Comment by vasu-1** [comment]
Screenshot_2021-10-03-21-26-24-53
Align your code to left

**Comment by vasu-1** [comment]
Also there are some markdown formatting errors please check it for once.

**Pull request closed without merging**
