### PR TITLE
Insertion operation in linked list 

### PR DESCRIPTION
**Pull request by akratikushwah**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 
issue number #7455 
<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by akratikushwah** [comment]
please check @vasu-1

**Comment by vasu-1** [comment]
image
Remove this `#` from both the words for labeling

**Review by vasu-1 — CHANGES_REQUESTED** [review]
- First of all add your  file link into respective `readme.md` file
- add explaination of the insertion operation (you can write steps or pseudo code)
- Also do some markdown formatting
- Make a function called `insertion` and do the stuff in that function.

**Comment by vasu-1** [comment]
Also mention time nd space complexities

**Comment by akratikushwah** [comment]
please review again @vasu-1

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Add file link in the readme.md

**Comment by akratikushwah** [comment]
Done Please review again @vasu-1

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Just Last Changes ..
Beautify your inputand output (by putting them in backticks)..
And Also Add Explenation of insertion operation.
Mention time and space complexities.

**Comment by akratikushwah** [comment]
Done @vasu-1

**Review by vasu-1 — CHANGES_REQUESTED** [review]
move the explaination before the code snippet.

**Comment by akratikushwah** [comment]
Done @vasu-1

**Review by vasu-1 — APPROVED** [review]
LGTM @akratikushwah 

@Saviour1001

**Pull request merged**
