### PR TITLE
Python: 1.5 Brief history of python

### PR DESCRIPTION
**Pull request by Yashesvinee**
<hr>

## Description 📜

Created and added Video to Python: 1.5 Brief history of Python
Issue #76 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
----
[Brief history](https://drive.google.com/file/d/1UlFpH0LBUs57MM-h0nHtYSCPHo1xwJsV/view?usp=sharing "Brief history")
<hr>

### CODE REVIEW

**Comment by Yashesvinee** [comment]
@adityabisoi  I made the required changes

**Comment by Yashesvinee** [comment]
@adityabisoi

**Comment by adityabisoi** [comment]
Please resolve conflicts

**Comment by Yashesvinee** [comment]
@adityabisoi i have a doubt...
someone's pull request was merged before mine so it is creating conflicts in mine because of the change in the readme file. The same happened in the morning how do I prevent this?

**Comment by Yashesvinee** [comment]
i resolved them  please check it now

**Comment by Yashesvinee** [comment]
This is just a suggestion but wouldn't it be better if the readme file is updated to contain all the topics so there is no need to change it everytime a person contributes to a new topic

**Comment by adityabisoi** [comment]
> This is just a suggestion but wouldn't it be better if the readme file is updated to contain all the topics so there is no need to change it everytime a person contributes to a new topic

That way, it will contain empty links. Better to update them with each topic.

**Comment by Yashesvinee** [comment]
Okay thanks

**Pull request merged**
