### PR TITLE
DSA 1.1.5.5 Arrays: Standard Problems (Problem 5)

### LINKED ISSUE #2237: DSA 1.1.5.5 Arrays: Standard Problems (Problem 5)
### Description

Find the least average subarray in a given array.

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by RahulJaiswal-18**
<hr>

## Description 📜

DSA 1.1.5.5 Arrays: Standard Problems (Problem 5)
Find the least average subarray in a given array.
Fixes #2237

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by Anandkx007** [comment]
please assign it to me

**Review by vikhyatsingh123 — CHANGES_REQUESTED** [review]
change your file extension to .md

**Review by vikhyatsingh123 — CHANGES_REQUESTED** [review]
Add time complexity of efficient approach too. It will be better if you made separate heading of time complexity.

**Comment by goelesha** [comment]
@RahulJaiswal-18 Pls create the file inside the Standard Problems folder in arrays.

**Review by goelesha — COMMENTED** [review]
@RahulJaiswal-18 Pls create the file inside the Standard Problems folder in arrays.

**Comment by RahulJaiswal-18** [comment]
@goelesha @vikhyatsingh123 I have done the changes suggested by you. Please review and suggest if something need's to be changed

**Review by goelesha — APPROVED** [review]
@RahulJaiswal-18 Looks good to me. Congrats on getting your PR merged.

**Pull request merged**
