### PR TITLE
[DSA] 1.1.3.6 Array: Range Queries

### LINKED ISSUE #473: DSA 1.1.3.6 Arrays: Range Queries
## Description
Provide the description and implementation of Square Root Decomposition Technique.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by motasimmakki**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #473 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise, Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations, and regular explanatory films are all possibilities, etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] DS#A

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Discuss about intuition and algorithm and about time complexity and space complexity.

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Add input-output examples and discuss time and space complexities

**Comment by motasimmakki** [comment]
> Add input-output examples and discuss time and space complexities

Kindly review, I've added the Time and Space complexity and also the Input/Output example.

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by harshsri28 — APPROVED** [review]
LGTM

**Comment by motasimmakki** [comment]
> Please review @harshsri28 @sneha-nitdgp

Kindly merge this PR.

**Review by nimisha-yadav — COMMENTED** [review]
LGTM. Just rename your file 1.1.3.6_Square_Root_Decomposition.md

**Comment by motasimmakki** [comment]
> LGTM. Just rename your file 1.1.3.6_Square_Root_Decomposition.md

Kindly check it.

**Review by nimisha-yadav — APPROVED** [review]
Congrats on getting your PR merged!

**Pull request merged**
