### PR TITLE
Machine learning

### PR DESCRIPTION
**Pull request by purvanshgarg**
<hr>

## Description 📜

This is to inform that a video contribution has been made to give the people starting their ml journey some basic idea about topics like variance, standard deviation and expectation.
Fixes # 607 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Randrita — COMMENTED** [review]
content looks fine from my end. have a look @abhisheks008 @raina-akshay

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
The video content is good but the reference links that you've provided looks messed up. Try to use bullet points to show the links.
Eg. 
1. Expected Value (https://en.wikipedia.org/wiki/Expected_value)
2. ....
3. ....
4. so on....

**Comment by purvanshgarg** [comment]
I had used '-' as bullets but after creating pull request it automatically shifted to this structure

**Comment by purvanshgarg** [comment]
is it ok now, I tried applying the changes you mentioned

**Pull request merged**
