### PR TITLE
Java 2.3 : Blocks & Lexicals - Audio

### LINKED ISSUE #1199: Java 2.3:
<hr>

## Description 📜

Add audio, documentation, and video regarding the **Blocks and lexicals**.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `Blocks and lexicals` folder which is inside the `Fundamental` folder present in the  `Java` main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by UditJain77**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1199 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by AkMo3** [comment]
@UditJain77 Please comment on discord in your respective Java batch channel so that appropriate mentor can take a look

**Comment by UditJain77** [comment]
@AkMo3 yes, I have commented in Batch -5 and tagged you. Kindly check.

**Comment by AkMo3** [comment]
@UditJain77 Keep in mind from next time to keep length less than 6 min. As I had iterated this before, keep it simple, straight to the point. I am approving, for the time being, it may be required to be changed if the next review feel so

**Review by AkMo3 — APPROVED** [review]
@garvitraj

**Comment by garvitraj** [comment]
> @UditJain77 Keep in mind from next time to keep length less than 6 min. As I had iterated this before, keep it simple, straight to the point. I am approving, for the time being, it may be required to be changed if the next review feel so

@UditJain77 pls follow this guideline try to keep audio within 5 min

**Review by ghost — APPROVED** [review]
From next time keep the audio within 5min

**Comment by UditJain77** [comment]
@garvitraj Yeah sure, i'll keep take care of that next time onwards. Am i eligible to take up a new issue from tomorrow onwards?

**Pull request merged**
