### PR TITLE
Java 1.3: Evolution of Java

### PR DESCRIPTION
**Pull request by Yashesvinee**
<hr>

## Description 📜

Added Video to Evolution of Java. Video gives a gist of Java's evolution and its versions. Duration- 1:30min approx
Issue #1107 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
[Video link](https://drive.google.com/file/d/1eFeqKZ9iwe574Mbwl0-lP_6pAQZyEaew/view?usp=sharing)
<hr>

### CODE REVIEW

**Comment by Yashesvinee** [comment]
@AkMo3

**Comment by AkMo3** [comment]
@sakshamlamba109 Please start the review process. @Yashesvinee Congratulations on start of journey 🥳

**Comment by Yashesvinee** [comment]
> @sakshamlamba109 Please start the review process. @Yashesvinee Congratulations on start of journey 🥳

Thank you

**Comment by garvitraj** [comment]
@Yashesvinee pls use the tool which doesn't have a watermark if you are making slides then prefer PowerPoint
try to find out something from there.
Rest content is good just com back with the changes

**Comment by Yashesvinee** [comment]
hi i have removed the watermark
is it fine now?

**Comment by AkMo3** [comment]
@Yashesvinee The video is great. Just one problem, the image you have used is actually a copyright image and we cannot use that.

Can you please add your own graphic. There are still 6 days left so lets not hurry up the merge the PR.

PS: I am talking about this image.
image

**Comment by Yashesvinee** [comment]
Okay

**Comment by AkMo3** [comment]
Also, the latest version is JDK 17. Please see https://openjdk.java.net/projects/jdk/17/

**Comment by garvitraj** [comment]
@Yashesvinee whats the progress and update

**Comment by Yashesvinee** [comment]
I am making some changes in my video
It will be ready by tomorrow

**Comment by AkMo3** [comment]
@Yashesvinee Please share some updates on it.

**Comment by Yashesvinee** [comment]
hi there are some conflicts that i am unable to solve can I open another pull request after I make some changes in my repo?

**Comment by AkMo3** [comment]
@Yashesvinee Just rename your file to `Evolution_Of_Java_Video`. It would solve the merge conflict.

**Comment by Yashesvinee** [comment]
Hi I made the changes
the link is not from google drive but canva
is it okay?

**Comment by Yashesvinee** [comment]
Done!!

**Review by AkMo3 — APPROVED** [review]
@Yashesvinee Great :heart_eyes:, cannot expect anything more.

**Comment by luvksahu** [comment]
\assign Document

**Pull request merged**
