### PR TITLE
Added roadmap to readme - by Lakshit

### LINKED ISSUE #254: Android-Kotlin: 00.2 Readme Update W.R.T Roadmap
Update the [readme](https://github.com/girlscript/winter-of-contributing/blob/Android_Development_With_Kotlin/Android_Development_with_Kotlin/README.md) of Android Dev with Kotlin with the content given in the roadmap (already given in the #general channel) with clean documentation.

### PR DESCRIPTION
**Pull request by Lakshit-Chiranjiv**
<hr>

## Description 📜

Updated Readme , added roadmap , resources and project guide
Fixes #254 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by Lakshit-Chiranjiv** [comment]
@rahulsain 
Please review the readme

**Comment by rahulsain** [comment]
Change README of this file
`winter-of-contributing/Android_Development_with_Kotlin/README.md`

**Comment by Lakshit-Chiranjiv** [comment]
> Change README of this file
> `winter-of-contributing/Android_Development_with_Kotlin/README.md`
> 
> not of `winter-of-contributing/README.md`

okk got it!!

**Comment by rahulsain** [comment]
Why you have merged main into your branch, only merge our branch

**Pull request closed without merging**
