### PR TITLE
Data Science with Python : Adaptive Resonance Theory

### PR DESCRIPTION
**Pull request by Apoorv-17**
<hr>

## Description 📜

This issue will help readers in gaining all the guidance that one needs to know about Adaptive Resonance Theory. Tutorial to Adaptive Resonance Theory and how it's applied using sample code. 
Fixes : #1827

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

All images should be under "Images" folder
In README.md, you can add overall summary and final conclusion at the end
In .ipynb instead of getting into code directly, add a short intro before it. 

Kindly work on it. @Apoorv-17

**Comment by Apoorv-17** [comment]
Made all the changes.
That were asked earlier.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs the project file name, I mean .ipynb file should be in snake case. 

@Apoorv-17

**Comment by Apoorv-17** [comment]
Changed the .ipynb file name to snake case format as asked.

@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Congrats, your PR is approved. Yay. Great work. Keep it up. 🎇✔@Apoorv-17

**Comment by Apoorv-17** [comment]
@prathimacode-hub could you please add hacktoberfest accepted label so that this PR can be marked as a valid contribution for hacktoberfest 2021.

**Pull request merged**
