### PR TITLE
C/CPP : DNF(Dutch National Flag) Sort Algorithm in c++

### LINKED ISSUE #4231: C/CPP : DNF(Dutch National Flag) Sort Algorithm in c++
## Description 📜

I will create a folder DNF Sort in the directory(C_CPP/Algorithmic Approaches/Sorting/) ( under the CPP Domain ) and inside that folder, I will add documentation to explain DNF(Dutch National Flag) Sort Algorithm with code.
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by PranaySanjule**
<hr>

## Description 📜

Under the C/CPP domain, In the directory "/C_CPP/Algorithmic Approaches/Sorting/", I made one more folder "DNF Sort" inside that folder I've added 2 files, first is the documentation to explain DNF Sort Algorithm with examples and remaining 1 file containing C++ code to sort an array using DNF Sorting Algorithm.I hope my files are correct.
Fixes #4231

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by PranaySanjule** [comment]
Please review my PR @Saviour1001

**Comment by Saviour1001** [comment]
Hey @PranaySanjule, there is a better way to include your images in the MD file. GitHub allows you to host your images and then you can just add the links to these images in your MD file. Here is how to do it , [article link](https://dev.to/adityatyagi/host-images-for-free-on-github-3d1c)

**Comment by PranaySanjule** [comment]
@Saviour1001 Ok sir, I will correct it. Thank You for this idea it will help me a lot.

**Comment by PranaySanjule** [comment]
@Saviour1001 Done Sir, I made all the changes.

**Comment by PranaySanjule** [comment]
@Saviour1001 Sir, Please review my PR. I made all the changes.

**Pull request merged**
