### PR TITLE
MERN_React: 2.1 Introduction to JSX(Documentation)

### LINKED ISSUE #582: MERN_React: 2.1 Introduction to JSX
# Instructions 

## Project directory
    Branch MERN>Web_Development/MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## Introduction to JSX
- Write a brief summary on what is JSX? 
- Write with the help of code examples.

Please refrain from coping from internet. You can use any source as inspiration. 

# Task 
- [ ] Audio
- [ ] Documentation
- [ ] Video

### PR DESCRIPTION
**Pull request by Saurabh-crypto16**
<hr>

## Description 📜

Documentation of introduction to JSX, brief summary on what is JSX, and code examples.
Fixes #582  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] MERN

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Saurabh-crypto16** [comment]
@manjeetdhayal please check it.

**Review by manjeetdhayal — CHANGES_REQUESTED** [review]
Looks good! One key point is please try to include must points like Only one outermost element will be there. But by using React.fragment there can be multiple elements.

**Comment by Saurabh-crypto16** [comment]
Check this out @manjeetdhayal

**Review by saloni-15 — CHANGES_REQUESTED** [review]
please work in directory `/MERN/Topic/Frontend/React/`
and rename the file as `2.1_Introduction_to_JSX.md`

**Comment by Saurabh-crypto16** [comment]
@saloni-15 Done

**Comment by manjeetdhayal** [comment]
> @saloni-15 Done

Hey @Saurabh-crypto16 It seems like the directory isn't changet yet. Please change it to `/MERN/Topic/Frontend/React/`. Please check that out once

**Comment by Saurabh-crypto16** [comment]
@manjeetdhayal changed it to /MERN/Topic/Frontend/React/

**Review by saloni-15 — APPROVED** [review]

**Review by manjeetdhayal — APPROVED** [review]
looks great! good job @Saurabh-crypto16

**Pull request merged**
