### PR TITLE
Create DSA 1.1.5.6 Arrays: Standard Problems (Problem 6).md

### PR DESCRIPTION
**Pull request by Harsh-Chaudhary7**
<hr>

## Description 📜

Approach explanation and Implementation of Standard problem 6 #2239

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

Screenshot 2021-09-29 at 10 29 14 AM

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Harsh-Chaudhary7** [comment]
Please review it @goelesha and sorry for the delay

**Review by Muskan-creator — CHANGES_REQUESTED** [review]
Add some screenshots and provide space and time complexity of code

**Comment by Harsh-Chaudhary7** [comment]
Do i have to add screenshot in the .md file too?

**Comment by goelesha** [comment]
@Harsh-Chaudhary7 Looks good to me. Just add the references you have used. Then you are good to go.

**Comment by Harsh-Chaudhary7** [comment]
> @Harsh-Chaudhary7 Looks good to me. Just add the references you have used. Then you are good to go.

Done @goelesha

**Review by goelesha — CHANGES_REQUESTED** [review]
@Harsh-Chaudhary7 Pls add a small explanation about the time and space complexity as well. Like how did you find out the complexities. You can talk about the iterations of the loop.

**Comment by goelesha** [comment]
@Harsh-Chaudhary7  Great Work !! Congrats on getting your PR merged.

**Pull request merged**
