### PR TITLE
[JS] Topic: Added summary about scheduling in JavaScript

### LINKED ISSUE #1276: JS: Scheduling
# Scheduling
Scheduling in JavaScript
# Directory
```Topics/11.Scheduling```
## Description 📜
- setTimeout()
- setInterval()
- clearTimeout()
- clearInterval()

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

# Format

- [x] Documentation

### PR DESCRIPTION
**Pull request by SakshiMishra1**
<hr>

## Description 📜

Added summary about scheduling in JavaScript
Fixes #1276 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [x] JavaScript_Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by SakshiMishra1** [comment]
@paramsiddharth @dakshsethi @s4-2 @subhendudash02 Please review :)

**Review by s4-2 — APPROVED** [review]
Looks good to me:-)

**Comment by subhendudash02** [comment]
Else, it looks good to me!

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Comment by SakshiMishra1** [comment]
@paramsiddharth :)

**Comment by SakshiMishra1** [comment]
@paramsiddharth please merge this

**Review by paramsiddharth — APPROVED** [review]

**Pull request merged**
