### PR TITLE
Frontend With frameworks: What and Why React.js

### PR DESCRIPTION
**Pull request by trip0le**
Fixes : #297 

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by trip0le** [comment]
@anandhu720 Sir, did I do it the right way? Please suggest changes, if any.

**Review by anandhu720 — CHANGES_REQUESTED** [review]
change the name of file to What and why React.md.
Added little more history of react
Add little bit about React architecture.(can also add flowchart images and relevent pics)

**Review by anandhu720 — APPROVED** [review]

**Comment by trip0le** [comment]
@anandhu720 Sir, can I head over and work on another issue? I mean, did I finish working on this one?

**Comment by anandhu720** [comment]
yes you can

**Pull request merged**
