### PR TITLE
ML 1.16 : Bootstrap Sampling (D)

### PR DESCRIPTION
**Pull request by AdityaStark7**
Hey, I've added the documentation.
You can see it.

### CODE REVIEW

**Comment by abhisheks008** [comment]
Follow the PR template before creating any PR. @AdityaStark7

**Comment by AdityaStark7** [comment]
> Follow the PR template before creating any PR. @AdityaStark7

Where Can I find PR template?

**Comment by AdityaStark7** [comment]
[MACHINE LEARNING] This will!

**Comment by abhisheks008** [comment]
Mention your issue number please atleast. And PR template is in the template section of the main repository.

Here it is, https://github.com/girlscript/winter-of-contributing/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by AdityaStark7** [comment]
issue Number: #2273

**Comment by abhisheks008** [comment]
PR Approved @AdityaStark7

**Pull request merged**
