### PR TITLE
Data Science with Python : Support Vector Machines #424

### LINKED ISSUE #424: Data Science with Python : Support Vector Machines
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Support Vector Machines. Tutorial to Support Vector Machines and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Nithin / Dhruv Bajaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ELLIPSIS009**
<hr>

## Description 📜

I did an extensive documentation on Support Vector Machines giving all the guidance that one needs to learn about Support Vector Machines, and how it's applied using sample code. Added one MD and one IPYNB files.
Fixed #424

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ELLIPSIS009** [comment]
@prathimacode-hub please have a look at my PR, Thanks

**Comment by prathimacode-hub** [comment]
Your PR is currently under reviewing process.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Amazingly represented. Fab readme file. But few changes necessary.

Changes to be done 👍

The issue contribution should be under "/Machine Learning/Libraries/Support Vector Machines
The project file name should be in snake case : support_vector_machines.ipynb
Change the file name of readme file as README.md
Add short intro in your .iynb file before you get into code implementation and final outcome at the end.
In README.md, add a proper conclusion from all the work you had done.

Kindly work on it. @ELLIPSIS009

**Review by ELLIPSIS009 — COMMENTED** [review]
@prathimacode-hub please check

**Comment by prathimacode-hub** [comment]
Perfect. Who are your mentors? @ELLIPSIS009

**Comment by ELLIPSIS009** [comment]
I am not sure but i think Aishani Singh was my mentor of Data Science with Python Group - 16

**Comment by ELLIPSIS009** [comment]
@prathimacode-hub is there anything else that i have to do before you merge my PR?

**Review by prathimacode-hub — APPROVED** [review]
Congrats, your PR is approved. Perfect start and one of best PR till date. Very well explained. Long way to go. 👏🎉@ELLIPSIS009

**Pull request merged**
