### PR TITLE
Python: 3.2 What is Logical and Comparison Operator? #412

### PR DESCRIPTION
**Pull request by shecoderfinally**
I have submitted documentation  (Its a Jupyter Notebook) for the issue:
Python: 3.2 What is Logical and Comparison Operator? #412

@adityabisoi

### CODE REVIEW

**Comment by adityabisoi** [comment]
You have to commit into `Python` branch, not `main`

**Comment by shecoderfinally** [comment]
Python/Operators/python-3-2-what-is-logical-and-comparison-operator-412.ipynb
It is in the Python Branch..if this not the correct path then please send me the path..

**Comment by adityabisoi** [comment]
Python folder and python branch as well. You can reach out to mentors on discord for help

**Comment by shecoderfinally** [comment]
https://github.com/girlscript/winter-of-contributing/pull/3955
This is the updated Pull Request. I have requested to merge in Python Branch and uploaded the code in Python Folder..Please merge it..

**Comment by adityabisoi** [comment]
As said, you've raised a PR to main branch.

**Comment by shecoderfinally** [comment]
> As said, you've raised a PR to main branch.

@adityabisoi can you please help me?

**Pull request closed without merging**
