### PR TITLE
Create DSA 1.1.5.2 Arrays: Standard Problems (Problem 2) .md

### LINKED ISSUE #1239: DSA 1.1.5.2 Arrays: Standard Problems (Problem 2)
## Description
Find largest sum contiguous subarray.

## Task
- [x] Documentation
- [x] Audio
- [x] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by ujju20**
<hr>

## Description 📜

I have added one Question of DSA which is Largest sum subarray in which we have to find the largest sum present in the subarray of the array. A subarray is a contiguous part of an array.

Fixes #1239

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot from 2021-10-02 16-20-43

<hr>

### CODE REVIEW

**Review by goelesha — CHANGES_REQUESTED** [review]
@ujju20 You have written that below is the code for sorted arrays. But you are not using any kind of sorting algorithm in your code. And input can be random as well. So kindly correct that.

Secondly, output the subarray as well along with the sum.

**Comment by ujju20** [comment]
> @ujju20 You have written that below is the code for sorted arrays. But you are not using any kind of sorting algorithm in your code. And input can be random as well. So kindly correct that.
> 
> Secondly, output the subarray as well along with the sum.

Done 👍🏻

**Review by goelesha — CHANGES_REQUESTED** [review]
@ujju20 Pls give subarray as output not only the largest sum. 
You have written it in the explanation only.

**Comment by ujju20** [comment]
> @ujju20 Pls give subarray as output not only the largest sum. You have written it in the explanation only.

Done 👍🏻

**Comment by ujju20** [comment]
Anything Else left to do?
Please tell me.

**Comment by ujju20** [comment]
> @ujju20 Add references and we are good to go.

References means what?
You mean from where I have taken help to write this Documentation?

**Comment by ujju20** [comment]
> @ujju20 Add references and we are good to go.

Ok Done 👍🏻

**Review by goelesha — APPROVED** [review]
Great Work !!

**Pull request merged**
