### PR TITLE
Create Bubble_sort.md

### LINKED ISSUE #878: CPP: Bubble Sort
<hr>

## Description 📜

I want to create a documentation explaining bubble sort technique in C++.

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by Xyandraa9**
<hr>

## Description 📜

I added my documentation explaining bubble sort in c++.
Fixes #878

<hr>

## Type of change 📝

- [ x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ x] C/CPP

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by apeksha235 — APPROVED** [review]
@Xyandraa9  Good job! 
@Saviour1001 @Suvraneel Please merge it

**Review by Suvraneel — CHANGES_REQUESTED** [review]
@Xyandraa9  Move files to correct folder

**Comment by Xyandraa9** [comment]
@suvraneel thankyou for the follow-up, will make the desired changes.

**Comment by Xyandraa9** [comment]
I moved the file to Arrays folder, but I accidentally sent a pull request to the main branch. Kindly let me know, if I should make any other changes.

**Comment by Suvraneel** [comment]
@Xyandraa9 
Can't merge until you restore these files

Screenshot_2021-09-23-13-58-36-409_com brave browser

**Pull request closed without merging**
