### PR TITLE
Data Science with Python: Elastic Net Regression

### PR DESCRIPTION
**Pull request by Hritik157**
<hr>

## Description 📜

I have worked on the issue " Elastic Net Regression " in which I have explained the detailed information about the  Elastic Net Regression and provided code for example of  Elastic Net Regression in .ipynb also in **Colaboratory** shareable link.
Fixes : #407 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README and .ipynb file needs more information. Kindly elaborate it. @Hritik157

**Comment by Hritik157** [comment]
I have made the requested changes.
Please evaluate @prathimacode-hub mam

**Comment by Hritik157** [comment]
@prathimacode-hub

**Comment by Hritik157** [comment]
Any updates? @prathimacode-hub Mam

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Change the file name of .ipynb file to snake case : elastice_net_regression.ipynb

Kindly do this change. @Hritik157

**Comment by Hritik157** [comment]
Done Mam

**Comment by Hritik157** [comment]
@prathimacode-hub 👆Done Mam

**Comment by Hritik157** [comment]
@prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The file name i said it to keep it as "elastic_net_regression.ipynb". This is the format of writing file names in snakecase, that's what i had addressed. Like not meant to be included in file name.

**Comment by Hritik157** [comment]
SORRY for the mistake mam. I have made the requested changes @prathimacode-hub mam.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. 🙌👌@Hritik157

**Pull request merged**
