### PR TITLE
Frontend With FrameWork - (React) - Learn About Babel

### PR DESCRIPTION
**Pull request by Himanshi1805**
<hr>

## Description 📜

I have given all the information about Babel. It's uses and benefits. I have also explained the connection between ReactJS and Babel.  I have myself coded the examples to explain the work of babel. I have also mentioned the steps to install Babel in react apps. 
All the information is reviewed and checked by me and all the code examples are run by me and tested.

Fixes # React-1.2 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Himanshi1805** [comment]
Sir I have worked on introduction to babel issue in React - Frontend with framework. I hope it is good to merge. Pls tell If it has any issue.
Thankyou!

**Comment by the-pro** [comment]
Just mention the issue you worked on using #

**Review by mukeshmjn — APPROVED** [review]
Well Done

**Comment by Himanshi1805** [comment]
Thankyou sir

**Review by anandhu720 — COMMENTED** [review]
It is good

**Pull request merged**
