### PR TITLE
Create BestCSSLibraries.md

### LINKED ISSUE #2460: Best CSS Libraries
### Description

Here I will,
- explain what CSS libraries are
- list a few of the best CSS libraries out there
- explain those libraries in brief

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by cookieg13**
Best CSS Libraries

## Description 📜
 
In my documentation, I have given a short description about CSS library and discussed about few of the best CSS libraries that are available for developers today.
Fixes #2460

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Remove this emoji add any other.
image

Fontawesome is not a CSS library to be very precise it is an icon library so remove it. You can add Tailwind CSS or bootstrap.

**Review by 2024-SANDHYA — APPROVED** [review]

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Looks neat @cookieg13 👍
I would suggest you to include some more like Foundation, Bulma etc., which are equally great, and used widely.

That would make it more awesome 🎊

**Comment by cookieg13** [comment]
Thanks for the feedback! I am adding what you mentioned here,😁 I feel it would be great after the changes are made.

**Comment by cookieg13** [comment]
@code-reaper08 can you please have a look at my edited documentation? I have made the needed changes😊

**Comment by code-reaper08** [comment]
> @code-reaper08 can you please have a look at my edited documentation? I have made the needed changes😊

Looks perfect now @cookieg13 😄👍

**Review by code-reaper08 — APPROVED** [review]

**Comment by cookieg13** [comment]
Thank you @code-reaper08😀  I have made a new directory named BestCSSLibraries, put this .md file inside, and then committed. Could you please check if it's alright? I am a little confused as I am contributing for the first time, sorry

**Comment by code-reaper08** [comment]
> Thank you @code-reaper08😀 I have made a new directory named BestCSSLibraries, put this .md file inside, and then committed. Could you please check if it's alright? I am a little confused as I am contributing for the first time, sorry

### It looks super cool now 👏 
No issues, If you need any help, just ping me on **Discord**, I'll be happy to help 😄

**Comment by cookieg13** [comment]
Thank you so much again 😁

**Pull request merged**
