### PR TITLE
1.2.4.1 NP-Complete Problem - Documentation

### LINKED ISSUE #1781: DSA 1.2.4.1 NP-Complete Problem - Documentation
## Description
What do you understand by NP-Completeness? Discuss in detail, what is NP, P, NP-complete and NP-Hard problems?

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by GenMech**
Made a well documented file on this topic.

<hr>

## Description 📜

A well documented file on NP-Complete Problem
Fixes #1781

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by GenMech** [comment]
@nimisha-yadav Pls check this and let me know if there is any change or it is good to go.

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Set the file name DSA/1.1 Arrays/1.2.4.1_NP_Complete_Problem.md

**Comment by GenMech** [comment]
> Set the file name DSA/1.1 Arrays/1.2.4.1_NP_Complete_Problem.md
 
Currently file is DSA/1.1 Arrays/1.2.4.1 NP-Complete Problem.md , what should i change in this👀

**Comment by GenMech** [comment]
@harshsri28 @nimisha-yadav Now check

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by sneha-nitdgp — APPROVED** [review]
Good.

**Review by nimisha-yadav — CHANGES_REQUESTED** [review]
@GenMech although you've mentioned the source but the content is wholly copied and lacks originality. Resources available online are only for references and not just putting up as it is. Showcase your understanding of the topic and your individuality. Try to restructure/rephrase the content, and add pictures made by you. We are here to make meaningful contributions so people get more value than the already popular resources.

Once you're done, update the fork and put the file in NP Complete Problem folder present in Analysis of Algorithms.

**Comment by GenMech** [comment]
@nimisha-yadav Done!!

**Review by nimisha-yadav — APPROVED** [review]

**Pull request merged**
