### PR TITLE
[Frontend Dev HTML/CSS/JS]: Random Quote Generator

### LINKED ISSUE #6302: [Frontend Dev HTML/CSS/JS]: Random Quote Generator
### Description

I would like to provide documentation about making a random quote generator using JS.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by areenoverclouds**
<hr>

## Description 📜

This is the documentation about creating a Random Quote Generator using JS.
Fixes #6302 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Looks cool @areenoverclouds ✨
The explanation is short and brief. It would be nice if it's more detailed with some output screenshots.

**Comment by areenoverclouds** [comment]
> Looks cool @areenoverclouds ✨ The explanation is short and brief. It would be nice if it's more detailed with some output screenshots.

I have made the suggested changes, please recheck. Thankyou!

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
Add reference links(if any).

**Comment by areenoverclouds** [comment]
> Add reference links(if any).

Done

**Review by kashishahuja2002 — APPROVED** [review]
LGTM

**Review by code-reaper08 — APPROVED** [review]
🎉✨

**Pull request merged**
