### PR TITLE
Android-Kotlin : 03.1 Installing Android Studio

### LINKED ISSUE #346: Android-Kotlin : 03.1 Installing Android Studio
## Description :
* Give a stepwise description of how to install the latest version of android studio. (For Windows, Mac, Linux)
*  Required documentation or video.

* Changes should be made in **Android_Development/Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
> Supervisor @rahulsain

### PR DESCRIPTION
**Pull request by tanishqchugh2002**
<hr>

## Description 📜
Created a Complete Document for installing Android Studio and implementing Kotin as the language for Windows,Mac and Linux.
Fixes #346

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by rahulsain** [comment]
@sitamadex11 Review it please

**Review by sitamadex11 — APPROVED** [review]
Nice One

**Comment by rahulsain** [comment]
@tanishqchugh2002 add hyperlink wherever necessary

**Comment by tanishqchugh2002** [comment]
> @tanishqchugh2002 add hyperlink wherever necessary
I have added a hyperlink wherever I felt was necessary. can you please help me out by being more precise so i can make it better?

**Comment by tanishqchugh2002** [comment]
> @tanishqchugh2002 add hyperlink wherever necessary

There was some error due to which the hyperlinks were not visible. It is resolved now please review it

**Comment by sitamadex11** [comment]
now the links are visible.

**Comment by tanishqchugh2002** [comment]
> now the links are visible.

Please approve it so that I can contribute more  :)

**Pull request merged**
