### PR TITLE
Data Science with Python : Tokenization and Lemmatization

### PR DESCRIPTION
**Pull request by Robinrai2612**
<hr>

## Description 📜

I have explained about the Tokenization and Lemmatization.
Fixes issue #1856 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Robinrai2612** [comment]
@prathimacode-hub Ma'am please review my PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

You can add more details in README.md. Like its purpose, why its used, advantages of it, where it can be applied, its usage, any visuals and workflow of the concepts and conlusion

Kindly work on it. @Robinrai2612

**Comment by Robinrai2612** [comment]
@prathimacode-hub Ma'am I have committed the changes.Please review it.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Yayy, amazing explanation and very well justified your project. Well done. ✨✔@Robinrai2612

**Pull request merged**
