### PR TITLE
Function & Recursion and it's Types 

### LINKED ISSUE #1002: C/CPP Function & Recursion and it's Types
<hr>

## Description 📜

This documentation explains Function & Recursion and it's types in C language .
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by I-ArchanaDash**
<hr>

## Description 📜

This Documentation explains Function ,Recursion and it's types in C language
Fixes #1002

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x]My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@I-ArchanaDash Please note the following: 
- There is already a file for **Recursion and its types** made so you can't make a documentation on that.
- And for **Function and its types** a documentation this short is not sufficient. Please elaborate it more and try using some code snippets in all the types that you have provided.

**Comment by I-ArchanaDash** [comment]
> @I-ArchanaDash Please note the following:
> 
> * There is already a file for **Recursion and its types** made so you can't make a documentation on that.
> * And for **Function and its types** a documentation this short is not sufficient. Please elaborate it more and try using some code snippets in all the types that you have provided.

Okay I will definitely change it, but the issue "C/CPP Function & Recursion and it's Types #1002" was assigned to me then how another file of recursion already exists

**Comment by Saviour1001** [comment]
@I-ArchanaDash the issues are getting assigned by a bot. No one can physically traverse through all the open issues on CPP domain, thus its your responsibility to check if the content on a specific topic already exists or not.

As the documentation already exists here and we don't want your efforts to go in vain thus I would suggest you to convert this content to audio or video format. 
I am closing this PR as of now and you can create a new one with the audio/video file.

**Comment by I-ArchanaDash** [comment]
@Saviour1001 May I do the documentation of " Function and its type ", as I was the first one to create an issue regarding it and nobody else has created it before mine.

**Comment by Saviour1001** [comment]
@I-ArchanaDash have a look at the current state of the GWOC repo and work on any topic which doesn't exist. Search the keyword of the topic you want to work on and then just search in issues. We don't want your efforts to get wasted so just do these steps before working on any topic.

**Comment by I-ArchanaDash** [comment]
> @I-ArchanaDash have a look at the current state of the GWOC repo and work on any topic which doesn't exist. Search the keyword of the topic you want to work on and then just search in issues. We don't want your efforts to get wasted so just do these steps before working on any topic.

Okay ,Thanks @Saviour1001

**Pull request closed without merging**
