### PR TITLE
[JS] Topic: TypeScript

### LINKED ISSUE #5128: JS: TypeScript
### Directory
Flavours/Typescript

### Description
What is Typescript?
Why Typescript is better?
What are types?
How to define types?
Generics

### Domain

JavaScript_Domain

### Type of Contribution

- [x] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by WajihaFatim**
<hr>

## Description 📜

Fixes #5128

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [x] JavaScript_Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by WajihaFatim** [comment]
@paramsiddharth sir please review my pr and tell if I need to improve something

**Comment by WajihaFatim** [comment]
Okay

**Comment by WajihaFatim** [comment]
@paramsiddharth is it fine now

**Comment by WajihaFatim** [comment]
@subhendudash02 is it fine now

**Comment by subhendudash02** [comment]
Cool!👍 Let mentors check on their side and I am not sir😂, I am a contributor like you.

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 @amino19 Please review.

**Comment by WajihaFatim** [comment]
done @dakshsethi

**Comment by WajihaFatim** [comment]
@paramsiddharth please merge this if it has been approved

**Comment by WajihaFatim** [comment]
@paramsiddharth done

**Pull request merged**
