### PR TITLE
Create Basic_operations.md

### LINKED ISSUE #7376: Operations in Binary Tree
### Description

I have prepared a documentation on Operations in Binary Tree which includes:
- Inserting an element into a Binary Tree
- Deleting an element from a Binary Tree
- To traverse through the Binary Tree in INORDER
- To count the number of nodes in the Binary Tree
- To find the height of the Binary Tree
- To traverse tree in LEVEL ORDER
- To search a value in the Binary Tree

Hope you learn from the documentation :)

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Preet1406**
<hr>

## Description 📜

I've added a file for basic operations of binary tree
Fixes #7376 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Preet1406** [comment]
@apeksha235

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@Preet1406 give an example input output for all types of traversals

**Comment by Preet1406** [comment]
@apeksha235 changes done, please check

**Review by apeksha235 — APPROVED** [review]
@Preet1406 perfect!! @Suvraneel please merge this

**Review by kashishahuja2002 — APPROVED** [review]
LGTM, great work.

**Comment by Suvraneel** [comment]
@Preet1406  LGTM ❤️ :octocat:  🚀

**Pull request merged**
