### PR TITLE
DSA:2.1.1.2 Strings: Implementation of Strings in C & C++ fixes#3071-Docume…

### PR DESCRIPTION
**Pull request by 1PRatgit**
…ntation

<hr>

## Description 📜

Implementation of Strings in C & C++. 
Fixes # 3071 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
@Suvraneel remove this c/cpp label from this issue ( don't consider this message @1PRatgit ).

**Review by goelesha — CHANGES_REQUESTED** [review]
@1PRatgit Pls explain about the implementation of strings in C as well as C doesn't have classes.  
Also, segregate the implementation in C and Cpp so the viewer is able to differentiate easily while reading.  
And pls try explaining things using one or two examples apart from just including the code.
Rest is good.

**Review by goelesha — CHANGES_REQUESTED** [review]
@1PRatgit Brilliant Work !!
Pls, add references at the end and we are good to go.

**Review by goelesha — APPROVED** [review]
@1PRatgit Great Work !!
Congrats on getting your PR merged.

**Pull request merged**
