### PR TITLE
Fixes Dijksta's shortest path algorithm

### LINKED ISSUE #5920: DSA 3.2.14 Dijkstra’s Shortest Path Algorithm
## Description
Discuss in detail - Dijkstra’s Shortest Path Algorithm.
**Important: Do not use assign command for this issue.**
## Task
- [ ] Documentation

## Note
- After completion of your task, add your file in this [folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/14.%20Dijkstra%E2%80%99s%20Shortest%20Path%20Algorithm) as its readme.md
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by 1PRatgit**
<hr>

## Description 📜

Discussed in detail about Dijkstra’s Shortest Path Algorithm.
Fixes #5920 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by 1PRatgit** [comment]
@sneha-nitdgp  Thanks for suggestions.  Updated recommended changes.

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by nimisha-yadav — APPROVED** [review]
Great work! @1PRatgit

**Pull request merged**
