### PR TITLE
Created documentation on colors in CSS

### PR DESCRIPTION
**Pull request by Sakshamgupta90**
<hr>

## Description 📜

Fixes # <1607> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Could be explained more, that would make this better.

**Comment by Sakshamgupta90** [comment]
Sure I will do that.

**Comment by Sakshamgupta90** [comment]
@code-reaper08 I have made some changes kindly review it.

**Review by akashprasher — COMMENTED** [review]
looks good to me, a good explanation.

**Comment by Sakshamgupta90** [comment]
Thank you! 
Now can it be merged?

**Comment by akashprasher** [comment]
Sorry, I can't. I do not have write permission. I just compared your previous and latest explanation and you explained well in latest changes. @code-reaper08 can help you with merging.

**Comment by Sakshamgupta90** [comment]
Okay. @code-reaper08 is that issue  ready for merging?

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Looks like you are inspired from https://www.javatpoint.com/css-colors

You must attribute the sources. And moreover, this topic is already merged there in the repo **5 days ago.** Probably you are late 😕

**Already merged PR's issue date** : https://github.com/girlscript/winter-of-contributing/issues/1131 - **Sept 20**

**Your PR's issue date** : https://github.com/girlscript/winter-of-contributing/issues/1607 - **Sept 21**

**Already PR merged date** : https://github.com/girlscript/winter-of-contributing/pull/1610 - **Sept 22**

**Your PR raised date** : https://github.com/girlscript/winter-of-contributing/pull/2469/ - **Sept 24**



Please have a look! 
If there is a file already, please switch the way of contribution at least as audio or video. This would save your time, and would boost you on your other contributions as well. 

What you say @2024-SANDHYA?

**Comment by Sakshamgupta90** [comment]
Ohh...I didnt see anywhere that this issue have merged!

**Comment by code-reaper08** [comment]
> Ohh...I didnt see anywhere that this issue have merged!

You should check for existing files, when you are working on it, it's not only for GWoC, but also for your future open-source contributions.

**Comment by code-reaper08** [comment]
> Ohh...I didnt see anywhere that this issue have merged!

I think you could prepare another kind of contribution, so your work won't get wasted.

**Comment by Sakshamgupta90** [comment]
> > Ohh...I didnt see anywhere that this issue have merged!
> 
> You should check for existing files, when you are working on it, it's not only for GWoC, but also for your future open-source contributions.

okay thank you.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Looks like you are inspired from https://www.javatpoint.com/css-colors
> 
> You must attribute the sources. And moreover, this topic is already merged there in the repo **5 days ago.** Probably you are late 😕
> 
> **Already merged PR's issue date** : #1131 - **Sept 20**
> 
> **Your PR's issue date** : #1607 - **Sept 21**
> 
> **Already PR merged date** : #1610 - **Sept 22**
> 
> **Your PR raised date** : #2469 - **Sept 24**
> 
> Please have a look!
> If there is a file already, please switch the way of contribution at least as audio or video. This would save your time, and would boost you on your other contributions as well.
> 
> What you say @2024-SANDHYA?

Right @code-reaper08 . @Sakshamgupta90  You can either change this content to audio or video , as mentioned by Vishwa, that it already exists so .

**Pull request closed without merging**
