### PR TITLE
ML: House Price Prediction #7861 Resolved

### LINKED ISSUE #7861: ML : House Price Prediction
### 📌 Issues for Week 9 - Basic Projects of Machine Learning

🔴 **Project Title** : House Price Prediction
🔴 **Aim of the Project** : This project predicts the prices of houses located in the cities of the US, with the help of essential features.
🔴 **Dataset** : https://www.kaggle.com/shree1992/housedata
🔴 **Domain** : Machine Learning
🔴 **Special Credit** : **Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked through the accuracy scores to determine the best fitted model**

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain. 

**************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

**Take the Reference from these two projects attached here,** 
1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Changes should be made inside the `Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning` Branch.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- Batch Number : 
- GitHub Profile Link : 
- Approach for this Project :
- Are you a participant of GWoC21?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by VidhiBhatt01**
<hr>

## Description 📜

Added ML Project 
Fixes #7861

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [X] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
As majority of projects submitted have a common set of algorithms used, I have used various types of regression algorithms to make this project a little different.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
### Required Changes  
1. Put all the `.csv` and `.dat` files inside the `Dataset` folder, Don't create another folder named as `Data` inside the `Dataset` folder. Push the files directly inside the `Dataset` folder
2. In the conclusion section of `Model/README.md` file, provide the accuracy scores of all the models you've created and then compare them all. After that put the conclusion, which model is the better one with the accuracy score.
3. Rename the `requirements.txt.txt` file to `requirements.txt`.

Please do the needful @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
> ### Required Changes
> 1. Put all the `.csv` and `.dat` files inside the `Dataset` folder, Don't create another folder named as `Data` inside the `Dataset` folder. Push the files directly inside the `Dataset` folder
> 2. In the conclusion section of `Model/README.md` file, provide the accuracy scores of all the models you've created and then compare them all. After that put the conclusion, which model is the better one with the accuracy score.
> 3. Rename the `requirements.txt.txt` file to `requirements.txt`.
> 
> Please do the needful @VidhiBhatt01

@abhisheks008 I have made the required changes. Please Review them.

**Review by abhisheks008 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
@abhisheks008 shall I create a new PR for updating the readme of project folder??

**Comment by abhisheks008** [comment]
Which one? @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
> Which one? @VidhiBhatt01 

The one in which list of all projects and their respective links are there.

**Comment by abhisheks008** [comment]
Don't worry we'll do it 😄

**Pull request merged**
