### PR TITLE
Ceil and Floor Functions [Documentation]

### PR DESCRIPTION
**Pull request by ritika728**
<hr>

## Description 📜

I have explained about ceil() and floor() functions and the difference in round(), ceil(), and floor() functions in the documentation file. In the implementation file, I have written codes as an example of these functions. # <1884> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Shivani0701** [comment]
@ritika728 Please correct checklist

**Comment by ritika728** [comment]
> @ritika728 Please correct checklist

Done Ma'am

**Review by deeqakkk — CHANGES_REQUESTED** [review]
delete this extra documentation.MD

**Comment by ritika728** [comment]
> delete this extra documentation.MD

Done

**Comment by Shivani0701** [comment]
@Suvraneel good to be merged :)

**Comment by Suvraneel** [comment]
@Shivani0701 @ritika728  Ambiguous name 
Place it in a pre-created folder under CPP

**Comment by ritika728** [comment]
> @Shivani0701 @ritika728 Ambiguous name
> Place it in a pre-created folder under CPP

@Suvraneel in which folder can I put my files? I'm a bit confused.

**Comment by Suvraneel** [comment]
@ritika728 Observe directory change & readme change...
Next time try to find it yourself (this was an example) & do the same

**Comment by Suvraneel** [comment]
@ritika728  To more contributions :octocat:

**Comment by ritika728** [comment]
@Suvraneel Thank you so much!

**Pull request merged**
