### PR TITLE
DSA | issue #3193 | Linear Search And Binary Search

### LINKED ISSUE #3193: DSA 2.2.2 Linear Search & Binary Search
## Description
Give an introduction and explain the working of Linear Search & Binary Search, and compare them in terms of their complexities

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by palsahabmalviyan**
<hr>

## Description 📜

The PR fixes the issue #3193 by discussing :
1. Algorithm of Linear Search and Binary Search.
2. Iterative Implementation of Linear Search.
3. Both Iterative Implementation and Recursive Implementation of Binary Search.
4. Time Complexity of Both Linear and Binary Search.
5. Difference Between Linear and Binary Search.

Fixes  #3193.

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x]  DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by palsahabmalviyan** [comment]
@Sarthak-Agg sir, please review this pull request.

**Review by Sarthak-Agg — APPROVED** [review]
good presentation

**Comment by palsahabmalviyan** [comment]
@Sarthak-Agg please merge my pr

**Comment by Sarthak-Agg** [comment]
@palsahabmalviyan  I am not authorized to merge this

**Comment by Satyam175** [comment]
> @palsahabmalviyan I am not authorized to merge this

<h2>you can merge now</h2>
<p>make sure base branch is set specific to your domain branch or else edit it.</p>

**Pull request merged**
