### PR TITLE
CSS Animations

### LINKED ISSUE #1470: Frontend: CSS Animations
<hr>

## Description 📜

I will describe how to implement basic yet interesting Animations using just CSS.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

### PR DESCRIPTION
**Pull request by ayush02av**
<hr>

## Description 📜

Changing the file structure as mentioned :
Readme File: `winter-of-contributing/Web_Development/FrontEnd/CSS_Animations/Readme.md`
and
Banner Image: `winter-of-contributing/Web_Development/FrontEnd/CSS_Animations/animation.png`
and
9 gifs in the same folder `winter-of-contributing/Web_Development/FrontEnd/CSS_Animations/` for animations demonstration
Fixes #1470 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by ayush02av** [comment]
@sifa123 ma'am, I have included GIFs for the animations that I made. I have fixed some minor errors and given the credits for the banner image. There are no conflicts with the base branch.
I request you to review it now once again.

**Comment by Knighthawk-Leo** [comment]
> ## Description 📜
> Changing the file structure as mentioned :
> Readme File: `winter-of-contributing/Web_Development/FrontEnd/CSS_Animations/Readme.md`
> and
> Banner Image: `winter-of-contributing/Web_Development/FrontEnd/CSS_Animations/animation.png`
> and
> 9 gifs in the same folder `winter-of-contributing/Web_Development/FrontEnd/CSS_Animations/` for animations demonstration
> Fixes #1470
> 
> ## Type of change 📝
> * [x]  Documentation (Content Creation in the form of codes or tutorials)
> 
> ## Domain of Contribution 📊
> * [x]  Frontend Dev HTML/CSS/JS
> 
> ## Checklist ✅
> * [x]  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
> * [x]  I have performed a self-review of my own code or work.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  My changes generates no new warnings.
> * [x]  I'm GWOC'21 contributor

Specify the issue no. so that we can close that one

**Review by sifa123 — COMMENTED** [review]
Awesome:boom:

**Comment by Knighthawk-Leo** [comment]
Ohk can you do one thing more just reduce the size of gif it's too large
@ayush02av

**Comment by ayush02av** [comment]
Ok sure, will do it.

**Comment by ayush02av** [comment]
@Knighthawk-Leo I have reduced the Gif size as you said, should I make a new pull request as this one's closed?

**Pull request merged**
