### PR TITLE
Android-Java: 1.5 Run your app using virtual device and real device.

### LINKED ISSUE #59: Android-Java: 1.5 Run your app using virtual device and real device.
## Description :
* Describe how to set up your real device using USB debugging to run your app in android studio.
* Describe how to create an android-virtual-device using AVD manager to run your app in android studio.

* Changes should be made in **Android_Development/Java** directory under **Android_Development_With_Java** branch.
* You have to give your PR to the **Android_Development_With_Java** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.

### PR DESCRIPTION
**Pull request by prince02765**
<hr>

## Description 📜

Android-Java: 1.5 Run your app using virtual device and real device.
Fixes #59

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prince02765** [comment]
please review this @sitamadex11

**Review by sitamadex11 — APPROVED** [review]

**Review by Rohit-2602 — APPROVED** [review]

**Comment by prince02765** [comment]
If there are no changes required can you please merge it? @sitamadex11

**Comment by VikasPandey121** [comment]
Awesome work done @prince02765 just a small change requested, Please do these changes 

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Align centre all the images and refract `Android_Development` directory with `Android_Development_Wit_Java` and add your file in `Android_Development_With_Java/Introduction/` directory. 
- `squash` your commit.

**Comment by prince02765** [comment]
Done,

Should I create a new PR?

**Comment by Rohit-2602** [comment]
no, this is fine
Great Work 😀

**Review by Rohit-2602 — APPROVED** [review]

**Pull request merged**
