### PR TITLE
[VueJS] Frontend With Framework : 3.1 Inline Style Manipulation

### PR DESCRIPTION
**Pull request by nooobcoder**
<hr>

## Description 📜

This is a Week 3 Contribution, please refer to the designated folder, to find the source files.
Added documentation for using inline styling inside components in VueJS.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
- ~~[] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)~~
- ~~[ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)~~
- ~~[ ] Other (If you choose other, Please mention changes below)~~

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

Parent Issue referencing  #4866

### CODE REVIEW

**Comment by anandhu720** [comment]
@nooobcoder any updates

**Comment by nooobcoder** [comment]
@anandhu720 any other changes can be made, I have made very clear, the contributions panel cannot be edited by me atleast.
Feel free to close the PR, if giving proper contributions worry you a lot and to the GWoC team.

Thank You!

**Comment by anandhu720** [comment]
@noobcoder if your concern is that your name need to be in your contributed file.In top of the file the contributers name is showen by github itself.From that itself everyone can find who done this conctrinution.Thats why GWOC team is saying to not add this details at bottom.If you are not satisfied by that we can't do anything.Please Tell your final opinon

**Comment by nooobcoder** [comment]
Closing this PR, due to violation of rights of contributors. Anyone who wants to contribute without proper credits, may reopen another PR referencing the issue. 🙏🏽

**Pull request closed without merging**
