### PR TITLE
ML 3.4: DBSCAN (A)

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜 
DBSCAN audio content
Necessacity
DBSCAN Algorithm
Difference of DBSCAN and other clustering algorithm
Procedure
Reachability
Connectivity
Disadvantages
Applications
Fixes # <4128> 

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
@abhisheks008  kindly give a review on this

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@ron352 the thumbnail you've added is not visible. Please fix it.

**Comment by ron352** [comment]
I have added the files now @abhisheks008

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
Merged @ron352

**Pull request merged**
