### PR TITLE
OpenSource : 1. History of free and open-source software (1980 & 1990’s) 

### LINKED ISSUE #20: OpenSource :  1. History of free and open-source software (1980 & 1990’s)
### Description :
- **Explain the History of free and open-source software (1980 & 1990’s)**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by Adi7171**
<hr>

## Description 📜
History of free and open-source software (1980 & 1990’s) was created. It consists of the following sub-topics which tells about the history of open-source  - > The Release of the GNU License, World's First OS, Cathedral Bazaar, “Open source” is born, and Commercialisation of open source.
Fixes  #20

<hr>

## Added content on history of open source using google colab

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
After reviewing your PR below are some changes : 
-  Try to explain with `images, graphs, gif, charts etc` Don't write` text-heavy documentation`, No one gonna read those ones
-  Ask first that you adding particular content before doing any work, You can put your thoughts on issue threads 
- `PR description` should have some text of what you've done, Correct those `[x]` checkboxes
-  Change `PR Description` to `OpenSource : 1. History of free and open-source software`
-  Change `commit message` to `OpenSource : 1. History of free and open-source software` and merge all three into `one single commit` ( ie. commit squashing)
-  Remove `Explain the` from the heading of the document ( Since we are not adding any kind of Q/A docs here) 
-  Remove `All credits` section from doc
-  Be creative don't fully copy-paste from the internet or any other sources, use them only for starting off writing.
-  Remove this collab notebook line 👇
Screenshot from 2021-09-15 00-09-38
- Review your work by yourself first

**Comment by Aryamanz29** [comment]
For squashing commits follow  : https://www.youtube.com/watch?v=gXCkYkLQ3To&t=2s
https://www.git-tower.com/learn/git/faq/git-squash/

**Comment by Aryamanz29** [comment]
See this project `README.md` this how we want our documents
https://github.com/winterbe/java8-tutorial

**Comment by Adi7171** [comment]
How is it now.

**Comment by Adi7171** [comment]
I am getting merging problems with the read me file

**Comment by Aryamanz29** [comment]
What kind of problems ? Merge conflict?

**Comment by Adi7171** [comment]
> What kind of problems ? Merge conflict?

Yea and also whenever I try to squash it , the rebase stops at 6/31

**Comment by Aryamanz29** [comment]
> > What kind of problems ? Merge conflict?
> 
> Yea and also whenever I try to squash it , the rebase stops at 6/31 

Because there some conflicts between files when you're rebasing so try to solve them.

**Comment by Adi7171** [comment]
It shows an ! mark in the staging area of vscode

**Comment by Aryamanz29** [comment]
> It shows an ! mark in the staging area of vscode 

Yes `!` this means that particular file have conflict that you need to solve.
After solving just `git add .`

**Comment by Aryamanz29** [comment]
Please Fix this Image @Adi7171  👇

Screenshot from 2021-09-15 23-05-04

**Pull request closed without merging**
