### PR TITLE
Fractional Knapsack 

### LINKED ISSUE #7123: Fractional Knapsack
### Description

Solving Fractional Knapsack problem by Greedy approach. 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by balasai45**
<hr>

## Description 📜

Shown how Fractional Knapsack can be solved by greedy approach and also explained greedy algorithm by taking thief problem. 
Fixes #7123  

<hr>

## Type of change 📝
Added a file name <b> fractional knapsack </b> in greedy folder under algorithm approaches and also updated readme according to that.

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
image
Plagiarism, refactor it.

**Comment by vasu-1** [comment]
image
image
image

- it should look like this `[x]` .

**Comment by balasai45** [comment]
@kashishahuja2002  I dont how it matched but I changed the content I think now the plaglarism has been removed . please check it.

**Review by kashishahuja2002 — APPROVED** [review]
LGTM

**Review by vasu-1 — CHANGES_REQUESTED** [review]
File conflicts must be resolved first !!

**Comment by balasai45** [comment]
Done

**Review by vasu-1 — APPROVED** [review]
@Saviour1001

**Pull request merged**
