### PR TITLE
Frontend web development html css js

### LINKED ISSUE #1150: Frontend_Web_Development_HTML_CSS_JS: AJAX
# AJAX
---
AJAX in javascript

# Directory
---
```
Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/9.AJAX
```

# Description 📜
---
creating a tutorial on AJAX in Javascript for Front_End_Web_Development_HTML_CSS_JS branch and discussing the following:
- What is AJAX?
- How does AJAX Work?
- AJAX - The XMLHttpRequest Object
- Fetch API

# Domain of Contribution 📊
---

- [x] Frontend Dev (HTML, CSS, JS)

# Format
---
- [x] Documentation

### PR DESCRIPTION
**Pull request by Arya-Gupta**
<hr>

## Description 📜

Audio contribution for AJAX
Fixes #1150

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
Who's voice is that? 😰
Do you have proper rights to use it? 🤔

**Review by praveenscience — APPROVED** [review]
👍

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Hello @Arya-Gupta 
Everything looks cool, just have your file `Web_Development/Javascript/AJAX/AJAX.md` instead of `Web_Development/FrontEnd/AJAX/AJAX.md`. That would be more apt.

**Review by code-reaper08 — APPROVED** [review]
🆒

**Pull request merged**
