### PR TITLE
Data Science with Python : Support Vector Machines

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
<hr>

## Description 📜

Introduction to Support Vector Machines (SVM) #732 
<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given in guidelines document pinned up. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
Updated @prathimacode-hub do please check

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README needs more elaboration. It has no details. Kindly elaborate everything about topic you had chosen. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> Your README needs more elaboration. It has no details. Kindly elaborate everything about topic you had chosen.
> What's the audio length? @BhaswatiRoy

updated an elaborative version of readme and the audio is of 3min 21sec

**Comment by BhaswatiRoy** [comment]
@prathimacode-hub do please review this

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Have you noticed it? Both of your PR's turned out to be a single PR. WHY because earlier PR wasn't merged yet. So go one after the other. And whatever issue you work on, make sure your README.md file is elaborate and detailed. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> Have you noticed it? Both of your PR's turned out to be a single PR. WHY because earlier PR wasn't merged yet. So go one after the other. And whatever issue you work on, make sure your README.md file is elaborate and detailed. @BhaswatiRoy

Maam I submitted the 1st pr and then only I worked on the 2nd pr meanwhile you told me to change my 1st pr that is why both of them got submitted together............. And for both of the files, I was as elaborative as possible from my side.............. I have added everything I could have added there is nothing more I can add from my side............. what should I do now? submit pr one by one?

**Comment by BhaswatiRoy** [comment]
@prathimacode-hub please tell me what else should I do to get my pr merged.............I am stuck on this pr and unable to shift to any more issues.................

**Comment by BhaswatiRoy** [comment]
I have deleted one pr work for now and submitted.....................please review this @prathimacode-hub so that I can go to new issues now................. Every possible stuff which I could add I have added from my part.............there is nothing more left from my side to add.................. both in audio file and readme file

**Review by prathimacode-hub — APPROVED** [review]
Congrats, your PR is approved. 👍@BhaswatiRoy

**Pull request merged**
