### PR TITLE
Android Kotlin: Marvel vs DC Quiz App (project)

### LINKED ISSUE #6746: Android Kotlin: Marvel vs DC Quiz App
@rahulsain 
This is a quiz app related to superhero franchise DC and Marvel.

<p align = "left">

</p>

### PR DESCRIPTION
**Pull request by shubhmittal07**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #6746 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [x] Android Dev (Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by shubhmittal07** [comment]
> README section is perfect. @rahulsain please check it once.

Thanks. @sitamadex11 

I wanted to ask that I have made 6 contributions in Android kotlin domain but my commits are not counted in the Contributors List. How can I fix that?

**Comment by rahulsain** [comment]
> I have provided the Documentation Please review it . @rahulsain @sitamadex11 .
> 
> Also I wanted to ask that I have made 6 contributions in Android kotlin domain but my commits are not counted in the Contributors List. How can I fix that?

Can you share the reference of that list?

**Comment by shubhmittal07** [comment]
Is there any additional changes I have to make? @rahulsain @sitamadex11

**Comment by shubhmittal07** [comment]
image

Here it shows only 16 commits. @rahulsain @sitamadex11

**Comment by rahulsain** [comment]
> image
> 
> Here it shows only 16 commits. @rahulsain @sitamadex11

GWOC can see your merged PR, not your commits.

**Comment by rahulsain** [comment]
> > image
> > Here it shows only 16 commits. @rahulsain @sitamadex11
> 
> GWOC will see your merged PR, not your commits.

**Pull request merged**
