### PR TITLE
ML 0.3 : Real life application of Data Mining (D) #7315

### LINKED ISSUE #7315: ML 0.3 : Real life application of Data Mining (D)
### 📌  Issues of Week 1
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Real life application of Data Mining_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Ruchika-20**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7315 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter)
- [ ] Android Dev (Java)
- [ ] Android Dev (Kotlin)
- [ ] Backend Dev (Java)
- [ ] Backend Dev (.NET)
- [ ] Backend Dev (PHP)
- [ ] Backend Dev (Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript_Domain
- [ ] MERN
- [x] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by raina-akshay — APPROVED** [review]

**Comment by raina-akshay** [comment]
you need to edit the .md file above. seems to have some formatting issues.

**Comment by Ruchika-20** [comment]
sorry can you elaborate?

**Review by Isha307 — CHANGES_REQUESTED** [review]
Follow this : https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md

**Comment by Ruchika-20** [comment]
what to write inside module?

**Review by raina-akshay — APPROVED** [review]

**Comment by Ruchika-20** [comment]
changes updated @Isha307  please have a look

**Comment by abhisheks008** [comment]
Approved from my side @Ruchika-20 , let @Isha307 do the needful.

**Comment by Ruchika-20** [comment]
Okay....if psbl tell her to have a look before 11 am so that I can take up
new issues

**Review by Isha307 — APPROVED** [review]

**Pull request merged**
