### PR TITLE
 Ford Fulkerson Algorithm || Network Graph

### LINKED ISSUE #7973: Fold Fulkerson Algorithm || Network Flow Algorithm
### Description

I will explain how we can use Fold Fulkerson Algorithm to find maximum flow through the flow network.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by DwipshikhaLodh**
<hr>

## Description 📜

Here I explained how we can use Ford Fulkerson Algorithm to find maximum flow through a Network Graph.
Fixes #7973 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
@Suvraneel Sir ! Do check it out !

**Review by Suvraneel — CHANGES_REQUESTED** [review]
@DwipshikhaLodh  Noiceeeee topic selection
And very clear concise explanation...

### Changes Required:
- Move this to `Algorithmic Approaches/Greedy` folder
- Add to readme of Greedy folder

**Comment by DwipshikhaLodh** [comment]
Okayy

**Comment by DwipshikhaLodh** [comment]
@Suvraneel done.. can you please check now.

**Comment by Suvraneel** [comment]
@DwipshikhaLodh  LGTM ❤️ :octocat:  🚀  Awesome !

**Comment by DwipshikhaLodh** [comment]
@Suvraneel  Thank you ✨✨

**Pull request merged**
