### PR TITLE
OpenSource : 5.43 Explain everything related to Notary

### LINKED ISSUE #680: OpenSource : 5.43 Explain everything related to `Notary`
### Description :

- **Explain everything related to `Notary`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by itsbittoosharma**
<hr>

## Description 📜

Fixes #680 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Change filename to `5.43_Notary.md`

**Comment by Aryamanz29** [comment]
@itsbittoosharma  Any updates ?

**Comment by Aryamanz29** [comment]
This is a very bad sign from the contributor point of view, I just req small filename change but no-reply :(
I have to fork your repo and do that change.

**Review by Aryamanz29 — APPROVED** [review]
Approved after doing req changes
Thanks for contributing @itsbittoosharma 🎉🎉

**Comment by itsbittoosharma** [comment]
Sorry @Aryamanz29 
I seriously didn't received any notification untill I checked just now regarding the status of PR.
Sorry for not replying

**Pull request merged**
