### PR TITLE
JSON in Python

### PR DESCRIPTION
**Pull request by Yashesvinee**
<hr>

## Description 📜

Documentation on JSON in Python
 Issue #7396 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Yashesvinee** [comment]
@adityabisoi

**Comment by adityabisoi** [comment]
Pls tag a mentor for review.

**Review by queenish001 — CHANGES_REQUESTED** [review]
The Documentation looks good, 
One small change:
- Please don't make any change in the main README, i.e. `Python/README.md`, so kindly remove that from your PR.

**Comment by Yashesvinee** [comment]
I have removed the changes in Python/README.md now

**Pull request merged**
