### PR TITLE
Frontend web development html Entities

### PR DESCRIPTION
**Pull request by harshapriyaa**
<hr>

## Description 📜

added code block for html code which was getting rendered in markdown. added some more information and a useful website for list of entities for reference.
Fixes: #2348

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by harshapriyaa** [comment]
@sifa123 @Knighthawk-Leo please review the changes.

**Comment by ayushjain27** [comment]
I want to contribute

**Review by sifa123 — COMMENTED** [review]
Please explain more. If you can, add examples.

**Comment by ayushjain27** [comment]
https://colab.research.google.com/drive/1_fpgAlHBlyNM4EHQj7NDH1Ykv76jDiSN?usp=sharing

**Comment by harshapriyaa** [comment]
@sifa123 I have made the changes. Please check.

**Comment by sifa123** [comment]
> @sifa123 I have made the changes. Please check.

Awesome..well done 💯

**Pull request merged**
