### PR TITLE
1.1 Android Architecture Overview

### PR DESCRIPTION
**Pull request by Priyanshirathore**
<hr>

## Description 📜
It describes the Android Architecture and its five components. It thoroughly explains all the components with flowchart images.(https://docs.google.com/document/d/1hkog6VhT8iIo8HRgLvhYaSpwfNkHXcthR8mbNC3fb_g/edit)

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <143> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (133)

@VikasPandey121 sir please review.

<hr>

### CODE REVIEW

**Comment by sitamadex11** [comment]
@Priyanshirathore your shared link has no permission to read please check it once.

**Comment by Priyanshirathore** [comment]
Done sir, sorry for the trouble.

**Comment by Priyanshirathore** [comment]
Done sir, sorry for the trouble.

**Comment by VikasPandey121** [comment]
Awesome work done @Priyanshirathore just a small change requested, Please do these changes 

- Create a new branch with name `Android_Development_With_Java` and push your PR on `Android_Development_With_Java` branch.
- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Align centre all the images and refract `Android_Development` directory with `Android_Development_Wit_Java` and add your file in `Android_Development_With_Java/Introduction/` directory. 
- `squash` your commit.

**Comment by VikasPandey121** [comment]
I am closing this PR right now, Please do the required changes. and open a new PR.

**Pull request closed without merging**
