### PR TITLE
[JS] Other: Functions

### LINKED ISSUE #247: JS: Functions
# Functions
Functions in JavaScript

## Directory
```
Topics/5.Syntax/6.Functions
```

## Description
- What is scope?
- What is the lifetime of JavaScript variables?
- Basic function syntax.
- What are parameters in functions?
- Types of functions.
- Why use functions?

### PR DESCRIPTION
**Pull request by sushovanb02**
<hr>

## Description 📜
Created a document on JavaScript functions. 
Fixes #247 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by sushovanb02** [comment]
@paramsiddharth sir here is the PR that you requested, it's creating 1 conflict because of Siddhi's PR ig

**Comment by paramsiddharth** [comment]
> @paramsiddharth sir here is the PR that you requested, it's creating 1 conflict because of Siddhi's PR ig

Did you do a `git pull upstream Javascript` before creating a new branch, Sushovan?

**Comment by faisal-on-git** [comment]
@paramsiddharth Sir I want to add how this keyword works in arrow functions. Please assign it to me.

**Comment by sushovanb02** [comment]
@paramsiddharth sir, I am generating a fresh PR so that the conflict vanishes. You can close this one

**Comment by sushovanb02** [comment]
and also as Siddhi's PR is merged the README file has her work (after cloning the repo again) so do I have to delete the contents of the README and add? I am confused about what to do. Please guide..

**Comment by paramsiddharth** [comment]
> and also as Siddhi's PR is merged the README file has her work (after cloning the repo again) so do I have to delete the contents of the README and add? I am confused about what to do. Please guide..

No no, you are supposed to extend it. Add more content to it.

**Comment by sushovanb02** [comment]
Oh you mean in between her content I'll add my contents?

**Comment by sushovanb02** [comment]
but won't that result in merge conflicts?

**Comment by paramsiddharth** [comment]
> Oh you mean in between her content I'll add my contents?

Yes!

> but won't that result in merge conflicts?

No. It would have been a conflict IF hers wasn't merged and both of your PRs were to be merged.

**Pull request closed without merging**
