### PR TITLE
Created the Tower of Hanoi Video and file

### LINKED ISSUE #3247: DSA : Recursion using Tower of Hanoi
### Description

I will submit the documentation on the topic Recursion using Tower of Hanoi, where I will explain the concept of recursion, and its step by step working through Tower of Hanoi problem.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by mrkc2303**
<hr>

## Description 📜

I have recorded and added the video for The Tower of Hanoi problem and created the file as well.
Kindly check
Fixes #3247 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by mrkc2303** [comment]
@nimisha-yadav Kindly Review!

**Comment by mrkc2303** [comment]
@nimisha-yadav  Kindly Review the PR!

**Review by nimisha-yadav — COMMENTED** [review]
Great work but can you create a folder ``1. Tower Of Hanoi Using Recursion`` in Misc Algo folder and rename your file as ``8.2.1_Tower_Of_Hanoi_Video.md``

**Comment by mrkc2303** [comment]
@nimisha-yadav All Done!
Kindly Check!!

**Comment by mrkc2303** [comment]
Hey @nimisha-yadav!
I think something wrong happened while pushing into the repository. I am closing this PR as it has been a mess now and making a new PR for the same.
Sorry for the inconvenience. 
Thank You

**Comment by mrkc2303** [comment]
Kindly review pr #8441

**Pull request closed without merging**
