### PR TITLE
Data type in C

### PR DESCRIPTION
**Pull request by shreyarai05**
<hr>

## Description 📜

I have briefly defined the fundamentals data type in C using numerous example along with code syntax.
Fixes # 1295

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x ] I have performed a self-review of my own code or work.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] My changes generates no new warnings.
- [ x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by deeqakkk** [comment]
96 files changed😲???
Shreya plz fetch all the changes from the "girlscript/C_CPP" to your local machine and then make a PR.

**Comment by shreyarai05** [comment]
Okay

**Comment by shreyarai05** [comment]
is it done??

**Comment by shreyarai05** [comment]
is it okay now??

**Comment by apeksha235** [comment]
@shreyarai05 close this PR and then fetch all the changes from girlscript/CPP then make a PR

**Comment by Saviour1001** [comment]
Closing this PR. Please fetch the updated repo and make the new PR. Here is a [video](https://drive.google.com/file/d/1MT427pPKeay_pXGNNuE4kMJj0xRkn6G-/view?usp=sharing) explaining the workflow.

**Pull request closed without merging**
