### PR TITLE
Looping Techniques & Functions #3944

### PR DESCRIPTION
**Pull request by Cyber-Prajwal**
<hr>

In this issue #Looping Techniques & Functions #3944 I have discussed different functions that can be used accordingly in different scenarios, like looping through dictionaries, list, reversing, combining, sorting etc.

##Functions covered are:
-  zip()
- enumerate()
- reversed()
- sorted()
- set()
- sorted() in combination with set()
- iteritem()
- items()

For each function, I have used examples to showcase the use and functionality and also I have tried to make the examples fun by using some pop culture references so as to make the reader more involved and concentrated and thereby able to understand clearly.

<hr>

## Type of change 📝
- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊
- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by Cyber-Prajwal** [comment]
> /unassign

@him54 why did you write assign on a pull request 😅 and unassign it does not work like that u r still assigned , search on google on how to unassign from a PR .

**Comment by him54** [comment]
Okay we will do it bro✌🏼

**Review by queenish001 — CHANGES_REQUESTED** [review]
1. Change the folder name from `Looping Techniques & Functions` to `Looping_Techniques_&_Functions`
2. 
image

In Markdown format, you have to add space between '#' and your written content.

**Comment by Cyber-Prajwal** [comment]
> 1. Change the folder name from `Looping Techniques & Functions` to `Looping_Techniques_&_Functions`
> 
> image
> 
> In Markdown format, you have to add space between '#' and your written content.

Done the required changes . Thank you @queenish001

**Review by queenish001 — APPROVED** [review]
Approved 💯 

@adityabisoi Kindly have a look :)

**Pull request merged**
