### PR TITLE
Data Science With Python: Scale-Invariant Feature Transform #5059 

### PR DESCRIPTION
**Pull request by Ruchika-20**
<hr>

## Description 📜

I have added the required code and also done changes in the information regarding the same. I had few bugs while implementing the code which i have resolved finally and completed the tutorial successfully. #5059 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add issue number and this is not sufficient. @Ruchika-20

**Comment by Ruchika-20** [comment]
So what do I need to include now?

**Comment by prathimacode-hub** [comment]
It's a documentation and tutorial type of contribution. It should be detailed enough to know everything about this topic. It still has lot to cover in terms of explanation and coding. @Ruchika-20

**Comment by Ruchika-20** [comment]
okay i will try my best but since i am beginner i don't know much

**Comment by prathimacode-hub** [comment]
> okay i will try my best but since i am beginner i don't know much

I will guide you don't worry @Ruchika-20

**Comment by Ruchika-20** [comment]
okay so please guide me so that this issue get closed asap as i haven't
made min 5 contribution also and this is the last month

**Comment by prathimacode-hub** [comment]
Text me on discord. We can discuss further on it. @Ruchika-20

**Review by prathimacode-hub — APPROVED** [review]
PR approved. @Ruchika-20

**Pull request merged**
