### PR TITLE
Added TypeScript Tutorial

### LINKED ISSUE #2100: TypeScript : Web Development
### Description

I want to make documentation part of TypeScript

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Koustav-1250**
<hr>

## Description 📜

Introduction to TypeScript
Fixes #2100

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Koustav-1250** [comment]
@2024-SANDHYA  Updated the file . Please check

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
No this is not how the file should appear. 

image






Refer markdown tutorial, please.

**Comment by Koustav-1250** [comment]
@2024-SANDHYA  Please Check it!!

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Again It's wrong !! Please go through Markdown tutorial or documentation 

image

**Comment by Koustav-1250** [comment]
Can you please tell me one mistake . I am not able to identify . Is the heading wrong?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Can you please tell me one mistake . I am not able to identify . Is the heading wrong?

Everything is wrong. Also, don't work on this issues. The TypeScript is not a  part of our domain (HTML CSS JS ). Kindly refer the road-map.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> > Can you please tell me one mistake . I am not able to identify . Is the heading wrong?
> 
> Everything is wrong. Also, don't work on this issues. The TypeScript is not a part of our domain (HTML CSS JS ). Kindly refer the road-map.

**Pull request closed without merging**
