### PR TITLE
CSS Variables #7534

### PR DESCRIPTION
**Pull request by khush2706**
<hr>

## Description 📜

Added documentation for what are CSS variables, why and how to use them and how to update them using JavaScript.

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
Great work. Add reference source to images if they are not ss taken by you.

**Comment by khush2706** [comment]
> Great work. Add reference source to images if they are not ss taken by you.

All of them are screenshots...

**Comment by kashishahuja2002** [comment]
> > Great work. Add reference source to images if they are not ss taken by you.
> 
> All of them are screenshots...

okay

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
LGTM. Tag the supervisor of your batch for further reviewing and merging the PR.

**Review by kashishahuja2002 — APPROVED** [review]

**Comment by khush2706** [comment]
> LGTM. Tag the supervisor of your batch for further reviewing and merging the PR.

Thankyou 😊

**Pull request merged**
