### PR TITLE
Data Science with Python : Apriori Algorithm (#1836)

### LINKED ISSUE #1836: Data Science with Python : Apriori Algorithm
This issue will helps readers in gaining all the guidance that one needs to know about Apriori Algorithm. Tutorial to Apriori Algorithm and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Dhruv Bajaj / Kareem Negm

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by rachita11**
<hr>

##  📜

Contribution was made in form of documentation about Apriori algorithm in data mining. The folder is contained in Machine learning/Algorithms directory and it contains 3 elements. One is the readme.md file which contains all the necessary information and theory there is to know about this algorithm to get started. The next file is a .ipynb file which shows the implementation of the algorithm using a test dataset. The third is a folder of all the images that have been used as part of explanation.
Resources and datasets were also added in their respective directories. The motivation behind fixing this issue was not just for being able to learn but also of being able to help someone through this information in an easy beginner friendly way.
Fixes #1836 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

All the folders should be in this format : New Folder
It means there should be change of format for "Images", "Apriori Algorithm" in "DS Datasets" and "DS Resources"
Instead of creating resource file and adding all the resources, you can change it into "README.md" since we know it's in "DS Resources" repo.
In main README.md, you can add features, why its preferred, where should it be used, advantages, applications and conclusion with overall summary of the topic.
In .ipynb file, before getting directly into code, give some introduction of what this topic is and how it's derived from. You can also elaborate it more using some sample example of how this algorithm is used in particular project.

Kindly work on it. @rachita11

**Comment by rachita11** [comment]
The necessary changes have been done. Please see if it okay now ma'm @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, all images should be in "Images" folder. @rachita11

**Comment by rachita11** [comment]
@prathimacode-hub ma'am the way I have understood this, all the images are now in 'Images' folder of Apriori algorithm. Have I done the right changes?

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Congrats on your PR. Well done. Keep going. 🎇🎉🙌@rachita11

**Pull request merged**
