### PR TITLE
Java 12.5: Using final with Inheritance

### LINKED ISSUE #2428: Java 12.5: Using final with Inheritance
### Description

Add audio, documentation, and video regarding the **Using final with Inheritance**.

____

### Location of File to be added

The files should be added inside the `Using final with Inheritance`  folder which is inside the `Inheritance`  folder present in the   `Java`  main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by AbhinandanAdhikari**
<hr>

## Description 📜

Created Documentation for using final with Inheritance.
Fixes #2428 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AbhinandanAdhikari** [comment]
@AkMo3 @garvitraj Please review this Pull Request.

**Comment by garvitraj** [comment]
@sumitaccess007 pls have a look

**Review by garvitraj — COMMENTED** [review]
@AkMo3 rest it's fines for me

**Comment by garvitraj** [comment]
> @AbhinandanAdhikari
> You explained it beautifully, can you please add below details as well -
> 
> 1. Under Final Class
>    Tell that final class does not mean that the fields of objects of this class cannot be changed.
> 2. You explained about Final Primitive Variables
>    If possible also write about the use of final for Reference Variables
> 
> Thanks

@AbhinandanAdhikari pls follow up the change

**Comment by AbhinandanAdhikari** [comment]
> @AbhinandanAdhikari You explained it beautifully, can you please add below details as well -
> 
> 1. Under Final Class
>    Tell that final class does not mean that the fields of objects of this class cannot be changed.
> 2. You explained about Final Primitive Variables
>    If possible also write about the use of final for Reference Variables
> 
> Thanks

@sumitaccess007 Okay! Adding these points.

**Comment by AbhinandanAdhikari** [comment]
@garvitraj @sumitaccess007  Made the changes, now review it.

**Review by garvitraj — APPROVED** [review]

**Pull request merged**
