### PR TITLE
Python: Advanced functions-Map #572

### LINKED ISSUE #572: Python: Advanced functions-Map
### Description :
What is `Map` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by sangeetasingh17**
<hr>

## Description 📜

Python: Advanced functions-Map
I have prepared the documentation on the topic. Mapping in python is like cheery on the top. It makes the iterating work super easy.
Fixes #572  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Python_Domain
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Randrita — APPROVED** [review]
looks great to me! but @sangeetasingh17 please add it using a proper folder structure. I must tell you this earlier. My bad sorry! I am sharing the proper resources with you in the channel!

**Comment by sangeetasingh17** [comment]
I created a folder structure. Is that not correct? How else should I do it? @Randrita

**Comment by adityabisoi** [comment]
I see the index has not been updated?

**Comment by sangeetasingh17** [comment]
Yeah I will update it

**Comment by sangeetasingh17** [comment]
Yeah I will update it

**Pull request closed without merging**
