### PR TITLE
HTML Class and Id

### PR DESCRIPTION
**Pull request by Alankrita9**
<hr>

## Description 📜

documentation on HTML classes and id, covering all the information related to web development  #1277

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by sifa123 — COMMENTED** [review]
Describe more, add examples with output. Change the headline like **HTML Classes and Ids**

**Comment by Alankrita9** [comment]
@sifa123  okay will do that

**Comment by Alankrita9** [comment]
@sifa123  done all the changes please reivew.

- Introduction
- Class Selector
- When to assign an Class attribute to an HTML element
- Id Selector
- When to assign an id attribute to an HTML element
- DIFFERENCE BETWEEN CLASS AND ID (table + code + output )
- Using ID and CLASS together (code + output)
- WHEN TO USE CLASS VS ID IN CSS
- CONCLUSION

**Review by sifa123 — COMMENTED** [review]
Well done!!

**Pull request merged**
