### PR TITLE
Python: Yield Keyword

### LINKED ISSUE #2927: Python: Yield Keyword
### Description

Description:
What is the yield keyword?
Where yield keyword is used?
Advantages and Disadvantages.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by nakshatra-garg**
<hr>

## Description 📜

Added Yield Keyword Documentation.
Fixed #2927 
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

@adityabisoi @hritikksingh

### CODE REVIEW

**Comment by nakshatra-garg** [comment]
Please review @adityabisoi @hritikksingh

**Review by hritikksingh — APPROVED** [review]
@adityabisoi this can be merged.
But @nakshatra-garg try to study and then write it on your own if possible rather than using GFG straight away.

**Comment by adityabisoi** [comment]
@nakshatra-garg Please resolve conflicts.

**Comment by nakshatra-garg** [comment]
> @nakshatra-garg Please resolve conflicts.

done

**Pull request merged**
