### PR TITLE
Python: 1.3 Learning version control- GitHub terminologies

### PR DESCRIPTION
**Pull request by kunal-kumar-chaudhary**
<hr>

## Description 📜

Added the notebook explaining the basics of git and GitHub terminologies.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

The ipynb file should be as "learning_githb.ipynb"
The issue title is learning github. It means it should include everything. Starting from github, it's introduction, purpose, what are the terminologies used and final outcomes
Other than this, README.md is also needed which gives detailed elaborations from aim, definition, how it's used, how it works, brief overview, application, advantages, how to optimize, why should one chose github, visual representations, references you have referred  and conclusion derived out of it.

Kindly work on it. @kunal-kumar-chaudhary

**Comment by kunal-kumar-chaudhary** [comment]
> Changes to be done 👍
> 
> The ipynb file should be as "learning_githb.ipynb"
> The issue title is learning github. It means it should include everything. Starting from github, it's introduction, purpose, what are the terminologies used and final outcomes
> Other than this, README.md is also needed which gives detailed elaborations from aim, definition, how it's used, how it works, brief overview, application, advantages, how to optimize, why should one chose github, visual representations, references you have referred and conclusion derived out of it.
> 
> Kindly work on it. @kunal-kumar-chaudhary

Thanks for the feedback. I'll work on this!

**Comment by prathimacode-hub** [comment]
By when can I expect the changes, @kunal-kumar-chaudhary

**Comment by kunal-kumar-chaudhary** [comment]
> By when can I expect the changes, @kunal-kumar-chaudhary

I'm really sorry for this gap, University is open so hope you understand! I'll try to make all the changes by today itself and then create a pull request.

**Comment by kunal-kumar-chaudhary** [comment]
hey @prathimacode-hub i have created the pull request

**Comment by kunal-kumar-chaudhary** [comment]
> hey @prathimacode-hub i have created the pull request

I've followed the exact same directory hierarchy, but it's showing me conflicting files. there's a already a README file present. in that case, should i keep my both .ipynb file and README.md file inside a folder? if yes, then what should i name that folder?
kindly look into this.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Ok, if that's the case. It means you haven't made both main repo and forked repo even before starting with workflow so do that. 
And then do the workflow, if you're still getting issue then refork it again, make it even and do it. One more thing, there is video attached to pinned messages where in you can check on how to solve merge conflicts.

Contribution is perfect. Only do these changes and it's done. @kunal-kumar-chaudhary

**Comment by kunal-kumar-chaudhary** [comment]
> Changes to be done :
> 
> Ok, if that's the case. It means you haven't made both main repo and forked repo even before starting with workflow so do that. And then do the workflow, if you're still getting issue then refork it again, make it even and do it. One more thing, there is video attached to pinned messages where in you can check on how to solve merge conflicts.
> 
> Contribution is perfect. Only do these changes and it's done. @kunal-kumar-chaudhary

hey @prathimacode-hub , i have resolved the merge conflict.

**Comment by kunal-kumar-chaudhary** [comment]
> Changes to be done :
> 
> Ok, if that's the case. It means you haven't made both main repo and forked repo even before starting with workflow so do that. And then do the workflow, if you're still getting issue then refork it again, make it even and do it. One more thing, there is video attached to pinned messages where in you can check on how to solve merge conflicts.
> 
> Contribution is perfect. Only do these changes and it's done. @kunal-kumar-chaudhary

hey @prathimacode-hub please review the changes.

**Comment by kumarankm** [comment]
@adityabisoi close this pr

**Pull request closed without merging**
