### PR TITLE
Added video tutorial link for single inheritance

### PR DESCRIPTION
**Pull request by adityarajsahoo**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@adityarajsahoo Amazing work on the video! 
Just make a seperate branch for seperate issues

**Comment by adityarajsahoo** [comment]
Separate branch for the next issue right or this one? Is the present pull request going to be accepted?

**Comment by apeksha235** [comment]
No just delete the extra file @adityarajsahoo

**Comment by adityarajsahoo** [comment]
Ok I think I have deleted the extra files. Can you check @apeksha235

**Comment by Suvraneel** [comment]
@adityarajsahoo  Yes you had messed it up
Never delete a file to revert changes... Always look at the parent repo (here, girlscript/C_CPP) and keep the exact content on your copy...
You had deleted our readme.... That will never be merged...

Anyway, I fixed it for you ... Observe all the changes made on readme & your .md carrying video link & follow them next time...

Good work on the video ❤️  Hoping to see more such contributions

**Comment by Suvraneel** [comment]
@adityarajsahoo  Also next time, during the initial theory part, try showing some theory text...
Otherwise its a bit difficult to follow your voice without visual cues...

LGTM 🚀

**Comment by adityarajsahoo** [comment]
Thanks a lot @Suvraneel for the suggestions. I will look forward to not make these mistakes again and be a better contributer.

**Pull request merged**
