### PR TITLE
Bubble Sort

### LINKED ISSUE #878: CPP: Bubble Sort
<hr>

## Description 📜

I want to create a documentation explaining bubble sort technique in C++.

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

### LINKED ISSUE #885: C : dynamic memory allocation
<hr>

## Description 📜

I want to explain Dynamic memory allocation in C, using code examples. Documentation

<hr>

## Domain of Contribution 📊

- [x] C/CPP
<hr>

### PR DESCRIPTION
**Pull request by Xyandraa9**
<hr>

## Description 📜

I made a documentation for Bubble sorting in c++. I also added documentation for dynamic memory allocation.
Fixes #878
Fixes #885

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Shivani0701 — COMMENTED** [review]
Amazing Work ✌️@Xyandraa9 
@Suvraneel please merge it.

**Review by vasu-1 — APPROVED** [review]
@Suvraneel 
Make a directory named  ` Array Sorting ` and move ` BubbleSort.md ` to this directory !!
And Merge this.

**Comment by Suvraneel** [comment]
@vasu-1  There is already 1 directory
Data Structures > Sorting

**Comment by vasu-1** [comment]
> @vasu-1 There is already 1 directory
> Data Structures > Sorting
> Usi mein daal raha hun

Cool ! :100:

**Comment by Suvraneel** [comment]
@vasu-1 @Xyandraa9  Wait a minute,  why's there Dynamic Alloc files on this?

**Comment by Xyandraa9** [comment]
I apologise for the error, it's actually my first time contributing so I thought when i commit the changes to the Dynamic Memory Allocation issue, I will be able to create another PR, but I got confused. What should I do to rectify this?

**Comment by vasu-1** [comment]
@Xyandraa9 please delete this pr ..
And make two new saperate PRs for both the issues 👍

**Comment by Xyandraa9** [comment]
@vasu-1 okay

**Pull request closed without merging**
