### PR TITLE
Datascience with python : Music Recommendation Systems

### LINKED ISSUE #2261: Data Science with Python : Music Recommendation Systems
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Music Recommendation Systems. Tutorial to Music Recommendation Systems and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Kareem Negmj / Peehu Saxena

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by SaloniThete**
<hr>

## Description 📜
Added Tutorial with Detailed explanation of Music Recommendation Systems and how it's applied using sample code in jupyter notebook.
Added README.md
Added Requirements.txt
Added Images
Fixes #2261 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by SaloniThete** [comment]
Kindly review the PR.
@prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :
This is a project so it should go under "Datascience_with_Python/Machine Learning/Projects" folder
The .csv file should be in "DS Datasets/Music Recommendation Systems"

Do these changes other perfect. @SaloniThete

**Comment by SaloniThete** [comment]
Mam, I have made the requested changes, kindly review the PR.
@prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You have added in right place but you haven't removed the existing duplicate copy of this project. @SaloniThete

**Comment by SaloniThete** [comment]
deleted the duplicate copy. kindly review the PR.
@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Your dedication is amazing.✔👌@SaloniThete

**Pull request merged**
