### PR TITLE
Frontend : Html Text Formatting

### LINKED ISSUE #1048: Frontend : HTML Text Formatting
<hr>

## Description 📜
 I want to add documentation on HTML Text Formatting with it's code and output.
 Please /assign it to me 

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by ruhirani011**
<hr>

## Description 📜

I've documented about HTML Text Formatting , the different ways to style texts using HTML Elements .
Fixes #1048 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ruhirani011** [comment]
@code-reaper08  @praveenscience sir Please  check my contribution.

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
I would like to see you include, some lesser known Typographic elements here. That would make it more awesome.

**Comment by ruhirani011** [comment]
@code-reaper08 Sir by saying some lesser known typographic elements do you mean <u> <tt> <s> or shall I add <pre><code><cite> as well.

**Comment by ruhirani011** [comment]
@code-reaper08 Sir by saying lesser known typographic elaments \<u>

**Comment by ruhirani011** [comment]
@code-reaper08  @praveenscience Sir Please review this.

**Review by code-reaper08 — COMMENTED** [review]
Look once @2024-SANDHYA

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
It looks good !! @ruhirani011 
 Just mention the reference links at the bottom and that's all 😄

**Comment by ruhirani011** [comment]
@2024-SANDHYA Which reference links ? Can you please explain .🙂

**Comment by ruhirani011** [comment]
> It looks good !! @ruhirani011
> Just mention the reference links at the bottom and that's all 😄

@2024-SANDHYA Which reference links ? Can you please explain .🙂

**Comment by 2024-SANDHYA** [comment]
> 
> 
> > It looks good !! @ruhirani011
> > Just mention the reference links at the bottom and that's all 😄
> 
> @2024-SANDHYA Which reference links ? Can you please explain .🙂

The website links, from which you've taken the information or the idea. Mention their URLs. @ruhirani011

**Comment by ruhirani011** [comment]
> > > It looks good !! @ruhirani011
> > > Just mention the reference links at the bottom and that's all 😄
> > 
> > 
> > @2024-SANDHYA Which reference links ? Can you please explain .🙂
> 
> The website links, from which you've taken the information or the idea. Mention their URLs. @ruhirani011

I've taken ideas from many sites .Shall I mention all of them.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> > The website links, from which you've taken the information or the idea. Mention their URLs. @ruhirani011
> 
> I've taken ideas from many sites .Shall I mention all of them. @2024-SANDHYA

Of course 🤦🏻

**Review by 2024-SANDHYA — APPROVED** [review]

**Review by code-reaper08 — APPROVED** [review]
Looks good 🚀

**Pull request merged**
