### PR TITLE
What is kivy ?? & Creating your first GUI app with kivy , installation and setup . #8158

### PR DESCRIPTION
**Pull request by Cyber-Prajwal**
<hr>
What is kivy ?? & Creating your first GUI app with kivy , installation and setup . #8158

In this document, I have written a short intro to the Kivy module of Python.
- I have included all the requirements and separate modules required to use kivy.
- I have also used a lot of screenshots for showing the installation process.
                                                   and 
- I have created a small hello world GUI app 
- I have attached the Python code for each step.
                                                  and 
In the end, I have attached links to a few more good resources if someone liked to use kivy and wanted to learn more about kivy python app development.

<hr>

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

Screenshot (620)
Screenshot (621)
Screenshot (622)
Screenshot (623)
Screenshot (624)
Screenshot (625)
<hr>

### CODE REVIEW

**Comment by Cyber-Prajwal** [comment]
kindly check @adityabisoi

**Comment by kumarankm** [comment]
@Cyber-Prajwal Remove that doc file, not needed

**Comment by Cyber-Prajwal** [comment]
> @Cyber-Prajwal Remove that docx file, not needed

Removed 👍

**Review by kumarankm — APPROVED** [review]
Looks good 👍🏻 
You can merge this pr @adityabisoi

**Pull request merged**
