### PR TITLE
1.6. Maximum Likelihood Estimation.ipynb

### PR DESCRIPTION
**Pull request by amitrakshar01**
<hr>

## Description 📜

Added 1.6. Maximum Likelihood Estimation#591

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by amitrakshar01** [comment]
@abhisheks008 Added ipynb file. Images not compatible with .md file. Please check and merge.

**Comment by abhisheks008** [comment]
@amitrakshar01 I will create a folder `Assets`, you can upload all the required images, GIFs, thumbnails and then get the URL of that particular image from that folder, it will work. Try this first, if it's not working then you'll go with .ipynb file upload.

**Comment by amitrakshar01** [comment]
> @amitrakshar01 I will create a folder `Assets`, you can upload all the required images, GIFs, thumbnails and then get the URL of that particular image from that folder, it will work. Try this first, if it's not working then you'll go with .ipynb file upload.
> No need to change the readme file, pls keep it as it was. We'll be linking all the documents using a chart in the future times.

Done

**Comment by abhisheks008** [comment]
One last change requested, pls change the title of the `.md` file as `ML_1_6_Maximum_Likelihood_Estimation_(D).md`

**Comment by amitrakshar01** [comment]
> One last change requested, pls change the title of the `.md` file as `ML_1_6_Maximum_Likelihood_Estimation_(D).md`
> @amitrakshar01

np done :)

**Comment by abhisheks008** [comment]
Great work and congratulations on your first contribution. Good to go! @amitrakshar01

**Pull request merged**
