### PR TITLE
Added documentation of Sliding Window Maximum

### LINKED ISSUE #1217: Competitive Programming : : Sliding window maximum (documentation)
<hr>

## Description 📜

I would like to provide documentation about the Sliding window maximum problem.

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

### PR DESCRIPTION
**Pull request by areenoverclouds**
<hr>

## Description 📜

I have added the documentation of the Sliding Window Maximum Problem.
Topic: Maximum of all subarrays of given size K.
Language: C++
Format: Documentation
Fixes #1217

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ravireddy07** [comment]
@areenoverclouds The contributions are acceptable for documentation through either markdown or google colab.
Not a `.txt` file. please add it.

**Comment by areenoverclouds** [comment]
> @areenoverclouds The contributions are acceptable for documentation through either markdown or google colab. Not a `.txt` file. please add it.

I've added google colab link now. Please check if this is ok

**Review by ravireddy07 — CHANGES_REQUESTED** [review]
make the heading highlighted

**Comment by areenoverclouds** [comment]
> make the heading highlighted

done, sir

**Review by ravireddy07 — APPROVED** [review]

**Comment by areenoverclouds** [comment]
@ErzaTitania-2001 ma'am kindly merge my PR as it has been past 12 days and bot reassigned it.
Thank you.

**Pull request merged**
