### PR TITLE
Added npm in Opensource 

### LINKED ISSUE #2479: Open Source : npm in opensource
#### The npm Registry is a repository of open-source software packages hosted by npm for the Node. js developer community. Using npm's hosted service is free for open source software, and private package hosting is available for teams and individual developers.
<br>

*Points to Note*
* Describe and explain npm and npm packages 
* Their role in promoting opensource , shareable software for everyone . 
* Setting up npm in various operating system and linux distributions  .
* Basic commands used in npm .
* npm vs npx 

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by eshan1925**
<hr>

## Description 📜
I have added everything related to the role of npm in Opensource, with this I have also covered all the points mentioned in the issue.
Also, I have given the user to copy the code directly from the documentation where it is required.

Fixes #2479 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Review by ashish-patwal — APPROVED** [review]
LGTM

**Comment by ashish-patwal** [comment]
@Aryamanz29 please take a look ?

**Comment by Aryamanz29** [comment]
@eshan1925  Merging this now but we don't need any section named `NPM`  , Instead of you can create with the name `Popular OS projects & software` but nvm I'll do that and add your doc inside it

**Review by Aryamanz29 — APPROVED** [review]
LGTM
Thanks for contributing 🎉🎉

**Comment by eshan1925** [comment]
> @eshan1925  Merging this now but we don't need any section named `NPM`  , Instead of you can create with the name `Popular OS projects & software` but nvm I'll do that and add your doc inside it

@Aryamanz29 thank you so much but actually it was not mentioned clearly in the issue where to store the file ...will ask you next time if there is a confusion.
Thankyou Again😁

**Pull request merged**
