### PR TITLE
Stock Span Problem

### LINKED ISSUE #1059: Stock Span Problem Documentation
<hr>

## Description 📜

Stock Span Problem Documentation using stack

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by sinu-02**
<hr>

## Description 📜
I have provided a documentation of stock span problem using stack where the problem statement has been explained ,the algorithm followed to solve the problem and the code has been provided in cpp .

Fixes #1059  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Suvraneel** [comment]
@sinu-02  One thing I forgot to mention ...
Kindly put this files in a pre-defined directory...
I mean not a new directory
I'll merge after that...

**Comment by sinu-02** [comment]
@Suvraneel 

Sir in that pre- defined directory do I have to generate pr again??

**Comment by Suvraneel** [comment]
@sinu-02 No it'll be done in the same PR
Problems:
image
Fix :
Pull & merge from girlscript/C_CPP branch

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Like I said before, pull from girlscript/C_CPP branch

77 changed files wont do

**Comment by sinu-02** [comment]
@Suvraneel 
I have generated new pr for the same please look on to #1904 and after that I will close this pr. That new pr is pulled from C_CPP not from main stream.

**Comment by Suvraneel** [comment]
okay I'll close this one cuz this one's invalid anyway

**Pull request closed without merging**
