### PR TITLE
C_CPP: Parametrized Constructor

### LINKED ISSUE #2579: C_CPP: Parametrized Constructor
### Description

documentation

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by 124015001**
<hr>

## Description 📜

Explained about Parametrized Constructor. Also, performed a program explaining the same.
Fixes #2579  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by 124015001** [comment]
@vasu-1 Can you check if its fine?

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please Make two saperate Prs for these two issues !!!!
- Also Put some more content or add one or two lines for these topics.(Optional)

**Comment by vasu-1** [comment]
Kindly close this Pr or make this pr for 1 issue !!!

**Review by vasu-1 — APPROVED** [review]
Approved 
@Suvraneel  please merge this pr

**Comment by vasu-1** [comment]
Good Work @124015001

**Comment by vasu-1** [comment]
What is overloaded constructure Pr no ??

**Comment by 124015001** [comment]
I am unable to create another PR. The new commits are just getting merged with this PR.

**Comment by vasu-1** [comment]
just open another pr and make commits !!!

**Comment by Saviour1001** [comment]
You need to learn about branching with Git, creating branches allows you to keep work of separate issues on separate branches. This way from 2 different branches you will be able to create 2 different PRs. Here is something which will [help](https://www.gitkraken.com/learn/git/problems/create-git-branch).

**Comment by 124015001** [comment]
@Saviour1001 Thanks for sharing. Can you merge this PR till then? I will create another PR with a new branch.

**Pull request merged**
