### PR TITLE
DSA String: Super ASCII String Checker

### LINKED ISSUE #4474: DSA String: Super ASCII String Checker
### Description

In the Byteland country, a string S is said to super ASCII string if and only if the count of each character in the string is equal to its ASCII value. In the Byteland country ASCII code of ‘a’ is 1, ‘b’ is 2, …, ‘z’ is 26. The task is to find out whether the given string is a super ASCII string or not. If true, then print “Yes” otherwise print “No”.

Examples:

Input: S = “bba” 
Output: Yes

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by priyanka001tech**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #4474 

Super Ascii String Checker --Codevita Interview Question

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
@priyanka001tech add your file in strings standard problem folder and name it in succession of the file names.

Please review the doc @harshsri28 @sneha-nitdgp

**Comment by priyanka001tech** [comment]
> @priyanka001tech add your file in strings standard problem folder and name it in succession of the file names.

Ma'am I've done that

**Review by harshsri28 — CHANGES_REQUESTED** [review]
format your example , rest is looking good

**Comment by priyanka001tech** [comment]
> format your example , rest is looking good

Done

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by nimisha-yadav — APPROVED** [review]

**Comment by nimisha-yadav** [comment]
> @priyanka001tech add your file in strings standard problem folder and name it in succession of the file names.

Please do this change as well, and put your ascii string problem file in Standard Problem folder in 2.1 Strings. Rest is looking fine.

**Comment by priyanka001tech** [comment]
> > @priyanka001tech add your file in strings standard problem folder and name it in succession of the file names.
> 
> Please do this change as well, and put your ascii string problem file in Standard Problem folder in 2.1 Strings. Rest is looking fine.
> 
> Edit: Can you please also rename your Subarray file as 1.1.5.9_Largest...

Done ma'am

**Review by nimisha-yadav — APPROVED** [review]
Great work!

**Pull request merged**
