### PR TITLE
C cpp

### LINKED ISSUE #1649: CPP: Different Searching Techniques
<hr>

## Description 📜

Here, I will provide documentation of different searching techniques.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by krkaustubh**
<hr>

## Description 📜

Here I have covered the topics such as Linear Search and Binary Search.
Fixes #1649

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by krkaustubh** [comment]
@Saviour1001  please review my work.

**Comment by ChetasShree** [comment]
Hey @krkaustubh , since u have used gfg images so it will come under plagiarism, so you have two options, one to mention the resources from where you have taken the resources or change the images.

**Comment by krkaustubh** [comment]
Hey @ChetasShree , I have added the reference of gfg please check it once.

**Comment by krkaustubh** [comment]
@Saviour1001  @ChetasShree @Suvraneel  please review my work I have made the required changes

**Pull request merged**
