### PR TITLE
Machine learning

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
<hr>

## Description 📜

Audio P-Value #1263

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by kshitijshrivastava1903 — COMMENTED** [review]
Please add some background detail on null hypothesis theory, and also on how is p-value calculated, so that any reader can understand.

**Comment by BhaswatiRoy** [comment]
@kshitijshrivastava1903 changed and updated

**Comment by kshitijshrivastava1903** [comment]
The audio file is good, include some documentation as well, like images of graphs for explaining how is p-value calculated, and a clear explanation of conditions under which null hypothesis theory is accepted or rejected, so that, with a glace on the text, the reader can understand, and if he/she wants to know more about it, will open the audio file. Write like :

if (p-value<0.5)
.....
else
......

**Comment by BhaswatiRoy** [comment]
@kshitijshrivastava1903 readme updated

**Comment by abhisheks008** [comment]
Good one @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> Good one @BhaswatiRoy

Thank you

**Pull request merged**
