### PR TITLE
Data Science with Python : Normalization and Standardization

### PR DESCRIPTION
**Pull request by Samhitha-Jasti**
<hr>

## Description 📜

Issue on Data Science with Python: Normalization and Standardization has been solved
Fixes # <#471> 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the project structure given. It has nothing except with audio link. @Samhitha-Jasti

**Comment by Samhitha-Jasti** [comment]
OK ma'am, I'll add the details about the issue by evening or tomorrow @prathimacode-hub

**Comment by Samhitha-Jasti** [comment]
Ma'am I edited the readme file with all the data, can you please check @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The README.md file, you had created directly in main repo of GWOC. Instead it should go under "/Data_Science_with_Python/Machine Learning/Tutorials/Normalization and Standardization" folder.
In README.md, You can add purpose, applications, advantages, how it can be optimized then instead of just putting up a link, put up a subheading to say what it is, and outline of topics you had covered up in audio, then finally overall summary and conclusion. @Samhitha-Jasti

**Comment by Samhitha-Jasti** [comment]
I edited ma'am, can you check @prathimacode-hub

**Comment by prathimacode-hub** [comment]
It's still showing up in main repo. Transfer your project to mentioned repo as addressed in earlier comment. Kindly check through it. And you had added up things in README but conclusion is missing.

**Pull request closed without merging**
