### PR TITLE
Frontend web development html css js

### LINKED ISSUE #1155: Frontend_Web_Development_HTML_CSS_JS: The DOM
# The DOM
DOM in JavaScript
<hr>

# Directory
```Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/7.The DOM```
## Description 📜

Creating a tutorial on DOM in Javascript for Front_End_Web_Development_HTML_CSS_JS branch and discussing the following:
- What is the DOM?
- The DOM tree structure
- Accessing the DOM
- DOM Methods
- What is Document Object?

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

# Format
- [x] Documentation

### PR DESCRIPTION
**Pull request by Arya-Gupta**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1155

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Check the link once.

@2024-SANDHYA are you able to access the link, or is it just me?

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
For me too it's not working @code-reaper08

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
No need to add all this information about yourself, take this down. Information about DOM should be included in the readme where you've mentioned the link.

image

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Oops !! 

Do it like :

Heading 
  - About DOM
  - Link

**Review by code-reaper08 — APPROVED** [review]
Now it's cool 💯

**Review by 2024-SANDHYA — APPROVED** [review]
Looks good !! 💯

**Pull request merged**
