### PR TITLE
C_CPP: Created Spiral_Matrix.md

### LINKED ISSUE #2632: C_CPP : The Spiral Matrix
### Description

CODE for storing elements of any array in spiral matrix form and returning elements of any matrix in spiral order.

### Domain

C/CPP

### Type of Contribution

- [x] Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by subodh-kasaudhan**
<hr>

## Description 📜
I will write CODE for storing elements of any array in spiral matrix form and returning elements of any matrix in spiral order.
Fixes #2632 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

spiral_matrix spiral_array

<hr>

### CODE REVIEW

**Comment by shivam-iitk** [comment]
@kashishahuja2002 @vasu-1 please suggest changes if any!

**Comment by shivam-iitk** [comment]
Is it fine now? @Suvraneel

**Comment by vasu-1** [comment]
> Also, do I have to close PR after it gets merged? @Suvraneel

no need !

**Comment by Suvraneel** [comment]
@shivam-iitk  LGTM ❤️  Awesome

**Pull request merged**
