### PR TITLE
DSA

### PR DESCRIPTION
**Pull request by themonikanayak**
DSA: Spiral Print of 2D Array #1547

### CODE REVIEW

**Comment by khareyash05** [comment]
@themonikanayak Kindly resolve merge conflicts

**Comment by themonikanayak** [comment]
> @themonikanayak Kindly resolve merge conflicts

How to do that?

**Comment by khareyash05** [comment]
Update ur local branch with the branch using `git pull upstream/(your branch name)`

**Comment by Muskan-creator** [comment]
please review  @Sneha-0308

**Comment by nimisha-yadav** [comment]
PR has merge conflicts and the issue is repetitive so closing it.

**Pull request closed without merging**
