### PR TITLE
Data Science with Python : Ridge and Lasso Regression

### LINKED ISSUE #7398: Data Science with Python : Ridge and Lasso Regression
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know on how to work on implement Ridge and Lasso Regression Algorithms using Python

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : Pushpit Jain | Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by srini047**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7398 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

- Add what you had done in PR description and your issue title in your PR title.
This is a documentation contribution so be elaborate enough. README needs more detailing
- And there should be an .ipynb file which demonstrates the practical implementation of Lasso and Ridge Regression using test case. It should have short intro of issue topic, clear understanding of the implementation and overall summary at the end.
- Add all images, visualizations and screenshots in "Images" folder
- Add "requirements.txt" file with used libraries in this issue topic
- Keep your project folder as "Lasso and Ridge Regression" and file name of .ipynb in snake case

Kindly do the needful changes. @srini047

**Comment by srini047** [comment]
> Changes to be done :
> 
> - Add what you had done in PR description and your issue title in your PR title.
> This is a documentation contribution so be elaborate enough. README needs more detailing
> - And there should be an .ipynb file which demonstrates the practical implementation of Lasso and Ridge Regression using test case. It should have short intro of issue topic, clear understanding of the implementation and overall summary at the end.
> - Add all images, visualizations and screenshots in "Images" folder
> - Add "requirements.txt" file with used libraries in this issue topic
> - Keep your project folder as "Lasso and Ridge Regression" and file name of .ipynb in snake case
> 
> Kindly do the needful changes. @srini047 

Sure I will do the needful.

**Comment by prathimacode-hub** [comment]
Also this issue is of Datascience_with_Python domain, uncheck machine learning and check relevant one in your PR template. @srini047

**Comment by srini047** [comment]
> 

Sorry for this. My bad. 😔

**Comment by prathimacode-hub** [comment]
> > 
> 
> Sorry for this. My bad. 😔

And also add what you had done in this in your PR template description. Kindly do all the changes requested. @srini047

**Comment by srini047** [comment]
> > > 
> > 
> > 
> > Sorry for this. My bad. 😔
> 
> And also add what you had done in this in your PR template description. Kindly do all the changes requested. @srini047

Sure will do it within today.

**Comment by srini047** [comment]
- [x] Add all images, visualizations and screenshots in "Images" folder
- [x] Add "requirements.txt" file with used libraries in this issue topic
- [x] Keep your project folder as "Lasso and Ridge Regression" and file name of .ipynb in snake case
- [x] And there should be an .ipynb file which demonstrates the practical implementation of Lasso and Ridge Regression using test case. It should have short intro of issue topic, clear understanding of the implementation and overall summary at the end.
- [x] Add what you had done in PR description and your issue title in your PR title. This is a documentation contribution so be elaborate enough. README needs more detailing.

@prathimacode-hub I have done the necessary changes. Please re-review.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Datasets should be added in "/Datascience_with_Python/Machine Learning/Lasso and Ridge Regression". The file you loaded is in wrong place.
README can be more elaborated. @srini047

**Comment by srini047** [comment]
@prathimacode-hub I have done the necessary changes as per review.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add workflow, how it's implemented, its uses and benefits, data visualizations, conclusion in README.md @srini047

**Comment by srini047** [comment]
I have done the necessary changes as per previous review @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. You had done an impressive work. Keep it up. 👌👏@srini047

**Comment by srini047** [comment]
> PR approved. You had done an impressive work. Keep it up. 👌👏@srini047

Thanks, @prathimacode-hub mam for your feedback. It really means a lot.

**Pull request merged**
