### PR TITLE
[Frontend]: CSS Box Model

### LINKED ISSUE #930: Frontend :The Box Model in CSS
<hr>

## Description 📜
Every element is surrounded with a box. Here I will explain The Box Model in CSS via Video.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by nayyyhaa**
<hr>

## Description 📜

Here I've explained briefly about CSS Box Model in the documentation. The following topics are covered:
1) Content Box Model
2) Border Box Model

along with the examples and visual representation of both.

Fixes #930

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by nayyyhaa** [comment]
@code-reaper08, please review it :)

**Review by code-reaper08 — COMMENTED** [review]
Looks so awesome @nayyyhaa 🎊 
I'll merge it soon.

**Comment by nayyyhaa** [comment]
> Looks so awesome @nayyyhaa 
> I'll merge it soon.

Sure, thanks! 😃

**Review by code-reaper08 — APPROVED** [review]

**Comment by code-reaper08** [comment]
Hello @nayyyhaa!
I missed to spot that you didn't have a folder for this.

For example the file should be inside,
`winter-of-contributing/Web_Development/FrontEnd/CSS_BoxModel/yourfile.md`

Please have a look, and I'll merge it back.

**Review by code-reaper08 — COMMENTED** [review]
I've commented about file structure, do have a look.

**Comment by nayyyhaa** [comment]
> I've commented about file structure, do have a look.

Sure, will make the changes.

**Comment by code-reaper08** [comment]
Ping the new PR here, so that It'll be easy to merge.

**Pull request merged**
