### PR TITLE
[JS] Topic: add JavaScript history

### LINKED ISSUE #70: JS: Discuss the History of JavaScript
# Discuss the History of JavaScript
Talk about the historical development of JavaScript

## Directory
```
Topics/2.History
```

## Description
Refer to the history of the usage of scripting in front-end
and the [Wikipedia](https://en.wikipedia.org/wiki/JavaScript) page
for JavaScript.

## Notes
It is always considered a good practice to cite your sources.
Make sure you do that in your PR.

### PR DESCRIPTION
**Pull request by sushovanb02**
<hr>

## Description 📜
Created a documentation on history of JavaScript
Fixes #70 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [x] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by paramsiddharth** [comment]
@sushovanb02 Oh no, looks like you made changes to the main README file in the `Web_Development/Javascript` directory. This has led to undesired conflicts.

You were supposed to do it via the `Web_Development/Javascript/Topics/2.History/README.md`. Please make a fresh PR!
Let me know if you need my help with anything.

**Comment by sushovanb02** [comment]
@paramsiddharth sir can I generate another PR properly?

**Comment by paramsiddharth** [comment]
> @paramsiddharth sir can I generate another PR properly?

Yes! Use the same README and images, and create a new fresh PR.

**Comment by sushovanb02** [comment]
Sir I have generated a fresh PR, please check

**Pull request closed without merging**
