### PR TITLE
Datascience with python: Birch alogithm

### LINKED ISSUE #341: Frontend: Collecting HTML form response in Google Sheets
I'd like to explain here how we can collect HTML form responses in Google Sheets and managing them.
Please assign it to me @praveenscience

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜

Birch algorithm steps, advantages, disadvantages, neccessity ,applications
Fixes #341

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
@prathimacode-hub  kindly let me know if anything needs to be changed

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly add more information on "Birch Algorithm". There should be a README.md file and birch_algorithm.ipynb file

Work on it. @ron352

**Comment by ron352** [comment]
@prathimacode-hub mam, I have assigned with audio content. Do I need ipnyb file and I have already added a readme file like other audios in Machine learning section

**Comment by ron352** [comment]
@prathimacode-hub  mam changes done as u suggested . add a short code review and its snapshots in readme.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Keep .md file as README.md and all of your images in "Images" repo. @ron352

**Comment by ron352** [comment]
@prathimacode-hub mam changes done.

**Comment by prathimacode-hub** [comment]
It has 2 PR's in one both Depression and Birch Algorithm. Remove Depression files and keep only files related to birch. @ron352

**Comment by ron352** [comment]
@prathimacode-hub  would you check it now?

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good job and very well explained. 🏷👌 @ron352

**Pull request merged**
