### PR TITLE
Competitive Programming : : Sliding Window Maximum

### LINKED ISSUE #1217: Competitive Programming : : Sliding window maximum (documentation)
<hr>

## Description 📜

I would like to provide documentation about the Sliding window maximum problem.

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

### PR DESCRIPTION
**Pull request by areenoverclouds**
<hr>

## Description 📜

I have added the documentation of the Sliding Window Maximum Problem.
Topic: Maximum of all subarrays of given size K.
Language: C++
Format: Documentation
Fixes #1217 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ravireddy07** [comment]
Hey @areenoverclouds,
You're created this PR from main branch, You should point it to `Competitive_Programming` branch from `Competitive_Programming` or `Competitive_Programming:new_branch` of your fork. 

So, Make appropriate changes to this PR or make a new PR.

**Review by ravireddy07 — COMMENTED** [review]
Hey @areenoverclouds,
You're created this PR from main branch, You should point it to `Competitive_Programming` branch from `Competitive_Programming` or `Competitive_Programming:new_branch` of your fork. 

So, Make appropriate changes to this PR or make a new PR.

**Comment by areenoverclouds** [comment]
Sir, I have made the necessary changes and opened a new pull request #3063
Thank you.

**Comment by ravireddy07** [comment]
@areenoverclouds  you can this PR

**Pull request closed without merging**
