### PR TITLE
ML_Customer_Segmentation_(ML-Projects) 

### LINKED ISSUE #7858: ML : Customer Segmentation (ML-Projects)
### 📌 Issues for Week 9 - Basic Projects of Machine Learning

🔴 **Project Title** : **Customer Segmentation**
🔴 **Aim of the Project** : Analysing different types of customers around the globe and build a classification model accordingly.
🔴 **Dataset** : https://www.kaggle.com/vetrirah/customer
🔴 **Domain** : Machine Learning
🔴 **Special Credit** : **Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked through the accuracy scores to determine the best fitted model**

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain. 

**************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

**Take the Reference from these two projects attached here,** 
1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Changes should be made inside the `Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning` Branch.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- Batch Number : 
- GitHub Profile Link : 
- Approach for this Project :
- Are you a participant of GWoC21?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Basic Projects of Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by NikitaEmberi**
<hr>

## Description 📜
 Analysing different types of customers around the globe and build a classification model accordingly with the help of given dataset
Fixes #7858

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [X] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Isha307 — CHANGES_REQUESTED** [review]
I'm quite happy with the work you have done, loving it but the accuracy is not good so I would suggest you to do some data preprocessing and try to increase the accuracy.

**Comment by NikitaEmberi** [comment]
@Isha307 Thank you ma'am. I went through the solutions provided on Kaggle. Even the winning solution had an accuracy around 58% : https://www.kaggle.com/vetrirah/top-5-winning-solution-customer-segmentation. Even I tried my best to increase the accuracy. After doing some research I found that this dataset suffers from high variance, maybe getting more examples into the dataset would solve the purpose as you can see it performs well on training dataset in the case of RandomForest but is not able to perform well on testing dataset. I am actually beginner in ML, I have done the data preprocessing (label encoding and handling null values) to the best I could achieve. Please ma'am if you could point out some suggestions or some methods that I could try, it would really help me. I am willing to increase the accuracy.
https://www.kaggle.com/vetrirah/customer/code.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@NikitaEmberi Add the versions of the libraries used here, just like this, https://github.com/prathimacode-hub/ML-ProjectKart/blob/main/Airbnb%20Price%20Prediction/requirements.txt

I have gone through your project. Your presentation is top class and you have compared five algorithms with this dataset. Yeah sometimes, this happens like, you are not getting that good score in accuracy, but this does not mean you have not implemented the algorithm correctly. As your journey goes on in ML, you'll need to know how tuning is done, how Cross validation is used to make the models more accurate than the basic implementations, this is just the beginning. From your point of view, you have done a great job. Keep going like this 🚀

**Comment by NikitaEmberi** [comment]
@abhisheks008 thank you sir. I have added versions of libs in requirements file. Please verify.

**Comment by abhisheks008** [comment]
Approved from my side @NikitaEmberi

**Review by abhisheks008 — APPROVED** [review]

**Review by Isha307 — APPROVED** [review]

**Comment by Isha307** [comment]
Approved from my side also @NikitaEmberi

**Pull request merged**
