### PR TITLE
JSON

### LINKED ISSUE #1882: JS: JSON  Tutorial
### I will discuss what is JSON and how to use it?
```
Topics/8.JSON
```

### Domain

JavaScript

### Type of Contribution

- [x] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by yellowberard**
<hr>

## Description 📜

I have added basic knowledge about JSON. it's format , advantages and compared it with XML.  
Fixes #1882  

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by yellowberard** [comment]
@2024-SANDHYA please review this PR

**Comment by yellowberard** [comment]
can I make a New PR for this issue.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> can I make a New PR for this issue.

No need of creating New PR push commits here itself.

**Comment by yellowberard** [comment]
Actually I have to refork this repository because of some issue with github so I can't update is PR

**Pull request closed without merging**
