### PR TITLE
OpenSource : 5.39 Explain everything related to gRPC

### LINKED ISSUE #675: OpenSource : 5.39 Explain everything related to `gRPC`
### Description :

- **Explain everything related to `gRPC`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by riyapandey730**
<hr>

## Description 📜

Briefly explained  the gRPC...
Fixes #675

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by Suvraneel** [comment]
@riyapandey730 completely broken template... whichdomain do want to contribute to?
Just follow the directives... make another PR

**Comment by riyapandey730** [comment]
what the mistake i made

**Comment by Suvraneel** [comment]
@riyapandey730 

Delete all other domains from your comment.. like mentioned in official GWOC PR template directives
Kindly follow the issue template from next time ... & preach this to your fellow contributors

**Comment by Suvraneel** [comment]
@riyapandey730  I handled them for now...
Teach this to your peers too, okay... next time only yor domain

**Pull request closed without merging**
