### PR TITLE
Parameters and Arguments in Functions

### LINKED ISSUE #3774: Parameters and Arguments in Functions
### Description

Describe what is Parameters and Arguments in Functions using python ?

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Dhruvpandey08**
<hr>

## Description 📜

I Have made a Parameters and Arguments in function Documentation in python for better understanding and concept clarity. Because i feel more we contribute more we will get in return. Happy Contributing :)
Fixes #3774 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@Dhruvpandey08 
- I think it would be better if you add code snippets in your documentation along with typing the output instead of adding screenshots as those aren't readable for someone studying it for the first time. 
- Also please commit into the ```Python``` branch and not main

**Comment by Dhruvpandey08** [comment]
OK Sure i will work on it

**Comment by Dhruvpandey08** [comment]
I have made my changes and did another pull request #3953 , Kindly Review it Please

**Review by apeksha235 — APPROVED** [review]
@Dhruvpandey08 good work! 
@adityabisoi can be merged!

**Comment by adityabisoi** [comment]
Contribution should be done on Python branch

**Comment by Dhruvpandey08** [comment]
Anyway so i can again do that in python branch. What should i do?

**Comment by adityabisoi** [comment]
Yes

**Comment by Dhruvpandey08** [comment]
How should i do that please can you tell me?

**Comment by adityabisoi** [comment]
Close this PR and create a new PR to Python branch.

**Comment by Dhruvpandey08** [comment]
Ok got it

**Pull request closed without merging**
