### PR TITLE
Selection sort

### LINKED ISSUE #3179: Selection Sort using c++ with video and code
### Description
I have made a full video in English to explain selection sort algorithm and then write code by explaining it .

### Domain

Competitive Programming

### Type of Contribution

Video, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by samahuja642**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #3179

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive Programming
- [ ] Cyber#Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by samahuja642** [comment]
@nimisha-yadav @praveenscience @sumitaccess007 @salil-naik  please look my pr and also remove cyber security tag

**Comment by samahuja642** [comment]
@nimisha-yadav have i done everything correct actually that's my first pr , will it get merged? if yes then how long will it take?

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav have i done everything correct actually that's my first pr , will it get merged? if yes then how long will it take?

Hey @samahuja642, I'm supervising only DSA so, since you're contributing to CP, please tag CP supervisors/mentors, they'll let you know about the changes if needed.

**Comment by samahuja642** [comment]
how can i find cp supervisors ? as in discord noone is giving it a look

**Comment by samahuja642** [comment]
@salil-naik please review my pr

**Review by ravireddy07 — CHANGES_REQUESTED** [review]
Hey @samahuja642,

please update following changes:
1. The code mentioned in the doc isn't formatted, Add the code by `snippet`.
2. Please add complexity details also.
3. make folder in `Searching & Soring` by name `Selection_Sort`.
4. Inside that make another folder named `Video`
5. Inside video folder place this `markdown`

so the path should be `C++/Searching & Sorting/Selection_Sort/Video/selection_sort.md`.
Hope you got this.

**Comment by samahuja642** [comment]
Okay Thanks will be doing it by tonight @ravireddy07

**Comment by samahuja642** [comment]
@ravireddy07 is it fine now?

**Comment by ravireddy07** [comment]
use the exact location. `Selection_Sort/Video/selection_sort.md`.
* don't keep any spaces in-between.

don't make two files, like before just place the code and video link in `selection_sort.md` file. @samahuja642

**Comment by samahuja642** [comment]
@ravireddy07 is it fine now?

**Comment by ravireddy07** [comment]
Seems like the code isn't formatted correctly. Correct it once, we're good to merge @samahuja642 

image

**Comment by samahuja642** [comment]
image

**Comment by samahuja642** [comment]
it's happening because of start ``` cpp should i remove?

**Comment by ravireddy07** [comment]
you can, just add a title over there and add code snippet from next line.

**Comment by samahuja642** [comment]
Okay done with the formatting

**Comment by ravireddy07** [comment]
Still some syntax error.. Preview it once before making a push.

Please update like this: [Here]([url](https://drive.google.com/file/d/1p_l9RYLl-o74k9pQR3qZg4SOMkjtnXvg/view?usp=sharing))

**Comment by samahuja642** [comment]
@ravireddy07 Thanks for your guidance this is my first contribution so I am little unaware of the format , now check it

**Pull request merged**
