### PR TITLE
Android-Java: 1.2 Installing Intellij  issue#35 

### PR DESCRIPTION
**Pull request by anjanaaaaaaaa**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by anjanaaaaaaaa** [comment]
@VikasPandey121

**Comment by Rohit-2602** [comment]
>1.  Get IntelliJ IDEA from the Jetbrains website or from the link below:
> [link](https://www.jetbrains.com/idea/download/)
> Image
> 2. After you've downloaded the file, go to the Download location and run the installation. There's a chance you'll get a security > warning. Select 'Run' from the drop-down menu.

@anjanaaaaaaaa add image link, other than that great work 👍

**Comment by anjanaaaaaaaa** [comment]
@Rohit-2602 changes done....please review

**Review by Rohit-2602 — APPROVED** [review]

**Comment by VikasPandey121** [comment]
Awesome work done @anjanaaaaaaaa just a small change requested, Please do these changes 

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Align centre all the images and refract `Android_Development` directory with `Android_Development_Wit_Java` and add your file in `Android_Development_With_Java/Introduction`
- `squash` your commit.

**Comment by VikasPandey121** [comment]
@anjanaaaaaaaa one last change is requested,
Please align centre all the images. and mention the issue number in the comment section.

**Comment by VikasPandey121** [comment]
LGTM, Thanks for the contribution.

**Pull request merged**
