### PR TITLE
[DSA] feat: Implementation of Square Root Decomposition

### PR DESCRIPTION
**Pull request by motasimmakki**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # 473

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise, Low distortion)
- [ ] Video (Animations, screen-recordings, presentations, and regular explanatory films are all possibilities, etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [x] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [x] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

Screenshot (638)

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Please review @harshsri28

**Comment by motasimmakki** [comment]
> Please review @harshsri28

Kindly review it asap.

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Add some explanation

**Comment by motasimmakki** [comment]
> Add some explanation

In the file itself?

**Comment by nimisha-yadav** [comment]
> > Please review @harshsri28
> 
> Kindly review it asap.

@motasimmakki, you need to have patience. Further, I'd suggest you to send a fresh PR, this one has too many commits. 
You don't need to add any extra file, just add one file containing the documentation. Also, use only ``.md`` extension and not cpp. For the explanation, you may take reference from the merged files, present in the DSA branch folder already.

**Comment by harshsri28** [comment]
> > Add some explanation
> 
> In the file itself?

Yes

**Comment by motasimmakki** [comment]
Created a fresh PR with the less commit and .md file

**Comment by motasimmakki** [comment]
> Created a fresh PR with the less commit and .md file

Kindly have a look, PR #2785

**Pull request closed without merging**
