### PR TITLE
Topic: web-browser

### LINKED ISSUE #71: JS: Introduce JavaScript's usage in the Web Browser
# Introduce JavaScript's usage in the Web Browser
Discuss the prevalence of JavaScript as the most dominating
(only) front-end web scripting language and how it can be used
in conjunction with web pages.

## Directory
```
Topics/3.Web_Browser
```

## Description
- Talk about the use of the `<script>` tag.
- Discuss how we can connect an external script using the `src` attribute.
- What extension do we use for the scripts?
- Why do we even need JavaScript? Are HTML and CSS not enough? Explain.
- Why should JavaScript be chosen as the sole language for front-end web scripting?

## Hints
- Check out the [W3C tutorial](https://www.w3schools.com/js/).

### PR DESCRIPTION
**Pull request by daminimehra**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #71

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [x] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by daminimehra** [comment]
If any need of changes pls tell :)

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Comment by daminimehra** [comment]
@paramsiddharth

**Review by paramsiddharth — APPROVED** [review]

**Comment by paramsiddharth** [comment]
image

**Pull request closed without merging**
