### PR TITLE
Data Science with Python : Lung Segmentation using Computer Vision

### LINKED ISSUE #7665: Data Science with Python : Lung Segmentation using Computer Vision
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in learning the prediction of Lung Cancer, based on segmentation of images, using Computer Vision.

Dataset : https://wiki.cancerimagingarchive.net/display/Public/Lung+CT+Segmentation+Challenge+2017

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Aishani Singh | Ankit Kumar

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your  journey ahead. 😎

### PR DESCRIPTION
**Pull request by vishnupriya129**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7665

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Looks like your code blocks in .ipynb file are not compiled. Check on to it 
README.md can be elaborated in detailed way
Add your dataset used in "DS Datasets/Project Folder"
Add data analysis and visualizations in "Images" folder in your project folder.

Kindly do these changes. @vishnupriya129

**Comment by vishnupriya129** [comment]
@prathimacode-hub Mam can you please review my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README.md is not in viewable format and also images in it can't be seen. Add links of images that are present in this PR. 
In .ipynb file, if code blocks are compiled, add visualizations to it so that its outcomes are known and results attained are shown. @vishnupriya129

**Comment by vishnupriya129** [comment]
@prathimacode-hub Mam I have tried many times but images are not visible after uploading into github. What should I do can you please guide me

**Comment by prathimacode-hub** [comment]
<br>

Use this syntax. And add all the image you are using in README.md in "Images" folder in your project repo. @vishnupriya129

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Mam can you please text the syntax. It is not there in the above message.

Ok i shall text you. @vishnupriya129

**Comment by vishnupriya129** [comment]
@prathimacode-hub Mam can you please review the PR.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Highly appreciated for your efforts and precise PR. Well done. 👏👍@vishnupriya129

**Comment by vishnupriya129** [comment]
@prathimacode-hub Thank you mam!!

**Pull request merged**
