### PR TITLE
Quick Notes or Cheet Sheat of Python #2667

### PR DESCRIPTION
**Pull request by Kanishk0412**
<hr>

## Description 📜

I have Added Python Quick notes or Cheat Sheet in Documentation Form #2667
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Interview Prep

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Kanishk0412** [comment]
@syedareehaquasar Please review and Merge it.

**Comment by syedareehaquasar** [comment]
Please try not to provide hyper links wherever it's not required in the first para... It's misleading

**Comment by syedareehaquasar** [comment]
In order to speed up the process, I am making some changes as well! revert any if u feel else wise

**Comment by syedareehaquasar** [comment]
Please provide references also it's too long using hyper links to directly jump to content sounds best for that u have to make headings hyper links too... ping me if u are stuck!

**Comment by Kanishk0412** [comment]
How to add that hyper link please tell in detail.

**Pull request merged**
