### PR TITLE
[JS] Topic: AJAX in Javascript

### LINKED ISSUE #2358: [JS]: AJAX in JavaScript
### Description

# Description
---
Creating a tutorial on AJAX in Javascript and discussing the following:

- What is AJAX?
- How does AJAX Work?
- AJAX - The XMLHttpRequest Object
- Fetch API

# Directory
---
``` Javascript/Topics/13.AJAX ```

### Domain

JavaScript

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by aniketpathak028**
# Description 📜

Created a tutorial on AJAX in Javascript and elaborated upon the following:

- What is AJAX?
- How does AJAX Work?
- AJAX - The XMLHttpRequest Object
- Fetch API

Fixes #2358

# Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

# Domain of Contribution 📊

- [x] JavaScript

# Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

## Screenshots / Gif (Optional) 📸

### CODE REVIEW

**Comment by aniketpathak028** [comment]
@paramsiddharth @creatoon @dakshsethi kindly review this PR

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 Please review.

**Review by paramsiddharth — CHANGES_REQUESTED** [review]
Please add information on how to make POST requests, and how to send a body with the request. Also, please mention how to handle CORS.

**Review by sushovanb02 — APPROVED** [review]

**Review by s4-2 — APPROVED** [review]
Looks good to me:)

**Review by dakshsethi — CHANGES_REQUESTED** [review]

**Comment by aniketpathak028** [comment]
@dakshsethi I have made it bold please re-review

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Review by paramsiddharth — APPROVED** [review]

**Pull request merged**
