### PR TITLE
Data Science with Python : Tokenization & Lemmatization #1856

### LINKED ISSUE #1856: Data Science with Python : Tokenization & Lemmatization
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Tokenization & Lemmatization from scratch. Tutorial to Tokenization & Lemmatization and how it's applied using code snippets

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : Nithin / Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜

Made a presentation video about the topic Tokenization and Lemmatization. 
Fixes #1856 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilities etc)

<hr>

## Domain of Contribution 📊

- [ ] Datascience with Python
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam can you please review my PR.

Batch number: 5
serial number:174
Name: M. Ashish Reddy

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README.md can be more elaborated instead of getting into the topic directly, you can start with how this topic is derived, what's the purpose, why it's used, advantages of it, visual representations if any, applications it will be helpful in, overall summary and conclusion @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam I have updated can you please merge it , if everything is fine.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam I am ready with the other PR mam, will it be possible to merge this soon as I am ready with the other  PR also.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. You're going blazing high. Great content. ✔🙌@ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
Thank you mam

**Pull request merged**
