### PR TITLE
Added Documentation and code for Implementation of stack using two queues

### LINKED ISSUE #8486: [Create New Issue]: Implement stack using two queues
### Description

I will be creating the documentation for the implementation of stacks using 2 queues

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #8486  

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] DSA

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav Can you please review my PR?

**Comment by VaibhavMalik4187** [comment]
And let me know if changes are required

**Review by nimisha-yadav — APPROVED** [review]
Great work. No modifications required.

**Comment by VaibhavMalik4187** [comment]
> Great work. No modifications required.

Thanks a lot :)

**Pull request merged**
