### PR TITLE
Java  2.4 :  Strong Type Languages 

### LINKED ISSUE #1250: Java 2.4: Strong Type Languages
<hr>

## Description :scroll:

Add audio, documentation and video regarding **Strong Type Languages.**

<hr>

## Domain of Contribution :bar_chart:

- [x] Java

<hr>

## Location of File to be added

  The files should be added inside the `Strong Type Languages` which will be inside `Fundamentals` folder which will be inside of `Java` folder. If the folder is not present, create the folder with this exact name. The documentation file can be in the
`.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by lakshya7878**
<hr>

## Description 📜

Created an md file for Strong Type language. 
Fixes #1250 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (214)

<hr>

### CODE REVIEW

**Comment by AkMo3** [comment]
@nandini7637 Please do the initial review.

**Review by nandini7637 — COMMENTED** [review]
I think it's fine, no changes from my side.

**Review by AkMo3 — CHANGES_REQUESTED** [review]
@lakshya7878 Can you add some details on `static strong` vs `dynamic strong` as well?

**Comment by lakshya7878** [comment]
> @lakshya7878 Can you add some details on `static strong` vs `dynamic strong` as well?

yes working on it

**Comment by lakshya7878** [comment]
> @lakshya7878 Can you add some details on `static strong` vs `dynamic strong` as well?

done with the changes , you can review

**Comment by lakshya7878** [comment]
@AkMo3  do check the changes out

**Review by garvitraj — APPROVED** [review]

**Pull request merged**
