### PR TITLE
DSA: Spiral Print of 2D Array 

### PR DESCRIPTION
**Pull request by arsheelsheikh**
DSA: Spiral Print of 2D Array #1547

### CODE REVIEW

**Comment by Kashish05** [comment]
Can you please assign me this issue. I want to do it in C++.

**Comment by arsheelsheikh** [comment]
@Kashish05 the issue has already been done to get issue assigned go to issue section

**Comment by arsheelsheikh** [comment]
@themonikanayak I have made PR do review it and kindly merge my PR 
Thank You

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Your Approach is not optimal approach, you can optimize to SC : O(1)

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Content is fully plagiarised from GFG.

**Comment by arsheelsheikh** [comment]
@sneha-nitdgp Is copying not allowed?
I was not knowing as was not mentioned anywhere if

**Comment by sneha-nitdgp** [comment]
@arsheelsheikh You can use resources online only for references. Content submitted must be of your own, so as to qualify for being merged.

**Comment by arsheelsheikh** [comment]
ok thanks for letting me know @Sneha-0308 will try to make a new PR one and will tag you

**Pull request closed without merging**
