### PR TITLE
Fix : Added Documentation for Integers in  Java (#1251)

### LINKED ISSUE #1251: Java 3.1: Integers
<hr>

## Description :scroll:

Add audio, documentation and video regarding **Integers**

<hr>

## Domain of Contribution :bar_chart:

- [x] Java

<hr>

## Location of File to be added

  The files should be added inside the `Integers` which will be inside `Primitive Data Types` folder which will be inside of `Java` folder. If the folder is not present, create the folder with this exact name. The documentation file can be in the
`.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by kashyap1905**
<hr>

## Description 📜

Documentation for Integers in Java.
Fixes #1251  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by sumitaccess007 — CHANGES_REQUESTED** [review]
@kashyap1905, Documentation is fine.
Please help with below points -
1. move Documentation.md under "Integers".
Delete sub-directory under "Integers" with name "Integers in JAVA"
2. Change the name of "Documentation.md" to something like - "Documentation_On_Integers_In_JAVA.md"
Thanks

**Comment by kashyap1905** [comment]
@sumitaccess007 @AkMo3 @garvitraj 
Made changes as instructed. Please review it.

**Review by sumitaccess007 — COMMENTED** [review]
@garvitraj,
Level-1 Review is okay for #1251 
Please have a look and merge.

**Comment by garvitraj** [comment]
@kashyap1905 looks great now.

**Review by garvitraj — APPROVED** [review]

**Comment by kashyap1905** [comment]
> @kashyap1905 looks great now.

@garvitraj Thank You Sir !! It's really motivating !!

**Pull request merged**
