### PR TITLE
Python 1.6 : How to install Python (Documentation) #78

### PR DESCRIPTION
**Pull request by tejas342**
<hr>

## Description 📜

I had completed the documentation part for how to install python #78 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by tejas342** [comment]
@prathimacode-hub please review this.

**Comment by Suvraneel** [comment]
@tejas342 please delete all non-domains from your comment.. like the directives say
Kindly follow the issue template from next time

**Review by AkMo3 — COMMENTED** [review]
@tejas342 I had change the PR description and removed the fields and labels that were not required. Please remember to delete other domains so as that the bot works good.

**Comment by tejas342** [comment]
@AkMo3 @Suvraneel 
from next time i will remember that
and thanks for improving this time

**Comment by Suvraneel** [comment]
@tejas342  I'm from CPP domain... Kindly tag corresponding mentors

**Comment by tejas342** [comment]
@prathimacode-hub please review this and merge it

**Pull request closed without merging**
