### PR TITLE
Decision making in c/c++

### LINKED ISSUE #2467: [C/C++]: Decision making
### Description

I will add all details of if, else and else if statements in a very easy way that even a newbie can understand it easily!
I will use the documentation for this purpose.

### Domain

C/CPP

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by rishitajain01**
<hr>

## Description 📜

I have added conditional statements(if,if-else,nested if,jump statements).
Fixes #2467 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Hey @rishitajain01 

Please use your own words. Don't directly copy the sentences from other resources.
- Avoid plagiarism , It is againts our COC.
- kindly change the content , use your own words

Hope it will make sense to you ! 😇

**Comment by vasu-1** [comment]
Hey someone had already made one Issue on this topic before you #934  !!!!!!!!!!
You can create audio or video on this topic !!!!!!
kindly close this Pr and Respective Issue !!!!!

**Comment by vasu-1** [comment]
One more thing this issue is not yours !!!  #2467 
this was created by megna so only she can work on that issue !!!

**Comment by vasu-1** [comment]
@rishitajain01

**Comment by rishitajain01** [comment]
> One more thing this issue is not yours !!! #2467
> this was created by megna so only she can work on that issue !!!

But Sir, I was assigned #2647  for the documentation

**Comment by vasu-1** [comment]
> > One more thing this issue is not yours !!! #2467
> > this was created by megna so only she can work on that issue !!!
> 
> But Sir, I was assigned #2647 for the documentation

Not 2647 .
It is 2467

**Comment by vasu-1** [comment]
It is assigned to you.
But issue is not yours. 
It is possible that issue creater is already working it. But he or she forgot to assign to themselves.

Kindly close this PR ..
We can't merge it.
Because someone has already worked on it and also issue is not yours.
Sorry for this inconvenience. There are lots of topics , You can work on some other topic.
Thank you !!!
Kindly close this PR.

**Comment by vasu-1** [comment]
Please make new issue and assign it to yourself and then start your work..
Make sure that issue should not be duplicate..

**Comment by vasu-1** [comment]
Please refer # announcement  Channel in c/c++
If you don't see this channel.
Please mention me in your c/c++ channel

**Pull request closed without merging**
