### PR TITLE
Python:Loops-while loop #557

### LINKED ISSUE #557: Python: Loops- while loop
### Description :
What is `while` loop in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by subhoshreep**
This is a tutorial video on while loop, explaining what it is? how to use it? and what attributes it provides.
contributed by- 
Subhoshree pattnaik
python batch 1

<hr>

## Description 📜
This is a tutorial video on while loop, explaining what it is? how to use it? and what attributes it provides.
contributed by- 
Subhoshree pattnaik
python batch 1

 
Fixes #557

<hr>

## Type of change 📝

- [x] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Python_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
while

<hr>

### CODE REVIEW

**Comment by subhoshreep** [comment]
@adityabisoi  @ankurg132 can you please review my PR

subhoshree pattnaik
python batch 1

**Comment by ankurg132** [comment]
Can you use # with the number 557 so that the issue can be directly linked as #3425

**Comment by subhoshreep** [comment]
> Can you add the correct issue linked with this PR using # and the **issue** number.

The issue number is # 557

**Review by kumarankm — APPROVED** [review]
@subhoshreep  Everything looks fine, your video explanation is also good. Nice work 👍🏻 
You can merge this pr @adityabisoi

**Pull request merged**
