### PR TITLE
Create Cybersecurity: 3 Computer Viruses? #1671.md

### PR DESCRIPTION
**Pull request by Harsh-Chaudhary7**
<hr>

## Description 📜

Explanation of What are Computer Viruses? How it spreads, its types and ways to protect against computer virus.

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Cyber #Security

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Harsh-Chaudhary7** [comment]
Please review it @Anant1711 .

**Review by Anant1711 — COMMENTED** [review]
90% Plag!
Please correct it!

**Review by Anant1711 — CHANGES_REQUESTED** [review]
.

**Comment by Harsh-Chaudhary7** [comment]
Re-review it please @Anant1711

**Review by Anant1711 — APPROVED** [review]

**Pull request merged**
