### PR TITLE
Data Science with Python : Markov's Chain #377

### PR DESCRIPTION
**Pull request by surjyaneeh**
<hr>

## Description 📜

Fixes : #377

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by surjyaneeh** [comment]
Please review @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Your PR is currently under reviewing

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The issue contribution should be under "/Statistics/Tutorials/Markov's Chain
Elaborate your README file. It needs more detailing. You can find the things you can add up in Project structure document
The project file name should be in snake case : markovs_chain.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Markov's Chain"

Kindly work on it. @surjyaneeh

**Comment by prathimacode-hub** [comment]
Add up the respective datasets used in "DS Datasets" in "Statistics" folder and resources referred in "DS Resources" in "Statistics" folder @surjyaneeh

**Comment by prathimacode-hub** [comment]
Your PR is approved. Congrats on your first PR. This was a great choice of an issue and amazing start. Long way to go. 👌👍@surjyaneeh

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats on your first PR. This was a great choice of an issue and amazing start. Long way to go. 👌👍@surjyaneeh

**Pull request merged**
