### PR TITLE
21.14 Android Permission [ issue - #5876 ]

### LINKED ISSUE #5876: Android Kotlin: 21.14 Explain about Android Permission and how to use it.
<hr>

## Description :scroll:

* At first explain what is android permission and the type of permissions.
* Give a step-by-step tutorial of using runtime permission in android(Kotlin).
*  Required Documentation or Video or Audio.

<hr>

## Domain of Contribution :bar_chart:

- [x] Android Dev (Kotlin)

<hr>

<hr>

## References :
https://guides.codepath.com/android/Understanding-App-Permissions

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in Android_Development_With_Kotlin/ directory under Android_Development_With_Kotlin branch.
* Inside Android_Development_With_Kotlin/ directory creates a directory and names it according to the topic ( for this issue 14. Storage)
* Inside 14. Storage/ directory add your task with subtopic number and name and make changes accordingly.
* You have to push your PR to the Android_Development_With_Kotlin branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.
* Will assign you on a first come first serve basis.
* Please try to complete your assigned task within 7 days. If you need some more time then, please inform mentors and supervisors.
* If you have two previously assigned issues on Android-Kotlin pending then please first complete them.
> Supervisor @rahulsain

### PR DESCRIPTION
**Pull request by ayush-sleeping**
<hr>

## Description 📜

Fixed  #5876 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by ayush-sleeping** [comment]
Hey @rahulsain , Please review my PR and if any mistake is not there kindly merge it .

**Comment by ayush-sleeping** [comment]
Hey @rahulsain , Please review my PR and if any mistake is not there kindly merge it .

**Comment by rahulsain** [comment]
I have updated where this file should be placed, check PR heading.
Delete the file from here and move this file to 21. Android JetPack folder with this file name as 21.14 Android Permissions.md

**Comment by ayush-sleeping** [comment]
Hey @rahulsain , Tasks completed . Please review it and if all things are correct kindly merge it .

**Comment by sitamadex11** [comment]
hey @rahulsain, Can we make the file structure like this,  `21. Android JetPack`  ->  `3. Behaviour Components` -> `4 Android Permission.md` ?

**Review by sitamadex11 — APPROVED** [review]
Cool work bro @ayush-sleeping

**Pull request merged**
