### PR TITLE
5.44 Explain everything related to OpenTelemetry

### LINKED ISSUE #682: OpenSource : 5.44 Explain everything related to `OpenTelemetry`
### Description :

- **Explain everything related to `OpenTelemetry`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by Adi7171**
<hr>

## Description 📜
Given a brief Information regarding opentelemetry and explained why it is important
Fixes  #682

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] OpenSource

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Adi7171** [comment]
@Aryamanz29 Sorry for the delay It took me a long time for the other topic issue to get merged.

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Change filename to `5.44_Explain_everything_related_to_OpenTelemetry.md`

**Comment by Adi7171** [comment]
@Aryamanz29  done

**Review by Aryamanz29 — APPROVED** [review]
LGTM
Thanks for contributing 🎉🎉

**Pull request merged**
