### PR TITLE
[JS] Topic : Error-Handling

### LINKED ISSUE #3281: JS:  Error-Handling
### Description

Discussion about error-handling
- What is a try-catch block?
- How to use it to deal with exceptions in code?
- Example

Directory:

### Domain

JavaScript

### Type of Contribution

- [x] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by rwiteshbera**
<hr>
GWoC

## Description 📜

Discussion about error-handling
- What is error-handling?
- Different types of error (Syntax error, runtime error, logical error)
- What is a try-catch block?
- How to use it to deal with exceptions in code?
- Example

Fixes #3281

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Java#Script
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by paramsiddharth** [comment]
@Divyanshigarg Would you like to contribute? Please go to the issue instead: #3281.

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 Please review.

**Review by s4-2 — COMMENTED** [review]
Good work @rwiteshbera , it will be good if you add more examples of **try-catch** and ** try-catch-finally**. Keep up the good work:)

**Comment by rwiteshbera** [comment]
@paramsiddharth @s4-2 Please check my PR once.

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Review by s4-2 — APPROVED** [review]
Awesome 🎉 @rwiteshbera
Looks good to me:)

**Review by paramsiddharth — APPROVED** [review]

**Pull request merged**
