### PR TITLE
ML 2.6: Logistic Regression (V) #2797

### PR DESCRIPTION
**Pull request by Apoorv-17**
<hr>

## Description 📜

This issue will help readers in acquiring all the knowledge that one needs to know about Logistic Regression. The type of contribution made is in the form of Video(V).
Fixes # <2797> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Apoorv-17** [comment]
@Isha307 i have completed the logistic regression video type contribution. Could you please review my PR.

**Review by Isha307 — CHANGES_REQUESTED** [review]
@Apoorv-17 you had written that your batch no. is 7 but there are only 6 ml batch.

**Comment by Apoorv-17** [comment]
I accidentally copied my DSA batch number. Now I have changed my batch number to 5.
@Isha307 now could review my PR again.

**Review by Isha307 — APPROVED** [review]

**Comment by Apoorv-17** [comment]
@Isha307 could you please add hacktoberfest accepted label so that this PR can be marked as a valid contribution for hacktoberfest 2021.

**Comment by Isha307** [comment]
@Apoorv-17 We are adding hacktoberfest accepted label to the Week 3 issues and onwards.

**Pull request merged**
