### PR TITLE
What are Switches?

### LINKED ISSUE #786: Cybersecurity: 2.9 Switches
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by LegendSumeet**
done with doc and video

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #786

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Cyber #Security

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by Nupurksk** [comment]
@LegendSumeet The Documentation part is good..But you have to change the video it's having plag of 93%.

**Comment by LegendSumeet** [comment]
Ohkkk let me work on it?

**Comment by Nupurksk** [comment]
> Ohkkk let me work on it?

Yaa, take time till Thursday.

**Review by LegendSumeet — COMMENTED** [review]
now merge it

**Comment by LegendSumeet** [comment]
@Nupurksk review it

**Review by Anant1711 — COMMENTED** [review]
98% Plagiarism

**Comment by LegendSumeet** [comment]
@Anant1711 the Documentation is not ```98% Plagiarism``` and the documentation was reviewed by @Nupurksk

**Comment by Nupurksk** [comment]
Check it yourself

Link to the plag checker
https://smallseotools.com/plagiarism-checker/

**Pull request closed without merging**
