### PR TITLE
[DSA] feat: Circular Queue Concept and Implementation

### LINKED ISSUE #7157: DSA 4.2.5.3 Circular Queue - Documentation
## Description
What is Circular Queue? Discuss in detail its implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by motasimmakki**
<hr>

## Description 📜

Included the concept and implementation of Circular Queue in C++ along with the running I/O and the TC trade off.
Fixes #7157

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by motasimmakki** [comment]
@nimisha-yadav 
Kindly have a look!

**Comment by nimisha-yadav** [comment]
@harshsri28 @sneha-nitdgp

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by nimisha-yadav — APPROVED** [review]

**Pull request merged**
