### PR TITLE
Python_Stack&_Queue

### PR DESCRIPTION
**Pull request by Akhilkumar272002**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
<hr>

## Domain of Contribution 📊

- [ ] Python
<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by gauravdas014** [comment]
Change the branch. Don't give PR to main

**Comment by Suvraneel** [comment]
@Akhilkumar272002  Mention domain of contribution properly

**Comment by Akhilkumar272002** [comment]
Python: Stack & Queue #2876 Solved @gauravdas014 @Suvraneel

**Pull request closed without merging**
