### PR TITLE
Python Math Module

### LINKED ISSUE #7401: Python Math Module
### Description

Brief description about Python math module through documentation.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by yashh18**
<hr>

## Description 📜

Brief description about Python math module through audio contribution
Fixes #7401 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by yashh18** [comment]
@adityabisoi please review my PR

**Comment by adityabisoi** [comment]
Plz tag a mentor for review.

**Comment by hritikksingh** [comment]
image
This part of the readme is too cluttered. Can you format it in a better way by adding proper linespace and intendation? And a few more basic formatting to your liking.

**Comment by yashh18** [comment]
image
@hritikksingh actually i already updated the readme with proper intendentation, I am wondering why it is still showing like this?
Can u recheck once?

**Comment by hritikksingh** [comment]
@yashh18 got it.
@adityabisoi all good and can be merged.

**Pull request merged**
