### PR TITLE
Basic Datatypes of Python- int, str & float 

### LINKED ISSUE #245: Python: 1.10 Basic Datatypes of Python
I want to make a documentation contribution on this issue. Please assign me this @adityabisoi sir.

### PR DESCRIPTION
**Pull request by gracyashhh**
<hr>

## Description 📜

An Audio link explaining the Basic Datatypes of Python - int, str & Float
Fixes #245 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by gracyashhh** [comment]
@prathimacode-hub Please check if this PR can be merged :)

**Comment by gracyashhh** [comment]
Fixed

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Hey, it has no details in README.md file except the audio link. Elaborate about the issue topic you had chosen theoretically in text as well. @gracyashhh

**Comment by gracyashhh** [comment]
@prathimacode-hub I thougt the person working on documentation would be adding the text part, I can add the description alone though

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub I thougt the person working on documentation would be adding the text part, I can add the description alone though

No, this is your individual contribution not a group contribution so you should do your part. @gracyashhh

**Comment by gracyashhh** [comment]
Sure @prathimacode-hub could you please assign me to this again I guess it has been unassigned by mistake

**Comment by gracyashhh** [comment]
Sure, will update and let you know @prathimacode-hub

**Comment by roopali-1** [comment]
@prathimacode-hub mam i want to work on this issue could you please assign this issue to me .. so that i can work on this issue ...!!

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
