### PR TITLE
DSA 1.2.4.1 NP-Complete Problem - Audio #1780

### LINKED ISSUE #1780: DSA 1.2.4.1 NP-Complete Problem - Audio
## Description
What do you understand by NP-Completeness? Discuss in detail, what are NP, P, NP-complete and NP-Hard problems?

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by Shruti-Subu**
<hr>

## Description 📜

What is np completeness ? What are NP, P, NP-complete and NP-Hard problems?
Fixes #1780

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — COMMENTED** [review]
Mention algorithm in document and discuss about time complexity and space complexity

**Comment by Shruti-Subu** [comment]
@harshsri28  
do i need to make any changes in the audio clip ? 
or just the document needs to be edited.

**Comment by harshsri28** [comment]
> @harshsri28 do i need to make any changes in the audio clip ? or just the document needs to be edited.

just update document

**Comment by Shruti-Subu** [comment]
ok

**Comment by Shruti-Subu** [comment]
@harshsri28  i have  made another pull request after working on your suggestion , Please review that .
Should i close this pr?

**Comment by harshsri28** [comment]
close this one

**Pull request closed without merging**
