### PR TITLE
C/CPP: Kadane's Algorithm

### LINKED ISSUE #832: Kadanes Algorithm
<hr>

## Description 📜

Its a code which gives the maximum sum of subarray

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by bindaldhara**
<hr>

## Description 📜

Fixes #832 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
The coding part looks good.
You can add 2-3 lines on what is Kadane's algorithm by commenting and provide a ss for the I/O as well.
And yes remove .exe file before making a PR.

**Comment by bindaldhara** [comment]
Where the ss should be added??

**Comment by Suvraneel** [comment]
@bindaldhara  always contribute to C_CPP or respective branches not main

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Submitted same code twice 
Delete output.png
Instead make a .md file & explain the problem & its approach properly

**Comment by Suvraneel** [comment]
Plagiarised from here:
https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/

Changing variable names doesn't bring novelty

**Pull request closed without merging**
