### PR TITLE
DNS and Working of DNS 

### LINKED ISSUE #1329: FrontEnd: DNS & Working of DNS?
<hr>

## DNS & Working of DNS? 📜

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by GenMech**
<hr>

## DNS and Working of DNS  📜

Created a well Documented file on DNS and Working of DNS.
Fixes #1329  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by GenMech** [comment]
@code-reaper08 @sifa123 Pls check this out and let me know if there is any changes or its good to do.

**Comment by Akshita-Sharma-25** [comment]
Hey this is Akshita from batch -4 of frontend 
I would like to work on this issue please assign this issue to me

**Review by sifa123 — COMMENTED** [review]
Everything looks fine but mention from where you collected these images.

**Comment by GenMech** [comment]
> Everything looks fine but mention from where you collected these images.

I have collected it from different sites where should i mention it?

**Comment by sifa123** [comment]
> > Everything looks fine but mention from where you collected these images.
> 
> I have collected it from different sites where should i mention it?
Below the image, I think

**Comment by code-reaper08** [comment]
> > > Everything looks fine but mention from where you collected these images.
> > 
> > 
> > I have collected it from different sites where should i mention it?
> > Below the image, I think

Exactly!

**Comment by GenMech** [comment]
@sifa123 @code-reaper08  I have added links of all images i used.

**Comment by GenMech** [comment]
Pls look at it and I think it should be perfect now!

**Comment by sifa123** [comment]
> Pls look at it and I think it should be perfect now!

Yesss it's perfect now

**Pull request merged**
