### PR TITLE
OpenSource : 2.2 Learn open source basics #27

### PR DESCRIPTION
**Pull request by nayakaj**
<hr>

## Description 📜

basics of open source #fixes #issue_number line

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [x] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
- Update your fork
- Change this doc completely, We don't want copy paste text here, Try to write docs by your own
-  Add images, graphs, flowcharts
-  Add this doc under `section-2`
-  Rename this to `2.2_Open_Source_Basics.md`
-  Change PR description,  add issue number in `fixes #issue_number line`
-  Mark ticks in PR checkboxes

**Comment by nayakaj** [comment]
hi Aryaman
i have changed the name of the file
stilli have to change any thing plz let me  know

**Comment by Aryamanz29** [comment]
@nayakaj 
- Update your fork
-  Add images, graphs, flowcharts
-  Add this doc under `section-2`

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
@nayakaj 
- Update your fork
-  Add images, graphs, flowcharts
-  Add this doc under `section-2`

**Comment by Aryamanz29** [comment]
Any updates on this ?? @nayakaj

**Comment by Aryamanz29** [comment]
Closing this due to inactivity

**Pull request closed without merging**
