### PR TITLE
[JS] Topic: Local Storage And Session Storage

### LINKED ISSUE #1980: [JS]: Local Storage and Session Storage
## Local Storage and Session Storage
A documentation describing Local Storage and Session Storage in JavaScript

## Directory
Topics/13.Web_Storage/Local_Storage_And_Session_Storage

## Description
- Description about Local Storage and Session Storage
- Reading, adding, creating and updating data using local storage object with example
- Reading, adding, creating and updating data using session storage object with example

### Domain

JavaScript

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by OptimalLearner**
<hr>

## Description 📜
Documentation for Local Storage and Session Storage in JavaScript added.
Topics Covered in the Documentation:
- Introduction to Local Storage and Session Storage
- About Local Storage, methods and properties provided by Local Storage with examples
- About Session Storage, methods and properties provided by Session Storage with examples
- Summary

Fixes #1980 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by chaudharydivya199** [comment]
@paramsiddharth  please assign this issue to me.

**Comment by paramsiddharth** [comment]
> @paramsiddharth please assign this issue to me.

@chaudharydivya199 The issue is #1980. :) Please comment on it.

**Review by paramsiddharth — APPROVED** [review]
@Creatoon @dakshsethi @s4-2 @amino19 Please review.

**Review by amino19 — CHANGES_REQUESTED** [review]
@OptimalLearner: Thanks for your contribution. Some minor changes need to configure, set the screenshots to align as `center` & reduce the size to `80%`. So, it will render beautifully.

Thanks! :slightly_smiling_face: 

@paramsiddharth: Any insights?

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Comment by OptimalLearner** [comment]
@amino19, Thank you for your suggestions. I have made the required changes. Can you review it again?

**Review by amino19 — APPROVED** [review]
@OptimalLearner: Amazing, LGTM! :partying_face:

**Pull request merged**
