### PR TITLE
Data Science With Python : Local Convolutional Features with Unsupervised Training for Image Retrieval

### LINKED ISSUE #4386: Data Science With Python : Local Convolutional Features with Unsupervised Training for Image Retrieval
### Description

Welcome to the 'DSWP' Team, good to see you here

With this issue, readers will get introduced to core information to Local Convolutional Features with Unsupervised Training for Image Retrieval along with sample code completely in an effective way.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Computer Vision 

Mentors Assigned: Dhruv Bajaj / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include the issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of the 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by kishlayaug15**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Audio discussing in detail about Image Retrieval using local CNN and its different layers.

Fixes #4386

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the project guidelines and structure given. This is not sufficient and not added in appropriate category as mentioned. This repo is not a part of Hacktoberfest. @kishlayaug15

**Comment by kishlayaug15** [comment]
> @prathimacode-hub Actually, I wanted to ask that I am contributing audio. So, for that also I have to provide code compilation in .ipynb files? or is it work for the one who was assigned for documentation?

@prathimacode-hub ,Please will you assist me I have doubt

**Comment by prathimacode-hub** [comment]
Your PR had files of 2 issues. Kindly correct it. For audio, code is not needed but needs brief elaboration in README.md file. @kishlayaug15

**Comment by kishlayaug15** [comment]
@prathimacode-hub For both of the Contributions, #4386 and #3521 Audio is assigned to me.

**Comment by kishlayaug15** [comment]
@prathimacode-hub  Please view my request all the necessary changes have been made. It was approved earlier by @Rohit484 . This was assigned to me for Audio only. Please merge it also I have to work on next issues too!

**Comment by prathimacode-hub** [comment]
Who is @Rohit484. He is not a mentor for DSWP. @kishlayaug15

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README can be elaborated. And Rohit is not your mentor for this issue neither for DSWP domain. Your mentors are Dhruv Bajaj and Aishani Singh. @kishlayaug15

**Comment by kishlayaug15** [comment]
Please review my readme.md file. I am contributing for audio. If their are
any improvements please let me know. Because I have to open PR for next
issue. After this I have to work for 2 more issues assigned by you in which
one is already done. I am waiting for this PR to merge.

Also there are other domains too where are have to contribute. They are not
accepting my request because my PR is not merged.

**Comment by kishlayaug15** [comment]
OK , I'll work on it. And also please review my audio too.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great work. Keep going. 👌🎉@kishlayaug15

**Comment by prathimacode-hub** [comment]
@Rohit484, are you a mentor for GWOC or DSWP?

**Review by DhruvBajaj01 — COMMENTED** [review]
Reviewed!

**Pull request merged**
