### PR TITLE
HTML video and audio tag

### LINKED ISSUE #5180: HTML Audio and video tag
### Description

how can we add audio and video in html. 
make  2 files HTML_Audio.md  and HTML_Video.md -> create HTML_Audio_And_Video(subfolder) -> frontend folder (subfolder) -> web development main folder. 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by yellowberard**
<hr>

## Description 📜

Documentation on HTML  audio and video tag
Fixes #5180 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by yellowberard** [comment]
@2024-SANDHYA Please review my PR.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Don't create 2 separate MD files. Merge both of them in one; under different headings. @yellowberard

**Comment by yellowberard** [comment]
But in the issue it is said to make two different files. @2024-SANDHYA

**Comment by 2024-SANDHYA** [comment]
> But in the issue it is said to make two different files. @2024-SANDHYA

Merge both in one @yellowberard

**Comment by yellowberard** [comment]
@2024-SANDHYA I have merged both the files.

**Comment by 2024-SANDHYA** [comment]
63% Plagiarized 

image

**Comment by yellowberard** [comment]
@2024-SANDHYA I have made the changes do I have to open a new PR for this?

**Review by 2024-SANDHYA — APPROVED** [review]

**Pull request merged**
