### PR TITLE
Data Science with python: Feature Selection Techniques

### LINKED ISSUE #347: Data Science with Python : Feature Selection Techniques
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about feature selection techniques. Tutorial to feature selection techniques and how it's applied using sample code. Be as elaborative as possible. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Peehu Saxena](https://github.com/PeehuSaxena) / [Arya Patel](https://www.github.com/AryaPatel1111)

Points to Note : 

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by deepthi1107**
<hr>

## Description 📜

Feature Selection Techniques #347:
- I have written various techniques and types of feature selection.
- I have written code on how we can use it while dealing with the dataset.
Fixes #347

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by deepthi1107** [comment]
Please evaluate @prathimacode-hub.
Name: Deepthi M
Issue:  Feature Selection Techniques #347
Type: Documentation 
Batch number:  5
Serial number: 172

**Comment by prathimacode-hub** [comment]
This PR is currently under reviewing process

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The issue contribution should be under "/Machine Learning/Tutorials/Feature Selection Techniques
Elaborate your README file. It needs more detailing. You can find the things you can add up in Project structure document like breif introduction, how it works, advantages, applications, features, how it's optimized, usage and proper conclusion providing overall summary and what you conclude
The project file name should be in snake case : feature_selection_techniques.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Feature Selection Techniques"
And In .ipynb file you had come straight to the point Go it in flow with basic intro and and explain your sample codes. It has no information of what you had done. You can add sub headings and how these techniques are used individually. 

Kindly work on it. @deepthi1107

**Comment by deepthi1107** [comment]
Ok, @prathimacode-hub I will do all required changes.

**Comment by deepthi1107** [comment]
Hello, @prathimacode-hub I have made a new file. Kindly evaluate.

**Comment by prathimacode-hub** [comment]
Changes haven't done yet. Kindly look for the changes that needs to be addressed. @deepthi1107

**Comment by deepthi1107** [comment]
Mam @prathimacode-hub i have made other pull request mam, please check the other PR

**Comment by prathimacode-hub** [comment]
The link you shared is not a PR link. Kindly provide the correct link to check up. @deepthi1107

**Comment by deepthi1107** [comment]
It automatically merges I have created .md file @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> It automatically merges I have created .md file @prathimacode-hub

But it isn't showing up here. @deepthi1107

**Comment by deepthi1107** [comment]
Mam I will create a new pull request @prathimacode-hub

**Comment by deepthi1107** [comment]
Can you check now @prathimacode-hub

**Comment by deepthi1107** [comment]
I have made a new pull request.
https://github.com/girlscript/winter-of-contributing/pull/2130, @prathimacode-hub

**Pull request closed without merging**
