### PR TITLE
feat: Graph Coloring Algorithm

### LINKED ISSUE #5927: DSA 3.2.22 Graph Coloring Problem
## Description
Discuss the Graph Coloring Problem in detail.
**Important: Do not use assign command for this issue.**
## Task
- [ ] Documentation

## Note
- After completion of your task, add your file in this [folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/22.%20Graph%20Coloring) as its readme.md
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by motasimmakki**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #5927 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by motasimmakki** [comment]
@nimisha-yadav 
Kindly review 🎈

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @japneetbhatia

**Comment by motasimmakki** [comment]
@japneetbhatia 
Kindly have a look!

**Comment by motasimmakki** [comment]
> @motasimmakki apologies for the confusion, name your file as readme itself for the graph colouring problem folder. @japneetbhatia we've started specifying folder and naming in the alloted issue itself to avoid confusion.

The way you say @nimisha-yadav, Kindly have a look!

**Pull request merged**
