### PR TITLE
Added 04.0 Overview of Android-Manifest file (issue - 516)

### LINKED ISSUE #516: Android-Kotlin : 04.0 Overview of Android-Manifest file
## Description :
* Give a brief overview of **AndroidManifest.xml** file.
*  Required documentation or video.

* Changes should be made in **Android_Development/Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
> Supervisor @rahulsain

### PR DESCRIPTION
**Pull request by ayush-sleeping**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #516  

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by ayush-sleeping** [comment]
@rahulsain  Please review this PR .

**Comment by rahulsain** [comment]
Please follow the folder structure

first folder of the topic then this readme file in it

**Comment by ayush-sleeping** [comment]
> Please follow the folder structure
> 
> first folder of the topic then this readme file in it

okkk , so what I have to do now

**Comment by rahulsain** [comment]
Make a folder and then put this readme file in that, folder name should be
topic name

**Pull request closed without merging**
