### PR TITLE
Python: Flask

### LINKED ISSUE #2250: Python: Flask
### Description :
What is Flask?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by shaurya24sri**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2250 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by hritikksingh** [comment]
image
Please format this part correctly like the example of Flask usage in Apps should be on the last and the last 2 lines should be after the first one.
And please don't forget to add space after the full stop :)

**Comment by shaurya24sri** [comment]
Ok sure I will do it

**Comment by shaurya24sri** [comment]
@hritikksingh .Kindly review it

**Comment by hritikksingh** [comment]
Looks good and the Audio file is also good.
@adityabisoi this can be merged.

**Comment by nayakaj** [comment]
@hritikksingh  plz check #6650

**Comment by nayakaj** [comment]
Check #6650 @hritikksingh

**Pull request merged**
