### PR TITLE
Data Science with Python ; Machine Learning Evaluating Algorithms

### LINKED ISSUE #5811: Data Science with Python : Machine Learning Evaluate Algorithms
### Description

Welcome to 'DSWP' Team, good to see you here

The evaluation of algorithm consist three following steps:
1. Test Harness
2. Explore and select algorithms
3. Interpret and report results

In this issue, you will make a tutorial about Evaluate Algorithms

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow, and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : @Kareem-negm / @DhruvBajaj01

Start from: you can use this [notebook ](https://www.kaggle.com/kareem3egm/learn-machine-learning-faster-1)to give you a sample overview 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data science with Python

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by vishnupriya129**
<hr>

## Description 📜

I have added Machine learning Evaluating Algorithms
Fixes #5811

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by vishnupriya129** [comment]
@prathimacode-hub Please review my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Use file name of .ipynb in snake case and folder names as "ML Evaluating Algorithms" and "Diabetes Prediction"
The code blocks in .ipynb file aren't compiled. Check it up. 
In README, it can be elaborative. You only listed evaluating algorithms. Before that add its introduction, how it's derived, short description of what it is and then after this evaluating algorithms, add why its used, purpose, advantages, where are they applied, show some visulizations links, overall summary and conclusion. 
Also add "requirements.txt" file wherein you will list all the libraries that you had used in this issue. @vishnupriya129

**Comment by vishnupriya129** [comment]
@prathimacode-hub Mam can you please review my PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Are your code blocks in .ipynb file compiled?

**Comment by vishnupriya129** [comment]
@prathimacode-hub yes they are compiled

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Fab work. Well done. 👌👏@vishnupriya129

**Comment by vishnupriya129** [comment]
@prathimacode-hub Thank you mam!!

**Pull request merged**
