### PR TITLE
Priyanshu688 patch 23

### PR DESCRIPTION
**Pull request by priyanshu688**
Discussed the steps of Gmail Integration.

<hr>

## Gmail Integration 📜

Discussed the steps of Gmail Integration.
Fixes # #7431 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by priyanshu688** [comment]
@VikasPandey121 Please review this PR

**Comment by priyanshu688** [comment]
@paramsiddharth Please review this PR

**Comment by paramsiddharth** [comment]
> @paramsiddharth Please review this PR

@priyanshu688 I'm sorry! :) I can only review PRs for JavaScript.

**Comment by priyanshu688** [comment]
@paramsiddharth this commit have some javascript files also

**Pull request closed without merging**
