### PR TITLE
INPUT AND OUTPUT OPERATIONS IN C

### LINKED ISSUE #2337: Input and Output Operations in C Programming Language
### Description

- Managing Input/Output
- Formatted Input/Output
- C Format Specifier
- Escape sequences in C
- Reading Character in C
- Difference between getchar(), getc(), getch() and getche()
- Writing Character in C

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜
I have prepared a documentation on:

INPUT AND OUTPUT OPERATIONS IN C

Listing the following concepts:
- Managing Input/Output
- Formatted Input/Output
- C Format Specifier
- Escape sequences in C
- Reading Character in C
- Difference between getchar(), getc(), getch() and getche()
- Writing Character in C

Fixes #2337 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
See..
- fetch upstream
- then Delete Algorithms_FlowCharts_In_C.md (take backup)
- and also remove the line from the readme.md
- then commit your changes

**Comment by vasu-1** [comment]
hey why you have closed this ?

**Comment by ikavyajain** [comment]
Creating both PRs again

**Comment by vasu-1** [comment]
> Creating both PRs again

No Need !
Please Follow the steps that  i have told you

**Comment by ikavyajain** [comment]
PR no :3082

**Comment by ikavyajain** [comment]
Again it’s the same problem i guess

**Comment by vasu-1** [comment]
> Again it’s the same problem i guess

Kyu Thak rahi ho !!!
Please close that one !!!!

**Comment by vasu-1** [comment]
Reopen this

**Pull request closed without merging**
