### PR TITLE
Creating file_handling.md

### LINKED ISSUE #1929: CPP: File Handling
### Description

File Handling and I/O Management using CPP

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by sheril04**
<hr>

## Description 📜File handling in C++

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes  #1929 

<hr>

## Type of change 📝File handling and I/O Mangement

- [ x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ x] C/#CPP

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [ x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ipsitagoel** [comment]
@sheril04 Please try to improve the readability by using proper markdown/formatting and ensure that the entire code comes inside the code block.

**Comment by sheril04** [comment]
@ipsitagoel  okay

**Comment by ipsitagoel** [comment]
/C/CPP

**Comment by sheril04** [comment]
> @sheril04 Please try to improve the readability by using proper markdown/formatting and ensure that the entire code comes inside the code block.

I have made the changes , now u can review and merge it

**Comment by ipsitagoel** [comment]
@Suvraneel Have a look. It's good to merge from my side.

**Comment by Suvraneel** [comment]
@sheril04  Great work ❤️  :octocat:

**Pull request merged**
