### PR TITLE
[JS] Topic: Added topics Iterables, Sets and Maps in JavaScript Objects

### LINKED ISSUE #1833: [JS]Topic: Iterables, Sets and Maps in JavaScript Objects
### Description

 # Iterables, Sets and Maps in JavaScript Objects
In this, We'll discuss Iterables, Sets, and Maps in JavaScript Objects

## Directory
Topics/5.Syntax/Objects/

# Description
I want to update the already made README file for Javascript  objects with some additional contents

### Domain

JavaScript

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by daminimehra**
<hr>

## Description 📜

updated the already made README file for Javascript objects with some additional contentsand added Iterables, Sets and Maps in JavaScript Objects
Fixes Issue #1833 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [x] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by daminimehra** [comment]
@paramsiddharth pls review it!

**Review by s4-2 — APPROVED** [review]
Looks good to me.

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Review by paramsiddharth — CHANGES_REQUESTED** [review]
Incorrect file modified, Damini. Please look at the issue description.

image

To avoid any commits conflicting with existing PRs, I'll close this PR. Create a fresh PR with the newly-added topic directory and the README corresponding to it.

**Comment by daminimehra** [comment]
Here I have to change directory?

**Pull request closed without merging**
