### PR TITLE
Concepts of Friend Functions in Cpp

### LINKED ISSUE #7223: Concepts of Friend Functions in Cpp
### Description

Description

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by RahulRam29**
<hr>

## Description 📜

I have made a documentation about certain features and concepts of friend functions in C++.
Fixes #7223 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by apeksha235 — COMMENTED** [review]
@RahulRam29 documentation on friend function has already been made [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/OOPs%20in%20C%2B%2B/Virtual%20Functions%2C%20Friend%20Functions%20%26%20Friend%20Classes/Friend_function_in_c%2B%2B.md) 
Please check the files before making a pr. 
You can still contribute to this issue with video/audio file
@Suvraneel

**Comment by RahulRam29** [comment]
@apeksha235 I have added other concepts too, please check it. If syntax is removed from my content, it will be fine. Please check.

**Comment by RahulRam29** [comment]
@apeksha235 I will remove syntax, features, simple program.

**Comment by RahulRam29** [comment]
Only syntax is same because syntax remains the same even if you view it from different websites. And features are a little alike. So if I remove syntax and features the rest of the content is no where the same. Please check @apeksha235 @Suvraneel

**Comment by Suvraneel** [comment]
We're not saying ki it's copied...
It's just that 2 documentations for same topic will not be considered because the issue you made has already been contributed on...

There can NOT be 2 PRs on the same issue
If you want you can change the mode... Audio/Video

**Pull request closed without merging**
