### PR TITLE
kth largest element using priority queue

### LINKED ISSUE #4190: Kth largest element using Priority Queue
### Description

In this document , I will be discussing how to find kth largest element of an array using Priority Queue . I will be providing algorithm as well as code  for that.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by am-dusky**
<hr>

## Description
I have provided the algorithm as well as code to find kth largest element using priority queue. 
I have also included why we need to use priority queue .
There is subfolder named priority queue under Standard Template Library , I will be contributing there.
Fixes #4190

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
) 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ChetasShree** [comment]
Amazing work @am-dusky !!
@Saviour1001 @Suvraneel pls review this PR and merge it :)
Thank you!!

**Review by gunjan-g — CHANGES_REQUESTED** [review]
Please mention an index line in readme along with relative links as well

**Comment by am-dusky** [comment]
Since there was  no readme in priority queue folder , I have created one and updated it with relative link .

**Comment by Suvraneel** [comment]
@am-dusky  Well done  🐇 ❤️ :octocat:

**Comment by gunjan-g** [comment]
> Since there was no readme in priority queue folder , I have created one and updated it with relative link .

Great job 👍🏻

**Pull request merged**
