### PR TITLE
Important questions on recursion

### PR DESCRIPTION
**Pull request by akratikushwah**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by akratikushwah — COMMENTED** [review]
Great

**Review by akratikushwah — COMMENTED** [review]
I reviewed them all.

**Review by ipsitagoel — CHANGES_REQUESTED** [review]
@akratikushwah Add readme file giving a description of the codes that you have covered.

**Review by ipsitagoel — CHANGES_REQUESTED** [review]
Also, try to add sample input and output either as text or as images for the codes to make them more understandable.

**Comment by Saviour1001** [comment]
Hey @akratikushwah , you can't add so many questions haphazardly anywhere in the repository. I consider you should have a look at some of the previously merged PRs in the CPP domain and you will get a better idea. We also never include the exe files in the PR. 
Closing this PR and I suggest you should have a look around how the general workflow is and then make a new PR. Ping me on Discord if still in doubt.

**Comment by akratikushwah** [comment]
> Hey @akratikushwah , you can't add so many questions haphazardly anywhere in the repository. I consider you should have a look at some of the previously merged PRs in the CPP domain and you will get a better idea. We also never include the exe files in the PR. 
> Closing this PR and I suggest you should have a look around how the general workflow is and then make a new PR. Ping me on Discord if still in doubt. 

So do I need to Pull request again on this repository??

**Comment by akratikushwah** [comment]
> Hey @akratikushwah , you can't add so many questions haphazardly anywhere in the repository. I consider you should have a look at some of the previously merged PRs in the CPP domain and you will get a better idea. We also never include the exe files in the PR. 
> Closing this PR and I suggest you should have a look around how the general workflow is and then make a new PR. Ping me on Discord if still in doubt. 

And I am not able to assign any other issue because I have 3 opened issues... The due date of them has been passed

**Comment by akratikushwah** [comment]
> Hey @akratikushwah , you can't add so many questions haphazardly anywhere in the repository. I consider you should have a look at some of the previously merged PRs in the CPP domain and you will get a better idea. We also never include the exe files in the PR. 
> Closing this PR and I suggest you should have a look around how the general workflow is and then make a new PR. Ping me on Discord if still in doubt. 

Kindly tell me what to do

**Pull request closed without merging**
