### PR TITLE
Added Roadmap to readme

### LINKED ISSUE #254: Android-Kotlin: 00.2 Readme Update W.R.T Roadmap
Update the [readme](https://github.com/girlscript/winter-of-contributing/blob/Android_Development_With_Kotlin/Android_Development_with_Kotlin/README.md) of Android Dev with Kotlin with the content given in the roadmap (already given in the #general channel) with clean documentation.

### PR DESCRIPTION
**Pull request by Lakshit-Chiranjiv**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #254  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

@rahulsain 
Please review this

### CODE REVIEW

**Comment by rahulsain** [comment]
The image is not visible, can you frame those projects into bigger points?

**Comment by Lakshit-Chiranjiv** [comment]
bigger points ...like could you give an example ??
and for the image , it is a banner image so if you allow then i will put the image in the image folder and push it to this branch...or should i remove the image??

**Comment by rahulsain** [comment]
1. Yes can host the image somewhere and use that link here
2. Can you elaborate those points that till this you can create these type of projects , etc

**Comment by Lakshit-Chiranjiv** [comment]
ok got it...
i will try to elaborate them a bit....

**Comment by Lakshit-Chiranjiv** [comment]
I guess its all good to go now
Please check it again

**Pull request merged**
