### PR TITLE
 Data Science with Python : Text Preprocessing in NLP #392

### LINKED ISSUE #392: Data Science with Python : Text Preprocessing in NLP
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers understand with the concepts of Text preprocessing or cleaning scripts in NLP like Eg. Lowercasing, Punctuation Removal, Removing stopwords, text standardization, Spelling correction, Tokenization, etc. along with sample code. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : [Arya Patel](https://www.github.com/AryaPatel1111) / Gauri Bharadwaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by Deepika-Pavundoss**
<hr>

## Description 📜

Video explaining Text Preprocessing in NLP.

Fixes #392

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Deepika-Pavundoss** [comment]
Please evaluate @prathimacode-hub.
Name: Deepika Pavundoss
Issue: Data Science with Python : Text Preprocessing in NLP #392
Type: Video
Batch number: 5
Serial number: 161

**Comment by avinash-218** [comment]
@prathimacode-hub 
I would like to work on this.
Name : Avinash R
Type: Documentation
Batch: 19
Issue: 796
Approach:
1) Expand Contractions (Eg: Don't -> Do not)
2) Convert to Lower Case
3) Remove Punctuations
4) Remove words containing digits
5) Stop-words Removal
6) Stemming
7) Lemmatization
8) Remove extra space
9) Tokenization - Word, Sentence etc...
10) Spelling Correction
11) POS tagging
12) Frequency Distribution

**Comment by Deepika-Pavundoss** [comment]
Could you please evaluate my PR @prathimacode-hub

**Review by AryaPatel1111 — APPROVED** [review]
Changes have been approved and waiting for the supervisor to merge.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

In .ipynb file instead of getting directly into code you can add a short intro of your issue topic and overall summary of what you had done at the end.
In README.md file, you can add purpose, usage, advantages, applications, why is this preferred, visual representations, conclusion

Your video explanation is wow.

Kindly work on it. @Deepika-Pavundoss

**Comment by Deepika-Pavundoss** [comment]
@prathimacode-hub 
Ma'am could you please check now?

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👍@Deepika-Pavundoss

**Pull request merged**
