### PR TITLE
DSA 1.2.3.1 Algorithms : Space Complexity #2233

### LINKED ISSUE #2233: DSA 1.2.3.1 Algorithms : Space Complexity
### Description

Analysis of space complexity of algorithms.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by lvi131**
<hr>

## Description 📜

Added information about space complexity of algorithms and some examples with explanation.
Fixes #2233

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by lvi131** [comment]
@goelesha
Please review my PR.

**Review by goelesha — CHANGES_REQUESTED** [review]
Rename the name of the file to that mentioned in the issue. 
Also, add the links from where you have taken references for writing this content.

**Comment by goelesha** [comment]
> /assign

@jaigora24 Kindly share what kind of contribution will you be making?

**Comment by lvi131** [comment]
> Rename the name of the file to that mentioned in the issue.
> Also, add the links from where you have taken references for writing this content.

Currently the naming is DSA/1.2 Analysis of Algorithms/3. Space_Complexity/1.2.3.1_Space_Complexity.md
What should i rename it to ?

I have used notes and stuff, haven't used any direct references.

**Comment by jaigora24** [comment]
@goelesha I have already created a PR for review

https://github.com/girlscript/winter-of-contributing/pull/2742

**Comment by goelesha** [comment]
> > Rename the name of the file to that mentioned in the issue.
> > Also, add the links from where you have taken references for writing this content.
> 
> Currently the naming is DSA/1.2 Analysis of Algorithms/3. Space_Complexity/1.2.3.1_Space_Complexity.md
> What should i rename it to ?
> 
> I have used notes and stuff, haven't used any direct references.

If you have not used any references then i guess its good to go !! 
Happy Contributing 👍

**Comment by lvi131** [comment]
@goelesha Thank You!

**Pull request merged**
