### PR TITLE
Data Science With Python : Introduction to Numpy

### LINKED ISSUE #434: Data Science with Python : Introduction to Numpy
Welcome to 'DSWP' Team, good to see you here

This issue will help in gaining clarity of how numpy is used in various ways. Tutorial to Numpy and how it's applied using its relevant sample codes with brief examples.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Jivitesh Jain / Arya Patel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by shripaddhopate**
<hr>

## Description 📜

Topic: Data Science with Python : INTRODUCTION TO  NUMPY<Br>
 
<h2>  Video Link:<a href ="https://drive.google.com/file/d/1T4sMIwsXHV50xifCZBXf9ABZxMvQP-zZ/view?usp=sharing" > INTRODUCTION TO NUMPY<a></h2><br>
What is NumPY?<br>
NumPy is a core Python Library
NumPy is the fundamental package for scientific computing in Python.
It has large collection of high level mathematical functions to operate on arrays.<br>
<br>
Where is it used?
We can create a multi dimensional arrays in NumP
We can perform Mathematical Operations using NumPy 
NumPy is used for scientific calculations.

<br>

Fixes #434

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly reach out to your mentor. Its not loaded in right place and also no data on your issue except video link. The data you added is of PR template. Also in your PR template here, add your issue number, what you had done, and check out the options appropriately. @shripaddhopate

**Comment by shripaddhopate** [comment]
Yes I'll do it

**Comment by shripaddhopate** [comment]
maam how can i get  my issue number can you please help me

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
@shripaddhopate, Kindly refer to already merged README files. This is not how a README file should be. It should have the detailed information on your issue topic. Also you can know of subheadings you can add through contributing guidelines document. You had added PR template in your README. Create a README.md and do needful changes. Any queries, you can reach out to your mentors assigned over your issue or to me.

**Pull request closed without merging**
