### PR TITLE
Python: 2.2 What is virtual environment? #338

### PR DESCRIPTION
**Pull request by nayakaj**
<hr>

## Description 📜

This is the document of what is virtual environment in python # 338

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [x] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by adityabisoi** [comment]
You can ask mentors for details on contributing.

**Comment by nayakaj** [comment]
@adityabisoi  plz merge my pr

**Comment by adityabisoi** [comment]
Plz reach out to mentors with this PR. It doesn't follow contribution guidelines.

**Comment by nayakaj** [comment]
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
@nayakaj Why did you close your PR?

**Comment by prathimacode-hub** [comment]
You should wait until it's checked and should never be closed PR's from your end. @nayakaj

**Comment by nayakaj** [comment]
if you dont  mind can u plz tell how to check pinned messages

**Comment by adityabisoi** [comment]
Merging this PR.  @prathimacode-hub Thank you for your work.

**Comment by adityabisoi** [comment]
Yeah

**Pull request closed without merging**
