### PR TITLE
Data Science with Python : Diabetes Classification #2402

### LINKED ISSUE #2402: Data Science with Python : Diabetes Classification
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about working on Diabetes Classification. Tutorial to Diabetes Classification and how it's applied using sample code with multiple algorithm.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Kareem Negm / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by deepthi1107**
<hr>

## Description 📜

Python code explaining Diabetes Classification.
Fixes  #2402  

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

In .ipynb file before getting into implementation, give a small intro of what your issue title is. Then you had used only random forest algorithm. Instead use multiple algorithm and show the comparison of how accuracies have been varied with preferrable algorithm to choose for Diabetes Classification issue.
And in README.md, you just added an outline of code. Instead it should be elaborate enough to be called as a tutorial to this issue. 

Kindly work on it. @deepthi1107

**Comment by deepthi1107** [comment]
I have made changes please do evaluate mam @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly elaborate your README. This is only an outline. @deepthi1107

**Comment by vanshika230** [comment]
@prathimacode-hub  Ma'am I am the one who created this issue and was working on the documentation. I have completed the entire code and Readme file with 6 algorithms implemented. What shall I do now? Should I create a pull request?

**Comment by prathimacode-hub** [comment]
@deepthi1107, you had been assigned with video right earlier but you had created the same issue and got it assigned for documentation? But from the issue I had created documentation was assigned to @vanshika230

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Ma'am I am the one who created this issue and was working on the documentation. I have completed the entire code and Readme file with 6 algorithms implemented. What shall I do now? Should I create a pull request?

Yes, I am clarifying @vanshika230

**Comment by deepthi1107** [comment]
mam @prathimacode-hub, I have made a video mam, please do evaluate mam.

**Comment by vanshika230** [comment]
@prathimacode-hub  thankyou ma'am. Can I make my pull request? Please inform me when🙏

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub thankyou ma'am. Can I make my pull request? Please inform me when🙏

Yes, you can make it @vanshika230

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👍@deepthi1107

**Pull request merged**
