### PR TITLE
added video about HTML Style attribute

### LINKED ISSUE #201: HTML Style Attributes(video presentation)
I have seen the roadmap given and I would like to contribute about **HTML style attributes**
I would like to demonstrate usage of style attribute on vs code  and explaining it (video) .  I would like to work on this issue. Please assign this to me.

**Language:** English

### PR DESCRIPTION
**Pull request by harshithatnbr**
<hr>

## Description 📜

I have made video about  HTML Style attribute. 
Harshitha (GWOC FrontendHTML_CSS_JSContributor Batch-5)
Fixes #201 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
 **click image for video**
[videoTitle](https://drive.google.com/file/d/1jWQIPUxqhF48oIGEmdq5IEpDcysg8g8D/view?usp=sharing)

<hr>

### CODE REVIEW

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Looks okayish !! Try to write at least 5-10 lines about the topic in the beginning instead & then attach the video. No need to write your details like all that batch, remove it. Also, check the alignment. 

image

**Comment by harshithatnbr** [comment]
Ok I will make the changes

**Comment by harshithatnbr** [comment]
@2024-SANDHYA  I have made changes as you instructed .Please review my PR.

**Review by 2024-SANDHYA — APPROVED** [review]
LGTM!!  💯

**Review by code-reaper08 — APPROVED** [review]
Looks Awesome @harshithatnbr 😄

**Pull request merged**
