### PR TITLE
Cholesky Method in C++

### LINKED ISSUE #7934: Cholesky Method In C++
### Description

I have prepared a Documentation on Cholesky Method in C++:
The documentation contains code for:
- Decomposing a matrix into Lower Triangular
- Displaying Lower Triangular and its Transpose

Hope you learn from it :)

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜

I have prepared a Documentation on Cholesky Method in C++:
The documentation contains code for:
- Decomposing a matrix into Lower Triangular
- Displaying Lower Triangular and its Transpose

Hope you learn from it :)
 
Fixes #7934  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@ikavyajain 
- Please write a few lines about it in your own words. 
- Give a sample input output of your code

**Review by apeksha235 — COMMENTED** [review]
It also seems like you've directly taken the code from [here](https://www.geeksforgeeks.org/cholesky-decomposition-matrix-decomposition/) 
@Suvraneel

**Comment by ikavyajain** [comment]
This was one of the method i have encountered while learning C++
I’ll make changes and revert back to you

**Comment by Suvraneel** [comment]
@ikavyajain  Plagiarised from [here](https://www.geeksforgeeks.org/cholesky-decomposition-matrix-decomposition/)

Just redecorating the main driver wont do... Also doc needed... Remake PR

**Pull request closed without merging**
