### PR TITLE
Cp

### PR DESCRIPTION
**Pull request by iam-sakshi**
<hr>

## Description 📜

Optimized way to find Top K frequent elements present in a list.
Find the Top K Frequent Elements #8397

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by iam-sakshi** [comment]
@ravireddy07 please review.

**Comment by ravireddy07** [comment]
why all this commits..? @iam-sakshi

**Review by ravireddy07 — CHANGES_REQUESTED** [review]
Please add some more explanation on how you approached to solve this problem.

**Comment by iam-sakshi** [comment]
> why all this commits..? @iam-sakshi

It is showing as I have changed the location of the folder of heap ,twice.

**Comment by iam-sakshi** [comment]
> Please add some more explanation on how you approached to solve this problem.

ok

**Comment by iam-sakshi** [comment]
done all the suggested changes , kindly review.

**Review by ravireddy07 — CHANGES_REQUESTED** [review]
@iam-sakshi  Add the formatted code. Use any code formatter which uses 4-space indentation.

**Comment by iam-sakshi** [comment]
done all the required changes please review.

**Review by ravireddy07 — CHANGES_REQUESTED** [review]
differentiate the Apporoaches and add formatted code.
Use any code formatter online.

**Comment by iam-sakshi** [comment]
Done all the required changes

**Review by ravireddy07 — APPROVED** [review]

**Comment by iam-sakshi** [comment]
@Rishabh510 please review

**Review by ravireddy07 — CHANGES_REQUESTED** [review]
Please update your branch and PR.

Don't merge this PR @Rishabh510 @ErzaTitania-2001

**Comment by iam-sakshi** [comment]
@ravireddy07 I have tried updating it but still these commit are visible . I have even tried to squash and merge  but nothing happen .

**Comment by ravireddy07** [comment]
> @ravireddy07 I have tried updating it but still these commit are visible . I have even tried to squash and merge but nothing happen .

What branch you're updating..?
you should update your cp(created-one) branch with upstream's Competative_Programming branch

**Comment by iam-sakshi** [comment]
I have tried alot should I create a new PR , with this file?
@ravireddy07

**Comment by iam-sakshi** [comment]
I have fetch from upstream's Competitive_Programming branch.

**Comment by ravireddy07** [comment]
To update your branch you need to follow this steps:

1. goto your domain branch and `git pull upstream domain-branch`
2. now, Here you create a new branch and checkout to it(ex:  `issue-1`)
3. start working on it and raise the PR.
4. If you want to work on other issues, just create `issue-2` branch domain-branch and raise another PR. Through this `issue-1` will never impact `issue-2`.
5. And whenever this gets closed/merged. update your domain-branch(step-1) and Here
- if you want to work on same `issue-1` branch then checkout to it and merge your domain-branch. `git merge domain-branch`. This will update your `issue-1` with latest changes and start working on new tasks on same branch.
- If you want to create a new branch, then checkout to new branch and raise PR.

@iam-sakshi

**Comment by ravireddy07** [comment]
No need to fetch everytime, Once please understand the significance of `fetch`. You can even check the latest commits through `git log` to verify the updates are there or not.

**Pull request closed without merging**
