### PR TITLE
[JS] Topic: JavaScript Static Methods(#3327)

### LINKED ISSUE #3327: [JS] Topic: JavaScript Static Methods
Directory
Topics/5.Syntax/6.Functions/

Description
I want to add topic JavaScript Static Methods

Domain
JavaScript

Type of Contribution
 Documentation

### PR DESCRIPTION
**Pull request by sakshi168**
<hr>

## Description 📜
Static method in javascript with example and important points.
Fixes #3327 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript_Domain
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 @amino19 Please review.

**Comment by sakshi168** [comment]
> I guess it is necessary to discuss static methods in object-oriented programming also.

but i think that already cover in different topic if its not then we should raise a another issue for that

**Comment by subhendudash02** [comment]
> > I guess it is necessary to discuss static methods in object-oriented programming also.
> 
> but i think that already cover in different topic if its not then we should raise a another issue for that

Oh, I didn't see that, cool!!👍

**Comment by sakshi168** [comment]
> Rename the file to `README.md`

i have tried it its showing that its already exits

**Comment by dakshsethi** [comment]
> > Rename the file to `README.md`
> 
> i have tried it its showing that its already exits

This is because already a file is there, just add your extra point in that file itself
No need to make a new file.

**Comment by sakshi168** [comment]
> > > Rename the file to `README.md`
> > 
> > 
> > i have tried it its showing that its already exits
> 
> This is because already a file is there, just add your extra point in that file itself No need to make a new file.

so may i make a video on this?

**Pull request merged**
