### PR TITLE
Added all about Defer and Error Handling in Golang

### LINKED ISSUE #1579: GoLang: 10.0.DOC Defer and Error Handling
<hr>

## Description 📜
**Defer and Error Handling**
with some description about:

- [Defer](https://www.geeksforgeeks.org/defer-keyword-in-golang/)
- [Error & Exception Handling](https://golangdocs.com/errors-exception-handling-in-golang)
- [Custom Errors](https://www.digitalocean.com/community/tutorials/creating-custom-errors-in-go)
- [Panic](https://www.geeksforgeeks.org/panic-in-golang/) and [Recover](https://www.geeksforgeeks.org/recover-in-golang/)

<hr>

## Domain of Contribution 📊

- [x] Golang

<hr>

## Instructions ✔

* Kindly make a `README.md` for this issue, inside the folder as per topic.
* Changes should be made under the **Golang** branch only and push your PR to the same.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

### PR DESCRIPTION
**Pull request by eshan1925**
<hr>

## Description 📜
I have added/covered all the required topics that were mentioned in the description of the issue and with this I have also given the option to the user for copying the code directly from the doc if he/she wants.
THANK YOU

Fixes #1579

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Go#lang

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Review by amino19 — CHANGES_REQUESTED** [review]
@eshan1925: Thanks for the contribution, some minor changes repeating again & again.
Would like to see changes here as follows:
- Use `#`, `##`, `###`, `####` for the topics/subtopics. _(not for points)_
- In Golang, we can use `//` for commenting, but also we've facilitating with `/* comment(s) */` _(multi-line comments)_.
- All the images are of the same size, try settings images width & height using HTML code, so it won't get that blur, & have a beautiful outlook. :slightly_smiling_face: 
- Do not leave blank lines unnecessary, either use, `</br>` tag for a break.
- Add some emoji as `:emoji: Any topic`, so it will really appreciable.

**Comment by eshan1925** [comment]
Hey, @amino19 You can now merge the PR. I have changed all the changes that were requested.
Thankyou

**Comment by eshan1925** [comment]
@amino19 I have committed all the requested changes, you can merge the PR now.
Thankyou

**Comment by amino19** [comment]
@eshan1925: Some issues still not configured, pl try to fix them.
Thanks! :slightly_smiling_face:

**Review by amino19 — CHANGES_REQUESTED** [review]
@eshan1925: Remove all `<pre><code>` & use backtick/acute (```) with `go`, so it'll render beautifully, like 
```
```go
```
example:-
```go
package main

import (
    "fmt"
    "errors"
)

func e(v int) (int, error) {
    if v == 0 {
        return 0, errors.New("Zero cannot be used")
    } else {
        return 2*v, nil
    }
}

func main() {
    v, err := e(0)

    if err != nil {
        fmt.Println(err, v)      // Zero cannot be used 0
    }   
}
```

**Comment by eshan1925** [comment]
Done @amino19 Please review.

**Comment by eshan1925** [comment]
Done @amino19 Please review.

**Comment by amino19** [comment]
@eshan1925: Everything's resolved, thanks for your contributions!
Respect your patience, time & efforts you made, finally the documentation LGTM! :partying_face:

**Comment by eshan1925** [comment]
Thankyou so much @amino19

**Pull request merged**
