### PR TITLE
Data Science with python : Stock Price Prediction using LSTM

### LINKED ISSUE #6888: Data Science with Python :  Stock Market Price Prediction using LSTM
### Description

This issue was created to guide readers on how to do Stock Market Price Prediction using LSTM. The libraries used will be pandas, numpy, matplotlib, sklearn, lstm, etc.

It will include a tutorial with sample code and required comments.

Mentors: Aishani Singh | Ankit Kumar

Supervisor: @prathimacode-hub 

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by deepeshaburse**
<hr>

## Description 📜

Stock Price Prediction using recurrent neural networks. 
Fixes #6888

- [x] Notebook file
- [x] README.md
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials) 

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README.md has no details on neither LSTM nor Stock Prices Prediction. Focus on these topics to elaborate your README
Even .ipynb file can be more refined and add proper explanation of code for better understanding. Give short intro and summary of your work at the end.

@deepeshaburse

**Comment by deepeshaburse** [comment]
> Your README.md has no details on neither LSTM nor Stock Prices Prediction. Focus on these topics to elaborate your README Even .ipynb file can be more refined and add proper explanation of code for better understanding. Give short intro and summary of your work at the end.
> 
> @deepeshaburse

Kindly review the changes made.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, the files should go under /Datascience_with_Python/Deep Learning/Projects" folder. @deepeshaburse

**Comment by deepeshaburse** [comment]
> Only change it needs, the files should go under /Datascience_with_Python/Deep Learning/Projects" folder. @deepeshaburse

I have changed the path of the files. Let me know if you need any more changes.

**Comment by deepeshaburse** [comment]
> Only change it needs, the files should go under /Datascience_with_Python/Deep Learning/Projects" folder. @deepeshaburse

The changes have been made, kindly let me know if you need me to make any more.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. 👍🙌@deepeshaburse

**Pull request merged**
