### PR TITLE
Cybersecurity: week_1 folder the issue #82

### PR DESCRIPTION
**Pull request by iamKushGupta**
<hr>

## Description 📜

made a folder week_1 , and added to the the fix for #82 
Fixes # <82> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Cyber Security

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by Ayush7614 — APPROVED** [review]

**Review by Anant1711 — CHANGES_REQUESTED** [review]
Sorry @iamKushGupta 
I found plag greater than 80%
Please change it!
Only 25% plag is accepted

**Comment by Ayush7614** [comment]
> Sorry @iamKushGupta
> I found plag greater than 80%
> Please change it!
> Only 25% plag is accepted

@iamKushGupta yess Please Correct it

**Comment by Anant1711** [comment]
> > Sorry @iamKushGupta
> > I found plag greater than 80%
> > Please change it!
> > Only 25% plag is accepted
> 
> @iamKushGupta yess Please Correct it

@Ayush7614 I think this is not your domain?

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
Please Correct it @iamKushGupta  I found Pleg

**Comment by Ayush7614** [comment]
> > > Sorry @iamKushGupta
> > > I found plag greater than 80%
> > > Please change it!
> > > Only 25% plag is accepted
> > 
> > 
> > @iamKushGupta yess Please Correct it
> 
> @Ayush7614 I think this is not your domain?

@Anant1711 my domain is open source

**Comment by Anant1711** [comment]
> > > > Sorry @iamKushGupta
> > > > I found plag greater than 80%
> > > > Please change it!
> > > > Only 25% plag is accepted
> > > 
> > > 
> > > @iamKushGupta yess Please Correct it
> > 
> > 
> > @Ayush7614 I think this is not your domain?
> 
> @Anant1711 my domain is open source

Yeah!
and this PR is for the Cybersecurity domain!
Check again!

**Comment by Aryamanz29** [comment]
> > > > > Sorry @iamKushGupta
> > > > > I found plag greater than 80%
> > > > > Please change it!
> > > > > Only 25% plag is accepted
> > > > 
> > > > 
> > > > @iamKushGupta yess Please Correct it
> > > 
> > > 
> > > @Ayush7614 I think this is not your domain?
> > 
> > 
> > @Anant1711 my domain is open source
> 
> Yeah!
> and this PR is for the Cybersecurity domain!
> Check again!

😂😂

**Comment by iamKushGupta** [comment]
@Anant1711 
Please re-verify my pull request for the given issue #82.

**Review by Anant1711 — APPROVED** [review]

**Pull request merged**
