### PR TITLE
Python Strings

### PR DESCRIPTION
**Pull request by Eswari-Priya**
<hr>

## Python Strings 📜
I elaborated on what strings are, how they can declared and accessed and some of the common operations that are perfoemed on strings.

Fixes # <3120> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Eswari-Priya** [comment]
@hritikksingh pls review my work, and suggest if there are changes to be made.

**Review by hritikksingh — CHANGES_REQUESTED** [review]
image
You have written "won" change it to "own" as you can see in the above image.

Else everything is good and can be merged after correcting that word.

**Comment by Eswari-Priya** [comment]
ok sir

**Comment by Eswari-Priya** [comment]
Sir, I've made the changes suggested. Please review it! @hritikksingh

**Comment by hritikksingh** [comment]
> Sir, I've made the changes suggested. Please review it! @hritikksingh

@Eswari-Priya everything else is good.
@adityabisoi this can be merged.

**Review by hritikksingh — APPROVED** [review]

**Comment by adityabisoi** [comment]
Please resolve conflicts

**Comment by Eswari-Priya** [comment]
@adityabisoi I've resolved the conflicts!

**Pull request merged**
