### PR TITLE
Data Science with Python : Multidimensional Scaling

### PR DESCRIPTION
**Pull request by AdityaNikhil**
<hr>

## Description 📜

In this, I have clearly explained the Multidimensional scaling as well as some concepts of PCA.

**Outline of the video**
1. PCA
2. MDS
3. Metric MDS and Non-Metric MDS

**Fixes :** #5853

<hr>

## Type of change 📝

- [X] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [X] Data Science with Python

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Link to the video! ⬇

[image](https://youtu.be/ly5HfgqgYHw)

    

<hr>

### CODE REVIEW

**Comment by AdityaNikhil** [comment]
@prathimacode-hub 
My apologies for raising this late as I was out of town.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README needs more detailing and elaborative. This topic has lot to say and express. Kindly do the changes. @AdityaNikhil

**Comment by AdityaNikhil** [comment]
@prathimacode-hub Please review the changes.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. Well done. 🙌👌@AdityaNikhil

**Pull request merged**
