### PR TITLE
Solved Issue #4393

### LINKED ISSUE #4393: Frontend with Framework: Introduction to useContext
### Description

Description
Contributors are required to create documentation and explain:- 

- What is `useContext`
- Why to use `useContext`
- Advantages of `useContext`

Note :
Plagiarism is strictly prohibited.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Files need to be added into the Week3 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Ajinkyap331**
<hr>

## Description 📜

Solved Issue #4393 
Fixes #4393

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by Ajinkyap331** [comment]
@NikhilSharma03 please review this one

**Comment by NikhilSharma03** [comment]
Looking Good. Nice Work @Ajinkyap331

**Comment by NikhilSharma03** [comment]
@Ajinkyap331 No. Let's wait until one of the P.A. merge/provide feedback on this PR.

**Comment by Ajinkyap331** [comment]
@NikhilSharma03 what is the status

**Pull request merged**
