### PR TITLE
Insertion and Extraction Operators in C++

### LINKED ISSUE #1631: Insertion and Extraction Operators in C++
<hr>

## Description 📜

In this we will get a brief idea about the insertion and extraction operators used in C++ and also get to know about cin and cout.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by achsahxavier**
<hr>

## Description 📜

This gives a detailed information about the insertion and extraction operators used in C++ along with examples.
Fixes #1631 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by achsahxavier** [comment]
@kashishahuja2002
Please check this and tell me if any change is to be made.

**Comment by achsahxavier** [comment]
@Suvraneel 
Please check this and let me know if any change is to be made.

**Comment by achsahxavier** [comment]
@gunjan-g

Please check this and let me know if any change is to be made.

**Review by kashishahuja2002 — COMMENTED** [review]
Good. Tho there are a few grammatical mistakes, try correcting them. And add reference links if you have referred any.

**Comment by kashishahuja2002** [comment]
DoneReviewed and added comment. Sent from Mail for Windows 10 From: Achsah XavierSent: 22 September 2021 14:48To: girlscript/winter-of-contributingCc: Kashish Ahuja; MentionSubject: Re: [girlscript/winter-of-contributing] Insertion and Extraction Operators in C++ ***@***.*** check this and tell me if any change is to be made.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Suvraneel** [comment]
@SouravKr2001 Why you spamming /assign on every PR, this doesn't even make sense

**Comment by achsahxavier** [comment]
@gunjan-g
Please check this one.

**Review by gunjan-g — CHANGES_REQUESTED** [review]
@achsahxavier please put the files in the folder, Introduction to C and make a folder in that if you want.
Also, put an index line in readme after you're done with the above changes

**Comment by achsahxavier** [comment]
> @achsahxavier please put the files in the folder, Introduction to C and make a subfolder in that if you want.
> Also, put an index line in readme after you're done with the above changes

@gunjan-g 
Please check now and tell me if its done or not.

**Comment by gunjan-g** [comment]
> > @achsahxavier please put the files in the folder, Introduction to C and make a subfolder in that if you want.
> > Also, put an index line in readme after you're done with the above changes
> 
> @gunjan-g
> Please check now and tell me if its done or not.

You've not pushed your commit, the changes are not visible. Please see to this.

**Comment by achsahxavier** [comment]
@gunjan-g 
Could you please guide me how to do that.

**Comment by gunjan-g** [comment]
> @gunjan-g
> Could you please guide me how to do that.

Just put your files in the folder "Introduction to C" which is already present in the C_CPP branch. Put your files there and commit them to the repository you're working upon. Add an index line in the readme of "Introduction to C" folder containing the name of your file and its relative link like this [Name](relative_link)

**Comment by achsahxavier** [comment]
@gunjan-g 
Please check this and let me know if it needs further changes.

**Comment by Suvraneel** [comment]
@achsahxavier Moved to correct directory

Corrections :
1. You had committed the same file twice at 2 places... Should've removed 1
2. Follow naming Convention from next time
3. Modified the correct readme

Observe changes & follow them next time...

Content : Awesome ❤️ :octocat:

**Pull request merged**
