### PR TITLE
[JS] Others : Objects

### LINKED ISSUE #246: JS: Objects
# Objects
Objects in JavaScript.

## Directory
```
Topics/5.Syntax/6.Functions_And_Scope
```

## Description
* About JavaScript objects.
* How to define them?
* Getters and setters.
* What are keys and values?

### PR DESCRIPTION
**Pull request by aniketpathak028**
<hr>

## Description 📜

I have updated the already created readme file, with some additional information on Objects, which I felt were important and could help.
Fixes #246 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by aniketpathak028** [comment]
@paramsiddharth Since, Abhinandan's PR on objects had already been merged, I update his README.md file with the extra information that I had created while researching on the same topic.
I hope it helps and this PR gets merged!
Thanks

**Review by paramsiddharth — APPROVED** [review]
@Creatoon @dakshsethi @s4-2 Please review further.

**Review by s4-2 — APPROVED** [review]

**Comment by s4-2** [comment]
It looks good to me. Well done, keep it up:-)

**Comment by aniketpathak028** [comment]
@Creatoon @dakshsethi pls approve this PR, ig it's good to be merged 🙂

**Comment by Creatoon** [comment]
There are more ways of creating object like using function constructors, object.create(), please also add them

**Review by dakshsethi — APPROVED** [review]

**Pull request merged**
