### PR TITLE
Python: What is Automation?

### LINKED ISSUE #1087: Python: What is Automation?
<hr>

## Description 📜

Automation is the most fun topic of Python. Like, take, for example, you've to check your Facebook messages, or checking the speed of your CPU regularly, or in my case, checking the email every two hours which for me is quite boring. But if I write a particular code and ask it to implement in every two hours, then EUREKA!!! That's what automation is, to make a process to operate automatically.

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

### PR DESCRIPTION
**Pull request by PhantomANaz**
<hr>

## Description 📜

Automation is the most fun topic of Python. Like, take, for example, you've to check your Facebook messages, or checking the speed of your CPU regularly, or in my case, checking the email every two hours which for me is quite boring. But if I write a particular code and ask it to implement in every two hours, then EUREKA!!! That's what automation is, to make a process to operate automatically. 
Fixes #1087

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by PhantomANaz** [comment]
@Randrita how about now?

**Comment by PhantomANaz** [comment]
@Randrita It's done.

**Review by Randrita — CHANGES_REQUESTED** [review]
will you please update readme?

**Review by Randrita — APPROVED** [review]
looks cool @adityabisoi  Have a look at it

**Pull request merged**
