### PR TITLE
Maven - Plugins and Dependencies

### LINKED ISSUE #3042: Maven - Plugins and Dependencies
### Description

<h1>Maven</h1>
<h3>Explanation about maven and its plugins and dependencies and their use and how to add them. </h3>

### Domain

Backend Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by YASHMAROO**
<hr>

## Description 📜

Added Documentation for Maven, its plugins, and dependencies 
Fixes #3042

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials) 

<hr>

## Domain of Contribution 📊

- [x] Backend Dev #(Java)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by YASHMAROO** [comment]
@Satyam175 please review this PR.

**Comment by Satyam175** [comment]
> @Satyam175 please review this PR.

<h3>Can you add a Simple Java Program also ? </h3>
<h3>Anyways Great Explaination 👍</h3>

**Review by Satyam175 — APPROVED** [review]

**Comment by YASHMAROO** [comment]
> > @Satyam175 please review this PR.
> 
> ### Can you add a Simple Java Program also ?
> ### Anyways Great Explaination +1

What kind of Java Program should I add ?

**Comment by Satyam175** [comment]
> > > @Satyam175 please review this PR.
> > 
> > 
> > ### Can you add a Simple Java Program also ?
> > ### Anyways Great Explaination +1
> 
> What kind of Java Program should I add ?

<h3>I meant a sample pom.xml file showing plugins and dependencies . </h3>

**Comment by Satyam175** [comment]
> @Satyam175 I have added a sample pom.xml code Please check it.

<H3>ok great work yash , I really appreciate it

**Pull request merged**
