### PR TITLE
adding README.md and helper-function file

### PR DESCRIPTION
**Pull request by kunal-kumar-chaudhary**
<hr>

## Description 📜

I have added a python script file which contains few different and important helper functions which can be used by a data scientist. they can directly import these functions in their notebook and use them.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by kunal-kumar-chaudhary** [comment]
if there are further any changes to be made, please notify me!

**Comment by kunal-kumar-chaudhary** [comment]
@Aryamanz29

**Comment by kunal-kumar-chaudhary** [comment]
@Aryamanz29 please see if any further changes are to be made.

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Hey @kunal-kumar-chaudhary 
- First update your fork repo ( It should be in sync with `Girlscript : Opensource` branch)
- This issue is related to c**reate your own open source project** and **deploy it** then add its source code repo link and deployed link to a particular doc, See this PR https://github.com/girlscript/winter-of-contributing/pull/1927
-  Please don't submit your doc in `.pynb` format , Currently we are accepting docs only in `markdown .md` format

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Also, add issue number in PR to link

**Comment by Aryamanz29** [comment]
Closing this PR due to inactivity
Thanks

**Pull request closed without merging**
