### PR TITLE
Calendar In C

### LINKED ISSUE #7386: Calendar In C
### Description

I have prepared a documentation on Calendar In C

This fascinating program prints a calendar of the year on the basis of :
- Year
- Month by Month in sequential order by inputting Year by the user
- Day by inputting Date , Month and Year

Hope you find the Date, Date, Month of your choice! :)
Enjoy the code!

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜

I have prepared a documentation on Calendar In C

This fascinating program prints a calendar of the year on the basis of :
- Year
- Month by Month in sequential order by inputting Year by the user
- Day by inputting Date , Month and Year

Hope you find the Date, Date, Month of your choice! :)
Enjoy the code!

Fixes #7386 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by deeqakkk — APPROVED** [review]
@Suvraneel it's good to be merged, do verify and merge it.
Good Work kavya.

**Review by Suvraneel — CHANGES_REQUESTED** [review]
The things you've written in PR descriptioon wont appear in final contribution...
Briefly mention them here in document... About features & all

**Comment by ikavyajain** [comment]
Okay sir,

**Comment by ikavyajain** [comment]
@Suvraneel I have added a description part above the code and some comments in the code as well :)
I have made the required changes. Have a look 👍

**Pull request merged**
