### PR TITLE
Data Science with Python: Poisson Distribution #6361

### LINKED ISSUE #6361: Data Science with Python: Poisson Distribution
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, readers will get introduced to the core information about 'Poisson Distribution.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Statistics

Mentors Assigned : @Pushpit07 / @aishanii

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by surjyaneeh**
<hr>

## Description 📜

Fixes #6361  

<hr>

## Type of change 📝
- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :
In README file, add its purpose, how its derived, why this is useful and where it can applied, also mention some sample applications, what you had done in your .ipynb file, overall summary and conclusion
Add one more test case in .ipynb file and visualization diagrams in "Images" folder and link them up in README file. 

@surjyaneeh

**Comment by surjyaneeh** [comment]
> Changes to be done : In README file, add its purpose, how its derived, why this is useful and where it can applied, also mention some sample applications, what you had done in your .ipynb file, overall summary and conclusion Add one more test case in .ipynb file and visualization diagrams in "Images" folder and link them up in README file.
> 
> @surjyaneeh

@prathimacode-hub I have made changes.

**Comment by prathimacode-hub** [comment]
> > Changes to be done : In README file, add its purpose, how its derived, why this is useful and where it can applied, also mention some sample applications, what you had done in your .ipynb file, overall summary and conclusion Add one more test case in .ipynb file and visualization diagrams in "Images" folder and link them up in README file.
> > @surjyaneeh
> 
> @prathimacode-hub I have made changes.

All changes aren't done yet. @surjyaneeh

**Comment by surjyaneeh** [comment]
> > > Changes to be done : In README file, add its purpose, how its derived, why this is useful and where it can applied, also mention some sample applications, what you had done in your .ipynb file, overall summary and conclusion Add one more test case in .ipynb file and visualization diagrams in "Images" folder and link them up in README file.
> > > @surjyaneeh
> > 
> > 
> > @prathimacode-hub I have made changes.
> 
> All changes aren't done yet. @surjyaneeh

Ma'am are you talking about the visualization part?

**Comment by prathimacode-hub** [comment]
> > > > Changes to be done : In README file, add its purpose, how its derived, why this is useful and where it can applied, also mention some sample applications, what you had done in your .ipynb file, overall summary and conclusion Add one more test case in .ipynb file and visualization diagrams in "Images" folder and link them up in README file.
> > > > @surjyaneeh
> > > 
> > > 
> > > @prathimacode-hub I have made changes.
> > 
> > 
> > All changes aren't done yet. @surjyaneeh
> 
> Ma'am are you talking about the visualization part?

Yes @surjyaneeh

**Comment by surjyaneeh** [comment]
> > > > > Changes to be done : In README file, add its purpose, how its derived, why this is useful and where it can applied, also mention some sample applications, what you had done in your .ipynb file, overall summary and conclusion Add one more test case in .ipynb file and visualization diagrams in "Images" folder and link them up in README file.
> > > > > @surjyaneeh
> > > > 
> > > > 
> > > > @prathimacode-hub I have made changes.
> > > 
> > > 
> > > All changes aren't done yet. @surjyaneeh
> > 
> > 
> > Ma'am are you talking about the visualization part?
> 
> Yes @surjyaneeh

@prathimacode-hub done Ma'am.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good job. Keep it up. 👌✔@surjyaneeh

**Pull request merged**
