### PR TITLE
String and their functions in C #1753

### PR DESCRIPTION
**Pull request by Narotam-singh**
<hr>

## Description 📜

I have made the documentation on String and their functions in C.

## Resources 
- https://www.geeksforgeeks.org/
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by deeqakkk — APPROVED** [review]

**Comment by deeqakkk** [comment]
@Suvraneel plz check that directory link thing.

**Comment by Narotam-singh** [comment]
@Suvraneel Sir, Kindly check this PR.

**Comment by Narotam-singh** [comment]
@Saviour1001 Sir, Kindly check this PR

**Comment by Saviour1001** [comment]
Hey @Narotam-singh great work on the content, just place it in the correct folder and this PR is ready to merge. You can place the file [here](https://github.com/girlscript/winter-of-contributing/tree/C_CPP/C_CPP/Strings%20and%20their%20functions). Update the index of the folder as well which will have the relative link to your content.

**Comment by Narotam-singh** [comment]
@Saviour1001 Can I create a new PR to change the folder?

**Comment by Saviour1001** [comment]
Nah, just change the file location and commit, this PR will get updated. If still in doubt ping me on discord.

**Comment by Narotam-singh** [comment]
@Saviour1001 Is it correct now?

**Pull request merged**
