### PR TITLE
Why .NET

### LINKED ISSUE #2843: [Create New Issue]: Why .NET
### Description

Advantages of .NET over other frameworks, uses of .NET and so and so on.

### Domain

Backend Dev (.NET)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Adityanr**
<hr>

## Description 📜

I have added a ReadMe.md file which gives a brief overview on why .net should be used by developers. 
Fixes #2843 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Backend Dev #(.NET)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Adityanr** [comment]
Hi, please review my PR on Issue #2843 @shikharvashistha
I have added the changes to the new branch as suggested here: https://github.com/girlscript/winter-of-contributing/pull/3469#issuecomment-929931210

**Comment by shikharvashistha** [comment]
> Hi, please review my PR on Issue #2843 @shikharvashistha
> I have added the changes to the new branch as suggested here: https://github.com/girlscript/winter-of-contributing/pull/3469#issuecomment-929931210

Hi @Adityanr 

Few changes are required before merging the pull :

- [ ] Use the dotnet folder. (dotnet/README.md or dotnet/Why_.NET.md) would be preferred.

- [ ] If you want to add a readme file then the naming convention should be README.md (in caps).

**Comment by Adityanr** [comment]
Comment resolved: https://github.com/girlscript/winter-of-contributing/pull/3482#issuecomment-930818869
Please review @shikharvashistha

**Comment by shikharvashistha** [comment]
> Comment resolved: https://github.com/girlscript/winter-of-contributing/pull/3482#issuecomment-930818869
> Please review @shikharvashistha 

A suggestion : you could use the dotnet folder directly instead of creating extra folder hierarchy. (docs)

Best 
@shikharvashistha

**Comment by Adityanr** [comment]
that is a good suggestion, i have modified accordingly: https://github.com/girlscript/winter-of-contributing/pull/3482#issuecomment-931328489
@shikharvashistha

**Comment by shikharvashistha** [comment]
LGTM 🎉

Great work @Adityanr

**Pull request merged**
