### PR TITLE
Data Science with Python : House Prices Prediction #7346

### LINKED ISSUE #7346: Data Science with Python : House Prices Prediction
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know on how to use advanced regression techniques for predicting the house prices

Here is the dataset to follow : https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Kaggle Competitions

Mentors Assigned : Aarya Patel | Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Deepika-Pavundoss**
<hr>

## Description 📜

Code for House Prices Prediction using various Machine Learning algorithms (Contains explanation of dataset, different algorithms and the code)
 
Fixes #7346 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Deepika-Pavundoss** [comment]
Please evaluate @prathimacode-hub @AryaPatel1111 @shivangdubey
Name: Deepika Pavundoss
Issue: Data Science with Python : House Prices Prediction #7346
Type: Documentation
Batch number: 5
Serial number: 161

**Review by AryaPatel1111 — APPROVED** [review]
PR approved. Waiting for supervisor to merge.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add accuracies you have gained and conclusion to your projects and understandings out of it in README.md

@Deepika-Pavundoss

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Fab work.👌🙌@Deepika-Pavundoss

**Pull request merged**
