### PR TITLE
Data Science with Python : Iris Classification 

### LINKED ISSUE #1525: Data Science with Python : IRIS Dataset Classification using Different Approaches
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with IRIS Dataset Classification. Tutorial to IRIS Dataset Classification and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Gauri Bharadwaj / Jivitesh Jain

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by srini047**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1525  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by srini047** [comment]
Please Review my PR😊

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

- Instead of ending it abruptly in .ipynb file, show the final outcomes at end of all the algorithms along with accuracies.
- Create  a README.md, and write a brief tutorial of your project.

Kindly work on it. @srini047

**Comment by srini047** [comment]
> Changes to be done :
> 
> * Instead of ending it abruptly in .ipynb file, show the final outcomes at end of all the algorithms along with accuracies.
> * Create  a README.md, and write a brief tutorial of your project.
> 
> Kindly work on it. @srini047

**Yes mam definitely😊**

**Comment by srini047** [comment]
I have done the changes as per your feedback. Please review the PR. If there are any changes to be made do let me know.😊

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add theroetical explanation in README.md and also to get refernce of what all topics you could add, you can refer with the project structure document provided. @srini047

**Comment by srini047** [comment]
Mam kindly look into the changes I have updated the ReadME File. @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats on your PR. Great job. Keep rising high. Good representation of things in understandable way. 👌🎉🙌@srini047

**Pull request merged**
