### PR TITLE
Added Overview of Android ISSUE NUM (138)

### PR DESCRIPTION
**Pull request by priyanshu688**
I have documented about Android about its History, Features and everything about Android.

## Overview of Android 📜

I have documented about Android. # <138>

### CODE REVIEW

**Comment by priyanshu688** [comment]
@VikasPandey121 please look into this

**Comment by VikasPandey121** [comment]
Awesome work done @priyanshu688 just a small change requested, Please do these changes 

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Add some infographic data as well in order to make it easier to understand and grasp.
- `squash` your commit.

**Comment by priyanshu688** [comment]
How do I squash my commit ...???? I don't know how to do that

**Comment by VikasPandey121** [comment]
> How do I squash my commit ...???? I don't know how to do that

I hope this [link](https://stackoverflow.com/questions/14534397/squash-all-my-commits-into-one-for-github-pull-request) will be helpful. If you find it hard then don't worry about it I will do it from my side. First, please try to make your contribution a bit more infographic.

**Pull request closed without merging**
