### PR TITLE
Fixed Issue Number - 1084 - Pointers and One Dimensional Arrays

### LINKED ISSUE #1870: Update readme with Relative Links
### Description

Change All absolute or missing links to relative links

Example -

- [Title](relative_link) 

Just copy the relative path from url & use it

@kashyap1905

### Domain

C/CPP

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by kashyap1905**
<hr>

## Description 📜

Created descriptive documentation on the topic - Pointers and One Dimensional Arrays. Added a markdown file for documentation and a .c file as a sample code for the topic.

Fixes Issue #1084
Resolves #1870 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by kashyap1905** [comment]
@Suvraneel
Sir I have added the relative path of my directory to the Readme.md file  in this PR. Can u please review it and tell that whether I have to do same thing for other Readme's or some changes are required??

**Comment by Suvraneel** [comment]
@kashyap1905  This is alright lekin Did you know?
You can embed pictures in the Md file?

Try it :octocat:
Just copy the diarams & paste on the documentation file...
Zyada accha dikhega..

**Comment by kashyap1905** [comment]
@Suvraneel 
Made changes as per your instructions. Please Review.

**Comment by kashyap1905** [comment]
@Suvraneel Made changes to all readme files in the C_CPP directory. Please review it.

**Review by Suvraneel — APPROVED** [review]

**Pull request merged**
