### PR TITLE
Smallest Sum Contiguous Subarray

### LINKED ISSUE #1240: DSA 1.1.5.3 Arrays: Standard Problems (Problem 3)
## Description
Find smallest sum contiguous subarray.

## Task
- [x] Documentation
- [x] Audio
- [x] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by divya1467**
<hr>

## Description 📜

Documentation on finding sum of the elements of the contiguous subarray having the smallest sum.

Fixes #1240 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by vikhyatsingh123 — COMMENTED** [review]
Please correct your reference link. It's not directing to gfg

**Review by vikhyatsingh123 — CHANGES_REQUESTED** [review]
Correct your code at line 99

**Comment by divya1467** [comment]
Thank you @vikhyatsingh123, I have made the required change.

**Comment by goelesha** [comment]
@divya1467 Looks good to me. 
Congrats on getting your PR merged !!

**Comment by divya1467** [comment]
> @divya1467 Looks good to me. Congrats on getting your PR merged !!

Thank you @goelesha !

**Pull request merged**
