### PR TITLE
Python : What is Automation 

### LINKED ISSUE #1087: Python: What is Automation?
<hr>

## Description 📜

Automation is the most fun topic of Python. Like, take, for example, you've to check your Facebook messages, or checking the speed of your CPU regularly, or in my case, checking the email every two hours which for me is quite boring. But if I write a particular code and ask it to implement in every two hours, then EUREKA!!! That's what automation is, to make a process to operate automatically.

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

### PR DESCRIPTION
**Pull request by roopali-1**
<hr>

## Description 📜

Here I explain about automation with the help of one ppt and as a audio contribution
Fixes #1087 

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
@roopali-1 good job dear! Will you please add references to your ppt?

**Comment by roopali-1** [comment]
Yes mam i am adding them

**Comment by roopali-1** [comment]
@Randrita ma'am i added the references kindly check .

**Review by Randrita — APPROVED** [review]
@adityabisoi can be merged!

**Pull request merged**
