### PR TITLE
Opensource : 7.0 Licenses In Open Source

### LINKED ISSUE #4492: Opensource : 7.0 `Licenses` In Open Source
### Description

Detailed information `about licenses` and `different types of licenses in open source` and `their importance`.

### NOTE 👇
Please put your doc `7.License/` with the name `7._About_License.md`

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by VandanaKumari18**
<hr>
created a folder of LICENSE in which everything about license have been explained and two types of license ( MIT license and APACHE license ) have been seperately explained in 7.3 and 7.4 
fixes #4492
## Description 📜
<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open #Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by VandanaKumari18** [comment]
@Aryamanz29  i have made a PR pls merge it. 
and please view the documentation in preview condition of md file as i have made a table which is indented according to the preview condition but it is looking broad and wide in md format. pls consider this.

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Hey @VandanaKumari18  Nice work but it would be better if you create different issues for every doc then raise separate PR for each of them. We only accepting `1 issue == 1 PR == 1 doc == 1 contributor` approach.

Now, what do you have to do?
-  Follow [this issue format](https://github.com/girlscript/winter-of-contributing/issues/4492) and create a separate issue for each `docs` and ask for assignments there.
-  Once you'll get assigned then raise PR for the same.
-  One more thing` please link your PR's` with using this keyword `Fixes #issue_number_here`
-  Also please follow `doc_naming_convention` like you have put `7.2 Importance of license.md ` it should be `7.2_Importance_Of_License.md`
-  And create `7.License/7.1_About_License.md` directory **not** `7.Licence.md/7.license/7.1 About licenses.md `

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
@VandanaKumari18  The directory name should be `7.License/` and file name `7_About_License.md`

**Comment by Aryamanz29** [comment]
@VandanaKumari18  It is still the same :point_down: 
Screenshot from 2021-10-05 21-21-29

**Review by Aryamanz29 — APPROVED** [review]
LGTM
Thanks for contributing @VandanaKumari18  🎉🎉

**Pull request merged**
