### PR TITLE
Jdk install

### LINKED ISSUE #34: Android-Java: Installing Java JDK
## Description ->
- What is Java JDK
- Give a brief on how to download and install java on a device (Mac, Windows, Linux).

## Source ->
- https://www.guru99.com/install-java.html

## Note ->
- Changes should be made inside the Android_Development/Java directory & Android_Development_with_java branch.
- Issue only for GWOC'21 contributors.
- Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.

Must-Follow: Contributing Guidelines & Code of Conduct before start Contributing.

### PR DESCRIPTION
**Pull request by sumitmukharjeeeeee**
<hr>

## Description 📜

Added installation steps for JDK on Linux, Windows, Mac OS
Fixes #34  

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Rohit-2602 — APPROVED** [review]

**Comment by Rohit-2602** [comment]
@sumitmukharjeeeeee great job 😀

**Comment by sumitmukharjeeeeee** [comment]
> @sumitmukharjeeeeee great job 😀

Thanks

**Comment by VikasPandey121** [comment]
Awesome work done @sumitmukharjeeeeee just a small change requested, Please do these changes 

- Create a new branch and push your PR on `Android_Development_With_Java` branch
- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Align centre all the images and refract `Android_Development` directory with `Android_Development_Wit_Java` and add your file in `Android_Development_With_Java/Introduction/` directory. 
- `squash` your commit.

**Comment by sumitmukharjeeeeee** [comment]
> Awesome work done @sumitmukharjeeeeee just a small change requested, Please do these changes
> 
> * Create a new branch and push your PR on `Android_Development_With_Java` branch
> * use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
> * Align centre all the images and refract `Android_Development` directory with `Android_Development_Wit_Java` and add your file in `Android_Development_With_Java/Introduction/` directory.
> * `squash` your commit.

Made changes as per requested in #824

**Comment by VikasPandey121** [comment]
@sumitmukharjeeeeee because your PR has previously merged commits I can't merge this PR.
Please follow the steps mentioned above with the new branch and PR. 
Note: Always check out first before starting your contribution and pull before pushing it to the remote branch,

I am closing this PR and I hope you will do the needful changes and come up with the new PR.

**Comment by sumitmukharjeeeeee** [comment]
> @sumitmukharjeeeeee because your PR has previously merged commits I can't merge this PR.
> Please follow the steps mentioned above with the new branch and PR.
> Note: Always check out first before starting your contribution and pull before pushing it to the remote branch,
> 
> I am closing this PR and I hope you will do the needful changes and come up with the new PR.

Okay I am making a fresh branch and will merge changes into that

**Comment by VikasPandey121** [comment]
Thank you @sumitmukharjeeeeee, make sure to checkout to the `Android_Development_With_Java` branch first and then use `git pull origin Android_Development_With_Java`  before starting your contribution.

**Comment by sumitmukharjeeeeee** [comment]
Please assign me there again as I want to start over in #34

**Comment by VikasPandey121** [comment]
> Please assign me there again as I want to start over in #34

The issue is already assigned to you. You just need to follow the above steps and make a new PR.

**Comment by sumitmukharjeeeeee** [comment]
> > Please assign me there again as I want to start over in #34
> 
> The issue is already assigned to you. You just need to follow the above steps and make a new PR.

alright

**Comment by sumitmukharjeeeeee** [comment]
> > Please assign me there again as I want to start over in #34
> 
> The issue is already assigned to you. You just need to follow the above steps and make a new PR.

#1046

**Pull request closed without merging**
