### PR TITLE
Python: Django and web framework

### LINKED ISSUE #2249: Python: Django
### Description :
What is Django?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by roopali-1**
<hr>

## Description 📜

In this PR in explain about Python Django and web framework and audio contribution
Fixes #2249 ( and I want this contribution to count in HactorberFest as well )

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by queenish001 — COMMENTED** [review]
Just change the folder name from `Python Django` to `Python_Django`
Rest is good :)

**Comment by roopali-1** [comment]
@queenish001 done with the changes ..kindly check :)

**Comment by roopali-1** [comment]
@queenish001 for changing the folder name i have to delete this one ...?? I am not able to change folder name her .. can you please help me out !!

**Comment by roopali-1** [comment]
@queenish001 yes done !! kindly check :)

**Review by queenish001 — APPROVED** [review]
Approved :)

@adityabisoi 🌚

**Comment by roopali-1** [comment]
@adityabisoi sir can this PR is eligible for HactroberFest ?? It is great if you put the tag of HactroberFest also ..  :)  
Thank you

**Pull request merged**
