### PR TITLE
Added Tower of Hanoi doc and code

### LINKED ISSUE #3247: DSA : Recursion using Tower of Hanoi
### Description

I will submit the documentation on the topic Recursion using Tower of Hanoi, where I will explain the concept of recursion, and its step by step working through Tower of Hanoi problem.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by priyashajain**
<hr>

## Description 📜

I have created documentation and code to explain recursion using Tower of Hanoi
Fixes #3247

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by nimisha-yadav — COMMENTED** [review]
Looks good! Just rename your folder as ``2. Recursion Tower of Hanoi``

**Comment by priyashajain** [comment]
I am not being able to change the name of the folder 😥

**Comment by nimisha-yadav** [comment]
In your forked repo, edit the file name and keep pressing backspace until you enter into folder name, change folder name and press ``/`` you will enter the file name section. Keep the same file name and click save.

**Comment by nimisha-yadav** [comment]
Or watch [this video](https://youtu.be/94MbtcIKYDg) from 2:10 time stamp

**Comment by priyashajain** [comment]
Thank you so much!! I have changed the folder name. Please review.

**Review by nimisha-yadav — APPROVED** [review]

**Comment by priyashajain** [comment]
Has my PR been merged successfully?

**Comment by priyashajain** [comment]
If I want to contribute to DSA domain of GWOC again, how should I go about it? Which branch or repository to delete to be able to contribute?

**Comment by priyashajain** [comment]
And do I have to delete this branch?

**Pull request merged**
