### PR TITLE
ML_2_4_Pandas Cheatsheet Most Useful Functions and Methods_(D)

### PR DESCRIPTION
**Pull request by Tirth-AI**
<hr>

## Description 📜

I have created a **Pandas Cheat sheet** : Most Useful Functions and Methods in the form of Goggle Colab Notebook. 

Fixes **# 2793**

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] **Documentation** (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] **Machine Learning**
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Please change the file name as, `ML_2_4_Pandas Cheatsheet Most Useful Functions and Methods_(D).ipynb` @Tirth-AI

**Comment by Tirth-AI** [comment]
@abhisheks008  What changes are needed?

**Comment by Tirth-AI** [comment]
> Please change the file name as, `ML_2_4_Pandas Cheatsheet Most Useful Functions and Methods_(D).ipynb` @Tirth-AI

Is it good now ?

**Review by geeythree — APPROVED** [review]
Great work! 😄

**Comment by abhisheks008** [comment]
@Tirth-AI Change the file name not the title of the PR! The .ipynb file you've uploaded named as `Pandas Cheatsheet.ipynb` that'll be changed as `ML_2_4_Pandas Cheatsheet Most Useful Functions and Methods_(D).ipynb`

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
PR approved 🎉

**Pull request merged**
