### PR TITLE
C/CPP: Number System

### PR DESCRIPTION
**Pull request by Akshat-2002-coder**
<hr>

A brief description of Number System is given in this file

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <856> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by Suvraneel — CHANGES_REQUESTED** [review]
image


Place it in a proper directory under C_CPP/...../....

**Comment by Akshat-2002-coder** [comment]
can u plz guide me how to do that

**Comment by Akshat-2002-coder** [comment]
sir plz tell me how to do the required changes . I am new to git hub.

**Comment by Saviour1001** [comment]
@Akshat-2002-coder here is an [video](https://drive.google.com/file/d/1MT427pPKeay_pXGNNuE4kMJj0xRkn6G-/view?usp=sharing) which explains the complete process. If still having any doubts discuss on Discord.

**Comment by Akshat-2002-coder** [comment]
sir can u plz review it now

**Pull request merged**
