### PR TITLE
Data Science With Python : Email Spam detection model #4383

### LINKED ISSUE #4383: Data Science With Python : Email Spam detection model
### Description

Welcome to the 'DSWP' Team, good to see you here

With this issue, readers will get introduced to core information to the Email Spam detection model along with sample code completely in an effective way.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned: Dhruv Bajaj / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include the issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of the 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜

Made a video presentation.

Fixes #4383  

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ashish-reddy-20-08** [comment]
@DhruvBajaj01 @prathimacode-hub , Can you please evaluate my PR.

**Comment by ashish-reddy-20-08** [comment]
@DhruvBajaj01 , Kindly evaluate soon sir, As i am ready with other PR also sir.

**Review by AryaPatel1111 — CHANGES_REQUESTED** [review]
Please add the dataset link or the dataset itself. So, if someone wants to follow the video then they have all the resources required. @ashish-reddy-20-08

**Review by AryaPatel1111 — CHANGES_REQUESTED** [review]
Can you add back the README file because it is not present. I think you have removed it by mistake. @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
NO EVERYTHING IS CORRECT @AryaPatel1111  SIR. I CROSS CHECKED THE READ ME FILE IS ALSO THERE.

image

PLEASE SEE THE IMAGE.

@prathimacode-hub , Mam can you please merge it as i am ready with other PR too.

**Review by AryaPatel1111 — APPROVED** [review]
Work is nicely done. Keep it up!

Waiting for the supervisor to approve.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 😀👌@ashish-reddy-20-08

**Pull request merged**
