### PR TITLE
ML_2_17_Random Forest Algorithms_(D)

### PR DESCRIPTION
**Pull request by AdityaStark7**
- [Machine Learning ] 
- [#2938  ] 
- 

- [ GWOC'21]

### CODE REVIEW

**Comment by AdityaStark7** [comment]
#2938

**Comment by AdityaStark7** [comment]
#2938

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Change the file name as `ML_2_17_Random Forest Algorithms_(D).ipynb`.

**Comment by AdityaStark7** [comment]
Done

**Comment by abhisheks008** [comment]
The file you've uploaded, change its name! @AdityaStark7

**Comment by AdityaStark7** [comment]
> The file you've uploaded, change its name! @AdityaStark7

Done

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
PR approved 🎉  @AdityaStark7

**Pull request merged**
