### PR TITLE
Issue :- https://github.com/girlscript/winter-of-contributing/issues/7809

### PR DESCRIPTION
**Pull request by Narotam-singh**
<hr>

## Description 📜

Hey, I have created documentation on Infix to Postfix using Stack in C++.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by nimisha-yadav — COMMENTED** [review]
Name the file as 4.1.11.2_Infix_To_Postfix.md

**Comment by Narotam-singh** [comment]
Kindly review again

**Review by harshsri28 — APPROVED** [review]
LGTM

**Comment by Narotam-singh** [comment]
@nimisha-yadav Kindly review

**Review by nimisha-yadav — APPROVED** [review]
Great work!

**Pull request merged**
