### PR TITLE
Java 4.1: Single dimension arrays

### LINKED ISSUE #1534: Java 4.1: Single dimension arrays
<hr>

## Description 📜

Add audio, documentation, and video regarding the **Single dimension arrays**.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `Single dimension arrays` folder which is inside the `Arrays` folder present in the  `Java` main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by SB2318**
<hr>

## Description 📜

 Single_Dimension_Array.ipynb is added inside the Single Dimension Array which will be inside Arrays folder which will be inside of Java folder. 

Here I submit an audio file in .mp3 format and have submitted it through a Google drive link.

Fixes #1534

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by SB2318** [comment]
Please Check This @AkMo3 and @garvitraj

**Comment by SB2318** [comment]
This is my first work. But now, I understand the work.
I will give more improve performances from the next work.

**Comment by AkMo3** [comment]
@SB2318 Keep in mind from next time to keep length less than 5 min. As I had iterated this before, keep it simple, straight to the point. @garvitraj Please review this. I do not have time to listen to the entire audio.

**Comment by SB2318** [comment]
> @SB2318 Keep in mind from next time to keep length less than 5 min. As I had iterated this before, keep it simple, straight to the point. @garvitraj Please review this. I do not have time to listen to the entire audio.
Okay, I will remember this point 😇. Thanks for merging it.

**Pull request merged**
