### PR TITLE
SQL Data Types And SQL Operators #2468

### PR DESCRIPTION
**Pull request by sakshi168**
<hr>

## Description 📜
Explained SQL Data Types And SQL Operators
Fixe issue #2468
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Database

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by deeqakkk — APPROVED** [review]
content is fine but @Suvraneel check its labels plz. It belongs in cpp folder or somwhere else.

**Comment by sakshi168** [comment]
> content is fine but @Suvraneel check its labels plz. It belongs in cpp folder or somwhere else.

Yes actually by mistake I added the C/CPP label in this PR and I don't know how to correct this. this PR belongs to the Database only.

**Comment by Suvraneel** [comment]
@sakshi168  Just editing & removing the C/CPP under domain would've fixed it

**Comment by sakshi168** [comment]
> @sakshi168 Just editing & removing the C/CPP under domain would've fixed it

yes its resolved now

**Comment by Ash515** [comment]
Happy Contributing !

**Pull request merged**
