### PR TITLE
Python 1.6 : How to install Python (Documentation) [ issue #78 ]

### PR DESCRIPTION
**Pull request by tejas342**
<hr>

## Description 📜

I had completed the documentation part for how to install python #78

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by tejas342** [comment]
@prathimacode-hub please review my PR and merge it

**Review by Randrita — CHANGES_REQUESTED** [review]
@tejas342  will you please update the readme file of the main python folder as well? and can you please export to .ipynb and add the file directly to the folder! you can change folder name to -> How to install python and add references if you take help from sites and image references too

**Comment by tejas342** [comment]
@Randrita I had made the suggested changes, please check them.

**Review by Randrita — CHANGES_REQUESTED** [review]
@tejas342 you have to update Readme of main python folder too! I am adding the link!
https://github.com/tejas342/winter-of-contributing/blob/Python/Python/README.md

Again! Will you please add Reference Subheading and add the link of official py website link over there? and can you please mention anywhere in your document that user can download any of the desired version! instead of the latest one! And also try to add "python --version" this command too! Kindly look into it!

**Pull request merged**
