### PR TITLE
Android-Kotlin: 02.1 Datatypes in Kotlin

### PR DESCRIPTION
**Pull request by LavleenAgrawal**
<hr>

## Android-Kotlin: 02.1 Datatypes in Kotlin
issue number <#443>

# index:
1. Number
2. Character
3. Boolean
4. Array
5. String

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by LavleenAgrawal** [comment]
@rahulsain Sir please verify my PR and suggest changes if some...!

**Comment by rahulsain** [comment]
Can you share the collab link?

**Comment by LavleenAgrawal** [comment]
Sure sir...should I share link here? or on discord?.....and please teach me that too how to add in .md instead of colab one..... @rahulsain

**Comment by rahulsain** [comment]
> Sure sir...should I share link here? or on discord?.....and please teach me that too how to add in .md instead of colab one..... @rahulsain

Here only

**Comment by LavleenAgrawal** [comment]
@rahulsain 
https://colab.research.google.com/drive/1zYcXWRH8eTp1R8_3HT6spNRd2OuKujCc?usp=sharing

**Comment by rahulsain** [comment]
I think you have to manually copy-paste the text and design again in .md format

**Comment by sitamadex11** [comment]
@LavleenAgrawal I think you can check previously merged Docs. So that you can get the idea about how to create the .md file.

**Comment by LavleenAgrawal** [comment]
@rahulsain @sitamadex11 sir please teach me how to add readme.md file in this same pull request....i completed creating it but dont know how to combine with the same pull request...

**Comment by LavleenAgrawal** [comment]
@rahulsain @sitamadex11 sir I created the .md file, now verify and review.....!
and sir I am unable to delete the previous file...please guide..!!

**Pull request merged**
