### PR TITLE
FRONTEND WITH FRAMEWORK: VueJS-2.4 => Watchers in Vue.js

### LINKED ISSUE #2303: FRONTEND WITH FRAMEWORK: VueJS-2.4 => Watchers in Vue.js
### Description

Contributors are required to explain about Computed Properties in Vue.js, which should cover questions like:-
What are Watchers in Vue.js?
Why there is a need for watchers as we already have computed properties?
When do we have to use this?
How does this work?
How to implement Watchers with code (also give theory explanation of code)?
You can take 2-3 examples with codes of different types to explain this.
etc....

**Note:**

Plagiarism is strictly prohibited.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Files need to be added into the Week2 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Hritik157**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes  #2303

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
 

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Hritik157** [comment]
@anandhu720 sir any updates about review?

**Comment by anandhu720** [comment]
@SourabhSaraswat-191939 will review your pr bro.

**Comment by Hritik157** [comment]
@SourabhSaraswat-191939 sir, I have made the following changes:

1.  Added HTML,CSS codes in the code examples.
2.  Explanation of working of code and adding comments.
3.  Added References at the end.

**Comment by SourabhSaraswat-191939** [comment]
@anandhu720, we can merge this PR.

**Pull request merged**
