### PR TITLE
readme.md file for sort in stl in cpp

### PR DESCRIPTION
**Pull request by sakshi168**
<hr>

## Description 📜

C/CPP: Sort functions in C++ SLT 
#1758  

## Type of change 📝
- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 
<hr>
## Domain of Contribution 📊
- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@sakshi168  please put your file in the proper Data structure/STL folder since you are using STL

**Comment by sakshi168** [comment]
> @sakshi168 please put your file in the proper Data structure/STL folder since you are using STL
ma'am, actually I have completed my work on goggle collab and I don't know where to attach that particular file so I just simply copy and paste in the readme file  
Below is a link to my google collab notebook
 [https://colab.research.google.com/drive/15y9wfGpmfuKHAmQwPU-RA6QffKHMtnG2]

**Comment by apeksha235** [comment]
@sakshi168  You can copy paste your work in the readme file but it should be inside the folders that have been provided that is in the girlscript C_Cpp branch-> C/cpp->Data structures/Standard Template library

**Comment by sakshi168** [comment]
> @sakshi168 You can copy paste your work in the readme file but it should be inside the folders that have been provided that is in the girlscript C_Cpp branch-> C/cpp->Data structures/Standard Template library

okay ma'am now its clear sorry for the mistake

**Comment by Suvraneel** [comment]
@sakshi168 Your PR is already merged

**Pull request closed without merging**
