### PR TITLE
Python: 1.5 Brief history of python

### LINKED ISSUE #76: Python: 1.4 Brief history of python
### Description :
Give a brief history of python.

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by Yashesvinee**
<hr>

## Description 📜

Created and added Video to Python: 1.5 Brief history of Python
Issue #76 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
----
[Brief history](https://drive.google.com/file/d/1UlFpH0LBUs57MM-h0nHtYSCPHo1xwJsV/view?usp=sharing "Brief history")
<hr>

### CODE REVIEW

**Comment by adityabisoi** [comment]
Make the changes in the respective folder.

**Comment by Yashesvinee** [comment]
i did the changes in the folder
(branch) python-->created new folder- About python-->created new folder- Brief history-->added video file

**Comment by Yashesvinee** [comment]
@adityabisoi

**Comment by adityabisoi** [comment]
Can you pull the latest changes, it has the folder structure. You can place your files in there.

**Comment by anushbhatia** [comment]
always do attach a screenshot/gif it would be easy for us to review.

**Comment by Yashesvinee** [comment]
@anushbhatia which way should I upload my video
image
image

**Comment by adityabisoi** [comment]
Hello, you need to make separate PRs from separate issues.

**Comment by Yashesvinee** [comment]
I am so sorry that was my mistake
I didn't realize it
@adityabisoi  could you please check it now?

**Pull request closed without merging**
