### PR TITLE
Data Science with Python : Generative Adversarial Networks 

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜

I have added a readme file about GAN architecture, advantages , disadvantages and its applications and one ipnyb file about the sample code.
Fixes : #469

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure provided in the document. @ron352

**Comment by ron352** [comment]
@prathimacode-hub  can you check it now?

**Comment by prathimacode-hub** [comment]
Kindly follow the project structure provided. @ron352

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to do 👍 

The project file name should be in snake case : "generative_adversarial_networks.ipynb"
The project file just describes code snippets you had place but it's not compiled.
In project file, you had come straight to coding, instead give a introduction of what you are working on and then present it with compiled code snippets and final outcomes at the end
Place the datasets used in "DS Datasets" in respective categories and same goes with references you have referred and add those links of dataset and references in README.md file as links

Kindly work on it. @ron352

**Comment by ron352** [comment]
Changes I have made:

1.  Added Dataset in DS Datasets as a zip file because of its huge volume of images.
2. Changed ipnyb file name as suggested.
3.  In ipnyb file , a brief summary of implementation has been provided at the top and with proper snapshots.
4.  References are cited as links !


Have a check and suggest if any changes are needed. Thank you  😀 

@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your PR. Your PR is approved. Excellently justified the issue topic. Fab start. 🎉🙌@ron352

**Comment by ron352** [comment]
Thanks a lot for your suggestions ! 😄

**Pull request merged**
