### PR TITLE
Python: 2.3 Installing development & debugging software fixes #339

### LINKED ISSUE #339: Python: 2.3 Installing development & debugging software
### Description :
Mention common development & debugging software for python, and where to install them from.

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by AJgthb2002**
<hr>

## Description 📜

Created documentation that lists the popular software used for the development and debugging of python with a brief description. Added links to official websites for downloading the software.

Fixes #339 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generate no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by AJgthb2002** [comment]
@adityabisoi please check

**Comment by adityabisoi** [comment]
Include one more line in `Learning path` in README

**Comment by AJgthb2002** [comment]
Done

**Comment by AJgthb2002** [comment]
@adityabisoi Please review and merge my PR

**Comment by ankurg132** [comment]
@adityabisoi looks good to me!

**Pull request merged**
