### PR TITLE
[JS] Topic: Objects in javascript

### PR DESCRIPTION
**Pull request by aniketpathak028**
<hr>

## Description 📜

Created a README.md file elaborately explaining Javascript Objects, including all the mentioned points like defining objects, key-value pairs, getters and setters, etc.
Fixes # 246

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by aniketpathak028** [comment]
@paramsiddharth could you please review my PR, I have created the README.md file in the same order as it was mentioned in the guidelines. Thank you 😊

**Comment by paramsiddharth** [comment]
> @paramsiddharth could you please review my PR, I have created the README.md file in the same order as it was mentioned in the guidelines. Thank you 😊

I and the mentors will review it! :)
Please avoid branching out from the `main` branch. Use the `Javascript` branch instead.

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi Please review.

**Comment by aniketpathak028** [comment]
@paramsiddharth As the directory has been changed, I deleted my forked repository, hence creating a new PR as instructed. Please close my pull requested in case not deleted.
Thanks

**Pull request closed without merging**
