### PR TITLE
FRONTEND WITH FRAMEWORK: VueJS-1.4 => Intro to Lifecycle Diagram and Lifecycle Hooks (Theory explanation)

### LINKED ISSUE #540: FRONTEND WITH FRAMEWORK: VueJS-1.4 => Intro to Lifecycle Diagram and Lifecycle Hooks (Theory explanation)
Contributors are required to include an Intro to Lifecycle Diagram, which should cover questions like :-
Vue instance
What is LifeCycle Hooks and Diagrams
Explain every 8 life cycle hook
etc....

Also, make sure -
Iclude Diagrams and code snippets for better understanding
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

### LINKED ISSUE #681: FRONTEND WITH FRAMEWORK: React -> Getting Started with React
### NEED TO CONTAIN

- What is React JS?
- Installation and Setup
- Hello World with Stateless Functions
- Absolute Basics of Creating Reusable Components
- Create React App
- Hello World Component

#### You can take refer from [React Official Documentation](https://reactjs.org/)

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ React inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

### PR DESCRIPTION
**Pull request by a12baghel2**
<hr>

## Description 📜

Fully explained Lifecycle diagram and Hooks in Vue with code.
Fixes #540 

<hr>

## Type of change 📝

- [ ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Frontend Dev React/Angular/Vue

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by SourabhSaraswat-191939** [comment]
Hey @a12baghel2,
I know it takes a lot of time to work on the issue and create a PR. But as we already mentioned in the description of the issue that to Avoid copy/paste. So we cannot merge this PR.
Because most of the content is copied from the link below:-
https://blog.logrocket.com/introduction-to-vue-lifecycle-hooks/

Buddy, it's ok to use some of the content from some site on which you learned. Because we cannot replace some of that word/sentence.  But try to do as much as in your language/thoughts. 

If you need any help you can ping us any time we are here to help you.
Hope you will understand and take care of this next time.

**Comment by a12baghel2** [comment]
Okay  I will make changes to it.

**Comment by SourabhSaraswat-191939** [comment]
Try to write from your own

**Comment by SourabhSaraswat-191939** [comment]
@a12baghel2,
Yes, you did changes in your content, but still many of the content is same as that I mentioned earlier.

It will be good If you can avoid this.
For this time only I am allowing to merge this kind of PR. But take care of this next time.
Hope you can understand.

**Comment by SourabhSaraswat-191939** [comment]
@anandhu720,  we can merge it.

**Comment by a12baghel2** [comment]
> @a12baghel2,
> Yes, you did changes in your content, but still many of the content is same as that I mentioned earlier.
> 
> It will be good If you can avoid this.
> For this time only I am allowing to merge this kind of PR. But take care of this next time.
> Hope you can understand.

Okay i will take care of that next time. 🙂

**Review by anandhu720 — APPROVED** [review]

**Pull request merged**
