### PR TITLE
C_CPP: added basic array problems

### LINKED ISSUE #2576: C_CPP: Basic questions on array
### Description

In this documentation I will be adding basic questions on array like displaying elements of array, sum of elements of array etc. 
Code will be in both c and cpp language.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by jaissumi1402**
<hr>

## Description 📜

Added basic array problems in c and cpp language
Fixes #2576

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by deeqakkk — APPROVED** [review]

**Review by deeqakkk — APPROVED** [review]

**Comment by jaissumi1402** [comment]
@Suvraneel there is some conflict in this pr? what should I change?

**Comment by Suvraneel** [comment]
@jaissumi1402  LGTM ❤️ :octocat:

**Comment by jaissumi1402** [comment]
Thankyou so much @Suvraneel

**Pull request merged**
