### PR TITLE
Create Diffrent Sorting Techniques in CPP.md

### LINKED ISSUE #976: CPP:Diffrent Sorting Techniques
<hr>

## Description 📜

Here I will provide detailed description in documentation of diffrent sorting technique with codes.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by Rohit-dubey45**
<hr>

## Description 📜

Topics Covered
* **Insertion Sort**
* **Selection sort**
* **Bubble sort**
Fixes #976

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Rohit-dubey45** [comment]
@Saviour1001  please review and suggest changes.

**Comment by Saviour1001** [comment]
Awesome work @Rohit-dubey45 !!

**Comment by Rohit-dubey45** [comment]
@Saviour1001 please guide me how i can place it in algorithm folder

**Comment by Rohit-dubey45** [comment]
@Suvraneel I have placed my file under the algorithms folder, please review

**Comment by Saviour1001** [comment]
Great!

**Comment by Rohit-dubey45** [comment]
thankyou @Saviour1001

**Pull request merged**
