### PR TITLE
Python: 1.6 How to install Python?

### LINKED ISSUE #78: Python: 1.6 How to install Python?
### Description :
Explain how to install python on your OS.

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by shaurya24sri**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #78

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by shaurya24sri** [comment]
@prathimacode-hub Kindly review my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

This is a audio contribution. As mentioned, audio contribution should have a must presentation of all the details that's been explained in audio format.
Next is README.md file, where in you add all the general overview of the details concerning the issue where in you add this drive link with a heading. To know general overview and what to add, you can check the project structure. 
The audio file just lasts 1minute, you have to be elaborative about the the installation of Python

Kindly work on it. @shaurya24sri

**Comment by shaurya24sri** [comment]
Ma'am In audio contribution only the link of the audio file is required the presentation is optional?

**Comment by prathimacode-hub** [comment]
> Ma'am In audio contribution only the link of the audio file is required the presentation is optional? @prathimacode-hub

Ok, if in that case provide a proper README file and be elaborative with your explanation in your audio file. @shaurya24sri

**Comment by shaurya24sri** [comment]
Ma'am Can I create a new Pull request @prathimacode-hub .I don't know how to change request and make changes in already created pull request

**Comment by prathimacode-hub** [comment]
Kindly follow the project structure. @shaurya24sri

**Comment by prathimacode-hub** [comment]
Just do the changes in your forked repository and push the changes back. It would be automatically updated. @shaurya24sri

**Comment by shaurya24sri** [comment]
ok maam i will do it

**Comment by shaurya24sri** [comment]
Ma'am @prathimacode-hub  I have made the necessary changes in the PR .Kindly review it https://github.com/girlscript/winter-of-contributing/pull/1658

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Elaborate your README file with all the details of your issue title. @shaurya24sri

**Comment by shaurya24sri** [comment]
Ma'am I have elaborated the readme file of audio. @prathimacode-hub .Please reveiw it.https://github.com/girlscript/winter-of-contributing/pull/1658

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Elaboration means explaining in detailed manner about the topic choosen in all aspects of it. You provided the outline of the topics you had included in your audio file. But it needs more detailing about issue in theoretical way.  @shaurya24sri

**Comment by shaurya24sri** [comment]
OK ma'am @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
It needs more elaboration. Installation of Python is more necessarily should be contextual of how it's done. @shaurya24sri

**Comment by shaurya24sri** [comment]
Okkk ma'am I will elaborate it.

**Comment by shaurya24sri** [comment]
@prathimacode-hub Ma'am i have updated my file please review

**Review by prathimacode-hub — APPROVED** [review]
@shaurya24sri, this PR is approved and ready to be merged.

**Comment by adityabisoi** [comment]
@shaurya24sri Please resolve conflicts, so that I can merge.

**Comment by shaurya24sri** [comment]
I am unable to resolve conflict .the resolve conflict button is disable it says the conflicts are too complex to be solve in the web editor. @prathimacode-hub @adityabisoi

**Comment by shaurya24sri** [comment]
I have resoled the conflict @adityabisoi

**Pull request merged**
