### PR TITLE
Uploaded video on Decorators

### PR DESCRIPTION
**Pull request by saurav3232**
<hr>

## Description 📜

I have added a readme file inside the video folder  in the Decorators/video folder, which contains the link for video
Fixes # 576

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by saurav3232** [comment]
@Randrita please review my pr

**Review by Randrita — CHANGES_REQUESTED** [review]
@saurav3232 the video that you have added is not visible! again you create a video folder in the documentation folder, you can separate two things!

**Comment by saurav3232** [comment]
@Randrita have updated the readme please check now and readme file is present in the Decorators documentation/videos
Screenshot 2021-09-23 144357

**Review by Randrita — COMMENTED** [review]
@saurav3232  content looks fine! can you please move the video folder from the documentation folder! place it with documentation

**Comment by saurav3232** [comment]
@Randrita  i have fixed that , please confirm if its visible

**Review by Randrita — APPROVED** [review]
looks good to me, you can merge it if it's fine with you @adityabisoi

**Pull request merged**
