### PR TITLE
Competitive programming : C++ : Stacks and Queues

### LINKED ISSUE #1183: Competitive Programming : Stacks, Queues and Arrays
<hr>

## Description 📜

Would like to add the codes for Implementation and Concepts (Stacks, Queues and Arrays - Data Structures) 
Can you please assign me for this issue?
Thanks 

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming
- [x] DSA
- [x] Open Source

<hr>

### PR DESCRIPTION
**Pull request by hariketsheth**
<hr>

## Description 📜

Added implementation of some basic concepts in Stacks and Arrays under Competitive Programming branch. 
Would be adding more soon.
Fixes  #1183 

Please have a look, @nimisha-yadav 
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming
- [x] DSA
- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image
image

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Hey, I can't review since I'm only supervising DSA branch. You may tag CP supervisors for the same

**Comment by Suvraneel** [comment]
@hariketsheth  Kindly tag the CP mentors,,,
And from next time select 1 domain

**Review by ravireddy07 — COMMENTED** [review]
Hey @hariketsheth ,
* The contribution is allowed in Documentation, Audio and Video format only. No raw code.
* You can explain the code/solution and approaches.
* Make sure you include one single file in each contribution.

Please close this and make new PR's with proper documentation or Audio or Video.

**Pull request closed without merging**
