### PR TITLE
CSS Transition and Transform

### PR DESCRIPTION
**Pull request by Ab2602**
<hr>

## CSS Transition and Transform

Added a documentation on CSS Transition and Transform.

<hr>

## Type of change 📝
- [x ] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x ] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Hello 👋 @Ab2602 
You've presented a PDF, Instead of **.md** file. Present your file in .md format.

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Oops! look like a lot of plagiarism going on here 😕😐

This is exactly from **MDN docs**
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transforms/Using_CSS_transforms

You are free to get Ideas from different sources, but not to copy the exact same thing.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Reference link missing. Image credits too

**Review by code-reaper08 — APPROVED** [review]
Looks nice to me, have a look once @2024-SANDHYA

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
I think an example, with the output too will look good. 🤔 What say @code-reaper08

**Comment by code-reaper08** [comment]
> I think an example, with the output too will look good. 🤔 What say @code-reaper08

Yes it would make it more awesome!

**Comment by Ab2602** [comment]
I have edited the documentation please review it @code-reaper08 @2024-SANDHYA

**Review by 2024-SANDHYA — APPROVED** [review]
Good Work 💯

**Pull request merged**
