### PR TITLE
C_CPP: Why is Deallocation necessary?

### LINKED ISSUE #8222: C_CPP: Why is Deallocation Necessary?
### Description

Description

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by 124015001**
<hr>

## Description 📜

Explained why deallocation necessary. Also, showed few codes to explain the same.
Fixes #8222  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by 124015001 — COMMENTED** [review]
remove previous PR's files.

**Review by 124015001 — COMMENTED** [review]
resolved conflicts

**Comment by Saviour1001** [comment]
The Merge Conflicts are still there. Would recommend to close this PR, update your repo and make a fresh PR. Else you can ping me the changes you want to do and I will resolve the conflicts accordingly.

**Comment by 124015001** [comment]
Option to resolve the conflicts is disabled.

image

**Comment by 124015001** [comment]
@Saviour1001 I am closing this PR and going to make a new one.

**Pull request closed without merging**
