### PR TITLE
Python: Web scraping

### LINKED ISSUE #1096: Python: Web scraping
<hr>
@adityabisoi @prathimacode-hub 

## Description 📜

Web scraping is the process of using bots to extract content and data from a website.

To extract data using web scraping with python, the following steps are done:
- Find the URL that you want to scrape
- Inspecting the Page
- Find the data you want to extract
- Write the code
- Run the code and extract the data
- Store the data in the required format 

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

### PR DESCRIPTION
**Pull request by nakshatra-garg**
<hr>

## Description 📜

I've added a jupyter notebook for web scraping with beautiful soup and also updated the README file for the same.
Fixes #1096

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

Please review @adityabisoi

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
@nakshatra-garg will you please push the folder? and add the same in the readme instead of the file link!

**Comment by nakshatra-garg** [comment]
> @nakshatra-garg will you please push the folder? and add the same in the readme instead of the file link!

I did add the files in the Web_Scraping folder!
Can you please elaborate on what I need to do? I don't understand.

**Comment by nirvikagarwal** [comment]
The Documentation is well-written, you can just an installation step for beautiful Soup for making it more complete. You can also add a section talking about some of the alternatives.

**Comment by nirvikagarwal** [comment]
> > @nakshatra-garg will you please push the folder? and add the same in the readme instead of the file link!
> 
> I did add the files in the Web_Scraping folder!
> Can you please elaborate on what I need to do? I don't understand.

You need to add the link to the folder that you have created in the [README.md](https://github.com/girlscript/winter-of-contributing/blob/Python/Python/README.md)

**Pull request closed without merging**
