### PR TITLE
Data Science with Python : Exploratory Data Analysis using Python #348

### PR DESCRIPTION
**Pull request by ayushijindal**
<hr>

## Description 📜
Created documentation on Exploratory Data Analysis using Cancer Survival Dataset 
Issue title:  Data Science with Python: Exploratory Data Analysis using Python #348 
Fixes : #348
ID : 253

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations, and regular explanatory films are all possibilities, etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [x] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by DhruvBajaj01** [comment]
The files are under reviewing process.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Your README needs more detailing about the topic
Both README.md and and .ipynb file should be in your project folder (Exploratory Data Analysis using Python).
Remove the empty readme,md file.
Your project folder should be as "Exploratory Data Analysis using Python"
Your project file should be as "exploratory_data_analysis.ipynb"
This is a visualization issue so you can put up your visualizations in "Images" folder in your project repository.
Kindly remove the main README.md file you had created under "Data Analysis and Visualization"
If you had referred any resources, add them up in README.md file and also in "DS Resources" folder.

Kindly do these changes. @ayushijindal

**Comment by prathimacode-hub** [comment]
Kindly address all the changes. It isn't shown up yet. @ayushijindal

**Comment by ayushijindal** [comment]
> Kindly address all the changes. It isn't shown up yet. @ayushijindal

@prathimacode-hub  I am working on it and adding all the required changes that need to be done

**Comment by ayushijindal** [comment]
> > Kindly address all the changes. It isn't shown up yet. @ayushijindal
> 
> @prathimacode-hub I am working on it and adding all the required changes that need to be done and upload it soon

**Comment by ayushijindal** [comment]
@prathimacode-hub I have made the required changes in the file as it was told

CHANGES MADE:
1. Removed(Delete) wrongly placed readme.md file
2. Added readme.md file in the required folder(EDA)
3.  Made changes in the readme.md file to elaborate the documentation 
4. Added images folder in EDA folder to use screenshots in the  .md  file 
5. Remove old .ipynb file (cause it requires changes)
6. Made a separate .ipynb file add some more codes and plots and rename it as the issue name
7. Upload the newly made .ipynb file into EDAfolder
8. Uploaded dataset  .csv  file in DS dataset folder

kindly look into these changes and if there are still more changes that need to be made kindly inform me

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only changes it needs are file name formats.
All he readme file as titled as README.md
The project folder should be as "Exploratory Data Analysis" and project file name in snake case that is : exploratory_data_analysis.ipynb

Kindly do these changes. @ayushijindal

**Comment by ayushijindal** [comment]
@prathimacode-hub 
I have changed file name formats
kindly recheck it let me know if it needs any more changes

**Review by prathimacode-hub — APPROVED** [review]
Congrats. Your PR is approved. Wonderful execution of your issue. Keep it up. Your dedication is amazing. 👌✨@ayushijindal

**Comment by ayushijindal** [comment]
> Congrats. Your PR is approved. Wonderful execution of your issue. Keep it up. Your dedication is amazing. 👌✨@ayushijindal

@prathimacode-hub 
Thank you so much for helping me while making commits and PR

**Review by DhruvBajaj01 — COMMENTED** [review]
Reviewed! Neatly done

**Pull request merged**
