### PR TITLE
Liquid state machine (LSM)

### LINKED ISSUE #6364: Data Science with Python: Liquid state machine (LSM)
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, readers will get introduced to the core information about 'Liquid state machine (LSM)'.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : @Pushpit07 / @aishanii

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Vishaka830**
<hr>

## Description 📜

I've completed the documentation of Liquid State Machine under the Machine Learning Domain along with it's definition, structure, components and how it is different from SNN
Fixes #6364

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [X] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README can be explored more, and .ipynb file doesn't mean documenting theory. It should be shown practically using code blocks and examples using text cases. @Vishaka830

**Comment by Vishaka830** [comment]
@prathimacode-hub got it, ma'am. Now I've covered all the relevant aspects of LSM's in README file and also make changes in .ipynb file

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Sorry all the theoretical knowledge should be in README.md and in .ipynb file you should demonstrate it practically using code blocks along with short introduction and overall summary
You have added right but placed in wrong places. Your PR title should be as same as your issue title. @Vishaka830

**Comment by Vishaka830** [comment]
I value your feedback @prathimacode-hub, ma'am, & as per that I tried to make all the things up to the mark this time. Plz, review it.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In README.md you added references, it should be like links
In .ipynb file, looks like code block isn't compiled yet. @Vishaka830

**Comment by Vishaka830** [comment]
Oh, Pardon @prathimacode-hub  ma'am! Now I've added references as links and code blocks are also compiled.

**Comment by prathimacode-hub** [comment]
I couldn't see the code blocks compiled yet. Have you pushed it properly after doing the changes? @Vishaka830

**Comment by Vishaka830** [comment]
@prathimacode-hub yes ma'am. Code blocks are successfully compiled and pushed.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. 👌👍✔@Vishaka830

**Pull request merged**
