### PR TITLE
DSA 3.1.9.1_Doubly_Linked_List_Introduction_Audio

### LINKED ISSUE #5890: DSA 3.1.9.1_Doubly_Linked_List_Introduction_Audio
## Description
What is doubly linked list? Explain. Discuss it's implementation in C/Cpp or Java. 

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- After completion of your task, add your file in this [folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/09.%20Doubly%20Linked%20List) and name it 3.1.9.1_Doubly_Linked_List_Introduction_Audio.md
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by jaigora24**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #5890

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Add some description in readme

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Add a bit of description in readme

**Review by jaigora24 — COMMENTED** [review]
Updated

**Comment by jaigora24** [comment]
@nimisha-yadav @harshsri28 @sneha-nitdgp plz review again

**Review by nimisha-yadav — COMMENTED** [review]
@jaigora24 Add your file in this [folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/09.%20Doubly%20Linked%20List)

**Review by harshsri28 — APPROVED** [review]
LGTM

**Pull request closed without merging**
