### PR TITLE
Frontend : CSS Basics & Syntax

### LINKED ISSUE #2442: Frontend : CSS Basics & Syntax
<hr>

## Description 📜

I want to work/contribute on making a complete documentation on CSS Basics & Syntax.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by VenkateswarNayak**
<hr>

## Description 📜

Created Documentation for the issue:  CSS Basics & Syntax with suitable examples and codes.
Fixes #2442 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by sifa123 — CHANGES_REQUESTED** [review]
Please add some coded examples and the output for syntax.

**Comment by VenkateswarNayak** [comment]
Okay Mam, Doing it!!

**Comment by VenkateswarNayak** [comment]
> Please add some coded examples and the output for syntax.

I have updated the required changes mentioned by you. Please, kindly review it.

**Review by sifa123 — APPROVED** [review]

**Comment by VenkateswarNayak** [comment]
Hello Mam,
Since, The Pull Request has been merged. Should I close this issue?

**Comment by sifa123** [comment]
> Hello Mam,
> Since, The Pull Request has been merged. Should I close this issue?

Yes you can close the issue

**Comment by VenkateswarNayak** [comment]
Thank you, Mam!!

**Pull request merged**
