### PR TITLE
Data Science with Python : Depression Detection using ML

### LINKED ISSUE #3521: Data Science with Python : Depression Detection using ML
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Depression Detection using ML. Tutorial to Depression Detection using ML and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : AishanI Singh / Dhruv Bajaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜
Depression detection using three ml techniques and check accuracy
Fixes #3521

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
@prathimacode-hub  mam , can you check this PR? let me know if anything needs to be changed
Thank you !

**Comment by ron352** [comment]
@prathimacode-hub mam , can you check this PR? let me know if anything needs to be changed
Thank you !

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly elaborate your readme file and title it as README.md @ron352

**Comment by ron352** [comment]
@prathimacode-hub  mam, I have added snaps and also steps and changed the readme.file name also! Let me know if any changes need. Thank you !

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive work. 👌🙌@ron352

**Pull request merged**
