### PR TITLE
#7507 Resolved: ML 8.16 : Fourier and Discrete Cosine Transformations of Images (D)

### LINKED ISSUE #7507: ML 8.16 : Fourier and Discrete Cosine Transformations of Images (D)
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Fourier and Discrete Cosine Transformations of Images_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Seqential_Data_&_Visual_Data` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by VidhiBhatt01**
<hr>

## Description 📜

Added documentation for Fourier and Discrete Cosine Transformations of Images.
Fixes #7507

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by raina-akshay — CHANGES_REQUESTED** [review]
Include some code

**Comment by VidhiBhatt01** [comment]
> Include some code

Okay,will fix it soon.

**Comment by VidhiBhatt01** [comment]
> > Include some code
> 
> Okay,will fix it soon.

@abhisheks008 @raina-akshay What type of code is required? I can't figure it out.

**Comment by raina-akshay** [comment]
> > > Include some code
> > 
> > 
> > Okay,will fix it soon.
> 
> @abhisheks008 @raina-akshay What type of code is required? I can't figure it out.

Implement both of the transformations (DCT and FT) onto any sample image/s using any standard Python library like OpenCV, Scikit-Image, Scipy, and so on. Do some visualizations at the end to show the resulting transformations.

**Comment by abhisheks008** [comment]
@VidhiBhatt01 please do the needful changes, we can't merge your PR unless you rectify the issues.

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 please do the needful changes, we can't merge your PR unless you rectify the issues.

@abhisheks008 yes yes I know, am facing some issues fixing this and that's why it's taking time. Nevermind, I will do the changes and update the PR  today by evening 7 pm.

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 please do the needful changes, we can't merge your PR unless you rectify the issues.

@raina-akshay @abhisheks008 I made the changes, please review them.

**Comment by abhisheks008** [comment]
Approved the changes from my side, @raina-akshay will do the needful.

**Review by raina-akshay — APPROVED** [review]
resolved! 🎉

**Comment by VidhiBhatt01** [comment]
> resolved! 🎉

Thank you!

**Comment by VidhiBhatt01** [comment]
@raina-akshay @abhisheks008 @Isha307 I have completed all my assigned issues within the deadline. I can't find any more unassigned issues now. If there are any, do let me know, I will be more than happy to contribute! :)

**Comment by abhisheks008** [comment]
@VidhiBhatt01 DM any of the supervisors in your discord channels, there you'll get to know how you can contribute more!

**Pull request merged**
