### PR TITLE
Data Science With Python: Text Preprocessing in NLP

### LINKED ISSUE #392: Data Science with Python : Text Preprocessing in NLP
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers understand with the concepts of Text preprocessing or cleaning scripts in NLP like Eg. Lowercasing, Punctuation Removal, Removing stopwords, text standardization, Spelling correction, Tokenization, etc. along with sample code. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : [Arya Patel](https://www.github.com/AryaPatel1111) / Gauri Bharadwaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by deepeshaburse**
<hr>

## Description 

- [x] 📜 Documentation content
- [x]  Sample code 

This documentation includes the concepts of text preprocessing in NLP along with sample code.
Fixes #392 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Aaksha-sharma** [comment]
I want to contribute to this

**Review by AryaPatel1111 — APPROVED** [review]
Great Work @deepeshaburse the explanation was to the point for each and every step and code.

**Comment by deepeshaburse** [comment]
> Great Work @deepeshaburse the explanation was to the point for each and every step and code.

Thanks!!

**Comment by prathimacode-hub** [comment]
Changes to be done : 

- It needs README.md file where in you can add all the outlined topics of your issue title.
- You had put up your project in main repo. Instead it should go into the branch repo of "Data Science with Python"
- This project as mentioned in documentation provided should go under "Natural Language Processing/Tutorials. In this a issue title folder is expected to be created "Text Prepocessing".
- There would 2 files in total. .ipynb file and README.md file. README file would be having the outline of all the needed headings concerning the issue title. For reference, you can check out with the project structure given in guidelines document.
- The file names should be in snake case characters such as "text_preprocessing.ipynb" and readme file as "README.md"
- This is the project structured mentioned in the document provided for documentation

Kindly do all these changes. Your notebook file is outstanding. @deepeshaburse

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

- It needs README.md file where in you can add all the outlined topics of your issue title.
- You had put up your project in main repo. Instead it should go into the branch repo of "Data Science with Python"
- This project as mentioned in documentation provided should go under "Natural Language Processing/Tutorials. In this a issue title folder is expected to be created "Text Prepocessing".
- There would 2 files in total. .ipynb file and README.md file. README file would be having the outline of all the needed headings concerning the issue title. For reference, you can check out with the project structure given in guidelines document.
- The file names should be in snake case characters such as "text_preprocessing.ipynb" and readme file as "README.md"
- This is the project structured mentioned in the document provided for documentation

Kindly do all these changes. Your notebook file is outstanding. @deepeshaburse

**Comment by deepeshaburse** [comment]
> Changes to be done :
> 
> * It needs README.md file where in you can add all the outlined topics of your issue title.
> * You had put up your project in main repo. Instead it should go into the branch repo of "Data Science with Python"
> * This project as mentioned in documentation provided should go under "Natural Language Processing/Tutorials. In this a issue title folder is expected to be created "Text Prepocessing".
> * There would 2 files in total. .ipynb file and README.md file. README file would be having the outline of all the needed headings concerning the issue title. For reference, you can check out with the project structure given in guidelines document.
> * The file names should be in snake case characters such as "text_preprocessing.ipynb" and readme file as "README.md"
> * This is the project structured mentioned in the document provided for documentation
>   Add up the respective datasets used in "DS Datasets" in "Natural Language Processing" folder and resources referred in "DS Resources" in "Natural Language Processing" folder
> 
> Kindly do all these changes. Your notebook file is outstanding. @deepeshaburse

I'll make those changes asap. Thanks!

**Comment by prathimacode-hub** [comment]
Any update? @deepeshaburse

**Comment by deepeshaburse** [comment]
> Any update? @deepeshaburse

Can you please review the changes made?

**Comment by prathimacode-hub** [comment]
Changes aren't updated yet. @deepeshaburse

**Comment by deepeshaburse** [comment]
> Changes aren't updated yet. @deepeshaburse

Can you check it now?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README needs more elaboration. @deepeshaburse

**Comment by deepeshaburse** [comment]
> Your README needs more elaboration. @deepeshaburse

Please review the changes made.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Sorry to say, but README still lacks details. Text preprocessing is a vast topic in NLP. It can be more detailing. There is lot to describe on this topic. @deepeshaburse

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add purpose, why it's used and preferred, the workflow and functionalities how it works, applications, usage, advantages, overall summary and conclusion in README.md

Kindly add these changes. @deepeshaburse

**Comment by deepeshaburse** [comment]
> Add purpose, why it's used and preferred, the workflow and functionalities how it works, applications, usage, advantages, overall summary and conclusion in README.md
> 
> Kindly add these changes. @deepeshaburse

Please review the changes made.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Very well done. ✔🙌@deepeshaburse

**Pull request merged**
