### PR TITLE
Cyclic sort in C++

### PR DESCRIPTION
**Pull request by aniket-24**
<hr>

## Description 📜

In this, we will get a brief idea about the Cyclic Sort in C++
Fixes # 2431

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by aniket-24** [comment]
@nimisha-yadav  review this one, please!

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav review this one, please!

Hi @aniket-24, I'm supervising DSA. Your file can only be reviewed and merged by CPP supervisors, so you should tag them.

**Comment by aniket-24** [comment]
@Suvraneel review this one, please!

**Comment by Suvraneel** [comment]
@aniket-24  Resolved merge conflicts...
First put files in appropriate directories :
C_CPP->Algo folder -> sorting algos

And add line to Sorting/readme.md

Then mentors will review your PR

**Comment by Saviour1001** [comment]
Closing the PR !!

**Pull request closed without merging**
