### PR TITLE
OpenSource : 4.13 Explain everything related to FOSSEE Summer Fellowship

### LINKED ISSUE #310: OpenSource : 4.13 Explain everything related to `FOSSEE Summer Fellowship`
### Description :

- **Explain everything related to `FOSSEE Summer Fellowship`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by siddhi-244**
<hr>

## Description 📜
4.13 FOSSEE Summer Fellowship

Fixes #310 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by jannatulferdaws** [comment]
Is this issue taken?

**Comment by Aryamanz29** [comment]
> Is this issue taken?

This is PR not issue

**Comment by Aryamanz29** [comment]
@siddhi-244  Clean work again 🎉
Merging this one 🙌

**Comment by jannatulferdaws** [comment]
> > Is this issue taken?
> 
> This is PR not issue

Oh . Sorry

**Comment by siddhi-244** [comment]
> @siddhi-244 Clean work again 🎉
> Merging this one 🙌

Thank you😊

**Pull request merged**
