### PR TITLE
Added video for packages in java

### LINKED ISSUE #2505: Java 13.1: Defining Packages
> ### Description
> Add audio, documentation, and video regarding the **Defining Packages**.
> 
> ### Location of File to be added
> The files should be added inside the `Defining Packages` folder which is inside the `Packages` folder present in the `Java` main folder. The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.
> 
> **Note:**
> 
> * You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
> * Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
> * You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
> * Issues will be assigned on a first come first serve basis.
> 
> ### Domain
> Java_Domain
> 
> ### Type of Contribution
> Audio, Video, Documentation
> 
> ### Code of Conduct
> * [x]  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by vrukshaliii**
<hr>

## Description 📜
Adding Video for Packages in Java

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2505  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Java_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by akadkol05 — APPROVED** [review]

**Comment by AkMo3** [comment]
@Vrukshali-26 Please reduce the transition time from one slide to another.

**Comment by Vrukshali-26** [comment]
@AkMo3  I have made the mentioned changes. Please check once

**Review by AkMo3 — APPROVED** [review]
@Vrukshali-26 I am approving for the time being, but the might be required to be increased if the next reviewer feels so.

**Comment by AkMo3** [comment]
@garvitraj Please do the review

**Review by ghost — CHANGES_REQUESTED** [review]
@Vrukshali-26 pls make it to 3 to 4 min of content and bit interactive as it seems  a simple animation with background music

**Comment by Vrukshali-26** [comment]
@garvitraj I have made the changes. Do check!

**Review by ghost — APPROVED** [review]

**Pull request merged**
