### PR TITLE
INTRODUCTION TO C PROGRAMMING LANGUAGE

### PR DESCRIPTION
**Pull request by ikavyajain**
<hr>

## Description 📜
I have prepared a documentation on:

INTRODUCTION TO C
- [x] Some facts and features about C Programming Language
- [x] Advantages & Disadvantages
- [x] Syntax and Semantics
- [x] Errors
- [x] C Data Types
- [x] Variable declaration in C
- [x] Special use of sizeof() operator

This is the complete information which can help you to have a kickstart to C Programming Language! 
LEARN, PRACTICE and REPEAT! 💯 
Just have the motivation and grab positive results! 👍 

Issues fixed in Introduction_To_C_Programming
Fixes<2190> 

<hr>

## Type of change 📝
- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊
- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
Hey @ikavyajain 
i have seen your code and it seems like you have copied and pasted the content from the [other source.](https://www.w3schools.in/c-tutorial/intro/)
Please use your own words !
plagiarism is not allowed in the programm.
I hope it will make sense to you !
Kindly close this pr ! -> Update your code then -> reopen your pr !
Go Ahead :)

**Review by vasu-1 — CHANGES_REQUESTED** [review]
**Plagirism is not allowed**

**Comment by ikavyajain** [comment]
I’ll write in le mans language, Sir
Thankyou

**Comment by Saviour1001** [comment]
Closing this PR, update your repo and make a new PR

**Pull request closed without merging**
