### PR TITLE
what is virtual environment #338

### PR DESCRIPTION
**Pull request by nayakaj**
<hr>

## Description 📜

here i added what is virtual environment in python. 
 # 338

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Suvraneel** [comment]
@nayakaj remove all other domains from your comment..
Kindly follow the issue template from next time

**Comment by Suvraneel** [comment]
@nayakaj  Thanks... Preach this to your batchmates as well :)

**Comment by nayakaj** [comment]
@Suvraneel  is it completed or i have to change anything

**Comment by Suvraneel** [comment]
@nayakaj  Please tag a mentor from Python domain

**Comment by httpanand** [comment]
Directory spelling mistake 
image

**Pull request closed without merging**
