### PR TITLE
Added Documentation for Array Implementation of Stacks

### LINKED ISSUE #8485: [Create New Issue]: Array Implementation of Stacks
### Description

I will be providing documentation for Array Implementation Of Stack

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #8485 

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] DSA

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav can you please review my PR? And let me know if changes are needed

**Review by nimisha-yadav — APPROVED** [review]
Great work.

**Comment by VaibhavMalik4187** [comment]
> Great work.

I will be making one more PR today, as soon I finish the documentation of stack implementation using 2 queues

**Comment by nimisha-yadav** [comment]
> > Great work.
> 
> I will be making one more PR today, as soon I finish the documentation of stack implementation using 2 queues

That's great to hear. Thanks for all your contributions.

**Comment by VaibhavMalik4187** [comment]
> > > Great work.
> > 
> > 
> > I will be making one more PR today, as soon I finish the documentation of stack implementation using 2 queues
> 
> That's great to hear. Thanks for all your contributions.

Thanks a lot. Open Source For the Win :), also I got the Arithmetic Operations Using Numbers as Strings issue assigned to me so I request you to not close that issue, I'll make the PR for that issue tomorrow morning

**Comment by nimisha-yadav** [comment]
Sure, take your time :)

**Pull request merged**
