### PR TITLE
Java 6.1: If-else blocks

### LINKED ISSUE #1807: Java 6.1: If-else blocks
### Description

Add audio, documentation, and video regarding the **If - else blocks**.

____

### Location of File to be added

The files should be added inside the `If - else blocks`  folder which is inside the `Control Statements`  folder present in the   `Java`  main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by RahulJaiswal-18**
<hr>

## Description 📜

Added documentation for Java if-else statements
Fixes #1807

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AkMo3** [comment]
@RahulJaiswal-18 In which batch you are in?

**Comment by RahulJaiswal-18** [comment]
@AkMo3 I am in Java batch 5

**Comment by AkMo3** [comment]
Post details of your PR in that batch, it will be reviewed by appropriate mentors, and then we will review it

**Comment by madhushaw1012** [comment]
Madhu Shaw, Java batch-3
I want to do the documentation part.

**Comment by AkMo3** [comment]
@madhushaw1012 Is it is a PR, not a pull request.

**Review by AkMo3 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
