### PR TITLE
DSA 3.1 Linked Lists - Readme

### LINKED ISSUE #5901: DSA 3.1 Linked Lists - Readme
## Description
Contribute to the readme file of 3.1 Linked Lists
**Important: Do not use assign command for this issue.**

## Task
- [ ] Documentation

## Note

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by preestine**
<hr>

## Description 📜

Added a Detailed Readme file explaining Linked Lists and various operations like insertion and deletion.
Fixes #5901

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by preestine** [comment]
Hello! @nimisha-yadav. I have made the changes in the readme file as per your guidelines and updated the PR accordingly.
There is some sort of conflict arising. Please help me with this.
I guess there was a file named README.md already in the folder which was empty. According to your instructions I made another file with the same name and that is why the conflict is arising. Kindly look into it and please let me know at the earliest.Regards.

**Comment by preestine** [comment]
Hello! @nimisha-yadav. I have made the changes in the readme file as per your guidelines and updated the PR accordingly. There is some sort of conflict arising. Please help me with this.

I guess there was a file named README.md already in the folder which was empty. According to your instructions I made another file with the same name and that is why the conflict is arising. Kindly look into it and please let me know what I can do at the earliest. Regards.

**Comment by nimisha-yadav** [comment]
Hey, just update your fork, the issues was resolved.

**Comment by nimisha-yadav** [comment]
@preestine if you're facing any issue now, let us know.

**Comment by preestine** [comment]
@nimisha-yadav , Looks like I made the same mistake again.
I need to make a new PR once again, so kindly close this pull request.
My apologies for causing inconvenience.

**Pull request closed without merging**
