### PR TITLE
ML_7_6_Bayesian_Network_(D)

### LINKED ISSUE #7045: ML 7.6 : Bayesian Network (D)
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Bayesian Network_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Dimensionality_Reduction_&_Neural_Networks` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by srini047**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7045

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Isha307 — CHANGES_REQUESTED** [review]
Follow this: https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md
and please add some explanation also, just code is not enough.

**Review by Isha307 — CHANGES_REQUESTED** [review]
I told you add some description about Bayesian Network and Follow this "https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md" to see the template of documentation.

**Comment by srini047** [comment]
> I told you add some description about Bayesian Network and Follow this "https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md" to see the template of documentation.

Okay👍

**Comment by srini047** [comment]
I have added Theory in the Notebook. Please Re-Review @Isha307

**Comment by abhisheks008** [comment]
Approved from my side @srini047, let @Isha307 do the needful.

**Review by Isha307 — CHANGES_REQUESTED** [review]
Follow this "https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md"

**Comment by srini047** [comment]
> Follow this "https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md"

@Isha307 Can you be more specific on what parts I have to improve the notebook though I have followed the Template?

**Comment by Isha307** [comment]
Add this -
🔴 Type of Content : Documentation

🔴 Domain : Machine Learning

🔴 Module : Name of the module for every week

**Comment by srini047** [comment]
> Add this - 🔴 Type of Content : Documentation
> 
> 🔴 Domain : Machine Learning
> 
> 🔴 Module : Name of the module for every week

I have added it. @Isha307

**Review by Isha307 — APPROVED** [review]

**Pull request merged**
