### PR TITLE
Data Science with Python : Stochastic Gradient Descent Issue #466

### LINKED ISSUE #466: Stochastic Gradient Descent
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about Stochastic Gradient Descent . Tutorial to Stochastic Gradient Descent  and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Dhruv Bajaj](https://github.com/DhruvBajaj01) / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by Sakalya100**
<hr>

## Description 📜

Added the documentation with explanation and coding implementation of Stochastic Gradient Descent
Fixes #466 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by Suvraneel** [comment]
@Sakalya100 remove all other domains from your PR comment (as was directed in official Gwoc pr template)

**Comment by Sakalya100** [comment]
Sorry for the mistake. I will take care from next time @Suvraneel

**Comment by Sakalya100** [comment]
@prathimacode-hub Kindly review my PR.

**Comment by prathimacode-hub** [comment]
This PR is currently under reviewing process.

**Comment by prathimacode-hub** [comment]
Changes to be done 👍

The issue contribution should be under "/Machine Learning/Tutorials/Stochastic Gradient Descent
The project file name should be in snake case : stochastic_gradient_descent.ipynb
In README.md, you can add features, advantages and usage of it.
Add short intro in your .iynb file before you get into code implementation

Kindly work on it. @Sakalya100

**Comment by Sakalya100** [comment]
I have made the required changes @prathimacode-hub . Kindly review my PR

**Comment by prathimacode-hub** [comment]
Also, add up the respective datasets used in "DS Datasets" in "Machine Learning" folder and resources referred in "DS Resources" in "Machine Learning" folder @Sakalya100

**Comment by Sakalya100** [comment]
I have an inbuilt module dataset in Scikit learn. So there is no dataset in csv or xls format to be added. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> I have used an inbuilt module dataset in Scikit learn. So there is no dataset in csv or xls format to be added. @prathimacode-hub

Only change it needs, title your readme file as README.md

**Comment by Sakalya100** [comment]
> > I have used an inbuilt module dataset in Scikit learn. So there is no dataset in csv or xls format to be added. @prathimacode-hub
> 
> Only change it needs, title your readme file as README.md @Sakalya100

Made the change in title of Readme.md as README.md @prathimacode-hub .

**Review by prathimacode-hub — APPROVED** [review]
Congo on your first PR. Good start to your journey. Your PR is approved. 👌✨@Sakalya100

**Comment by Sakalya100** [comment]
Thank You @prathimacode-hub for the guidance throughout. I will be working more for this domain.

**Pull request merged**
