### PR TITLE
4.14 Everything related toOpen Mainframe Project Mentorship Program

### LINKED ISSUE #304: OpenSource : 4.14 Explain everything related to`Open Mainframe Project Mentorship Program`
### Description :

- **Explain everything related to `Open Mainframe Project Mentorship Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by siddhi-244**
<hr>

## Description 📜
4.14 Explain everything related toOpen Mainframe Project Mentorship Program

Fixes #304 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Aryamanz29** [comment]
@siddhi-244 I have redefined the `Branch structure`, So Please `Update your forks` & put your `doc` on the respective `sections`

**Comment by siddhi-244** [comment]
I am unable to pull the changes

**Comment by siddhi-244** [comment]
Please sir see to it

**Comment by Aryamanz29** [comment]
I have updated your fork, Please check once again

**Comment by siddhi-244** [comment]
> I have updated your fork, Please check once again

Ok wait

**Comment by siddhi-244** [comment]
> I have updated your fork, Please check once again

Yep now it's good. So do I have to make a new pr?

**Comment by Aryamanz29** [comment]
> > I have updated your fork, Please check once again
> 
> Yep now it's good. So do I have to make a new pr?

No, I have added my commit `fork updated` , Now its looks good to me

**Review by Aryamanz29 — APPROVED** [review]
LGTM 🎉🎉

**Comment by siddhi-244** [comment]
> LGTM

Thank you so much !

**Pull request merged**
