### PR TITLE
Datas Science with Python : Word Embeddings #386

### LINKED ISSUE #386: Data Science with Python : Word Embeddings
Welcome to 'DSWP' Team, good to see you here

This issue will help readers know about Word Embeddings. Tutorial to Word Embeddings and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : Gauri Bharadwaj / Arya Patel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by soumiksamanta007**
<hr>

## Description 📜

I have explained about word embeddings, how to generate them, and explained about different word embedding models such as word2vec and GloVe, and how to use them using code examples.

Fixes #386

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

Keep project title as "Word Embeddings"
And file name should be in snake case : word_embeddings.ipynb
In README.md, give conclusion at the end. 

Kindly work on it. @soumiksamanta007

**Comment by soumiksamanta007** [comment]
I have made the requested changes.
Please evaluate @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. Your PR is approved. Amazing start and good choice of issue. Well done. 🎉🙌@soumiksamanta007

**Comment by soumiksamanta007** [comment]
Thank You so much for guiding me.

**Pull request merged**
