### PR TITLE
Added documentation for ScanLine Algorithm

### PR DESCRIPTION
**Pull request by VaibhavMalik4187**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #5194 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [X] DSA

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav Can you please review my PR and let me know if I need to make any changes

**Comment by nimisha-yadav** [comment]
@VaibhavMalik4187 this documentation already exists, please [refer here](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/1.1%20Arrays/3.%20Range%20Queries/1.1.3.1_Sum_Product_Range_Queries.md), can you add a description in the PR itself to let us know how is your file different?

**Comment by nimisha-yadav** [comment]
> 
> @nimisha-yadav I came across this issue, I noticed that the previous PR related to this issue was not merged, and the issue was open. So, I decided to contribute to this particular issue since it was open and in the DSA domain we are not allowed to create our own issues, which makes it very hard to find an open issue like this. This is the reason I made this PR because the PR made earlier was not merged.

This issue was opened by a DSA Contributor himself and the PR wasn't merged for the same reason that the content was repetitive. And you can create your own issues provided they are not repetitive and are within week agenda. Presently, you may create issues on Stacks, Queues or Pattern Searching Algorithms.

**Comment by VaibhavMalik4187** [comment]
> > @nimisha-yadav I came across this issue, I noticed that the previous PR related to this issue was not merged, and the issue was open. So, I decided to contribute to this particular issue since it was open and in the DSA domain we are not allowed to create our own issues, which makes it very hard to find an open issue like this. This is the reason I made this PR because the PR made earlier was not merged.
> 
> This issue was opened by a DSA Contributor himself and the PR wasn't merged for the same reason that the content was repetitive. And you can create your own issues provided they are not repetitive and are within week agenda. Presently, you may create issues on Stacks, Queues or Pattern Searching Algorithms.

Okay thanks a lot for letting me know what topics are currently available, so what about this PR? I have invested time working on it, just because it was left open.

**Comment by nimisha-yadav** [comment]
Then you would need to refer to the file above and make some changes in it that improve the documentation or add a new relevant sub-topic in the file. Let us know what change are you making in the PR description.
For Week 4 topics, you may create issues on some standard problems that aren't already there. Refer to the Stacks, Queues or Pattern Searching folder to take a look at the topics that are already there.

**Comment by VaibhavMalik4187** [comment]
> Then you would need to refer to the file above and make some changes in it that improve the documentation or add a new relevant sub-topic in the file. Let us know what change are you making in the PR description. For Week 4 topics, you may create issues on some standard problems that aren't already there. Refer to the Stacks, Queues or Pattern Searching folder to take a look at the topics that are already there.

I have created 2 new issues, (1) Using a stack to reverse a string and (2) Representing a graph using linked lists, are these issues good to go?

**Comment by nimisha-yadav** [comment]
1st is fine. You may modify 2nd since we aren't doing graph issues for this week.

**Pull request closed without merging**
