### PR TITLE
Java

### LINKED ISSUE #2445: Java 13.1: Defining Packages
<hr>

## Description 📜

Add audio, documentation and video regarding the Need of Java.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `Defining Packages`  folder which is inside the `Packages` folder present in the `Java` main folder. If the folder is not present, create the folder with this exact name. The documentation file can be in the .md/.py/.ipynb format. Audio should be in .mp3 format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 Note:
 - You are required to comment with \assign CONTENT_TYPE, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned. 
- Issues will be assigned on the basis of first come first serve.

### PR DESCRIPTION
**Pull request by thatSophisticatedMess18**
<hr>

## Description 📜
I have fixed the issue of defining packages and  I have provided the documentation format of my issue here
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2445 

<hr>

## Type of change 📝

- [x] Vi#deo (Animations, screen-recordings, presentations, and regular explanatory films are all possibilities etc)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by garvitraj** [comment]
@AkMo3 i feel the ### content is good
but audio is little low , pls ave a look at it

**Comment by AkMo3** [comment]
@thatSophisticatedMess18 Please provide me with the link to the video, I am unable to find it currently

**Comment by thatSophisticatedMess18** [comment]
But sir, I just wanted to do the documentation part for this issue.

**Comment by AkMo3** [comment]
Ohk, the pull request description described it as video.

**Comment by thatSophisticatedMess18** [comment]
Sorry for this issue but is there any way now that I can change the type to documentation because as far as I remember I selected the type as documentation.

**Review by AkMo3 — APPROVED** [review]
GTH now!

**Comment by thatSophisticatedMess18** [comment]
Sorry but what do you mean by "GTH", I didn't understand?

**Comment by AkMo3** [comment]
I actually meant GTG i.e Good to Go

**Comment by thatSophisticatedMess18** [comment]
Alright.

**Pull request merged**
