### PR TITLE
Data Science with Python : Data Visualizations using Matplotlib #445

### LINKED ISSUE #445: Data Science with Python : Data Visualizations using Matplotlib
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about Data Visualizations with Matplotlib. Tutorial to Data Visualizations with Matplotlib and how it's applied visually.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualizations

Mentors Assigned : [Shivang Dubey](https://github.com/shivangdubey) / [Nithin](https://github.com/Nithin-Reddy-02)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by KhushiKV**
I would like to request you to kindly go through my codes, and accept my Merge Request if everything is fine. Thanks.

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #445

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

There is no proper PR title. It's already being said that issue title should be your PR title.
Next, your issue files should go under "Datascience_with_Python/Data Analysis and Visualization/Data Visualization using Matplotlib" repo, because yours is not the only file under data analysis and visualizations. Add all the files in this repo.
In .ipynb file, it was an abrupt ending. Instead end the file with final outcomes you had gained from your work.
Add a README.md file where it has complete detailing on the issue topic. 

Kindly work on it. @KhushiKV

**Comment by KhushiKV** [comment]
Sure, I would love to work on these things.. thank you very much for
bringing them to my notice..

Also, I would like you to please check once if there is any folder called
Data Visualisations using Matplotlib inside the Data analysis Domain...
Because I could not find it.

Thanks.

**Comment by KhushiKV** [comment]
hi,
@prathimacode-hub I have made the changes you asked me to do. I have uploaded the correct and edited files in the folder. Hope they are fine now, please tell me if you can see the changes I have made and if it is now alright.

Thank you very much.

**Comment by KhushiKV** [comment]
Hi,

I have updated my files and made all the changes you suggested. From my
end, I have committed the changes in the same pull request. I am not sure
if you received it as I did not get any kind of feedback on it. So, I would
like ot request you to please check if my PR is now correct and it can be
merged.

Thank you very much.

**Comment by KhushiKV** [comment]
@prathimacode-hub have you received the changes I have made on this PR. I have incorporated all the points you asked me to. Please let me know if it is proper now. I am not much used to this usage of Github, so might be I am not able to see if you gave some feedback on it.
Thanks.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👍@KhushiKV

**Pull request merged**
