### PR TITLE
Python 1.1 : Learning version control- What is Git & GitHub?

### PR DESCRIPTION
**Pull request by Pranav120602**
<hr>

## Description 📜

Python 1.1 Documentation and updation of the readme file #46 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [x] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Your PR has conflicts and total of 23 files. @Pranav120602

**Comment by Pranav120602** [comment]
@prathimacode-hub, I have tried to resolve the conflicts. 
https://github.com/girlscript/winter-of-contributing/pull/1037/

**Comment by prathimacode-hub** [comment]
Things are not in viewable format. @Pranav120602

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Create  a project folder of "What_Is_Git_And_Github" repo. In that, add the files related to your project
.docx files are not allowed
Add README.md file where in you provide good introduction and elaboration of Git and Github

Kindly work on it. @Pranav120602

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
