### PR TITLE
Data Science with Python: Decision Tree Algorithm

### LINKED ISSUE #1126: Data Science with Python : Decision Tree Algorithm
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Decision Tree Algorithm. Tutorial to Decision Tree Algorithm and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Shivang Dubey](https://github.com/shivangdubey) / [Kareem Negm](https://github.com/Kareem-negm)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by dev123singh**
<hr>

## Description 📜

In this Documentation, I have explored the Decision Tree Algorithm. we have performed Data preprocessing, Outliers detection, Model training, and Prediction. After the prediction, we have also done an Evaluation of the model.   
Fixes #1126 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by das-ankur** [comment]
I want to work on this. I am from Batch 4 ande serial no.  is 109.

**Comment by manthan89-py** [comment]
Interested in this work via documentation

**Comment by prathimacode-hub** [comment]
This is PR, not an issue. @manthan89-py

**Comment by prathimacode-hub** [comment]
Add your issue number? Check out for the right file name formats. @dev123singh

**Comment by dev123singh** [comment]
I have cleared up those issues, can you please check @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Keep your project folder as "Decision Tree Algorithm"
Add all images in "Images" folder
The .ipynb file should be as decision_tree_algorithm.ipynb
At start of the file give small intro about decision tree algorithm and overall summary at the end.
Also add libraries imported in "requirements.txt" file

Kindly work on it. @dev123singh

**Comment by dev123singh** [comment]
I have cleared up those issues, can you please check @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Very well done and executed. 👏🙌@dev123singh

**Pull request merged**
