### PR TITLE
Frontend With Framework:Angular-Interpolation

### LINKED ISSUE #1896: FRONTEND WITH FRAMEWORK: Angular ->
### Description

(This is a week-2 issue so make sure you include the file in week-2 folder)

- What is Interpolation?
- Why is it used?
- Explain with proper examples, syntax and code.
- Reference:- https://angular.io/guide/interpolation

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week2" directory
3. Tasks would be assigned on First Come First Serve Basis.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Ananyagupta43**
<hr>

## Description 📜
Created a documentation on the topic interpolation.The  documentation contains a brief explanation of the topic data binding and types of data binding.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1896

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by mukeshmjn** [comment]
@Ananyagupta43 can you check the images they are not visible to me

**Comment by Ananyagupta43** [comment]
@mukeshmjn Sir I checked the file using my friend's github Id (she is also a contributor in GWOC) and the images are visible . We have to add them in the assests folder right?

**Comment by mukeshmjn** [comment]
@anandhu720 @the-pro can you please check if images are visible to you if it is I will merge it

**Review by anandhu720 — CHANGES_REQUESTED** [review]
change image location to assets folder inside your perticular domain also look week

**Comment by Ananyagupta43** [comment]
@mukeshmjn Sir please review it now.I changed the location of images.

**Review by mukeshmjn — APPROVED** [review]

**Pull request merged**
