### PR TITLE
Added inherit.md

### LINKED ISSUE #5857: Documentation on multilevel inheritance
### Description

Add some info about multilevel inheritance

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by prak895**
<hr>

## Description 📜

Added documentation of multilevel inheritance
Fixes #5857 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
image
search by issue number

**Comment by prak895** [comment]
this is mine the ss u send

**Comment by vasu-1** [comment]
can you elaborate, what is your problem ! i am not getting your point !

**Comment by prak895** [comment]
The ss u send in that its clearly showing that 5857 is mine issue

**Comment by prak895** [comment]
nd there are many contributors so work in a same issue is any problem???

**Comment by vasu-1** [comment]
> same

for c/cpp 1 contributor -> 1 issue

**Comment by vasu-1** [comment]
You can create another issue !

**Comment by vasu-1** [comment]
only one person can work on the issue !

**Comment by vasu-1** [comment]
> Nice Documentation but we can't merge this PR because someone has already worked on this . see this folder `/C_CPP/OOPs in C++/Inheritance and its types or Function overriding/`
> 
> Kindly close this Pr and respective Issue. you can work on audio or video part of this topic if you want ! Happy contributing !

do this

**Comment by vasu-1** [comment]
> so which issue is left this happen with me second time. Can u tell plz?

Search in  C/CPP  folder. in girlscript official repo

**Comment by vasu-1** [comment]
close this @Suvraneel

**Pull request closed without merging**
