### PR TITLE
PYTHON File I/O #579

### PR DESCRIPTION
**Pull request by Anjali813**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Anjali813** [comment]
I/O SYSTEM:

Feature of I/O system:-

Communicate with multiple sources and destinations.
Input/output varied entities.
Communicate in multiple ways.
Deal with underlying file system.
Types of data used for I/O:

Text
Binary
Sequence of operations in File I/O:

STEP 1: Open a file.

STEP 2: Read/Write data to file.

STEP 3: Close the file.

OPENING FILE FOR READING--file=open(file_name,'r')

OPENING FILE FOR WRITING--file=open(file_name,'w')

CLOSING THE FILE--file.close()

NOTE:- Using with keyword while opening the file the closes itself after its work is done Ex:

  with open(file_name,'r') as file:

       content=file.read()

Write operation methods:

Writing strings:

 *   file.write(data_you_want_to_write)
 *   file.writelines(more_than_one_data_you_want_to_write)
Writing non-strings (First we need to convert them in string):

 *   file.write(str(object_name))
Read operation methods:

      *   file.read() -- reads all contents of the file and returns as string
      *   file.read(n) -- reads n characters and return as strings
      *   file.readline() -- reads a line and return as strings
      *   file.readlines() -- reads all lines and return as strings

Ways to read a file line by line till end:

Method 1:
In [ ]:
while 1:
  content=file.readline()
  if content=='':                                                               # when end of file is reached
    break
  else:
    continue
print(content,end="")
Method 2:
In [ ]:
for content in file:
  print(content,end="")
File Opening Modes:

'r'--opens file for reading in text mode
'rb'--opens file for reading in text mode
'w'--opens file for writing in text mode
'wb'--opens file for writing in text mode
'a'--opens file for appending in text mode
'ab'--opens file for appending in text mode
'r+' , 'rb+'--opens file for reading and writing
'w+' , 'wb+'--opens file for reading and writing
'a+' , 'ab+'--opens file for appending and reading
Moving within a file:

file.read(1)--reades file character by character
file.seek(position,reference)--moving to any postion before read/write operation

 --reference takes value 0,1,2 which represents starting,present and end of file respectively
 --position represents position at which you want start read/write operation
In [ ]:

Serialisation

Serialisation:Conversion of Python data into appropiate JSON types before writing data to a file using json module is called Serialisation. dump() is used for serialisation and writes the data to the file.

In [ ]:
json.dump(python_data,file)
Dserialisation

Deserialisation:Conversion of JSON types into appropiate Python data using json module is called Deserialisation. load() is used for reading the file and then deserialising thereafter returning the converted data.

NOTE:-Deserialising a tuple , returns a list.

In [ ]:
converted_data=json.load(f)

**Comment by Anjali813** [comment]
[](url)

**Comment by Anjali813** [comment]
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Python - Files I/O.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "f1RdizChnGj6"
      },
      "source": [
        "                                        I/O SYSTEM:\n",
        "\n",
        "Feature of I/O system:-\n",
        " \n",
        "* Communicate with multiple sources and destinations.\n",
        "* Input/output varied entities.\n",
        "* Communicate in multiple ways.\n",
        "* Deal with underlying file system.\n",
        "\n",
        "Types of data used for I/O:\n",
        "\n",
        "* Text \n",
        "* Binary\n",
        "\n",
        "Sequence of operations in File I/O:\n",
        "\n",
        "STEP 1: Open a file.\n",
        "\n",
        "STEP 2: Read/Write data to file.\n",
        "\n",
        "STEP 3: Close the file.\n",
        "\n",
        "**OPENING FILE FOR READING**--file=open(file_name,'r')\n",
        "\n",
        "**OPENING FILE FOR WRITING**--file=open(file_name,'w')\n",
        "\n",
        "**CLOSING THE FILE**--file.close()\n",
        "\n",
        "**NOTE:-** *Using with keyword while opening the file the closes itself after its work is done Ex:*\n",
        " \n",
        "      with open(file_name,'r') as file:\n",
        "\n",
        "           content=file.read()\n",
        "\n",
        "**Write operation methods:**\n",
        "\n",
        "\n",
        "1.   Writing strings:\n",
        "\n",
        "          *   file.write(data_you_want_to_write)\n",
        "          *   file.writelines(more_than_one_data_you_want_to_write)\n",
        "\n",
        "\n",
        "2.   Writing non-strings (First we need to convert them in string):\n",
        "\n",
        "          *   file.write(str(object_name))\n",
        "\n",
        "**Read operation methods:**\n",
        "\n",
        "          *   file.read() -- reads all contents of the file and returns as string\n",
        "          *   file.read(n) -- reads n characters and return as strings\n",
        "          *   file.readline() -- reads a line and return as strings\n",
        "          *   file.readlines() -- reads all lines and return as strings\n",
        "\n",
        "**Ways to read a file line by line till end:**\n",
        "* Method 1:\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "-8ZiRjqcMLzc"
      },
      "source": [
        "while 1:\n",
        "  content=file.readline()\n",
        "  if content=='':                                                               # when end of file is reached\n",
        "    break\n",
        "  else:\n",
        "    continue\n",
        "print(content,end=\"\")"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "MC1SOfOuNqlH"
      },
      "source": [
        "  * Method 2:"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "OVdtqNdcNzut"
      },
      "source": [
        "for content in file:\n",
        "  print(content,end=\"\")"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "LVxTYM4GOagv"
      },
      "source": [
        "**File Opening Modes:**\n",
        "\n",
        "*  'r'--opens file for reading in text mode\n",
        "*  'rb'--opens file for reading in text mode\n",
        "*  'w'--opens file for writing in text mode\n",
        "*  'wb'--opens file for writing in text mode\n",
        "*  'a'--opens file for appending in text mode\n",
        "*  'ab'--opens file for appending in text mode\n",
        "*  'r+' , 'rb+'--opens file for reading and writing\n",
        "*  'w+' , 'wb+'--opens file for reading and writing\n",
        "*  'a+' , 'ab+'--opens file for appending and reading\n",
        "\n",
        "\n",
        "**Moving within a file:**\n",
        "\n",
        "*   file.read(1)--reades file character by character\n",
        "*   file.seek(position,reference)--moving to any postion before read/write operation\n",
        "      \n",
        "         --reference takes value 0,1,2 which represents starting,present and end of file respectively\n",
        "         --position represents position at which you want start read/write operation\n",
        "\n",
        " \n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "NMLHL25zeI2q"
      },
      "source": [
        ""
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "SVp2gdlhd82l"
      },
      "source": [
        "**Serialisation**\n",
        "\n",
        "*Serialisation:Conversion of Python data into appropiate JSON types before writing data to a file using json module is called Serialisation. dump() is used for serialisation and writes the data to the file.* "
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "jI9KVS2-fQRy"
      },
      "source": [
        "json.dump(python_data,file)"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "dkkiMTMjfbxt"
      },
      "source": [
        "**Dserialisation**\n",
        "\n",
        "*Deserialisation:Conversion of JSON types into appropiate Python data using json module is called Deserialisation. load() is used for reading the file and then deserialising thereafter returning the converted data.* \n",
        "\n",
        "**NOTE:-**Deserialising a tuple , returns a list."
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "zzfUqI0tghmG"
      },
      "source": [
        "converted_data=json.load(f)"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
