### PR TITLE
Added a documentation on Counting and Radix sort

### LINKED ISSUE #4336: Documentation on Counting Sort and Radix Sort in C
### Description

I would like to add a documentation on the Linear Sort Algorithms which are Counting sort and Radix sort in C 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by rakeshbodavula**
…a markdown file

<hr>

## Description 📜 Explanation and C program for Counting and Radix sort 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #4336  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Kindly add your md file link in the readme of this subdirectory..
- no need to create another pr.
- just edit that readme and do commit and push it.

Hope it will make sense to you

**Comment by rakeshbodavula** [comment]
> Kindly add your md file link in the readme of this subdirectory..
> 
> * no need to create another pr.
> * just edit that readme and do commit and push it.
> 
> Hope it will make sense to you

Done added a link in readme can you please check it

**Comment by vasu-1** [comment]
Good work 👍.

Good to go for merge @Suvraneel

**Comment by rakeshbodavula** [comment]
> Good work 👍.
> 
> Good to go for merge @Suvraneel

@Suvraneel and @vasu-1 could you please review my work and merge it please

**Comment by vasu-1** [comment]
> > Good work 👍.
> > Good to go for merge @Suvraneel
> 
> @Suvraneel and @vasu-1 could you please review my work and merge it please

Be patient
Your pr will be merged soon.. 👍⚡

**Comment by rakeshbodavula** [comment]
> > > Good work 👍.
> > > Good to go for merge @Suvraneel
> > 
> > 
> > @Suvraneel and @vasu-1 could you please review my work and merge it please
> 
> Be patient Your pr will be merged soon.. 👍⚡

yeah thank you

**Comment by rakeshbodavula** [comment]
> Kindly make the algos in 2 different files

yeah i did that but i am unable to push the changes so i forked the repository again and made a new pull request please have a look at it and merge it fast so that it wont get ignored new pr #4810

**Pull request closed without merging**
