### PR TITLE
ML 7.9: Hidden Markov Model (V)

### LINKED ISSUE #7011: ML 7.9: Hidden Markov Model (V)
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Hidden Markov Model_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Bayesian_ML_&_Ensemble_based_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make :
    - [ ] Video

*************************************************************
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by kishlayaug15**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Video representation and brief introduction of  Markov Chain and Hidden Markov Model with examples & Codes in Colab.

Fixes #7011 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
File name should be, `ML_7_9_Hidden Markov Model_(V).md`

@kishlayaug15 do the needful changes.

**Comment by kishlayaug15** [comment]
@abhisheks008 Done!

**Comment by abhisheks008** [comment]
I can't open your video link, it has no access to other users. Change it @kishlayaug15

**Comment by kishlayaug15** [comment]
Yes, changed the access to drive settings.

**Comment by abhisheks008** [comment]
Where is your voice in the video through which you are explaining the topic? @kishlayaug15

**Comment by kishlayaug15** [comment]
I made it without voice @abhisheks008.

**Comment by kishlayaug15** [comment]
Give me few hours I'll update it @abhisheks008

**Comment by abhisheks008** [comment]
@kishlayaug15 look, when you are making a video contribution it's obvious that the video must contain the audio which will make understand the user, who are watching your video to get into the topic. Think about that and re-upload the same!

**Comment by kishlayaug15** [comment]
Yes I am currently working on it. Will upload as soon as it is done

**Comment by kishlayaug15** [comment]
@abhisheks008  Please review my work.

**Pull request merged**
