### PR TITLE
[JS] Topic: Functions

### LINKED ISSUE #247: JS: Functions
# Functions
Functions in JavaScript

## Directory
```
Topics/5.Syntax/6.Functions
```

## Description
- What is scope?
- What is the lifetime of JavaScript variables?
- Basic function syntax.
- What are parameters in functions?
- Types of functions.
- Why use functions?

### PR DESCRIPTION
**Pull request by sushovanb02**
<hr>

## Description 📜
Created a document on JavaScript functions. 
Fixes #247  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by sushovanb02** [comment]
@paramsiddharth sir, please review this

**Comment by paramsiddharth** [comment]
@sushovanb02 Looks really nice, Sushovan! Please preserve the document, we might have to merge Siddhi's PR for this issue, but the information you added in this document will be needed. I'll ask you to do another PR, updating the README that Siddhi created, and add your own data to it and name to the contributors' list.

**Comment by sushovanb02** [comment]
ok so sir my query is that if this PR doen't get merged will this be counted in contribution? @paramsiddharth sir

**Comment by paramsiddharth** [comment]
> ok so sir my query is that if this PR doen't get merged will this be counted in contribution? @paramsiddharth sir

Of course it will be! If this PR of yours doesn't get merged and your contribution looks good, I'll ask you to make another PR updating the existing contribution.

**Comment by paramsiddharth** [comment]
@sushovanb02 Please pull the updates to the `Javascript` branches, add more information to the documentation-based contribution, and create a new PR with the title prefixed with `[JS] Other:`.

**Comment by sushovanb02** [comment]
OK @paramsiddharth sir noted but add more information means that I shall write more about functions topic?

**Comment by paramsiddharth** [comment]
> OK @paramsiddharth sir noted but add more information means that I shall write more about functions topic?

Yes! It means you can add more content, including that which was in your PR but not in the one that was merged.

**Pull request closed without merging**
