### PR TITLE
ML 2.12 : Implement Logistic Regression without using any standard ML library like scikit-learn or more. (D)

### PR DESCRIPTION
**Pull request by divya-chhoriya**
<hr>

## I have implemented logistic regression without using any standard ML library on the Iris dataset.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # 2801

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
good job @divya-chhoriya! will you please add references? means you can attach link as well

**Comment by divya-chhoriya** [comment]
> good job @divya-chhoriya! will you please add references? means you can attach link as well

Sure

**Comment by Randrita** [comment]
@divya-chhoriya images are taken from that sites only na?

**Comment by divya-chhoriya** [comment]
> @divya-chhoriya images are taken from that sites only na?

Yes

**Review by Randrita — APPROVED** [review]
@raina-akshay looks good to me! Can be merged if it looks good to you too!

**Review by Isha307 — COMMENTED** [review]
@divya-chhoriya Everything is fine, just change the PR TITLE to this "ML 2.12 : Implement Logistic Regression without using any standard ML library like scikit-learn or more. (D)"

**Comment by divya-chhoriya** [comment]
> @divya-chhoriya Everything is fine, just change the PR TITLE to this "ML 2.12 : Implement Logistic Regression without using any standard ML library like scikit-learn or more. (D)"

Done

**Comment by abhisheks008** [comment]
@Isha307 Please merge it 💯

**Pull request merged**
