### PR TITLE
Data Science with Python :  Bayesian Regression

### PR DESCRIPTION
**Pull request by uttarabahad**
<hr>

## Description 📜

Explained about Regression briefly and then Bayesian Regression in detail with the mathematical formula, and a sample implementation code. Covered the advantages as well.
Fixes : #431

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by uttarabahad** [comment]
@aishanii @Yash621 Please review my PR. Thank you!

**Comment by aishanii** [comment]
@prathimacode-hub  please add me as assignee

**Comment by uttarabahad** [comment]
@prathimacode-hub Ma'am please review

**Comment by uttarabahad** [comment]
@aishanii Can You please provide an update?

**Review by Yash621 — CHANGES_REQUESTED** [review]
The code sample is pretty much good ,but in the readme the mathematical formula is not clear ,and if you are providing the advantages for bayesian regression ,also try to provide the disadvantages

**Comment by uttarabahad** [comment]
@Yash621 Updated the content.

**Review by Yash621 — CHANGES_REQUESTED** [review]
posterior formula is still not visible

**Comment by uttarabahad** [comment]
Is it visible now?

**Review by Yash621 — APPROVED** [review]
ya it's fine now ,Good work !!!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Bayesian Regression files should be under "/Datascience_with_Python/Machine Learning/Algorithms/Bayesian Regression" repo
The file names should be snake case like bayesian_regression.ipynb
In README.md, add purpose, workflow explanation, types of bayesian regression, visualization, usage, final outcomes and conclusion 
And in .ipynb file first introduce what the topic is instead of directly going into code. then take a sample topic to demonstrate this algorithm completely. It can be done more elaborately.

Kindly work on it. @uttarabahad

**Comment by prathimacode-hub** [comment]
Why have you closed the issue? @uttarabahad

**Comment by uttarabahad** [comment]
> Why have you closed PR? @uttarabahad

@prathimacode-hub I was a bit unsure about changing the file location, So I created a new pull request after doing the changes.
https://github.com/girlscript/winter-of-contributing/pull/3124

**Pull request closed without merging**
