### PR TITLE
Create 3.2.22_Graph_Coloring_Problem_Audio.md

### PR DESCRIPTION
**Pull request by afreenabegum**
Hi mam @nimisha-yadav 
Problem 3.2.22_Graph Coloring Problem Audio
issue #5926
I am adding audio file of Graph coloring problem with some examples and code.
Hope I have made required changes.
Kindly please review my PR mam.

Afreena begum
DSA Batch-1
Thank you.

### CODE REVIEW

**Review by nimisha-yadav — COMMENTED** [review]
@afreenabegum in your forked branch edit this file and add description of topic in md file itself. The changes will automatically get updated here in this PR. [See this file](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/1.2%20Analysis%20of%20Algorithms/5.%20Approximation%20Algorithms/DSA_1.2.5.1_Approximation_Algorithm_Video.md) as a reference, how this contributor described the topic briefly and then attached the audio/video file.

**Review by afreenabegum — COMMENTED** [review]
Hi mam @nimisha-yadav 
I have made require changes on Graph Coloring problem Audio file
Kindly please review and let me know if any changes required.
Hope, I have made required changes.
Thank you.

**Review by nimisha-yadav — APPROVED** [review]
LGTM!

**Comment by afreenabegum** [comment]
Thank you mam : )
 @nimisha-yadav

**Comment by afreenabegum** [comment]
Mam @nimisha-yadav a small help!!
Where  can  I check my contribution on my github profile.
I worked on 2 PR's got merged. Where can I find them on my profile.

**Comment by nimisha-yadav** [comment]
> Mam @nimisha-yadav a small help!! 1.Where can I check my contribution on my github profile. I worked on 2 PR's got merged. Where can I find them on my profile.
> 
> 2.Pull request successfully merged and closed You’re all set — the afreenabegum:DSA branch can be safely deleted. If you wish, you can also delete this fork of girlscript/winter-of-contributing in the settings.
> 
> And can I delete this mam?

Hey, your profile gets automatically updated. It shows the PR opened, merged, closed, reviewed in the contribution area and graph. For more detailed look, click on the repo for which you wish to see your contributions. 

And yes, you can delete that if you no longer wish to work on that project or repository.

**Comment by afreenabegum** [comment]
ok mam @nimisha-yadav 
Thank you.

**Pull request merged**
