### PR TITLE
C_CPP: Text Files and Binary Files

### LINKED ISSUE #3578: C_CPP: Text Files and Binary Files
### Description

Description

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by 124015001**
<hr>

## Description 📜

Explained about types of data with program as an example. Also, explained about Text file and binary file with examples.
Fixes #3578

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Content is good and informative as well.
But do add some more detailing and few more points.

**Comment by 124015001** [comment]
@deeqakkk Hi. I have planned to add the content in the next file which will be better to understand. I have already created an issue for it.

**Comment by 124015001** [comment]
@deeqakkk @vasu-1 Can you check please?

**Comment by Saviour1001** [comment]
Looking forward to get more PRs from you on this topic @124015001

**Pull request merged**
