### PR TITLE
Created 1.1.3.8_Searching_An_Element.md

### LINKED ISSUE #1908: DSA 1.1.3.8 Arrays: Range Queries (for searching an element)
### Description

Given an array of size N and Q queries in the form of L R X. For each query give the output Yes or No if X present in between the indices L and R. 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by jaissumi1402**
<hr>

## Description 📜

Fixes #1908

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by jaissumi1402** [comment]
@nimisha-yadav I have fixed the issue #1908 please review my PR and merge it.

**Comment by nimisha-yadav** [comment]
Please review @sneha-nitdgp @harshsri28

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Discuss Time complexity and space complexity

**Review by harshsri28 — APPROVED** [review]
LGTM

**Comment by jaissumi1402** [comment]
@nimisha-yadav do I have to change anything in my pr?

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Discuss space complexity

**Comment by jaissumi1402** [comment]
@sneha-nitdgp actually I have some confusion in space complexity that's why i didn't discuss that is it okay?

**Comment by sneha-nitdgp** [comment]
@jaissumi1402 You can resolve your doubts with the mentors over Discord.

**Comment by Muskan-creator** [comment]
Please don't just copy paste from popular websites, try to use images, explain the approach in different way  ,you can add reference of website ,firsty provide a naive approach and then try to add efficient approach.

**Review by get-satyam — COMMENTED** [review]
@jaissumi1402 Please explain the algorithm more clearly. You can use GFG for reference but can not copy-paste their content. Also, include the space-time complexity of your program. Mention your references as well in the end.

**Review by get-satyam — APPROVED** [review]

**Comment by jaissumi1402** [comment]
@goelesha @nimisha-yadav mam now is it okay? can you merge it?

**Review by nimisha-yadav — APPROVED** [review]
Looks good to me. Congrats on getting your PR merged!

**Comment by jaissumi1402** [comment]
@nimisha-yadav @get-satyam @harshsri28 @Muskan-creator @sneha-nitdgp Thankyou so much for guidance :)

**Pull request merged**
