### PR TITLE
Issue #3256-

### LINKED ISSUE #3256: DSA 1.2.2.2 Algorithms: Lower and Upper bounds - Audio/Video
## Description
Discuss Asymptotic Notations. What are Lower and Upper bounds? Describe their usages.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by shahhilag**
<hr>

## Description 📜

I have covered the following topics in detail in the video file:
<ol>
<li>What are Asymptotic Notations</li>
<li>What is the use of asymptotic notations</li>
<li>A world without Asymptotic Notations</li>
<li>Major Asymptotic Notations</li>
<li>Big O(Upper Bound)</li>
<li>Omega(Lower Bound)</li>
<li>Theta Notation</li>
</ol>

Fixes #3256 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by shahhilag** [comment]
@nimisha-yadav mam please review my pull request whenever you are free

**Comment by shahhilag** [comment]
Thankyou very much mam!

**Review by nimisha-yadav — CHANGES_REQUESTED** [review]
hi @shahhilag, you do not need to change the file names, that problem has been resolved, just update your fork. Also, create one md file. Upload your files as listed/unlisted Youtube video or drive links and insert the link in that md file.

**Comment by shahhilag** [comment]
> Thankyou very much mam!

Sure @nimisha-yadav  mam.But mam actually I am unable to clone the code there is some error message appearing with the filename.Thus I had to change it.
I have made the changes and created a .md file

**Comment by nimisha-yadav** [comment]
> > Thankyou very much mam!
> 
> Sure @nimisha-yadav mam.But mam actually I am unable to clone the code there is some error message appearing with the filename.Thus I had to change it. I have made the changes and created a .md file

Yeah that's why I said to update the fork, we have already renamed those files as per the guidelines. If you still face issue while cloning, let me know here

**Comment by shahhilag** [comment]
> > > Thankyou very much mam!
> > 
> > 
> > Sure @nimisha-yadav mam.But mam actually I am unable to clone the code there is some error message appearing with the filename.Thus I had to change it. I have made the changes and created a .md file
> 
> Yeah that's why I said to update the fork, we have already renamed those files as per the guidelines. If you still face issue while cloning, let me know here

Mam I gave pulled the changes and pushed again

**Comment by shahhilag** [comment]
> > > > Thankyou very much mam!
> > > 
> > > 
> > > Sure @nimisha-yadav mam.But mam actually I am unable to clone the code there is some error message appearing with the filename.Thus I had to change it. I have made the changes and created a .md file
> > 
> > 
> > Yeah that's why I said to update the fork, we have already renamed those files as per the guidelines. If you still face issue while cloning, let me know here
> 
> @nimisha-yadav Mam I gave pulled the changes and pushed again.But the commits are not getting erased from the pull request

Should I fork the repo again and add my stuff and again create a PR? @nimisha-yadav

**Comment by nimisha-yadav** [comment]
> Should I fork the repo again and add my stuff and again create a PR? @nimisha-yadav

Yes, this sounds good.

**Comment by shahhilag** [comment]
I am again creating a PR mam @nimisha-yadav

**Pull request closed without merging**
