### PR TITLE
DSA 1.2.5.2 Approximation Algorithms Example Problems - Audio

### LINKED ISSUE #1780: DSA 1.2.4.1 NP-Complete Problem - Audio
## Description
What do you understand by NP-Completeness? Discuss in detail, what are NP, P, NP-complete and NP-Hard problems?

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### LINKED ISSUE #1789: DSA 1.2.5.2 Approximation Algorithms Example Problems - Audio
## Description
Briefly explain the examples of approximation algorithms.
Vertex cover problem, Travelling salesman problem, Set covering problem.

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by Shruti-Subu**
<hr>

## Description 📜

Vertex cover, set covering and travelling salesman problems are NP HARD problems to which no polynomial time solution exits we have discussed approximate algorithm for these problems in the audio clip.
Fixes #1789 
Fixes #1780 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Shruti-Subu** [comment]
@harshsri28 please review it . I have added the changes you suggested.

**Review by harshsri28 — APPROVED** [review]
LGTM

**Review by harshsri28 — APPROVED** [review]

**Comment by Shruti-Subu** [comment]
@harshsri28 do i need to do anything else in this task ? Or it will be merged?

**Comment by harshsri28** [comment]
Just change the Branch from main  to DSA branch

**Comment by Shruti-Subu** [comment]
@harshsri28  how to chnage branch ? have i to make another pull request with branch DSA to merge and close this?

**Comment by harshsri28** [comment]
Add your file into DSA branch

**Comment by Shruti-Subu** [comment]
@harshsri28  made another pr after adding files to DSA branch . Should i close this pr?

**Comment by harshsri28** [comment]
> @harshsri28 made another pr after adding files to DSA branch . Should i close this pr?

just change branch , rest is good

**Comment by Shruti-Subu** [comment]
@harshsri28   i dont know i have made some mistake while making this pr request . its showing way more changes to merge,
i have made another pr with correct branch will u pls approve that ? i am unable to fix this pr.

**Comment by harshsri28** [comment]
> @harshsri28 i dont know i have made some mistake while making this pr request . its showing way more changes to merge, i have made another pr with correct branch will u pls approve that ? i am unable to fix this pr.

tag @nimisha-yadav  on that pr for merge

**Comment by Shruti-Subu** [comment]
OK

**Pull request closed without merging**
