### PR TITLE
Added documentation and code for HTML Lists.

### LINKED ISSUE #221: Front end: HTML Lists
I would like to work on this issue and add documentation to it. Please assign it to me.
image

### PR DESCRIPTION
**Pull request by KartikChinda**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #221 
Added code and documentation for lists in HTML. Contains essential info about the unordered, ordered and definition lists in HTML and their various attributes. 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by KartikChinda** [comment]
@praveenscience sir please review my PR. Thanks!

**Comment by KartikChinda** [comment]
@code-reaper08 @ghulamyazdani sirs, please review my PR. Thanks a lot!

**Comment by KartikChinda** [comment]
@moulikagrawal sir please review my PR. Thanks!

**Review by moulikagrawal — CHANGES_REQUESTED** [review]
Add your content to the existing file

**Comment by KartikChinda** [comment]
@moulikagrawal please check, some content has been updated for the existing file

**Comment by KartikChinda** [comment]
@moulikagrawal requested changes have been made, please check. Thanks!

**Review by moulikagrawal — CHANGES_REQUESTED** [review]
ok

**Review by moulikagrawal — APPROVED** [review]

**Pull request merged**
