### PR TITLE
Python: OOP-Inheritance #567

### LINKED ISSUE #567: Python: OOP-Inheritance
### Description :
What is `Inheritance` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by surjyaneeh**
<hr>

## Description 📜

Fixes #567

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by surjyaneeh** [comment]
@kumarankm , @adityabisoi Please review my PR.

**Review by kumarankm — CHANGES_REQUESTED** [review]
Add some content on the readme, please!

Because it's audio contribution right so they need a visual way of what you saying!

The remaining thing is good and good explanation in audio 👍🏻

**Comment by surjyaneeh** [comment]
> Add some content on the readme, please!
> 
> Because it's audio contribution right so they need a visual way of what you saying!
> 
> The remaining thing is good and good explanation in audio 👍🏻

@kumarankm I have made changes.

**Review by kumarankm — APPROVED** [review]
Now looks fine, good job 👍🏻 
You can merge this pr @adityabisoi

**Pull request merged**
