### PR TITLE
 Vectors in C++.md

### PR DESCRIPTION
**Pull request by Akriti-Choudhary**
<hr>

## Description 📜

Standard Template Library is a collection of classes that allows the programmers to use them without having to write and debug the classes.
Components of STL are - templated containers, algorithms, and iterators.

The documentation provides details about the Vector container and the functions supported by it.

Fixes # <issue_number_here> #2076 

<hr>

## Type of change 📝

- [ x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ x] C/CPP

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented on my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ChetasShree** [comment]
Hey @Akriti-Choudhary , pls check ur readme file,its showing in raw format ,

**Comment by Akriti-Choudhary** [comment]
> Hey @Akriti-Choudhary , pls check ur readme file,its showing in raw format 
I have done the changes, can you please confirm them and let me know what more  modifications I need to do

**Comment by ChetasShree** [comment]
@Akriti-Choudhary  name ur file with the extension of .md

**Comment by Akriti-Choudhary** [comment]
> @Akriti-Choudhary name ur file with the extension of .md

image
I have changed that already I don't know  why the change is not visible

**Comment by ChetasShree** [comment]
@Akriti-Choudhary not like this 🤦‍♀️, the way u save a cpp file as .cpp ,like wise ,when u create a .md file ,u save it as .md

**Comment by Akriti-Choudhary** [comment]
> @Akriti-Choudhary not like this 🤦‍♀️, the way u save a cpp file as .cpp ,like wise ,when u create a .md file ,u save it as .md
Ohh okay, I have done the changes.
please check once. Thank you

**Comment by ChetasShree** [comment]
@Akriti-Choudhary amazing work !!!
@Suvraneel @Saviour1001 pls review this pr and merge it :)
Thank you

**Comment by Akriti-Choudhary** [comment]
@ChetasShree Thankyou.
@Suvraneel @Saviour1001 pls merge this pull request. Thank you.

**Comment by vasu-1** [comment]
Merge this  @Suvraneel

**Comment by Suvraneel** [comment]
@Akriti-Choudhary  Awesome ❤️ :octocat:

**Comment by Akriti-Choudhary** [comment]
@Suvraneel  Thankyou :)

**Pull request merged**
