### PR TITLE
Added documentaion to Binary Strings problem

### PR DESCRIPTION
**Pull request by msbuddhu**
<hr>

## Explanation to the Binary Strings problem 📜
The idea is to generate all possible subsequences of the string and convert each subsequence to its equivalent decimal form. Print the largest prime number obtained from these subsequences. 

Fixes # 4364 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊
- [X] DSA

<hr>

## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by msbuddhu** [comment]
Hey @nimisha-yadav,
I have created a PR. Please have a look.

Shabi Kaushal (DSA Batch 10)

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Submit in .md file

**Comment by msbuddhu** [comment]
> Submit in .md file

Ok let me change it.

**Comment by msbuddhu** [comment]
> > Submit in .md file
> 
> Ok let me change it.

@nimisha-yadav Have a look now. Do I need to do anything else ?

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Use images for explaining

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Copied from GFG

**Comment by msbuddhu** [comment]
> Copied from GFG

Inspired by GFG as I have studies the whole DSA from GFG itself. What I am supposed to do now?

**Pull request closed without merging**
