### PR TITLE
DSA 2.2.4 Bisection method (Binary Search)

### LINKED ISSUE #3173: DSA 2.2.4 Bisection Method ( Binary search)
## Description
Give an introduction and explain the working of bisection method for root finding.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by debjitpal5040**
<hr>

## Description 📜
Added an introduction and explained the working of bisection method for root finding.
Fixes #3173

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
@pjdurden @Subhradeep10

**Comment by debjitpal5040** [comment]
Please review and merge this issue

**Review by Subhradeep10 — APPROVED** [review]
Perfect @nimisha-yadav

**Comment by debjitpal5040** [comment]
Please merge my PR.

**Comment by pjdurden** [comment]
Your pr has been merged @debjitpal5040

**Pull request merged**
