### PR TITLE
Opensource 2.1 Practice Git and GitHub fundamentals

### PR DESCRIPTION
**Pull request by developer-metalhead**
<hr>

## Description 📜

Issue #26 

Motivation: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
Motivation: https://blog.devmountain.com/git-vs-github-whats-the-difference/

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source
<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by Aryamanz29** [comment]
@developer-metalhead  Amazing Work 🎉🎉🎉 
**One Suggestion -** 
- Please `squash` (merge all commits into one single commit) your commits, Since you've made 7 commits, We want clean commit history :)
- `Commit message` should be `"Opensource : 2.1 Practice Git and Github fundamentals.md"`

Once you've done with the mention changes, I'll merge your PR, Once again thanks for working on this 🙌
Looking forward to more contributions from you 😉

**Comment by Aryamanz29** [comment]
@developer-metalhead  For squashing commit refer : 
https://youtu.be/gXCkYkLQ3To
https://www.git-tower.com/learn/git/faq/git-squash/

**Review by Aryamanz29 — APPROVED** [review]
Amazing Work 🎉🎉

**Comment by Aryamanz29** [comment]
@developer-metalhead  Why you close this  PR? Any reasons 🤔

**Comment by developer-metalhead** [comment]
I accidentally opened a new one with the changes that you suggested

**Comment by Aryamanz29** [comment]
> I accidentally opened a new one with the changes that you suggested

Ok , Go ahead ✌️

**Comment by developer-metalhead** [comment]
@Aryamanz29 already done! Check it out pls. Here's the link: https://github.com/girlscript/winter-of-contributing/pull/162/commits

**Pull request closed without merging**
