### PR TITLE
Length of longest substring 

### LINKED ISSUE #1283: Competitive Programming : : Longest Substring Without repeating characters (Documentation)
<hr>

## Description 📜

I wanted to provide Longest Substring Without Repeating Characters(Sliding Window) code

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [x] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

### PR DESCRIPTION
**Pull request by ksheetiz**
<hr>

## Description 📜

In this code the length of longest substring is found out using hashing(unordered maps) and solved in TC of O(n) #1283  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nayakaj** [comment]
@ksheetiz  even i have the same problem why iit is saying merging is blocked

**Comment by ksheetiz** [comment]
@nayakaj  Actually our job was till here only we just needed to create an issue now its up to the domain head or mentor to approve the merge request

**Review by ravireddy07 — COMMENTED** [review]
You're pointing this PR to `main` branch, You should point it to `Competitive_Programming `branch. This PR can't be merged to main.

Please close this and make a new proper PR.

**Comment by tamalbag117** [comment]
\assign Document

**Pull request closed without merging**
