### PR TITLE
Python: dict & set #551

### PR DESCRIPTION
**Pull request by nayakaj**
<hr>

## Description 📜

Python: dict & set #551

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [# ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [# ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nayakaj** [comment]
@ankurg132  plz check now
let me know is that ok or i need to change anything

**Comment by nayakaj** [comment]
> You're using the .py extension, use .md instead for markdown.

i dont know about that can u plz explain @ankurg132

**Comment by meinhoonharsh** [comment]
https://www.markdowntutorial.com/
https://guides.github.com/features/mastering-markdown/
@nayakaj Just have a look at these sites, hope they will help you

**Comment by nayakaj** [comment]
can u check once plz
@ankurg132

**Comment by ankurg132** [comment]
You are still code using the correct code syntax for markdown, you are using ''' instead of which you should use \` (backticks). 
image
You can also see your preview and the code should look like `this`.

**Comment by nayakaj** [comment]
once check @ankurg132 @meinhoonharsh 
im not getting that thick line

**Pull request merged**
