### PR TITLE
Create Vector.md

### LINKED ISSUE #918: C_CPP : Vectors in C++ (Documentation)
<hr>

## Description 📜

This will explain the Vectors in STL.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>
Documentation

### PR DESCRIPTION
**Pull request by Sunainacode**
<hr>

## Description 📜

This pull request adds Documentation about Vectors in Standard Template Library of Data Structures topic. It explains the basics of vectors and the pre-defined functions that vectors support. 
Fixes #918

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by apeksha235 — APPROVED** [review]
Good job! @Sunainacode 
please merge this @Suvraneel

**Comment by Suvraneel** [comment]
@Sunainacode  Do one last thing
In the readme at Data Structures/STL, add a line in the readme

**Comment by Sunainacode** [comment]
Done @Suvraneel sir

**Comment by Suvraneel** [comment]
@Sunainacode GG ! :octocat:

**Pull request merged**
