### PR TITLE
Create Explain everything related to containerd(#650)

### PR DESCRIPTION
**Pull request by mohitmishra786**
Explained about Containerd theoretically.

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [x] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by mohitmishra786** [comment]
@Aryamanz29  who will merge this PR

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@mohitmishra786 why do we need C_CPP/readme.md file in this PR? Can you please remove it?

**Comment by mohitmishra786** [comment]
@Kajol-Kumari i didn't added that

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari i didn't added that

I can see it in this PR and in your branch as well. Please delete the `C_CPP` folder. Also it would be great if you can add the reference link at the end of the file. Something like-

```
Reference Links - <url1> , <url2> etc.
```

**Comment by mohitmishra786** [comment]
> > @Kajol-Kumari i didn't added that
> 
> I can see it in this PR and in your branch as well. Please delete the `C_CPP` folder. Also it would be great if you can add the reference link at the end of the file. Something like-
> 
> ```
> Reference Links - <url1> , <url2> etc.
> ```

Is it okay now as I have deleted the C_CPP folder

**Comment by Kajol-Kumari** [comment]
> > > @Kajol-Kumari i didn't added that
> > 
> > 
> > I can see it in this PR and in your branch as well. Please delete the `C_CPP` folder. Also it would be great if you can add the reference link at the end of the file. Something like-
> > ```
> > Reference Links - <url1> , <url2> etc.
> > ```
> 
> Is it okay now as I have deleted the C_CPP folder

Great! Can you please add the reference links as well?

**Comment by mohitmishra786** [comment]
> > > > @Kajol-Kumari i didn't added that
> > > 
> > > 
> > > I can see it in this PR and in your branch as well. Please delete the `C_CPP` folder. Also it would be great if you can add the reference link at the end of the file. Something like-
> > > ```
> > > Reference Links - <url1> , <url2> etc.
> > > ```
> > 
> > 
> > Is it okay now as I have deleted the C_CPP folder
> 
> Great! Can you please add the reference links as well?

Sure adding

**Comment by mohitmishra786** [comment]
@Kajol-Kumari  Done, is there anything else to do?

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for doing the requested changes @mohitmishra786 

LGTM 👍

**Pull request merged**
