### PR TITLE
Overview of Android Components

### PR DESCRIPTION
**Pull request by Yugal41735**
<hr>

## Description 📜

I have added a documentation file for the topic Overview of Android-Application Components
Fixes # <146> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by sitamadex11** [comment]
@Yugal41735 in which directory you have added your file?

**Comment by Yugal41735** [comment]
INDRODUCTION SUB DIRECTORY

**Comment by Yugal41735** [comment]
@sitamadex11 could u tell me if there are any changes so that I could take up next issues

**Comment by sitamadex11** [comment]
can you please squash your 2 commit into one

**Comment by Yugal41735** [comment]
Thank you :) for the feedback, by the way could u tell me what is second commit for ?

**Comment by Yugal41735** [comment]
what i mean is that i had added only 1 file but unable to understand why there is 2 commits

**Comment by Yugal41735** [comment]
@sitamadex11

**Review by sitamadex11 — APPROVED** [review]

**Comment by sitamadex11** [comment]
@VikasPandey121 please check it once.

**Comment by VikasPandey121** [comment]
Hi @Yugal41735! 
Great work, Can you please add some infographic data as well so that the reader can find it more interesting and informative. 
Thanks.

**Comment by Yugal41735** [comment]
> Hi @Yugal41735!
> Great work, Can you please add some infographic data as well so that the reader can find it more interesting and informative.
> Thanks.

ok like kind of adding some pictures to look it more eye catching right?

**Comment by Yugal41735** [comment]
@VikasPandey121  could u please check it once. 
Thank You.

**Comment by VikasPandey121** [comment]
LGTM, Thanks for the contribution.

**Pull request merged**
