### PR TITLE
Fixes #1606 Types of Pointers

### LINKED ISSUE #1606: Types of Pointers
<hr>

## Description 📜

This documentation will contain the contents related to *Types of Pointers*

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Mode of Contribution

- [x] Documentation

### PR DESCRIPTION
**Pull request by silicolicious**
<hr>

## Description 📜

I have added documents in the folder *Types of Pointers* under - *Pointers and its types* folder.  

It includes the following topics -
1. NULL Pointer
2. Void Pointer
3. Wild Pointer
4. Dangling Pointer

I have also added and updated the readme.md files.

Fixes #1606  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by silicolicious** [comment]
Hey! @Saviour1001 @Suvraneel, 
This is my second PR, which includes the types of pointers. Please review it.
Thank You!

Name : Mageshkrishna R
Domain : C/C++
Batch : 9
Discord Username : Mag#2191

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Your content is all good.
But there are lots of grammar mistakes . please check all your files again and correct them.
Use [grammarly](https://www.grammarly.com/) to clear your grammar mistakes.

**Comment by silicolicious** [comment]
> Your content is all good.
> But there are lots of grammar mistakes . please check all your files again and correct them.
> Use [grammarly](https://www.grammarly.com/) to clear your grammar mistakes.

Thanks @vasu-1  for mentioning the grammar mistakes, I have corrected them as you said using Grammarly.
Please check.

**Comment by Suvraneel** [comment]
@deepakkk

**Review by deeqakkk — APPROVED** [review]
@Suvraneel it's good to be merged.

**Comment by Suvraneel** [comment]
@silicolicious  Awesome ❤️

**Pull request merged**
