### PR TITLE
Frontend: fixed issue #930 via video (CSS BOX MODEL)

### PR DESCRIPTION
**Pull request by dikshatakyar**
<hr>

## Description 📜
Fixed issue #930 via video where I have explained CSS Box Model

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by code-reaper08 — APPROVED** [review]
Looks cool @dikshatakyar 💯 
@2024-SANDHYA Just have a look here.

**Review by 2024-SANDHYA — APPROVED** [review]
This is so good !!🚀🚀 @dikshatakyar

**Comment by dikshatakyar** [comment]
thankyou so much <3 @code-reaper08 @2024-SANDHYA

**Comment by code-reaper08** [comment]
> thankyou so much <3 @code-reaper08 @2024-SANDHYA

Thanks for contributing 🚀🤝

**Pull request merged**
