### PR TITLE
Machine Learning : Types of Distributions widely used in ML

### LINKED ISSUE #1963: ML 1.13 : Types of Distribution (A)
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Types of Distribution**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by kishlayaug15**
<hr>

## Description 📜

Described in detail about Different Types of Distribution widely used in Statistics and Machine Learning . They are
- Normal Distribution
- Standard Normal Distribution
- Binomial Distribution
- Poisson Distribution
- Exponential Distribution

Fixes #1963

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Isha307 — CHANGES_REQUESTED** [review]
@kishlayaug15 You have made changes in the main instead of ML branch, Please remove those files from the main and add it to the branch.

**Comment by Isha307** [comment]
@kishlayaug15 you had been assigned to work on the audio part, then why did you created PR for documentation?

**Comment by kishlayaug15** [comment]
I commented earlier, I wanted to work with documentation and audio both. After this, I'll work on audio on my work. BTW , do I have to record screen also or just record my explanation.

**Comment by Isha307** [comment]
@kishlayaug15 that issue was for audio part only.
you can just record your audio and BTW create the PR ASAP.

**Pull request closed without merging**
