### PR TITLE
Data Science with Python : Feature Selection Techniques

### LINKED ISSUE #347: Data Science with Python : Feature Selection Techniques
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about feature selection techniques. Tutorial to feature selection techniques and how it's applied using sample code. Be as elaborative as possible. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Peehu Saxena](https://github.com/PeehuSaxena) / [Arya Patel](https://www.github.com/AryaPatel1111)

Points to Note : 

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜

I have made a presentation video on the topic Feature Selection Techniques and discussed the benefits and the methods of Feature Selection.

Fixes #347 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image
image

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

In "Videos" repository, create your project title as "Feature Selection"
README.md needs elaboration in theoretical way. You can check with procedure structure to get an ideas of topics you could include and provide a proper conclusion of it.

Kindly work on it. @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Can you please verify the work, I have worked and made all the changes.

**Comment by prathimacode-hub** [comment]
Your PR is currently under reviewing process.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Can I know one small thing, can we not make a pull request for another issue until this is completed, because I have done the other issue and the solution is there with me now, so can you please say me how to do that.

**Comment by prathimacode-hub** [comment]
You can make a pull request if you know the right workflow and push it into separate space, if not done properly both of the contributions would show up in single PR @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Mam I am new to open source, can you please help me. I don't know how to push it to a separate space.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

- The project folder should be titled as "Hierarchical Clustering"
- The file names should be in snake case : hierarchical_clustering.ipynb & heirarchical_clustering.pdf
- All the readme files should be titled as "README.md"
- The datasets should be in "DS Datasets" repo and any resources referred should be in "DS Resources"
- In README.md added in tutorials, You had come straight to the topic instead add how it's derived and what is the topic coming from, give short intro of what kind of algorithm it is and then at the end provide a overall summary of the topic and the final conclusion.

Kindly work on it. @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Mam if the hierarchical clustering is also under this pull request itself, how to make a new PR  for that can you please help me, mam.

**Comment by prathimacode-hub** [comment]
Hey, it has come under single PR. You have to create separate PR's for each issue. @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, yes mam can you please help me, mam, by saying how to do that. 
can we have meet mam now?

**Pull request closed without merging**
