### PR TITLE
ML 1.9 : Hypothesis Testing (D) #1258

### LINKED ISSUE #1258: ML 1.9 : Hypothesis Testing (D)
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Hypothesis Testing**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜

Made documentation on the topic of Hypothesis Testing and the ways we can perform the testing along with suitable examples.
Fixes #1258

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Delete the `test` file

**Review by Isha307 — COMMENTED** [review]
Please delete the test file and Can you please make the md file more attractive like add points?

**Comment by ashish-reddy-20-08** [comment]
@Isha307, I will add the bullet points and make it attractive and get back soon Mam.

**Comment by ashish-reddy-20-08** [comment]
@Isha307, I have added the bullet points, where ever necessary, can you please look into that and merge the PR if everything is fine.

**Review by Isha307 — APPROVED** [review]

**Pull request merged**
