### PR TITLE
[Go] Roadmap added

### PR DESCRIPTION
**Pull request by amino19**
<hr>

## Description 📜
Supervisor: Added the Golang Roadmap for Contributors & Mentors.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #NA  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Golang

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by amino19** [comment]
@avishj: Don't close this Pull request, I'm working on it, & will update! :slightly_smiling_face:

**Comment by avishj** [comment]
Can you move this PR to the repo's Golang branch before merging into main of the repo?

**Comment by gauravdas014** [comment]
@avishj This PR contains changes to 198 files. Which is not possible to review. Make sure your branch is updated.

**Comment by amino19** [comment]
@gauravdas014: Some folks are working on that folders, i.e., directly attached to the `Golang`, I noticed.
So, it arises conflicts while deleting their folders from our branch.

What are your insights? Why don't we delete their folders from our branch?

**Pull request closed without merging**
