### PR TITLE
Linked_List_Implementation_of_Stacks.md

### LINKED ISSUE #7538: Linked_List_Implementation_of_Stacks
### Description

Description
Linked List Implementation of Stacks

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by varnikarathee**
<hr>

## Description 📜Linked_List_Implementation_of_Stacks.md

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7538

<hr>

## Type of change 📝Linked_List_Implementation_of_Stacks.md

- [X] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] DS#A

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by nimisha-yadav — CHANGES_REQUESTED** [review]
Now your format is right. Just a small change, create a folder in ``4.1 Stacks`` by name of ``18. Linked List Implementation of Stacks`` and add your file in it as README.md

**Comment by varnikarathee** [comment]
@nimisha-yadav Actually i needed your help , here when i try to add my file , it shows that it is being crea added in my repo and askks me in return to create a pr , so that i can merge it . Like my folder isn't even visible . Am i doing it the right way?

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav Actually i needed your help , here when i try to add my file , it shows that it is being added in my repo and askks me in return to create a pr , so that i can merge it . Further now i went in patch1 branch and created a folder but now it shows 718 files . Is is the right way?

See you're adding file in main itself and then you create a new branch which is creating problem.

In your fork, go to DSA branch and then add the file and create a new branch while commiting the changes and then you're redirected to PR where it says to merge that branch in main. Don't merge. Cancel that window. Open the fork again, go to that branch which you created and create PR pointing to GWOC DSA branch.

**Comment by varnikarathee** [comment]
@nimisha-yadav I have added the file in new branch varnikarathee-patch.  Just a small doubt , do i need to fetch in patch1 before creating a pr? and do i need to go for compare and pull request or create a new pr  by myself.?

image

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav I have added the file in new branch varnikarathee-patch1. Just a small doubt , do i need to fetch in patch1 before creating a pr? and do i need to go for compare and pull request or create a new pr by myself.?
> 
> image

Yes, click on compare and pull request and while creating PR make sure it points to GWOC DSA branch. We fetch the latest commits in DSA branch itself before creating a new branch from there but since you've created a new branch so create the PR, we'll see if it generates any problem :)

**Comment by varnikarathee** [comment]
@nimisha-yadav This is my new pr https://github.com/girlscript/winter-of-contributing/pull/8522 see if its fine and if i can merge it.

**Pull request closed without merging**
