### PR TITLE
Java 12.2: Introduction to Super keyword

### LINKED ISSUE #2364: Java 12.2: Introduction to Super keyword
### Description

Add audio, documentation, and video regarding the **Introduction to Super keyword**.

____

### Location of File to be added

The files should be added inside the `Introduction to Super keyword`  folder which is inside the `Inheritance`  folder present in the   `Java`  main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Yashesvinee**
<hr>

## Description 📜

Added documentation of Introduction to super keyword. 
Fixes #2364

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Yashesvinee** [comment]
@AkMo3

**Review by sumitaccess007 — CHANGES_REQUESTED** [review]
Hello @Yashesvinee,

Documentation is good, can you please add below points as well -
1. Related to below point add a code snippet as well.
"When using super to access contructors, call to super() must be the first statement in Derived Class constructor."
2. Also write a small paragraph explaining How JVM adds implicitely super() if we do not specify it explicitely.
Rest all looks okay to me.
Thanks

**Comment by Yashesvinee** [comment]
@sumitaccess007  I made the required changes 
Is it okay now?

**Comment by Yashesvinee** [comment]
@adityabisoi

**Review by AkMo3 — APPROVED** [review]

**Pull request merged**
