### PR TITLE
Data Science with Python : Recurrent Neural Networks #467

### LINKED ISSUE #467: Data Science with Python : Recurrent Neural Networks
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Introduction to Recurrent Neural Networks. Tutorial to Recurrent Neural Networks and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Deep Learning

Mentors Assigned : [Dhruv Bajaj](https://github.com/DhruvBajaj01) / Peehu Saxena

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by sunidhii09**
<hr>

## Description 📜
I have provided a brief introduction about RNN.
Fixes #467 

<hr>

## Type of change 📝
Documentation

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
There in total 109 files but nothing relevant to issue title. Kindly check on to it. @sunidhii09

**Comment by sunidhii09** [comment]
@prathimacode-hub I have added a file titled 'RNN.ipynb' please check.

**Comment by prathimacode-hub** [comment]
It has 109 unnecessary files. Add only file related to you and nothing else than that. @sunidhii09

**Comment by sunidhii09** [comment]
I did not create those 109 files! I have created only one, titled 'RNN'. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> I did not create those 109 files! I have created only one, titled 'RNN'. @prathimacode-hub please check. I am having a really hard time doing this thing. Please help.

I understand it happens with first timers. May be workflow is not followed in order. I know you haven't created those files, but it's showing you had made changes in all those files. If i approve it, all changes would absorb. So correction should be done that only issue files could be seen. 

You just do one thing. Hope you have your files saved. Once they are saved in your local drive, delete your forked repo and refork it again. Now follow the right steps to make this work correctly. @sunidhii09

**Comment by sunidhii09** [comment]
Okay. Thanks! I'll close this PR and do it again.

**Pull request closed without merging**
