### PR TITLE
Rename file

### LINKED ISSUE #8457: Rename filename
changed file name

### PR DESCRIPTION
**Pull request by dhruti29**
<hr>

## Description 📜
Rename
Fixes #8457 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ X] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by dhruti29** [comment]
@nimisha-yadav Please check....!!

**Review by nimisha-yadav — APPROVED** [review]
Thanks @dhruti29 for the swift response :D

**Comment by dhruti29** [comment]
> Thanks @dhruti29 for the swift response :D

Thank you for correcting me..!!

**Comment by nimisha-yadav** [comment]
@dhruti29 Stack issue was resolved but Greedy folders weren't. See name the folder as 09. Kruskal and 10. Prim. File name will be readme.md of those folders.
Take this [example](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/3.2%20Greedy%20Algorithms/01.%20Introduction%20To%20Greedy%20Algorithms/readme.md) the folder serial number starts with 01. Introduction and file name for documentation is readme

**Comment by nimisha-yadav** [comment]
Dont create an issue, directly create a new PR for these two folders

**Comment by nimisha-yadav** [comment]
Also, update your fork and pull the upstream changes

**Pull request merged**
