### PR TITLE
Binary Search practice questions

### PR DESCRIPTION
**Pull request by geetika005**
<hr>

## Description 📜
This documentation consists of 5 practice question to polish the concept of binary search
Fixes # 4493 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by geetika005** [comment]
Please add the hacktoberfest label also

**Comment by ChetasShree** [comment]
Pls remove the wanted files like ' Javascript Functions ' and just keep the file which you want to get it merged @geetika005

**Comment by geetika005** [comment]
There is no unwanted file mam i have renamed that file to binary search and had worked on it

**Comment by geetika005** [comment]
There is only one file

**Comment by geetika005** [comment]
Ok mam i will make the changes

**Comment by ChetasShree** [comment]
I can see a javascript file " https://github.com/girlscript/winter-of-contributing/blob/a9fe77e7e1e31fa250f05d0be47be03987d1ac9b/C_CPP/Algorithmic%20Approaches/Javascript_Functions.md "

**Comment by geetika005** [comment]
updated the changes mam 
please review it

**Comment by ChetasShree** [comment]
Please mention an index line in readme along with relative link as well, and the rest is good to go

**Comment by ChetasShree** [comment]
Amazing work @geetika005  !!!
@Suvraneel @Saviour1001 pls review this PR and merge it :)
Thank you !!

**Pull request merged**
