### PR TITLE
Frontend : Flex properties add documentation (#974)

### LINKED ISSUE #974: Frontend : Flex properties
<hr>

## Description 📜

I will be adding different flex properties

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

### PR DESCRIPTION
**Pull request by SushantPatial**
<hr>

## Description 📜

Documentation for Flex properties
Fixes #974

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by iamsuyashpatel07** [comment]
can I work on this!

**Comment by sifa123** [comment]
Hey @SushantPatial someone already did this. If you want to work on video/audio, let me know.

**Comment by ayushjain27** [comment]
I want to work on video
batch-11

**Comment by ayushjain27** [comment]
Please let me know also you want muted video or voiced video

**Comment by sifa123** [comment]
> I want to work on video
> batch-11

Please create a new issue for video. I will assign you there

**Pull request closed without merging**
