### PR TITLE
Added 1.6: Maximum Likelihood Estimation Documentation

### PR DESCRIPTION
**Pull request by amitrakshar01**
Hey @abhisheks008, please check

## Description 📜

Added Documentation of 1.6: Maximum Likelihood Estimation in winter-of-contributing/Machine_Learning/Statistics_for_Machine_Learning/ Issue:#591

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Review by geeythree — CHANGES_REQUESTED** [review]
- [ ] Add relevant comments to the code snippet.
- [ ] Spell check in the last paragraph.

**Comment by amitrakshar01** [comment]
> [x]  Add relevant comments to the code snippet.
> [x]  Spell check in the last paragraph.

**Comment by amitrakshar01** [comment]
> * [x]  Add relevant comments to the code snippet.
> * [x]  Spell check in the last paragraph.

**Review by geeythree — APPROVED** [review]
LGTM!

**Comment by abhisheks008** [comment]
@amitrakshar01 please put the images properly, as they are not visible from an user point of view.

**Comment by abhisheks008** [comment]
@amitrakshar01 you are requested to make a fresh PR with proper images and proper title.
The title should be, `1.6. Topic Name`
We are closing this PR and deleting the commit that you've made.

**Pull request merged**
