### PR TITLE
Introduction to HTML

### LINKED ISSUE #208: Introduction to HTML
I will cover 
1. What is HTML
2. Sample HTML structure
3. HTML element

### PR DESCRIPTION
**Pull request by AnantDuhan**
<hr>

## Description 📜

Provided relevant information regarding to this issue i.e. basic code of HTML, explained each and every element and also provided the preview
Fixes #208  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by himanshu007-creator — APPROVED** [review]

**Comment by sifa123** [comment]
@AnantDuhan, this topic is already merged. If you want, you can work on video. I think there is no issue created by the video. Also, you can add more content to the existing folder if you think anything is missing.

**Comment by AnantDuhan** [comment]
> @AnantDuhan, this topic is already merged. If you want, you can work on video. I think there is no issue created by the video. Also, you can add more content to the existing folder if you think anything is missing.

what kind of content I can add, can you suggest.

**Comment by sifa123** [comment]
> > @AnantDuhan, this topic is already merged. If you want, you can work on video. I think there is no issue created by the video. Also, you can add more content to the existing folder if you think anything is missing.
> 
> what kind of content I can add, can you suggest.

Like- 
features of html
html editor
html comment
Why should you learn html
advantages
disadvantages

**Comment by AnantDuhan** [comment]
ok I'll do that

**Comment by AnantDuhan** [comment]
https://github.com/girlscript/winter-of-contributing/pull/4482

please have a look at this

**Pull request closed without merging**
