### PR TITLE
loops_break

### PR DESCRIPTION
**Pull request by Vibhu562**
<hr>

## Description 📜
Issue Number : #561
Explanation related to, loops_break

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [x] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Ankit-Tec40** [comment]
Ankit Kumar
Python Batch 5
I want to do this task

**Comment by prathimacode-hub** [comment]
> Ankit Kumar
> Python Batch 5
> I want to do this task

This is a PR not an issue. @Ankit-Tec40

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done.

- Your README.md can be more detailed.
- File names should be in snake case : loops_break.ipynb
- Even your .ipynb file, can be more details. 

Kindly work on it. @Vibhu562

**Review by nirvikagarwal — CHANGES_REQUESTED** [review]
Use code fences with the language to get correct syntax highlighting, Add proper indentation to the python code snippets.

**Comment by nirvikagarwal** [comment]
In the last paragraph where you have mentioned that the `break` statement can be used with 3 loops, it is true in general, but python does not have a `do while` loop. Add a bit of context there. And in the code `output` in your `README.md` file, there are extra blank lines, remove them. Rest looks good to me.

**Review by nirvikagarwal — APPROVED** [review]
Looks good to me. @prathimacode-hub you can check once

**Comment by prathimacode-hub** [comment]
Kindly add your issue number in your PR. @Vibhu562 

It looks good and can be merged once issue number is added. @adityabisoi

**Comment by Saviour1001** [comment]
Just removed the redundant labels.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Great work. Keep going. 🙌👏@Vibhu562

**Pull request merged**
