### PR TITLE
Python: 1.7 What is python interpreter

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
<hr>

## Description 📜

Audio Contribution of Python Interpreter #79 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

This is a audio contribution. As mentioned, audio contribution should have a must ppt presentation of all the details that's been explained in audio format.
Next is README.md file, where in you add all the general overview of the details concerning the issue where in you add this drive link with a heading. To know general overview and what to add, you can check the project structure. 
The audio file just lasts 1minute, you have to be elaborative about python interpreter

Kindly work on it. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> Changes to be done :
> 
> This is a audio contribution. As mentioned, audio contribution should have a must ppt presentation of all the details that's been explained in audio format.
> Next is README.md file, where in you add all the general overview of the details concerning the issue where in you add this drive link with a heading. To know general overview and what to add, you can check the project structure.
> The audio file just lasts 1minute, you have to be elaborative about python interpreter
> 
> Kindly work on it. @BhaswatiRoy

Maam in the guidelines it was mentioned that the ppt presentation is optional and regarding the audio I asked the mentors in discord they said there is no time limit so I was unaware of that.

**Comment by BhaswatiRoy** [comment]
I have updated the pr do please review it @prathimacode-hub

**Comment by prathimacode-hub** [comment]
@BhaswatiRoy, I'm not sure if you would do or not, but your README.md lacks detailing. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy, I'm not sure if you would do or not, but your README.md lacks detailing.

Okay maam will update and send another pr

**Review by hritikksingh — APPROVED** [review]
@BhaswatiRoy your readme.md looks good to me now.

**Comment by adityabisoi** [comment]
@prathimacode-hub @hritikksingh Is this good to go?

**Comment by hritikksingh** [comment]
@adityabisoi I went through the readme and that looks good to me as per @prathimacode-hub she elaborated each point.

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy your readme.md looks good to me now.

thank you waiting for @prathimacode-hub maam

**Comment by prathimacode-hub** [comment]
Sure, this suffices and good to go. PR can be merged. @adityabisoi

**Pull request merged**
