### PR TITLE
Data Science with Python : Face Mask Detection

### LINKED ISSUE #397: Data Science with Python : Face Mask Detection
Welcome to 'DSWP' Team, good to see you here

This issue helps in gaining extensive knowledge of getting started with face mask detection. Tutorial to Face Mask Detection using sample code is needed

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Computer Vision

Mentors Assigned : Kareem Negm / Jivitesh Jain

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by NeerajHazarika**
<hr>

## Description 📜

Created a detailed report on how to make a Face Mask Detection Model with OpenCV and Keras. This project uses the concept of supervised deep learning. Added a video at the end of the working model. Please review my pull request @prathimacode-hub
Fixes #397

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AkMo3** [comment]
@NeerajHazarika I had change the PR description and removed the fields that were not required. Please remember to delete other domains so as that the bot works good.

**Comment by NeerajHazarika** [comment]
@AkMo3 Sure thanks, I will make sure to do it next time.

**Comment by prathimacode-hub** [comment]
Your PR is currently under reviewing process.

**Comment by prathimacode-hub** [comment]
There are in total of 114 files and it's not in right project structure. Kindly check up with the document provided. @NeerajHazarika

**Comment by NeerajHazarika** [comment]
@prathimacode-hub should I make a new pull request, I have figured out the correct way to do it.

**Comment by NeerajHazarika** [comment]
I have created a new pull request at [link](https://github.com/girlscript/winter-of-contributing/pull/1609)
should i close this pull request ? @prathimacode-hub @AryaPatel1111

**Pull request closed without merging**
