### PR TITLE
Data Science with Python : Data Visualizations with Seaborn

### LINKED ISSUE #382: Data Science with Python : Data Visualizations with Seaborn
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in knowing all the information that one needs to learn about Data Visualizations with Seaborn. Tutorial to Data Visualizations with Seaborn and how it's applied should be explained briefly.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualizations

Mentors Assigned : Shivang Dubey / Nithin

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by vanshhhhh**
<hr>

## Description 📜

I did the implementation of Seaborn for data visualization. Added 1 notebook and updated the readme file.
Fix #382 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by vanshhhhh** [comment]
@prathimacode-hub Please check my PR.

**Comment by Kalyani02072003** [comment]
please assign the documentation to me
i am a beginner but I will try my best
batch - 5 python 
discord - STRAWHAT_LUFFY#8651

**Comment by prathimacode-hub** [comment]
> please assign the documentation to me
> i am a beginner but I will try my best
> batch - 5 python
> discord - STRAWHAT_LUFFY#8651

This is  a PR not an issue.  @Kalyani02072003

**Comment by Kalyani02072003** [comment]
@prathimacode-hub okay I didn't know that, I am sorry for the comment.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub okay I didn't know that, I am sorry for the comment.

No worries, any queries ask me in discord. @Kalyani02072003

**Comment by m0hit-kumar** [comment]
I want to contribute to this issue :
Name-Mohit Kumar
Domain-Data Science with Python
Batch-4
Issue Number- 831
Contribution Approaches-
what is Data Visualizations 
what it's used for
Data Visualizations with Seaborn
various techniques and intuion from visualization we can make

**Comment by Nithin-Reddy-02** [comment]
@m0hit-kumar This is a PR not an issue, you can navigate to the respective issue and mention it there.

**Comment by vanshhhhh** [comment]
@Nithin-Reddy-02 I have added the datasets in DS Datasets folder. Please review and merge my PR.

**Comment by shivangdubey** [comment]
@vanshhhhh Nice work, but documentation can have more detailing including additional details like pictures about various plots/charts you used; their syntax and implementation. Seaborn is not this tiny library, a lot can be added.

**Comment by vanshhhhh** [comment]
> @vanshhhhh Nice work, but documentation can have more detailing including additional details like pictures about various plots/charts you used; their syntax and implementation. Seaborn is not this tiny library, a lot can be added.

Sir, I have included detailed implementation of seaborn in .ipynb notebook file. Did you check it ?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add applications, overall summary, add up few sample visualization images with short explanations, outcomes, conclusion derived in README.md
Sample visualization images can be put up in "Images" folder created in your project repo.
If you have referred any resources to work on it, add it up in respective category in "DS Resources"

@vanshhhhh

**Comment by vanshhhhh** [comment]
@prathimacode-hub please check the changes I have made.

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. It's approved. What a wonderful start. Very well executed. 👏🎉@vanshhhhh

**Comment by vanshhhhh** [comment]
Thanks a lot @prathimacode-hub ma'am. Looking forward to contribute more :)

**Pull request merged**
