### PR TITLE
Android Java

### PR DESCRIPTION
**Pull request by pranjalkalal**
<hr>

## Description 📜

Download and Install android studio on windows/mac/linux # 36 

<hr>

## Type of change 📝

   Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

   Android Dev #(Java)
<hr>

## Checklist ✅

   I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
   I have performed a self-review of my own code or work.
   I have commented my code, particularly in hard-to-understand areas.
   My changes generates no new warnings.
   I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by pranjalkalal** [comment]
@gauravdas014  sir on google colab this images are visible but here not than what to do?

**Comment by VikasPandey121** [comment]
You did not follow the instructions while creating the PR. Please follow the instruction property and create a new PR as tag the issue number with it. 
Please keep these steps in your mind while contributing

1- Create a new branch `Android_Development_With_Java` using `git branch Android_Development_With_Java`.
2- Checkout to this new branch using  `git checkout Android_Development_With_Java`.
3- Now you add your file your files into this branch only using the command `git add .`
4- Commit your changes using the command `git commit -m "ENTER YOUR COMMENT HERE"`.
5- Push your changes using the command `git push origin Android_Development_With_Java`

Now create your PR.

**Comment by VikasPandey121** [comment]
I am closing this PR right now hoping that you will come up with the new PR with suggested changes soon.

**Comment by pranjalkalal** [comment]
Okk please check #2423 pr and review me is it ok or not

**Pull request closed without merging**
