### PR TITLE
OpenSource : 5.13 Explain everything related to Vitess

### PR DESCRIPTION
**Pull request by itsbittoosharma**
<hr>

## Description 📜

Isuue #638
Explained everything related to Vitess  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by itsbittoosharma** [comment]
Please review my PR

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@itsbittoosharma can we please add reverence link at the end of this file? Please see the end of [this](https://github.com/itsbittoosharma/winter-of-contributing/blob/Opensource/Open_Source/Section-5/5.19%20Explain%20everything%20related%20to%20containerd.md) file for your reference

**Comment by itsbittoosharma** [comment]
@Kajol-Kumari Done

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for making the requested changes @itsbittoosharma 
LGTM 👍

**Pull request merged**
