### PR TITLE
[JS] Topic: Await and Async in Javascript

### PR DESCRIPTION
**Pull request by daminimehra**
<hr>

## Description 📜

I have added and discussed topic JavaScript Await/Async. 
Fixes Issue #721 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [x] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by daminimehra** [comment]
@paramsiddharth pls review my PR

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 Please review.

**Comment by paramsiddharth** [comment]
@daminimehra Please follow the PR format mentioned in the contribution guide: https://github.com/paramsiddharth/gwoc-js-roadmap/releases/latest/download/JavaScript.Roadmap.for.GWoC.pdf

**Review by s4-2 — APPROVED** [review]
Looks good to me:)

**Comment by daminimehra** [comment]
> @daminimehra Please follow the PR format mentioned in the contribution guide: https://github.com/paramsiddharth/gwoc-js-roadmap/releases/latest/download/JavaScript.Roadmap.for.GWoC.pdf

Okay Sir!

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Comment by paramsiddharth** [comment]
Thank you so much for the amazing PR, Damini! Sadly another PR for the same issue under documentation has been merged. If you wish to contribute further to the same issue, you can create a PR improving the merged document or add your contribution in another format. Additionally, you can create multiple PRs for different issues, or create your own based on the roadmap here: https://github.com/paramsiddharth/gwoc-js-roadmap/releases/latest/download/JavaScript.Roadmap.for.GWoC.pdf

Good luck! :) Do join our acknowledgement session on Saturdays, 7 PM! We'd love to see you there.

**Pull request closed without merging**
