### PR TITLE
ML 1.15 : Types of Distribution (D) #1965

### PR DESCRIPTION
**Pull request by Ruchika-20**
<hr>

## Description 📜
A brief information regarding types of data distribution in statistics more specifically in machine learning.
 Issue Number# 1965

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by geeythree — CHANGES_REQUESTED** [review]
Hi Ruchika, your documentation is really good, but please remove the README file.

**Comment by abhisheks008** [comment]
@Ruchika-20 Create a fresh PR in the machine learning branch, not in the main branch, with the updated file.

**Comment by Ruchika-20** [comment]
Do I need to remove the readme file as well as told by @geeythree?

**Comment by abhisheks008** [comment]
Yeah remove that readme file.
Rename the .ipynb file in proper manner. `ML_1_15_Types of Distribution_(D).ipynb`
Create a fresh PR, with only the .ipynb file.

**Comment by Ruchika-20** [comment]
Okay....so do i need to fork the repo again or directly do the changes?
As I'm new to github I don't have that much idea

**Comment by abhisheks008** [comment]
Start from scratch again.

**Comment by Ruchika-20** [comment]
ok

**Comment by Ruchika-20** [comment]
I've updated the changes ...Kindly see the PR

**Pull request closed without merging**
