### PR TITLE
Break and Continue Statment 

### LINKED ISSUE #2589: Continue and Break Statement in CPP
### Description

Documentation

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Megha0606**
<hr>

## Description 📜

I have made documentation  on break and continue statements used in cpp. I have also included code snippets in md file. Please Review 
Batch-2
Fixes #2589

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by gunjan-g — COMMENTED** [review]
@Megha0606 this topic is already there in repo, please check the folder before creating an issue and working on it

**Comment by gunjan-g** [comment]
@Saviour1001 @Suvraneel this topic is already present in repo

**Comment by Megha0606** [comment]
@gunjan-g   there are 2 files that are already been merged on the same topic, then what's wrong here? And I think yesterday in meeting sir told they are looking for content because there 1000+ contribution

**Comment by Saviour1001** [comment]
This topic already exists [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Fundamentals/Break%20or%20Continue/break_continue_in_c_cpp.md). Thus closing this PR, you can provide the content you wrote in form of audio/video format and make a new PR.

**Pull request closed without merging**
