### PR TITLE
Java 2.1: Byte Code

### LINKED ISSUE #1196: Java 2.1: Byte Code
<hr>

## Description 📜

Add audio, documentation, and video regarding the **Bytecode**.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `Bytecode` folder which is inside the `Fundamental` present in the  `Java` main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by AbhinandanAdhikari**
<hr>

## Description 📜

Created a documentation for Java Bytecode.
Fixes #1196
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AbhinandanAdhikari** [comment]
@AkMo3 @garvitraj I have made the Pull request, please review it.

**Comment by AkMo3** [comment]
@nandini7637 Please start the review

**Comment by nandini7637** [comment]
I have reviewed it, @AbhinandanAdhikari  please correct the spelling of 'environment', else everything looks good, well done and I think we can merge it after the corrections.

**Comment by AbhinandanAdhikari** [comment]
> I have reviewed it, @AbhinandanAdhikari please correct the spelling of 'environment', else everything looks good, well done and I think we can merge it after the corrections.

@nandini7637 Ma'am, I've corrected the spelling.

**Review by AkMo3 — APPROVED** [review]

**Pull request merged**
