### PR TITLE
Lexicographic rank of a string

### LINKED ISSUE #3741: Lexicographic rank of a string
### Description

Given a string, find its rank among all its permutations sorted lexicographically.

### Domain

Competitive Programming

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by AastikSharma05**
<hr>

## Description 📜
Given a string, find its rank among all its permutations sorted lexicographically.
Fixes #3741  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by AastikSharma05** [comment]
@ravireddy07, @atarax665 Please review my PR.

**Comment by ravireddy07** [comment]
@AastikSharma05  Man don't copy paste from [anywhere](https://www.geeksforgeeks.org/lexicographic-rank-of-a-string/).
Please try to contribute unique content.

**Review by ravireddy07 — COMMENTED** [review]
@AastikSharma05  Man don't copy paste from [anywhere](https://www.geeksforgeeks.org/lexicographic-rank-of-a-string/).
Please try to contribute unique content.

**Comment by AastikSharma05** [comment]
@ravireddy07

**Pull request closed without merging**
