### PR TITLE
How to install react developer tools 

### PR DESCRIPTION
**Pull request by aasthasarswat24**
<hr>
## Installing React developer tools - weak-1 React JS
<hr>

## Type of change 📝

- [ X] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

 -[X] Frontend Dev #React/Angular/Vue

<hr>

## Checklist ✅

- [X ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X ] I have performed a self-review of my own code or work.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] My changes generates no new warnings.
- [X ] I'm GWOC'21 contributor

### CODE REVIEW

**Review by aasthasarswat24 — COMMENTED** [review]
How to install react developer tools

**Comment by 2024-SANDHYA** [comment]
Why 3 mds ? @aasthasarswat24

**Comment by anandhu720** [comment]
@aasthasarswat24 can you please mention the issue you worked on please

**Comment by s4-2** [comment]
@aasthasarswat24 Please go through the contribution guidelines. Your PR missing some points like mentioning issue number, check mark.

**Pull request closed without merging**
