### PR TITLE
Data Science with Python : Data Visualizations using Matplotlib #445

### LINKED ISSUE #445: Data Science with Python : Data Visualizations using Matplotlib
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about Data Visualizations with Matplotlib. Tutorial to Data Visualizations with Matplotlib and how it's applied visually.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualizations

Mentors Assigned : [Shivang Dubey](https://github.com/shivangdubey) / [Nithin](https://github.com/Nithin-Reddy-02)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ShubhamPatel01**
<hr>

## Description 📜

I prepared a video in which I covered topics which includes Introduction to Matplotlib library, several types of Visualization techniques using Matplotlib and also listed alternatives to Matplotlib for data visualizations in Python.
Fixes #445 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ShubhamPatel01** [comment]
Please evaluate @prathimacode-hub
Name: Shubham Patel
Issue: #445 
Type: Video
Batch number: 3
Serial number: 104

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

Only change it needs. Porject file name should be in snake case : data_visualizations_using_matplotlib.ipynb

@ShubhamPatel01

**Comment by ShubhamPatel01** [comment]
I have done the change @prathimacode-hub . Please check

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR, Your PR is approved. Great job and finest execution of your issue. Keep it up. ✨✔@ShubhamPatel01

**Pull request merged**
