### PR TITLE
Frontend With Framework - fixes issue-#2063

### LINKED ISSUE #2063: FRONTEND WITH FRAMEWORK: VueJS-2.1 => Data and Methods
Contributors are required to explain about Data and Methods in Vue.js, which should cover questions like:-
What is Data in Vue.js?
What is Methods in Vue.js?
Why it is needed?
How do they work?
How to use it? (Explain with basic code)
etc....

**Note:**
Plagiarism is strictly prohibited.

Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Files need to be added into the Week2 folder only.

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

### PR DESCRIPTION
**Pull request by CSAURABH**
<hr>

## Description 📜
fixes issue-#2063 :- FRONTEND WITH FRAMEWORK: VueJS-2.1 => Data and Methods 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2063 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [x] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by CSAURABH** [comment]
@SourabhSaraswat-191939 Please Review my pull request.

**Comment by anandhu720** [comment]
@SourabhSaraswat-191939 please review it

**Comment by anandhu720** [comment]
@CSAURABH bro any updates

**Comment by anandhu720** [comment]
@SourabhSaraswat-191939 please review it

**Comment by SourabhSaraswat-191939** [comment]
@CSAURABH, Please mention your references.

After that, we are good to go with your PR.

**Comment by anandhu720** [comment]
@CSAURABH please add reference and we can merge it

**Review by anandhu720 — APPROVED** [review]

**Pull request merged**
