### PR TITLE
Added Audio for arrays of pointers in C

### LINKED ISSUE #7887: Audio for array of pointers in C
### Description

I will be doing an audio contribution on the topic array pointers in C langauge.

### Domain

C/CPP

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Harsh652-cpu**
<hr>

## Description 📜

In C language we come across some situations where we need to use arrays to store values of pointers variables and for such cases we use array of pointers.In this audio I have explained it in a very detailed manner and I hope it will add some value in your coding journey.
Fixes #7887 

<hr>

## Type of change 📝

- [X] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Harsh652-cpu** [comment]
@Saviour1001 @Suvraneel @apeksha235 Please check it!

**Comment by Harsh652-cpu** [comment]
hey @Saviour1001 @Suvraneel

**Comment by Suvraneel** [comment]
@kashishahuja2002 @vasu-1

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Why you have deleted `/C_CPP/Pointer and its types/readme.md` ?

It should not been deleted !
Kindly restore it !

**Comment by Suvraneel** [comment]
@Harsh652-cpu  Either restore it... If you are unable to, then close this & make new PR

**Comment by Harsh652-cpu** [comment]
Okay I am making a new one now @Suvraneel

**Pull request closed without merging**
