### PR TITLE
LISTS.md added

### LINKED ISSUE #2370: Lists in C++ STL
### Description

I will give a brief description of lists in STL and its working in c++ .

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by emily876**
<hr>

## Description 📜

I gave a brief description of lists in c++ STL
Fixes #2370  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor
<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
kindly delete this pr ...
because someone has already worked on it #1307

**Comment by emily876** [comment]
@vasu-1  I'm not getting the option for deletion of pr. I guess only admin can do that. Please assist !!

**Comment by vasu-1** [comment]
image

you will find the option for deleting the PR :))
if you can't see send me the screenshot :)

**Comment by Saviour1001** [comment]
Closing this PR as the discussion is regarding that.

**Pull request closed without merging**
