### PR TITLE
Class and Functional Components and their lifecycles

### LINKED ISSUE #1093: MERN_React: 3.1 Class and Functional Components and their lifecycles
# Instructions 
## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## What are components?

-  What are class components, and their properties?
-  What are functional components, and their advantages over class based components?
-  Introduction to hooks and basic data fetching using the axios/fetch APIs using the ```useEffect``` hook in functional components and ```componentDidMount``` function in class based components.

Please refrain from plagiarising.

# Task 

- [ ] Documentation

### PR DESCRIPTION
**Pull request by GyaniRoman23**
<hr>

## Description 📜

<h2>Fixes #1093</h2>

<h3>Includes the following content:</h3> 

- What are Components and of how many type ?
- Class Component, how to create one and its class properties
- Functional Components, how to create one and its advantages over class components
- Converting a function to class
- Introduction to hooks and what they offer
- Data Fetching using the Fetch API through useEffect() hook for functional component
- Data Fetching using the Axios API through componentDidMount() method for class components
- External References

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] MERN

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by saloni-15 — CHANGES_REQUESTED** [review]
Hey, It looks great,  just rename the file as `3.1_Class_and_Functional_Components.md` and consider the nomenclature while naming PRs.

**Comment by GyaniRoman23** [comment]
Hey @saloni-15 I have made the changes, Kindly review them.

**Review by saloni-15 — APPROVED** [review]

**Review by manjeetdhayal — APPROVED** [review]
Hey @GyaniRoman23 it looks great but from next time please do not add additional topics there is separate issue for fetching data

**Comment by GyaniRoman23** [comment]
> Hey @GyaniRoman23 it looks great but from next time please do not add additional topics there is separate issue for fetching data

Sure. Actually I was unsure about a few topics as they were somehow linked up to one another, so I asked @v-rohan for it, but I didn't got any reply so following my intuition I included a few topics in brief. But from next time, I will surely adhere to the given instructions.

**Comment by manjeetdhayal** [comment]
> > Hey @GyaniRoman23 it looks great but from next time please do not add additional topics there is separate issue for fetching data
> 
> Sure. Actually I was unsure about a few topics as they were somehow linked up to one another, so I asked @v-rohan for it, but I didn't got any reply so following my intuition I included a few topics in brief. But from next time, I will surely adhere to the given instructions.

Ohk cool! And it is a really great PR. Content is nicely written ✨

**Pull request merged**
