### PR TITLE
Open Source : 4.7 Everything about Outreachy Program

### LINKED ISSUE #299: OpenSource : 4.7 Explain everything related to `Outreachy Program`
### Description :

- **Explain everything related to `Outreachy Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by KhafiaAyyub**
<hr>

## Description 📜
Explained Everything about Outreachy program in the form of documentation.
Fixes #299 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by KhafiaAyyub** [comment]
Hey @Aryamanz29 , you are requested to review and  let me know if any changes needed.

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
- Update your fork repo
- Put your doc inside `section-4/`
- Rename your doc `4.7_Outreacy_Program.md`

**Comment by KhafiaAyyub** [comment]
@Aryamanz29 please review. I have done the changes

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Please delete that `outreachy doc` from that loc  👇
Screenshot from 2021-09-18 17-12-28

**Review by Aryamanz29 — APPROVED** [review]
Great , thanks for contributing @KhafiaAyyub  🎉🎉

**Pull request merged**
