### PR TITLE
Constructor and destructor in c++

### LINKED ISSUE #858: Documentation in Constructor and destructor in cpp
<hr>

Introduction to Constructor and Destructor in classes in cpp  .

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by roopali-1**
<hr>

## Description 📜

in this I explain about Constructors and Destructors in c++
Fixes #858 

<hr>

## Type of change 📝

- [x ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Suvraneel** [comment]
@roopali-1  always make prs to the cpp branch and not main... (I fixed it this time)

**Comment by Suvraneel** [comment]
@roopali-1  Everything is perfect... remove  Python/What_is_python_interpreter/python_interpreter.md file
And I can merge

**Comment by roopali-1** [comment]
Okk sir i will make sure this next time

**Comment by roopali-1** [comment]
@Suvraneel sir what i have to remove i am not getting that ... can you please elaborate???? I have to remove the md file ..?? Or what ???

**Comment by Saviour1001** [comment]
@roopali-1 The Python file is not required in this PR as it is from a different domain, so just remove that and its ready to merge. If you want to contribute to multiple domains, you should create multiple branches so that the work of different domains stay separated. 
image

**Comment by roopali-1** [comment]
@Saviour1001 yes sir I deleted that python file ... now it is all ok ?

**Pull request merged**
