### PR TITLE
Data Science with Python : Drug Classification #3523

### LINKED ISSUE #3523: Data Science with Python : Drug Classification
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Drug Classification. Tutorial to Drug Classification using various algorithms and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Arya / Yash Goel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by Deepika-Pavundoss**
<hr>

## Description 📜

Code for Drug Classification using various Machine Learning algorithms (Contains code and its explanation)
 
Fixes #3523

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Deepika-Pavundoss** [comment]
Please evaluate @prathimacode-hub @AryaPatel1111 @Yash621
Name: Deepika Pavundoss
Issue: Data Science with Python : Drug Classification #3523
Type: Documentation
Batch number: 5
Serial number: 161

**Review by AryaPatel1111 — CHANGES_REQUESTED** [review]
I see you have done really good work with the code and explanation. Also, README file is containing good amount of knowledge. Can you either add the link or the dataset itself in the directory. Just in case someone wants to try it out.

**Comment by Deepika-Pavundoss** [comment]
Yeah I've added it in the DS datasets folder

**Review by AryaPatel1111 — APPROVED** [review]
Good work @Deepika-Pavundoss. Keep up the good work.

Waiting for the Supervisor to merge the changes.

**Comment by Deepika-Pavundoss** [comment]
Ma'am, could you please add hacktoberfest-accepted label, if possible? @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 🙌👌@Deepika-Pavundoss

**Pull request merged**
