### PR TITLE
Issue No - 924 - Pointers and Two Dimensional Array - Updated path of directory.

### LINKED ISSUE #924: Pointers and Two Dimensional Arrays in C
<hr>

## Description 📜

This will explain how we can access array elements using pointers. This thing is very helpful while working with a function that takes array as an argument.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Type of Contribution

- Documentation

### PR DESCRIPTION
**Pull request by kashyap1905**
<hr>

## Description 📜

Updated path as -  Pointer and its types/Introduction to Pointers/Pointers & 2D Array/Documantaion.md 
Fixes #924  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by kashyap1905** [comment]
@Suvraneel Updated the path as per your direction. Please review it sir.

**Review by Suvraneel — CHANGES_REQUESTED** [review]
1.
Put Diagram under 
C_CPP/Pointer and its types/Pointers & 2D Array/    as well

2. 
Add a line to readme of :
C_CPP/Pointer and its types/readme.md

- [Pointers & 2D Array](Pointers & 2D Array/ )

**Comment by kashyap1905** [comment]
@Suvraneel Made changes as per your direction. Please review it sir.

**Comment by Suvraneel** [comment]
@kashyap1905  Perfect...
See this and tell me if you understand relative links now

**Pull request merged**
