### PR TITLE
[Frontend_Web_Development_HTML_CSS_JS] Topic: Developer Console

### LINKED ISSUE #1621: Frontend_Web_Development_HTML_CSS_JS: Developer Console
# Developer Console

Create a tutorial on Developer Console

# Directory
```
Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/8.Developer_Console
```

# Description 📜
Creating a tutorial on Developer Console for Front_End_Web_Development_HTML_CSS_JS branch and discussing the following:
- What is Developer Console?
- Working with the Console in a Browser
- Chrome
- Firefox
- Other Browsers
- Understanding Other Development Tools

# Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

# Format

- [x] Documentation

### PR DESCRIPTION
**Pull request by aniketpathak028**
# Description 📜

Created a tutorial on Developer Console, and elaborated on the following topics:
- What is Developer Console?
- Working with the Console in a Browser
- Chrome
- Firefox
- Other Browsers
- Understanding Other Development Tools

Fixes #1621

# Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

# Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

# Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by aniketpathak028** [comment]
@moulikagrawal could you review this PR please

**Comment by aniketpathak028** [comment]
@moulikagrawal could you review this PR pls

**Review by moulikagrawal — CHANGES_REQUESTED** [review]
A high amount of plagiarism found. The content should not be plagiarized, you are free to rephrase the sentence & take an idea though.

**Comment by aniketpathak028** [comment]
@moulikagrawal As you suggested, I have rephrased the sentences, and restructured the paragraphs, to make this PR as original as possible, please review again and suggest changes if necessary.
Thanks

**Review by moulikagrawal — CHANGES_REQUESTED** [review]
[smallseotools-1632460482.pdf](https://github.com/girlscript/winter-of-contributing/files/7223017/smallseotools-1632460482.pdf)

Refer to this and try to increase originality.

**Comment by aniketpathak028** [comment]
@moulikagrawal I worked upon the changes you suggested and increased the originality to 96%, it's still 4% plagiarized, but those are very common sentences, hence might have matched with multiple documents on the web. I have attached the report below:
[smallseotools-1632543311.pdf](https://github.com/girlscript/winter-of-contributing/files/7229130/smallseotools-1632543311.pdf)
Please review again and suggest any changes if necessary.
Thanks

**Review by moulikagrawal — APPROVED** [review]

**Pull request merged**
