### PR TITLE
Data Science with Python : Sentiment Analysis

### LINKED ISSUE #419: Data Science with Python : Sentiment Analysis
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Sentiment Analysis. Tutorial to Sentiment Analysis and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : [Nithin](https://github.com/Nithin-Reddy-02) / Gauri Bharadwaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by divya-chhoriya**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #419 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [x] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
This PR is currently under reviewing process

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The issue contribution should be under "/Natural Language Processing/Tutorials/Sentiment Analysis
The project file name should be in snake case : sentiment_analysis.ipynb
Add a summary of your work in your .ipynb file after you are done with code implementation
Your README.md lacks details. It needs more information. For an idea or reference, you can refer to the project structure provided to know of what all tpics that can be added up into it.
You can also add your screenshots or images of your final outcomes in "Images" folder created under "Sentiment Analysis"

Your notebook file is worth appreciating. 
Kindly work on it. @divya-chhoriya

**Comment by divya-chhoriya** [comment]
Ok will work on it.

**Comment by divya-chhoriya** [comment]
@prathimacode-hub I cannot upload the dataset which I have used because it's a large file greater than 25MB. So I have mentioned the link in README.md and also in my .ipynb file.
I have done all changes that were required. Let me know if there are any other changes.👍🏻

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats on your first PR. Very well represented. Great start. 👏✔@divya-chhoriya

**Pull request merged**
