### PR TITLE
Boolean Data Type in Python #971

### LINKED ISSUE #971: Boolean Data Type in Python
<hr>

## Description 📜

Documentation on Boolean Data Type in Python

<hr>

## Domain of Contribution 📊

- [ ] Python

<hr>

### PR DESCRIPTION
**Pull request by AswathiGR**
<hr>

## Description 📜

Dcoumentation for Boolean Data Type in Python
Fixes #971 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by AswathiGR** [comment]
@rishabhrathore055 we shouldn't use  /assign in pr session, as mentioned in the python general channel of GWOC. Kindly click unassign.

**Comment by AkkineniYogitha** [comment]
If this issue is not yet assigned to anyone, I would be happy to work on it.
Name: Akkineni Yogitha
Python Batch: 1
Preference: Documentation

**Comment by AswathiGR** [comment]
@AkkineniYogitha  This is a pr session. If you want to work on this issue, please comment in the issue session. Currently, its documentation and video part is already assigned.

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
