### PR TITLE
Variables

### LINKED ISSUE #3135: Add the Programming Fundamentals of JavaScript
### Description

Add the Programming Fundamentals of JavaScript as defined in JavaSript RoadMap

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Sin-Sumit**
Add the Variables in Programming Fundamentals of JavaScript

<hr>

## Description 📜
Fixes #3135 
Add the Variables in Programming Fundamentals

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] My changes generates no new warnings.
- [ X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Sin-Sumit** [comment]
@sifa123 Please make a review.

**Review by sifa123 — CHANGES_REQUESTED** [review]
Please do not copy-paste. Write in your way, what you understand, do more research, but do not copy-paste. Take your time.

**Comment by Sin-Sumit** [comment]
HEy, @sifa123 Thanks for review and now I add extra words. Please review.

**Comment by Sin-Sumit** [comment]
Hey, @sifa123  please add the hacktoberfest label in FEWD issues, so that it will be counted in hactoberfest

**Comment by Sin-Sumit** [comment]
Hey @sifa123 I change the variables & Data Types files, Please review it.

**Review by sifa123 — APPROVED** [review]
Great!

**Pull request merged**
