### PR TITLE
Linked_List_Implementation_of_Stacks.md

### LINKED ISSUE #7538: Linked_List_Implementation_of_Stacks
### Description

Description
Linked List Implementation of Stacks

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by varnikarathee**
<hr>

## Description 📜Linked_List_Implementation_of_Stacks.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7538 

<hr>

## Type of change 📝Linked_List_Implementation_of_Stacks.

- [X] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] DS#A

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
@varnikarathee your PR format isn't correct. In your fork, commit changes in DSA branch and not main and then create a new branch and point to GWOC DSA branch in the PR. Once your PR shows 1 file changed instead of 717 then that would be the correct way.

**Comment by varnikarathee** [comment]
@nimisha-yadav Do i need to create a new pr ? like i have  tried but i m unable to gain clarity on how to do it.

**Comment by nimisha-yadav** [comment]
Follow these steps.
Save your documentation somewhere. 
Close this PR. Delete your fork.
Fork again. Go to DSA branch in GWOC repo. Add your file in required folder. Commit the changes in a new branch like eg patch 6 in DSA branch itself. Create a PR from patch 6(example) to GWOC DSA branch.

**Comment by varnikarathee** [comment]
@nimisha-yadav 
Done.
This is the new PR 
https://github.com/girlscript/winter-of-contributing/pull/8420
Please review and merge it.

**Pull request closed without merging**
