### PR TITLE
Python: Loops- pass Fixes #562

### LINKED ISSUE #562: Python: Loops- pass
### Description :
What is `pass` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by shrey-ya**
<hr>

## Description 📜

Video explaining pass statement in python loops
Fixes #562 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by shrey-ya** [comment]
Fixes #562

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@shrey-ya 

image

As shown in the output of this program there is an extra ```None``` which you have not addressed. It comes because the function you've written does not return anything. It will be  better if you point that out as well since the viewers might get confused. Excellent work otherwise!

**Comment by shrey-ya** [comment]
@apeksha235 I have made the changes, you can have a look now!

**Review by apeksha235 — APPROVED** [review]
@shrey-ya Amazing!! 
@adityabisoi please merge this

**Comment by adityabisoi** [comment]
Can you ping me in discord

**Pull request merged**
