### PR TITLE
Java: impact of Java on internet

### PR DESCRIPTION
**Pull request by aashigupta355**
<hr>

## Description 📜

I added impact of Java on Internet document.
Fixes # 1106 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by sumitaccess007 — COMMENTED** [review]
@garvitraj, Review is okay. We can proceed to merge this PR.

**Comment by AkMo3** [comment]
@sakshamlamba109 Please review it once and lets us know if something more needs to be added.

**Comment by sakshamlamba109** [comment]
@AkMo3 LGTM.
We can proceed with it

**Review by sakshamlamba109 — APPROVED** [review]
LGTM @AkMo3

**Review by AkMo3 — APPROVED** [review]

**Pull request merged**
