### PR TITLE
Exception Handling in C++ (file added)

### PR DESCRIPTION
**Pull request by 1PRatgit**
<hr>

## Description 📜

This document explains about Exceptions in C++ and how they are handled. 
Fixes # 966 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Use proper identations in code section.
Rest is good to be merged.

**Comment by 1PRatgit** [comment]
Thanks for the review. can you please suggest how to change it. I mean, need to add another pull request.

**Comment by deeqakkk** [comment]
> Thanks for the review. can you please suggest how to change it. I mean, need to add another pull request.

don't make another PR, just do changes in this one itself.

**Review by apeksha235 — APPROVED** [review]
Amazing.. @Suvraneel please merge this

**Pull request merged**
