### PR TITLE
Cybersecurity Issue #2800 - Practical-Create own virus

### PR DESCRIPTION
**Pull request by AtharvaaPatil**
3.9.6 Create own virus (documentation) added

<hr>

## Description 📜

Added documentation on the topic - Create own virus. 
Fixes # <1.9> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Cyber Security

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>``

### CODE REVIEW

**Review by Anant1711 — APPROVED** [review]
@AtharvaaPatil 
I saw this code is commented by someone else on some website!
But okay I'll merge it because you wrote something by yourself.
Next time please keep this in mind!

**Comment by Anant1711** [comment]
Second Thing, I think you commit in another directory rather than `cyber_Security`.
Please correct it, otherwise I can't merge i
Capture
t!

**Review by Anant1711 — CHANGES_REQUESTED** [review]
.

**Comment by AtharvaaPatil** [comment]
Thankyou, I'll edit the commit and correct it.

**Pull request closed without merging**
