### PR TITLE
Create Kadane's Algorithm 

### LINKED ISSUE #7811: Kadane’s Algorithm
### Description

Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers that has the largest sum. 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Mahi1901**
The basic idea of Kadane’s algorithm is to find all positive contiguous segments of the array (max_ending_here is used for this). At the same time, keep a track of maximum sum contiguous segment among all positive segments (max_so_far is used for this). Each time we get a positive-sum compare it with max_so_far and update max_so_far if it is greater than max_so_far

<hr>

## Description 📜

Kadane’s Algorithm is an iterative dynamic programming algorithm. It calculates the maximum sum subarray ending at a particular position by using the maximum sum subarray ending at the previous position.
Fixes #7811

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Put your file in appropriate directory

**Comment by vasu-1** [comment]
I guess your file should go  in `/C_CPP/Algorithmic Approaches/Dynamic/` directory

**Comment by vasu-1** [comment]
Also add your file link into the respective readme file

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
Add a md file and include code in it in snippet form.

**Pull request closed without merging**
