### PR TITLE
Create When to use which Sorting Algorithm.md

### LINKED ISSUE #3308: When to use which sorting algorithm
### Description

I want to create documentation on comparison of different sorting algorithms and when to use which 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by onlykingKD**
<hr>

## Description 📜
Included Documentation about when should we prefer which of the various Sorting algorithms
Fixes #3308

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by goelesha — CHANGES_REQUESTED** [review]
@onlykingKD Pls include the examples of each type of case which you are discussing and try to compare with the scenario if you use some other algo to solve that problem.
Also, include references.

**Comment by onlykingKD** [comment]
> @onlykingKD Pls include the examples of each type of case which you are discussing and try to compare with the scenario if you use some other algo to solve that problem. Also, include references.


@goelesha  Ma'am comparisons and giving examples would have been easier if the doc was about two or three sorting algorithms. But here I have included 9 sorting algorithms. So comparison is not feasible.  For the comparisons purpose I have included the reference links as you told which include the relevant examples also. Also I have included a chart comparing various various sorting algorithms.

**Review by goelesha — CHANGES_REQUESTED** [review]
@onlykingKD Only references won't work. Pls, explain at least one or two points in each algorithm. Otherwise, it's just copying and pasting from some source. Pls add your own explanation

**Comment by onlykingKD** [comment]
> @onlykingKD Only references won't work. Pls, explain at least one or two points in each algorithm. Otherwise, it's just copying and pasting from some source. Pls add your own explanation

@goelesha  Yaa OK I will do it soon. Thanks !

**Comment by goelesha** [comment]
@onlykingKD Congrats on getting your PR merged.

**Pull request merged**
