### PR TITLE
[+]Frontend with Framework : Introduction to Vue documentation

### LINKED ISSUE #405: Frontend With Framework - Introduction to Vue
### **NEED TO CONTAIN**

*  What is Vue.js
*  Why Vue.js
*  Advantage of Vue.js
*  Dis Advantages of Vue.js

can take referance form [https://vuejs.org/v2/guide/](url)

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ Vue inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

### PR DESCRIPTION
**Pull request by YASHMAROO**
<hr>

## Description 📜

Added documentation for an introduction to Vue.js, its advantages, and disadvantages, and also why it should be used.
Fixes #405  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by anandhu720** [comment]
@YASHMAROO  First thing,Please make sure you add Frontend with Framework before your PR heading as per instructions.Please take care this thing in next PR.Else your PR will be losted in tones of PR.

**Comment by SourabhSaraswat-191939** [comment]
Good Job @YASHMAROO,
But there are some changes needed. 
1) There are some typing errors.
2) The pros and cons you mentioned can be improved. I will just advise you to go through the latest surveys and check them. You can also see StackOverflow's 2020 survey and as per that Vue.js is just 2.9% below to that of react in the list of most loved web framework.
https://insights.stackoverflow.com/survey/2020#technology-most-loved-dreaded-and-wanted-web-frameworks

**Review by anandhu720 — CHANGES_REQUESTED** [review]
please make changes according to @SourabhSaraswat-191939  comment.Also dont create new folder called images,please add your image in assets folder inside week 1

**Comment by YASHMAROO** [comment]
> please make changes according to @SourabhSaraswat-191939 comment.Also dont create new folder called images,please add your image in assets folder inside week 1

I would surely make the necessary changes @anandhu720 and @SourabhSaraswat-191939

**Comment by YASHMAROO** [comment]
@SourabhSaraswat-191939 please review the new changes made

**Comment by SourabhSaraswat-191939** [comment]
@YASHMAROO  LGTM 👍🏻

**Comment by YASHMAROO** [comment]
> @YASHMAROO LGTM 👍🏻

Do I need to do anything else before my PR is merged @SourabhSaraswat-191939 ?

**Comment by SourabhSaraswat-191939** [comment]
> Do I need to do anything else before my PR is merged @SourabhSaraswat-191939 ?

No, it looks good.

@anandhu720, please merge this PR.

**Review by anandhu720 — APPROVED** [review]
Good work bro

**Comment by YASHMAROO** [comment]
@anandhu720 please add the GWOC'21 label and other necessary labels for this PR and kindly remove the review needed label.

**Pull request merged**
