### PR TITLE
Data Science with Python : Bagging and Boosting

### PR DESCRIPTION
**Pull request by ishreyakumari**
<hr>

## Description 📜

I added readme file which contains descriptive explanation of Bagging and Boosting. I also added 1 python notebook which contains code snippets for better understanding.
Fixes : #367  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

> There are around 160 unrelevant files but nothing considered to this issue title. Kindly check on to it. @ishreyakumari

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

Instead of getting directly with code implementation in .ipynb file, give a short introduction of from bagging and boostly had popped up from. Give intro and then put up bagging and boosting. It should be like a flow. Just like topics, it's harder to understand
The project file name should be in snake case : bagging_and_boosting.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Bagging and Boosting"
Your README file needs more details. You can find the things you can add up in Project structure document like features, usage, advantages, how it's optimized, applications, proper conclusion of work you had done and final outcome like an overall sumary of your issue.
The readme file should be as "README.md

Kindly work on it. @ishreyakumari

**Comment by prathimacode-hub** [comment]
Your PR is currently under reviewing process.

**Comment by ishreyakumari** [comment]
> Changes to be done 👍
> 
> Instead of getting directly with code implementation in .ipynb file, give a short introduction of from bagging and boostly had popped up from. Give intro and then put up bagging and boosting. It should be like a flow. Just like topics, it's harder to understand
> The project file name should be in snake case : bagging_and_boosting.ipynb
> If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Bagging and Boosting"
> Your README file needs more details. You can find the things you can add up in Project structure document like features, usage, advantages, how it's optimized, applications, proper conclusion of work you had done and final outcome like an overall sumary of your issue.
> The readme file should be as "README.md
> 
> Kindly work on it. @ishreyakumari

@prathimacode-hub Thank you Prathima. Can you please confirm the path of image folder. Is it data science with python/machine learning/Bagging and Boosting/Images?

**Comment by prathimacode-hub** [comment]
> > Changes to be done 👍
> > Instead of getting directly with code implementation in .ipynb file, give a short introduction of from bagging and boostly had popped up from. Give intro and then put up bagging and boosting. It should be like a flow. Just like topics, it's harder to understand
> > The project file name should be in snake case : bagging_and_boosting.ipynb
> > If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Bagging and Boosting"
> > Your README file needs more details. You can find the things you can add up in Project structure document like features, usage, advantages, how it's optimized, applications, proper conclusion of work you had done and final outcome like an overall sumary of your issue.
> > The readme file should be as "README.md
> > Kindly work on it. @ishreyakumari
> 
> @prathimacode-hub Thank you Prathima. Can you please confirm the path of image folder. Is it data science with python/machine learning/Bagging and Boosting/Images?

No it should be in "/Datascience_with_Python/Machine Learning/Algorithms/Bagging and Boosting/Images.
Along with it, also add up the respective datasets used in "DS Datasets" in "Machine Learning" folder and resources referred in "DS Resources" in "Machine Learning" folder. @ishreyakumari

**Comment by prathimacode-hub** [comment]
There are around 160 unrelevant files but nothing considered to this issue title. Kindly check on to it. @ishreyakumari

**Comment by ishreyakumari** [comment]
> There are around 160 unrelevant files but nothing considered to this issue title. Kindly check on to it. @ishreyakumari

@prathimacode-hub Sorry for that. I am new to git. I created new request will all the changes stated by you. Please review that - https://github.com/girlscript/winter-of-contributing/pull/2070.

**Pull request closed without merging**
