### PR TITLE
Create 5.48 Explain everything related to THANOS.md

### LINKED ISSUE #686: OpenSource : 5.48 Explain everything related to `THANOS`
### Description :

- **Explain everything related to `THANOS`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by sandeepkumar00110**
thanos

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #686

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Suvraneel** [comment]
@sandeepkumar00110 
Delete all other domains from your comment.. like mentioned in official GWOC PR template directives
Kindly follow the issue template from next time ... & preach this to your fellow contributors

**Comment by sandeepkumar00110** [comment]
ok sir

**Comment by sandeepkumar00110** [comment]
file name changed

**Comment by Aryamanz29** [comment]
> file name changed

Add images in your `doc` @sandeepkumar00110

**Review by Aryamanz29 — APPROVED** [review]
Awesome, Thanks for contributing 🎉🎉

**Pull request merged**
