### PR TITLE
DSA 1.1.2.6 Array Rotation some O(N) problems

### LINKED ISSUE #452: DSA 1.1.2.6 Array Rotation some O(N) problems
## Description
Left rotation, rotations required to sort array, elements at index I after k rotations.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by arjyo851**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #452 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
 

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Subhradeep10 — COMMENTED** [review]
@arjyo851 Can you add some picture..along with the documentation.
It will look more attractive!

**Comment by arjyo851** [comment]
OK I will add it soon!

**Comment by arjyo851** [comment]
is this alright @Subhradeep10 ?

**Comment by Subhradeep10** [comment]
@arjyo851 Perfect

**Review by Subhradeep10 — APPROVED** [review]

**Pull request merged**
