### PR TITLE
String implementation in java-Audio 

### PR DESCRIPTION
**Pull request by afreenabegum**
Hi mam @nimisha-yadav .
Issue: Implementation of strings in java- Audio
I have made required changes .once please check my PR.
Thank you.

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Follow this Git Workflow, we've mentioned everything here: https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#git-workflow

If you still face problems, seek guidance from the mentors over Discord.

**Comment by afreenabegum** [comment]
Hi mam @nimisha-yadav .
Sorry for pinging  you again and again.
I completed my work mam but am not getting without creating any branch how do I  do push after reading guidelines too.
Please help me mam .I am not finding any mentors too in server
I scared that my work will go into vain and I'll lose this opportunity.
I also tried to text dm u but its not accepting.

Please help me mam.

**Comment by nimisha-yadav** [comment]
> Hi mam @nimisha-yadav . Sorry for pinging you again and again. I completed my work mam but am not getting without creating any branch how do I do push after reading guidelines too. Please help me mam .I am not finding any mentors too in server I scared that my work will go into vain and I'll lose this opportunity. I also tried to text dm u but its not accepting.
> 
> Please help me mam.

Okay don't worry. Let's have a google meet today at 11pm, is that okay? @afreenabegum

**Comment by afreenabegum** [comment]
> @afreenabegum accept my request on discord or change your discord setting to anyone can DM you. Then, we can discuss there.

Accepted mam .But unable to send message.

**Pull request closed without merging**
