### PR TITLE
OpenSource : 4.6 Explain everything related to the Google Season of Docs (GSoD) 

### LINKED ISSUE #294: OpenSource : 4.6 Explain everything related to the `Google Season of Docs (GSoD)`
### Description :

- **Explain everything related to the `Google Season of Docs (GSoD)`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by yashikabhargava**
## **Explain everything related to the Google Season of Docs**
<hr>

## Description 📜

Done Documentation (Content Creation in the form of codes or tutorials) on Explain everything related to the Google Season of Docs.
Fixes #294 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅
- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

GSoD

<hr>

### CODE REVIEW

**Comment by yashikabhargava** [comment]
@Aryamanz29 can you please review my PR.

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Clean work , Nice @yashikabhargava  🎉🎉
Could you please rename your file to `4.6_Google_Season_of_Docs.md `, So I'll move forward to merge your work
Thanks

**Comment by yashikabhargava** [comment]
> Clean work , Nice @yashikabhargava 🎉🎉
> Could you please rename your file to `4.6_Google_Season_of_Docs.md `, So I'll move forward to merge your work
> Thanks

Thank you @Aryamanz29  
yes i'll rename it.

**Review by Aryamanz29 — APPROVED** [review]
Awesome, LGTM
Thanks for contributing 🎉🎉

**Pull request merged**
