### PR TITLE
Data Science with Python : Cheatsheet on Open CV Library

### LINKED ISSUE #7063: Data Science with Python : Cheatsheet on Open CV Library
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, readers will get a detailed Cheatsheet on OpenCV library.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Computer Vision

Mentors Assigned : Ankit Kumar | Yash Goel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by singhmansi25**
<hr>

## Description 📜

This issue deals with the documentation for cheat-sheet for matplotlib library of Python.
The readme.md will contain the codes and a .ipynb file will contains all the demonstration of all the codes.
Fixes #7063 

<hr>

## Type of change 📝

-  Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

-  Datascience with Python

<hr>

## Checklist ✅

-  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
-  I have performed a self-review of my own code or work.
-  I have commented my code, particularly in hard-to-understand areas.
-  My changes generates no new warnings.
-  I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by singhmansi25** [comment]
@prathimacode-hub 
Please review my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README can be elaborate, first introduce what is computer vision, what is open cv and how it's categorized, how it's applied, why its useful, its advantages. And also code snippets can be added up more in .ipynb to cover up all the angles of OpenCV. @singhmansi25

**Comment by singhmansi25** [comment]
@prathimacode-hub Please review my PR again
Thanks

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Wonderful work.✔✨@singhmansi25

**Pull request merged**
