### PR TITLE
added modular arithmetic

### LINKED ISSUE #884: Modular Arithmetic in C++
<hr>

## Description 📜

I want to Create an Documentation explaining the concepts of Modular Arithmetic in C++ with some code examples too.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### LINKED ISSUE #2889: Modular Arithmetic in C++
### Description

<hr>

## Description 📜

I want to Create an Documentation explaining the concepts of Modular Arithmetic in C++ with some code examples too.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by kaustubh0777**
<hr>

## Description 📜
Explained About the Concepts, Properties of Modular Arithmetic with some code examples in C++. I have also mentioned some important algorithms based on Modular Arithmetic 
Fixes #2889 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Saviour1001** [comment]
Great work on a content, could you just place it in Competitive Programming folder and this PR is good to merge

**Comment by kaustubh0777** [comment]
Done with Changes

**Comment by Saviour1001** [comment]
image
Remove the file from C++17 folder and make a commit and push.

**Comment by kaustubh0777** [comment]
Done Removing the modular_arithmetic.md file from C++17 folder

**Comment by Saviour1001** [comment]
Awesome work @kaustubh0777 !!

**Pull request merged**
