### PR TITLE
MERN_React: 2.3 Basics of React.createElement() #996 - Srijan Shovit

### LINKED ISSUE #996: MERN_React: 2.3 Basics of React.createElement()
<hr>

## Description 📜

# Instructions 

## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## Why and What is React.createElement()?
Write a brief summary on what is React.createElement()? Why it is used and when to use it? Please refrain from coping from internet. You can use any source as inspiration. 

# Task 
- [ ] Audio
- [ ] Documentation
- [ ] Video

<hr>

## Domain of Contribution 📊

- [X] MERN

<hr>

### PR DESCRIPTION
**Pull request by SrijanShovit**
<hr>

## Description 📜

I have worked on the documentation part of Basics of React.createElement() (including what it is, why and where it is used).
I have created React.createElement() #996.ipynb file and also included screenshots in it. 
Fixes #996 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [x] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by hardikk2002 — CHANGES_REQUESTED** [review]
@SrijanShovit 
Hey once check the file name that you have given, It should be corrected. 
- Current:
  ```
  MERN/Topic/Frontend/React/React.createElement() #996.ipynb
  ```
  
- Update it to:
  ```
  MERN/Topic/Frontend/React/2.3_Basics_of_React.createElement().md
  ```

**Comment by Artistic18** [comment]
@SrijanShovit are you still working on it?

**Comment by SrijanShovit** [comment]
@Artistic18 Yes ,actually I had worked and submitted.

**Comment by SrijanShovit** [comment]
@hardikk2002 I have renamed the file. Could you confirm whether it's fine now?

**Review by Artistic18 — APPROVED** [review]

**Comment by hardikk2002** [comment]
@SrijanShovit Hey actually I am not able to see the content in the proper format, in the PR that you have created. So that's why I have not accepted the PR, till now. See the image below:
---
image
---
That's what is visible.
@Artistic18 Are you able to see the proper written content?? If yes then please share the SS.
Thenks!

**Comment by Artistic18** [comment]
@hardikk2002 

It's an .ipynb file, there's should be an option somewhere in the top left to view a file.

Untitled

**Comment by Artistic18** [comment]
@hardikk2002 
Screenshot 2021-09-29 203955

**Comment by Artistic18** [comment]
@hardikk2002 it was visible earlier.
@SrijanShovit Please check the the contents of the file again and re-upload, leaving that aside it's still visible in google colab.

**Review by Artistic18 — CHANGES_REQUESTED** [review]
@SrijanShovit  I think you have changed a .ipynb file to .md extension. Please change back the extension.

**Comment by Artistic18** [comment]
> * Current:
>   ```
>   MERN/Topic/Frontend/React/React.createElement() #996.ipynb
>   ```
> * Update it to:
>   ```
>   MERN/Topic/Frontend/React/2.3_Basics_of_React.createElement().ipynb
>   ```

**Comment by hardikk2002** [comment]
> @SrijanShovit I think you have changed a .ipynb file to .md extension. Please change back the extension.

I see, but as we have to work with `.md ` files only so @SrijanShovit you need to convert your `.ipynb` file format to the markdown supported format, to make it work with `.md` files.

**Review by hardikk2002 — CHANGES_REQUESTED** [review]
Just saw your work [here](https://github.com/girlscript/winter-of-contributing/blob/3f00824daba5a3fdac361b600f559873708bf6a5/MERN/Topic/Frontend/React/React.createElement()%20%23996.ipynb), in commit history.

~~You have really worked on the issue, but unfortunately, this Jupyter Notebook format is not supported in this program.
So simply copy-paste your text from that file to the ".md" file. And to make it look good see how to apply markdown syntax from [here](https://guides.github.com/features/mastering-markdown/).~~

Edit: @SrijanShovit please follow @Artistic18 's suggested review, before I was thinking of something else.

Thanks!

**Comment by SrijanShovit** [comment]
@Artistic18 @hardikk2002 I have renamed the file from MERN/Topic/Frontend/React/2.3_Basics_of_React.createElement().md to 
MERN/Topic/Frontend/React/2.3_Basics_of_React.createElement().ipynb

Kindly confirm

**Review by hardikk2002 — APPROVED** [review]

**Review by manjeetdhayal — APPROVED** [review]
Hey @SrijanShovit Please try to work with markdown file. I'm merging this time but its better if you make a .md file instead

**Pull request merged**
