### PR TITLE
Datascience with python : XGBoost Algorithm Issue 

### PR DESCRIPTION
**Pull request by NikitaEmberi**
<hr>

## Description 📜

In this tutorial, I have explored XGBoost algorithm of Machine learning, starting from basic understanding of boosting, XGboosting, history, advantages, unique features, difference between xgboost and gradient boosting, I tried to cover every aspect of Xgboost algorithm including the math that goes behind with it and code implementation of XGBoost on Boston dataset. 
Fixes # 417

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [X] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

The images you had added up in README.md are not visible. Kindly check if it's in right syntax.
In .ipynb file, before directly starting with implementation, add short intro on your issue topic and write final outcomes of your project at the end.

Kindly work on it. @NikitaEmberi

**Comment by NikitaEmberi** [comment]
Yes @prathimacode-hub ma'am working on it.

**Comment by NikitaEmberi** [comment]
@prathimacode-hub ma'am I have made changes as requested. Please let me know, if it's fine now.

**Comment by NikitaEmberi** [comment]
@prathimacode-hub ma'am are there any changes to be done?

**Pull request merged**
