### PR TITLE
HTML Links and images

### LINKED ISSUE #1802: HTML Links and Images
### Description

Describe HTML links and images elements along with its attributes.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by anmolx001**
<hr>

## Description 📜
Describes about Adding and using links , images , its types and respective attributes in HTML with examples. 
Fixes #1802

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by heet-kumar** [comment]
> ## Description 📜
> Describes about Adding and using links , images , its types and respective attributes in HTML with examples. Fixes # <1802>
> 
> ## Type of change 📝
> * [ ]  Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
> * [ ]  Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
> * [x]  Documentation (Content Creation in the form of codes or tutorials)
> * [ ]  Other (If you choose other, Please mention changes below)
> 
> ## Domain of Contribution 📊
> * [ ]  Android Dev #(Flutter)
> * [ ]  Android Dev #(Java)
> * [ ]  Android Dev #(Kotlin)
> * [ ]  Backend Dev #(Java)
> * [ ]  Backend Dev #(.NET)
> * [ ]  Backend Dev #(PHP)
> * [ ]  Backend Dev #(Python)
> * [ ]  C/#CPP
> * [ ]  Competitive #Programming
> * [ ]  Cyber #Security
> * [ ]  DS#A
> * [ ]  Data#base
> * [ ]  Datascience with #Python
> * [ ]  Datascience with #R
> * [x]  Frontend Dev HTML/CSS/JS
> * [ ]  Frontend Dev #React/Angular/Vue
> * [ ]  Go#lang
> * [ ]  Interview #Prep
> * [ ]  Java_#Domain
> * [ ]  Java#Script
> * [ ]  ME#RN
> * [ ]  Machine #Learning
> * [ ]  Open #Source
> * [ ]  Python_#Domain
> * [ ]  Ru#st
> * [ ]  Statis#tics
> * [ ]  UI/#UX
> 
> ## Checklist ✅
> * [x]  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
> * [x]  I have performed a self-review of my own code or work.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  My changes generates no new warnings.
> * [x]  I'm GWOC'21 contributor
> 
> ## Screenshots / Gif (Optional) 📸

just write in the description properly Fixes #1802

**Review by heet-kumar — CHANGES_REQUESTED** [review]
Everything else is alright LGTM !! 🍾 so then lets wait for the supervisor approval whatever changes they mention make that changes too !

**Review by heet-kumar — APPROVED** [review]
@anmolx001 amazing work done 👍 
and LGTM !!!

**Review by anmolx001 — COMMENTED** [review]
Changes done, Kindly review.

**Comment by anmolx001** [comment]
@code-reaper08, Please review.

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
## ⚠️⚠️⚠️100% plagiarized ⚠️⚠️⚠️

Hello @anmolx001
The content you've done, is **100% plagiarized** from https://www.w3schools.com/html/html_links.asp
image
This is not we expect and it's not good for your open-source journey too. Taking inspiration from other websites is completely accepted, but completely ripping off content and plagiarizing is not at all accepted. 

I'm closing this PR now, if you plan to rephrase and correct the content, please tag me or @2024-SANDHYA here in the same thread.

**Pull request closed without merging**
