### PR TITLE
Added Linking User Accounts.md

### LINKED ISSUE #6851: Flutter: Any Topic Related to Firebase, with Flutter
### Description

Create new issues, for topics of Firebase, with Flutter.
You can take reference from : https://firebase.flutter.dev/

You are allowed to open any number of issues and can assign it to yourself. No need to ask for mentors or supervisors. Just check that is the topic is already covered to not.

### Domain

Android Dev (Flutter)

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Gagarod**
<hr>

## Description 📜

Created Linking User Accounts.md file explaining the process of how to link authentication providers.
Fixes #6851 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Gagarod** [comment]
@ViAsmit Please check it and merge if everything is good.

**Review by Procoder16 — APPROVED** [review]
@ViAsmit you may merge this now

**Comment by ViAsmit** [comment]
Thanks @Gagarod  @Procoder16

**Comment by Procoder16** [comment]
No problem 😊👍

**Pull request merged**
