### PR TITLE
HTML FORMS 

### LINKED ISSUE #199: 1. Basic HTML TAGS
**1.HTML TAGS WITH THIER USES**
**2.EXAMPLE CODE TO RUN**
**3.SCREENSHOTS OF OUTPUT**

please assign this to me. I am a gwoc contributor

### PR DESCRIPTION
**Pull request by siddhi-244**
<hr>

## Description 📜

Added html forms
Fixes #199 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by siddhi-244** [comment]
@praveenscience please check this pr!

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
You could add more input attributes. Some less known attributes could also be included. In that way it would be more awesome :-)

**Comment by siddhi-244** [comment]
> You could add more input attributes. Some less known attributes could also be included. In that way it would be more awesome :-)

Ok sir !

**Comment by siddhi-244** [comment]
@code-reaper08  Sir done !

**Comment by siddhi-244** [comment]
Sir someone assigned this pr to themselves plzz see to it as well. @code-reaper08

**Comment by code-reaper08** [comment]
> Sir someone assigned this pr to themselves plzz see to it as well. @code-reaper08

No issues, I think so, coz they've assigned themself to the issue.
Not to worry!

**Comment by siddhi-244** [comment]
Sir plzz review the pr as other people are also opening issues for html forms.

**Comment by siddhi-244** [comment]
@code-reaper08 sorry I have made the changes.

**Comment by code-reaper08** [comment]
> Sir plzz review the pr as other people are also opening issues for html forms. Also I am unable to open other issues.

No need to worry of other issues @siddhi-244 
I've requested for review from @praveenscience sir. Kindly just wait a bit.

**Comment by siddhi-244** [comment]
> > Sir plzz review the pr as other people are also opening issues for html forms. Also I am unable to open other issues.
> 
> No need to worry of other issues @siddhi-244
> I've requested for review from @praveenscience sir. Kindly just wait a bit.

Ok

**Comment by siddhi-244** [comment]
It's been 13 days now @code-reaper08

**Review by code-reaper08 — APPROVED** [review]

**Pull request merged**
