### PR TITLE
Exception Handling in C++

### LINKED ISSUE #6957: Exception Handling in C++
### Description

Video about handling Exceptions in C++.

### Domain

C/CPP

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by saniya44**
<hr>

## Description 📜

C_CPP:- Video of Exception Handling in C++ #6957 issue was assigned to me. I did my best and added VIDEO_Exception Handling in C++ folder into Exception Handling directory of C_CPP branch.
Fixes #6957 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by saniya44** [comment]
@Suvraneel plz review this corrected PR. I closed previous one cause of so many mistakes.

**Comment by saniya44** [comment]
@Suvraneel Plz review this corrected PR. Closed previous one cause of so many mistakes.

**Comment by Suvraneel** [comment]
@saniya44  You havent brought over those corrections here...

For example the video link is an image there...
Also, code highlighting is gone

**Comment by Suvraneel** [comment]
@saniya44  Anyway, fixed... Just take a note

LGTM ❤️ 🚀

**Comment by saniya44** [comment]
Okay thank you. Will surely remember next time👍

**Pull request merged**
