### PR TITLE
Longest Substring without repeating characters for a string

### PR DESCRIPTION
**Pull request by TammanaNiharika**
<hr>

## Description 📜

I provided the solution for the above problem (i.e. longest substring without repeating characters) in the form of code and explanation. The code returns the substring and also the length of substring.
Fixes # <1283> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by TammanaNiharika** [comment]
@adityabisoi

**Comment by ravireddy07** [comment]
Hey @TammanaNiharika, 
Seems like you're targeting your changes to merge into `main` branch. You should target it to `Competitive_Programming` branch. Please update the PR or raise a new PR in proper way.

**Comment by ravireddy07** [comment]
@TammanaNiharika 

Please refer this below steps to contribute:

* fork the original repo.
* clone your fork in your local.
* add upstream/reference to original-repo.
* switch to your domain-branch from main.
* create a new branch on your domain-branch like contribution-1
* start working on issues, add and commit your changes.
* now, to resolve or get rid of conflicts: switch to your domain-branch and pull the latest code of your domain-branch.
* after pulling, switch to your branch contribution-1 and run git merge domain-branch
* If there are any conflicts, resolve them and commit.
* now push your changes to contribution-1 branch and make a PR.

Hope this helps.

**Comment by TammanaNiharika** [comment]
@adityabisoi 
Please review my PR

**Pull request closed without merging**
