### PR TITLE
priority queue #1612

### PR DESCRIPTION
**Pull request by Raghavshalu**
<hr>

## Description 📜

In the folder "Data Structure" I can resolve an issue about **Priority Queue** by including some pictures.On the basis:-
   - Basic Operations
   - Priority Queue Representation
Fixes # 1612

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
App Screenshot
App Screenshot

<hr>

### CODE REVIEW

**Comment by ChetasShree** [comment]
@Raghavshalu ,hey under the "Insert / Enqueue Operation" topic ,pls give one line space after the sentence and before the picture as the image is coming in between the sentence

**Comment by akratikushwah** [comment]
> This issue [has been assigned](https://github.com/girlscript/winter-of-contributing/pull/2097#issuecomment-925505762) to @akratikushwah!
> It will become unassigned if it isn't closed within 12 days. A maintainer can also add the **pinned** label to prevent it from being unassigned.

okay

**Comment by Raghavshalu** [comment]
> hey @Raghavshalu amazing work ,but under the "Insert / Enqueue Operation" topic ,pls give one line space after the sentence and before the picture as the image is coming in between the sentence

I can do it @ChetasShree(mam) can u please check it once again and merge it. Thank you!

**Review by apeksha235 — CHANGES_REQUESTED** [review]
Add comments to explain your code @Raghavshalu

**Comment by ChetasShree** [comment]
@Raghavshalu , gwoc is strict when it comes to plagiarism .
Plagiarised from here:
https://www.tutorialspoint.com/data_structures_algorithms/priority_queue.htm

**Pull request closed without merging**
