### PR TITLE
Issue #570 Solved [Zip function]

### LINKED ISSUE #570: Python: Advanced functions-zip
### Description :
What is `zip` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by Ajinkyap331**
<hr>

## Description 📜

Created a Tutorial and Documentation for Zip Function in Python  Issue no. #570 
Fixes #570

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by kumarankm** [comment]
@Ajinkyap331 Link your [Advanced_Funciton_Zip/Documentation] folder with Python root readme on the index section

**Comment by Ajinkyap331** [comment]
Sorry @kumarankm, I don't know how to do it, Is there any source from where I can get to know it

**Comment by kumarankm** [comment]
@Ajinkyap331 
https://github.com/Ajinkyap331/winter-of-contributing/tree/Zip/Python
In this link, there is a readme file right?

Open it and click the edit icon
Untitled

And add this line given in the image

Where that 
"(./Advanced_Funciton_Zip/Documentation)" is the path from the readme file which you are editing.
"[Advanced_Funciton_Zip/Documentation]" is the message need to be displayed on the readme

From next time creating the pull do the same

**Comment by Ajinkyap331** [comment]
I edited The readme file  @kumarankm

**Comment by kumarankm** [comment]
> I edited The readme file @kumarankm, do I have to pull it to my forked repository

@Ajinkyap331  Looks perfect 👍🏻 . @adityabisoi will merge your pr soon
Thanks for your contribution !🎉

**Comment by kumarankm** [comment]
> I edited The readme file @kumarankm, do I have to pull it to my forked repository

No, it will automatically do!

**Comment by Ajinkyap331** [comment]
Thank You @kumarankm @adityabisoi  for your support !!!

**Comment by adityabisoi** [comment]
You have to commit to `Python` branch, not `Main`

**Comment by Ajinkyap331** [comment]
@adityabisoi I am confused between the main, python, zip branches. Please guide me

**Comment by kumarankm** [comment]
> @adityabisoi I am confused between the main, python, zip branches. Please guide me

@Ajinkyap331 
Close this pr and create a new one by following this video.

https://youtu.be/Ud6MIDHTzhc

Sorry for the inconvenience!

**Comment by Ajinkyap331** [comment]
@kumarankm I have done a new PR check it once, please

**Comment by kumarankm** [comment]
> @kumarankm I have done a new PR check it once, please

@Ajinkyap331 Close this pr

**Pull request closed without merging**
