### PR TITLE
Python: 1.7 What is python interpreter #79

### PR DESCRIPTION
**Pull request by archismansaha**
<hr>

## Description 📜
Added file for What is python interpreter .

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes : #79 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.

- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by archismansaha** [comment]
@adityabisoi plz review my pull request.

**Comment by adityabisoi** [comment]
You have to commit to Python branch, not main

**Comment by archismansaha** [comment]
@adityabisoi is it ok?

**Comment by archismansaha** [comment]
@prathimacode-hub  mam I resolved it. Is any other change I have to made?

**Comment by prathimacode-hub** [comment]
It's still showing conflicts. @archismansaha

**Comment by archismansaha** [comment]
@prathimacode-hub  mam resolved conflicts

**Comment by archismansaha** [comment]
@prathimacode-hub  mam would you plz review my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Need more elaboration on Python Interpreter. @archismansaha

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add how it's derived from, what's the purpose, usage, how it works practically, applications, advantages, test cases, overall summary, conclusion.  @archismansaha

**Comment by nirvikagarwal** [comment]
Make the necessary changes as suggested by @prathimacode-hub. Also, add a section to explain why python is machine-independent. You can also include some diagrams to make the explanation more clear

**Comment by prathimacode-hub** [comment]
Kindly do the changes addressed. @archismansaha

**Comment by archismansaha** [comment]
Yes @prathimacode-hub  mam Sure

**Comment by kumarankm** [comment]
@archismansaha Would you like to change the changes mentioned by a mentor or can we close this pr?

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
