### PR TITLE
Add documentation for multidimensional array

### PR DESCRIPTION
**Pull request by sheki018**
<hr>

## Description 📜

I've created a documentation for multidimensional array in Java.
Fixes # 1536

<hr>

## Type of change 📝

 - [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by nandini7637 — CHANGES_REQUESTED** [review]
@sheki018 if you have used any image from some source please give image credits else everything looks good!

**Review by garvitraj — CHANGES_REQUESTED** [review]
@sheki018 pls give the image credits for the documenation

**Comment by sheki018** [comment]
All images are created by myself. I have made all these tables and graphics from Canva by myself.

**Comment by garvitraj** [comment]
Okay

**Pull request merged**
