### PR TITLE
Python: 1.7 What is python interpreter #79

### PR DESCRIPTION
**Pull request by archismansaha**
<hr>

## Description 📜
I have made the documentation of what is python interpreter.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <79> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.

- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by archismansaha** [comment]
@adityabisoi plz kindly review my work.

**Comment by adityabisoi** [comment]
you need to update the index in readme also.

**Comment by archismansaha** [comment]
@adityabisoi would you kindly plz elaborate what you meant by updating index.

**Comment by adityabisoi** [comment]
Updating index of contents in Python root folder. Plz reach out to mentors with questions on issues.

**Pull request closed without merging**
