### PR TITLE
Create 5.15 Explain everything related to Helm(#647)

### LINKED ISSUE #647: OpenSource : 5.15 Explain everything related to `Helm`
### Description :

- **Explain everything related to `Helm`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by mohitmishra786**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #647 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [x] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Rename doc to `5.15_Everything_Related_To_Helm.md`

**Comment by mohitmishra786** [comment]
> Rename doc to `5.15_Everything_Related_To_Helm.md`

Done , check now

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory

**Comment by mohitmishra786** [comment]
> Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory

Because @Kajol-Kumari  She said me in my last PR that we don't need it so I removed it

**Comment by Kajol-Kumari** [comment]
> Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory

@Aryamanz29 why do we need that readme file? It' blank anyway and I believe someone has mistakenly added it.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Comment by Aryamanz29** [comment]
> > Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory
> 
> @Aryamanz29 why do we need that readme file? It' sblank anyway and I believe someone has mistakenly added it.

@Kajol-Kumari  Because when this branch ie `Opensource` is merging with `main` it creates conflict because `C_CPP/` is merging their contributions.

**Comment by Aryamanz29** [comment]
> > Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory
> 
> Because @Kajol-Kumari She said me in my last PR that we don't need it so I removed it

*HE

**Comment by Aryamanz29** [comment]
> > Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory
> 
> Because @Kajol-Kumari She said me in my last PR that we don't need it so I removed it

One more thing, I have cloned your forked and found that you've check out the new branch ie`patch-2` from  `C_CPP` instead of `Opensource` . that's why it's showing that folder (`C_CPP/ directory`) was delete, Since in `Opensource branch` there is no `C_CPP` directory. Marking this invalid PR, Create PR from `Opensource` branch & make sure one 1 file (ie. your doc) should be changed during the process.
Thanks

**Comment by mohitmishra786** [comment]
> > > Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory
> > 
> > 
> > Because @Kajol-Kumari She said me in my last PR that we don't need it so I removed it
> 
> One more thing, I have cloned your forked and found that you've check out the new branch ie`patch-2` from `C_CPP` instead of `Opensource` . that's why it's showing that folder (`C_CPP/ directory`) was deleted, Since in `Opensource branch` there is no `C_CPP` directory. Marking this invalid PR, Create PR from the `Opensource` branch & make sure that only one 1 file (ie. your doc) should be changed during the process.
> 
> Screenshot from 2021-09-22 16-40-37
> 
> Thanks

I don't get this, what's the problem with patch-2 branch and I have deleted C/CPP one because it was empty and other reviewer asked me to do this.

**Comment by Aryamanz29** [comment]
> > > > Why did you remove the others domain `directory` **(C_CPP/readme.md)**? Please recover that, Do changes only in the `Opensource` directory
> > > 
> > > 
> > > Because @Kajol-Kumari She said me in my last PR that we don't need it so I removed it
> > 
> > 
> > One more thing, I have cloned your forked and found that you've check out the new branch ie`patch-2` from `C_CPP` instead of `Opensource` . that's why it's showing that folder (`C_CPP/ directory`) was deleted, Since in `Opensource branch` there is no `C_CPP` directory. Marking this invalid PR, Create PR from the `Opensource` branch & make sure that only one 1 file (ie. your doc) should be changed during the process.
> > Screenshot from 2021-09-22 16-40-37
> > Thanks
> 
> I don't get this, what's the problem with patch-2 branch and I have deleted C/CPP one because it was empty and other reviewer asked me to do this.

Please do what I've said above ☝
Thanks for understanding

**Comment by mohitmishra786** [comment]
I do have done it, but can you please tell me so that I can understand why I am doing that.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Aryamanz29** [comment]
Closing this PR, Since it's marked as invalid

**Comment by mohitmishra786** [comment]
@Aryamanz29  Sorry Yesterday I got some work to do at night due to which I  was not able to meet on discord. Can we have meeting today at 1 PM

**Pull request closed without merging**
