### PR TITLE
Python: Advanced functions-Map #572

### LINKED ISSUE #572: Python: Advanced functions-Map
### Description :
What is `Map` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by sangeetasingh17**
<hr>

## Description 📜

Python: Advanced functions-Map
I have prepared the documentation on the topic. Map makes the iterating work super easy.
Fixes #572

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Python_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
Content looks Perfect! Can you please resolve the merge conflicts? and also add reference in the .ipynb file means add the links of the site from where you took content as it shows 20% plagiarism. and can you please change the file name from MAP to 'map()' as its predefined! Then it will be good to merge! Last turn girl do it!

**Comment by sangeetasingh17** [comment]
I have resolved the merge conflict. I didn't add reference in the .ipynb file, instead, I rephrased the sentences to avoid plagiarism. I also changed the file name from MAP to map().

**Comment by Randrita** [comment]
@sangeetasingh17 can you please delete old folder and add readme of your ipynb in map() folder only!

**Comment by sangeetasingh17** [comment]
Done with the changes. Is it okay now?

**Review by Randrita — APPROVED** [review]
Perfect! Well done Girl! Highly Appreciate your dedication. @adityabisoi looks good to me, ready to merge!

**Pull request merged**
