### PR TITLE
Data Science with Python : Q Learning

### PR DESCRIPTION
**Pull request by vanshhhhh**
<hr>

## Description 📜

Added a readme file and notebook for python implementation of Q Learning
Fixes : #1828

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by vanshhhhh** [comment]
@prathimacode-hub Please check.

**Comment by shivangdubey** [comment]
@vanshhhhh Nice start but you need to add more about the model including visuals like graphs and networks.

**Comment by vanshhhhh** [comment]
@shivangdubey This topic is quite new to me. There were no visual representations of anything on this topic from the resources where I've learned from. Rather than that just a graph for summarizing rewards given to the agent. Can you please be more specific what should I add ? Because I don't know if there is something relevant to be added.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great choice of issue. Not everyone would choose this topic. Appreciated. 🏷👏@vanshhhhh

**Comment by vanshhhhh** [comment]
Thanks @prathimacode-hub ma'am.

**Pull request merged**
