### PR TITLE
Data Science with Python : Dimensionality Reduction Documentation

### PR DESCRIPTION
**Pull request by BhaswatiRoy**
<hr>

## Description 📜

Dimensionality Reduction Documentation #464
<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README should be elaborate. Kindly add good detailing of your issue title in your README whatever project you take. That's the foremost thing one look for in any project taken. Even if you write code without detailed introduction to the topic, it wouldn't be understandable for anyone. It like just giving a one word answer for question asked. @BhaswatiRoy

**Comment by prathimacode-hub** [comment]
Kindly do the changes addressed. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
@prathimacode-hub I have added everything from my side!

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👍

**Pull request merged**
