### PR TITLE
Java 1.1: Need of Java #1105 

### PR DESCRIPTION
**Pull request by Sneha-0308**
<hr>

## Description 📜

Done Audio Explaining the Need of Java #1105 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Sneha-0308** [comment]
Need Of Java #1105 : Adding Need Of Java audio in .mp3 format

**Review by AkMo3 — CHANGES_REQUESTED** [review]
Hi @Sneha-0308 Can you please rename the file to `Audio_Need_Of_Java.md`. Rest, it look great to me!

**Comment by Sneha-0308** [comment]
Yeah sure!! @AkMo3

**Comment by AkMo3** [comment]
We have merged for the time being. Please keep this in mind for next time. Also, please rebase your branch, so that you do not face merge conflict. Congratulations for the feat🥳 🎉 .

**Pull request merged**
