### PR TITLE
Data Science with Python : Edges & Contours using OpenCV

### PR DESCRIPTION
**Pull request by Adi7171**
<hr>

## Description 📜
I have added Edges & Contours using OpenCV file in computer vision and tigers.jpeg and shapes.jpeg files to DSresources/computer vision. It includes a way to do edge detection and contour detection using canny and draw contour function. I have also added code with descriptions, comments such that its easy for everyone to understand the code .

Fixes # <issue_number_here> 
#370
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Adi7171** [comment]
@prathimacode-hub  How is it

**Comment by m0hit-kumar** [comment]
want to contribute 
mohit kumar
issue 1016
approach:
What are contours?
Application of Contours in Computer Vision
Different contour retrieval techniques

**Comment by Adi7171** [comment]
@prathimacode-hub How is it  now

**Comment by DhruvBajaj01** [comment]
We will review it and let you know. Your file is under processing.

**Comment by Adi7171** [comment]
> We will review it and let you know. Your file is under processing.

alright

**Comment by prathimacode-hub** [comment]
Issue reviewing will be done by mentors first. For structure glitches here it is

Changes to be done 👍 

- The issue contribution should be under "/Computer Vision/Libraries/Edges & Contours using OpenCV
- The project file name should be in snake case : edges_and_contours.ipynb
- The readme file should be as README.md
- You can add up many more topics like features, how it's optimized, advantages. 
- Provide overall summary of things done in conclusion so that final outcome said is been justified

Kindly work on these things until mentors get back to you. @Adi7171

**Comment by Adi7171** [comment]
@prathimacode-hub @DhruvBajaj01 I added the changes

**Comment by prathimacode-hub** [comment]
This PR will be merged once receives an approval from one of your mentor. @Adi7171 

@DhruvBajaj01, Look into this.

**Comment by prathimacode-hub** [comment]
Add up the respective datasets used in "DS Datasets" in "Computer Vision" folder and resources referred in "DS Resources" in "Computer Vision" folder @Adi7171

**Comment by Adi7171** [comment]
> Add up the respective datasets used in "DS Datasets" in "Computer Vision" folder and resources referred in "DS Resources" in "Computer Vision" folder @Adi7171

I didn't use any datasets and only images are the resources which I used and you told me me before not to keep there

**Comment by prathimacode-hub** [comment]
Your PR is approved. Congrats on your first PR. This was an amazing start. 👌✔@Adi7171

**Review by DhruvBajaj01 — COMMENTED** [review]
Reviewed! Nice work!

**Pull request merged**
