### PR TITLE
Frontend_Web_Development_HTML_CSS_JS: Basics of Internet: Domain Name Basics 

### LINKED ISSUE #2320: Frontend_Web_Development_HTML_CSS_JS: Basics of Internet: Domain Name Basics
## Description
Welcome to 'Frontend_Web_Development_HTML_CSS_JS'

 Through documentation, this issue will helps readers in gaining the foundational knowledge of `Domain Name`, which is important for understanding FrontEnd development.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by TishaJhabak1014**
<hr>

## Description 📜

Added the documentation for `Domain Name Basics` with relevant links for references.
Fixes #2320 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by nooobcoder — CHANGES_REQUESTED** [review]
Code references found from 
https://support.google.com/a/answer/48090?hl=en#:~:text=This%20system%20is%20essentially%20the,address%E2%80%94such%20as%2274.125.

Please mention references to give proper credits to authors.

Also, please write detailed explanations, this is a very short explanation of Domain names, mentioning name records, and whois authorities would be great.

P.S: Be more creative @TishaJhabak1014 

Thank You!

**Comment by TishaJhabak1014** [comment]
Added the requested changes to #2355

**Comment by TishaJhabak1014** [comment]
@nooobcoder Sir Do look into merging and closing the issue if things are all fine, so, that I can take up new issues.

**Comment by TishaJhabak1014** [comment]
@code-reaper08 Sir, can you plz review this PR, and merge it if things are good to go.

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
Remove all the binary files, merge them into the .md file. 
Give reference links to images just below them.

**Comment by TishaJhabak1014** [comment]
> Remove all the binary files, merge them into the .md file. Give reference links to images just below them.

Mam, can you plz help me with this. I am not sure how to add these changes.

**Comment by kashishahuja2002** [comment]
> > Remove all the binary files, merge them into the .md file. Give reference links to images just below them.
> 
> Mam, can you plz help me with this. I am not sure how to add these changes.

See all the binary files are images, just remove those files and directly add images in md file.
For adding images you can simply drag and drop, or you can follow this way.
image

And for adding links, follow this: 
image

**Comment by TishaJhabak1014** [comment]
> > > Remove all the binary files, merge them into the .md file. Give reference links to images just below them.
> > 
> > Mam, can you plz help me with this. I am not sure how to add these changes.
> 
> See all the binary files are images, just remove those files and directly add images in md file.
> For adding images you can simply drag and drop, or you can follow this way.
> image
> 
> And for adding links, follow this: 
> image
> 
> 


After this, can I delete all the image files from my local folder amd commit??

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
You made some mistakes in the image part, the images are not visible. Check that.

**Comment by TishaJhabak1014** [comment]
> > > Remove all the binary files, merge them into the .md file. Give reference links to images just below them.
> > 
> > 
> > Mam, can you plz help me with this. I am not sure how to add these changes.
> 
> See all the binary files are images, just remove those files and directly add images in md file. For adding images you can simply drag and drop, or you can follow this way. image
> 
> And for adding links, follow this: image



> You made some mistakes in the image part, the images are not visible. Check that.

Yes, mam, I noticed it. Trying to figure out things.

**Comment by TishaJhabak1014** [comment]
> You made some mistakes in the image part, the images are not visible. Check that.

@kashishahuja2002 Mam, can I use relative paths for the image??

**Comment by TishaJhabak1014** [comment]
@kashishahuja2002 Mam, so sorry but I am unable to make the changes you suggested.

**Comment by kashishahuja2002** [comment]
> > You made some mistakes in the image part, the images are not visible. Check that.
> 
> @kashishahuja2002 Mam, can I use relative paths for the image??

Yes

**Comment by kashishahuja2002** [comment]
> @kashishahuja2002 Mam, so sorry but I am unable to make the changes you suggested.

Refer to this: https://dev.to/adityatyagi/host-images-for-free-on-github-3d1c 
https://marinegeo.github.io/2018-08-10-adding-images-markdown/

**Comment by TishaJhabak1014** [comment]
@kashishahuja2002 Finally, made the changes and I hope it works now. Could drag-drop the gif as its size was greater than 10MB, so had to keep it. Learned a new thing, I was unaware of. Thank you, mam.

**Review by kashishahuja2002 — APPROVED** [review]
Try decreasing the size of the gif and then add in the .md file, if possible. Otherwise no issues.

**Comment by TishaJhabak1014** [comment]
> @kashishahuja2002 Finally, made the changes and I hope it works now. Could drag-drop the gif as its size was greater than 10MB, so had to keep it. Learned a new thing, I was unaware of. Thank you, mam.



> > @kashishahuja2002 Mam, so sorry but I am unable to make the changes you suggested.
> 
> Refer to this: https://dev.to/adityatyagi/host-images-for-free-on-github-3d1c https://marinegeo.github.io/2018-08-10-adding-images-markdown/

Mam, updated with the changes : ) Thank you for your guidance.

**Review by kashishahuja2002 — CHANGES_REQUESTED** [review]
Remove all the br tags and extra spacing.

**Comment by TishaJhabak1014** [comment]
@kashishahuja2002 mam updated with the changes. Plz, let me know of any further changes if needed.

**Comment by TishaJhabak1014** [comment]
@kashishahuja2002 Removed the rest of the br tags. And unfortunately I lost the references to the rest of the images.

**Comment by kashishahuja2002** [comment]
> > Good to go.
> 
> Thank you. Plz do merge it.

Tag the supervisor of your batch. He/She will do it.

**Comment by kashishahuja2002** [comment]
> > > @TishaJhabak1014 Update changes suggested by other mentors/supervisors. If completed, tag the supervisor of your domain to merge the PR.
> > 
> > 
> > Mam, sir @praveenscience has not mentioned the changes required. I am waiting for his video review.
> 
> Tag him or send your request no. on channel

@TishaJhabak1014  No updates for long, update changes, or close the PR.

**Comment by kashishahuja2002** [comment]
> > @TishaJhabak1014 Update changes suggested by other mentors/supervisors. If completed, tag the supervisor of your domain to merge the PR.
> 
> Mam, sir @praveenscience has not mentioned the changes required. I am waiting for his video review.

@praveenscience Please look into it.

**Comment by TishaJhabak1014** [comment]
@praveenscience sir, please find some time to guide me through this. Thank you.

**Review by praveenscience — APPROVED** [review]
👍

**Pull request merged**
