### PR TITLE
Documentation on Appbar widget

### LINKED ISSUE #1845: Flutter: documentation on Appbar Widget
### Description

I will be adding a documentation on appbar widget with example and images

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by jaissumi1402**
<hr>

## Description 📜
Created documentation on appbar widget
Fixes #1845
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Flutter)

<hr>
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by jaissumi1402** [comment]
@ViAsmit please review my pr and merge.

**Review by Procoder16 — CHANGES_REQUESTED** [review]
refer the discord server for the changes

**Comment by jaissumi1402** [comment]
@Procoder16 Okay sure

**Review by Procoder16 — COMMENTED** [review]
Changes mentioned in the discord server

**Review by Procoder16 — APPROVED** [review]
PR approved... @ViAsmit you may merge the PR now... I have checked it.

**Comment by ViAsmit** [comment]
@jaissumi1402 thanks for the PR, Well done!

Take care of indentation and formatting code properly, as it helps in easy understanding.
also when writing dart code in the readme file you can type 'dart' after that three backticks eg.(```dart), so you can get syntax highlighting also.

**Comment by jaissumi1402** [comment]
okay thankyou so much for this information @ViAsmit

**Pull request merged**
