### PR TITLE
[JS] Other: Added pros and cons of Promises

### LINKED ISSUE #1241: JS : Promises
# Promises
---
Promises in Javascript

# Directory
---
```
Topics/10.JSON
```
 
# Description 📜
---
- What is a Promise in Javascript?
- Why do we need Promises?
- How to create a Promise? (Syntax)
- Chained Promises
- Methods in Promises
- Examples

# Domain of Contribution 📊
---
- [x] JavaScript

# Format
---
- [x] Documentation

### PR DESCRIPTION
**Pull request by SakshiMishra1**
<hr>

## Description 📜

Added pros and cons of Promises
Fixes #1241

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [x] JavaScript_Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by SakshiMishra1** [comment]
@paramsiddharth  @dakshsethi @s4-2 Please review :)

**Review by s4-2 — APPROVED** [review]
Well Done 🎉 @SakshiMishra1 
Looks good to me.

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Comment by SakshiMishra1** [comment]
@paramsiddharth please approve and merge😄

**Review by subhendudash02 — APPROVED** [review]
Cool!!!

**Review by paramsiddharth — APPROVED** [review]

**Pull request merged**
