### PR TITLE
#563 : Python Loops-Continue documentation

### LINKED ISSUE #563: Python: Loops- continue
### Description :
What is `continue` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by Sreemoyee26**
<hr>

## Description 📜

Created the documentation for the topic Loops-Continue
Fixes #563

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Sreemoyee26** [comment]
Please review my pull request @adityabisoi

**Comment by Sreemoyee26** [comment]
Please review my pull request @adityabisoi

**Comment by adityabisoi** [comment]
Please tag the mentor of the issue, I can merge only after approval.

**Comment by ankurg132** [comment]
Hey @Sreemoyee26 can you please add the issue number in your description using #issue_no_here so that I can check the issue connected with this PR.

**Comment by Sreemoyee26** [comment]
Added it @ankurg132

**Comment by ankurg132** [comment]
Not in the title, I was telling you to add that in the description exactly in the way it was previously written in title, like #563 should do the work.

**Comment by Sreemoyee26** [comment]
I have added it in both places sir @ankurg132

**Comment by ankurg132** [comment]
Seems like there's still a misunderstanding, you need to replace "# issue_no_563" with "#563" in both places, hope it's clear now 🌚

**Comment by Sreemoyee26** [comment]
O acha sorry. I didn't understand at first. Changed it now.🥲 @ankurg132

**Comment by ankurg132** [comment]
No worries, Looks good to go now! @adityabisoi good to merge!

**Pull request merged**
