### PR TITLE
DSA 4.1.2 Implementation of Stacks - Documentation - Python

### LINKED ISSUE #7135: DSA 4.1.2 Implementation of Stacks - Documentation
## Description
Discuss in detail the implementation of Stacks in Java, Python, C++

Three contributors may take up this issue in these three different languages.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by deepeshaburse**
<hr>

## Description 📜

Implementation of stacks in python.
Fixes #7135 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by nimisha-yadav** [comment]
Please review @harshsri28 @sneha-nitdgp

**Review by harshsri28 — CHANGES_REQUESTED** [review]
Mention Time complexity

**Review by sneha-nitdgp — CHANGES_REQUESTED** [review]
Mention the complexities

**Comment by deepeshaburse** [comment]
@harshsri28 and @sneha-nitdgp kindly check the changes made.

**Review by nimisha-yadav — APPROVED** [review]

**Pull request merged**
