### PR TITLE
Python: Functions

### LINKED ISSUE #569: Python: Functions
### Description :
What is `Functions` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by Anujakumari**
<hr>

## Description 📜

In this Video i have shown what are Functions in Python, syntax for function declaration and function call , types of function, and some examples with their output.
Fixes #569

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Anujakumari** [comment]
@kumarankm
Plz, review my PR.
Thanks

**Comment by kumarankm** [comment]
@Anujakumari Add index and learning path on the main readme

**Comment by Anujakumari** [comment]
@kumarankm, is it correct now ?

**Comment by kumarankm** [comment]
@Anujakumari Solve the conflicts

**Comment by Anujakumari** [comment]
@kumarankm , 
solved the conflict
plz, check now.

**Review by kumarankm — APPROVED** [review]
@Anujakumari Everything looks good. Good job 👍🏻 
You can merge this pr @adityabisoi

**Pull request merged**
