### PR TITLE
Python: Advanced functions-Filter #571

### LINKED ISSUE #571: Python: Advanced functions-Filter
### Description :
What is `Filter` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by saniya44**
<hr>

## Description 📜

Python: Documentation of Advanced functions-Filter #571 issue was assigned to me. I did my best and added What_is_Filter_in_ python folder into Python directory into Python branch.
Fixes #571

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Suvraneel** [comment]
@saniya44  Delete all non-domains

**Comment by saniya44** [comment]
> @saniya44  Delete all non-domains from PR

Okay 👍

**Comment by saniya44** [comment]
Deleted all non-domains from PR

**Review by saniya44 — COMMENTED** [review]
Minor change

**Comment by saniya44** [comment]
Closing due to label issue, will open another.

**Pull request closed without merging**
