### PR TITLE
Class Components in React (2.2_Class_Components.md)

### LINKED ISSUE #1876: Frontend With Framework : Class Components in React
### Description

Need to add Details of Class Components in React,How It works,Why we use Class Components,dis advantages of class components and any thing relevant regarding class components in react

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by GyaniRoman23**
<hr>

## Description 📜

<h2>Fixes #1876</h2>

<h3>Includes the following content:</h3> 

- What are Class Components ?
- Create a Class Component
- Why we use Class Components ?
- Disadvantages of using Class Components
- Function Components (Just an intro)
- Converting a Function to a Class
- Conclusion
- External References

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by shreya024** [comment]
I would like to contribute documentation to this .Kindly assign this to me

**Review by heet-kumar — APPROVED** [review]
LGTM! And I like your way to explain things but let us wait for the approval of supervisors and if they suggest any changes you can do that too!

**Comment by heet-kumar** [comment]
@anandhu720 @the-pro review this PR from your side once .

**Comment by GyaniRoman23** [comment]
> LGTM! And I like your way to explain things but let us wait for the approval of supervisors and if they suggest any changes you can do that too!

Thank you man!!

**Review by anandhu720 — APPROVED** [review]

**Pull request merged**
