### PR TITLE
[FRONTEND WITH FRAMEWORK]: Angular(2.4)->What is Property Binding?

### PR DESCRIPTION
**Pull request by RIYANSHGARG**
<hr>

## Description 📜

What is property binding?
How it works?
Difference between property binding and interpolation.
How to bind directive property?
Brief about property binding among components.
Explain with code snippets/syntax.

Fixes # <3235> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

Screenshot (111)
<hr>

### CODE REVIEW

**Review by heet-kumar — COMMENTED** [review]
try to add references in the bottom of the documentation .
References means from where you have referred and prepared this documentation give them credits .
Because it is mentioned in sever-announcement channel in discord that it is necessary to add references .

**Comment by koshimagoyal** [comment]
@RIYANSHGARG please use links for reference only not to copy paste. Examples also can't be pasted, please create new one.

**Comment by RIYANSHGARG** [comment]
Hey I have made some changes please review them .

**Comment by koshimagoyal** [comment]
@RIYANSHGARG seems good to go

**Review by mukeshmjn — APPROVED** [review]
Well Done!

**Pull request merged**
