### PR TITLE
CSS Flexbox : Frontend web development_HTML_CSS_JS

### LINKED ISSUE #1227: CSS Flexbox
<hr>

## Description 📜

I want to make documentation on CSS Flexbox like what is flexbox, basic properties of flexbox, and some examples of code.

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [x] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

### PR DESCRIPTION
**Pull request by subhradwip01**
<hr>

## Description 📜

Flexbox documentation is created. There are 3 commits. First, commit for creating the first Readme file. Second commit  for fixing some spelling and the third commit for in assets folder image is edited
Fixes #1227

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
Plagiarised from [Harnessing Flexbox For Today’s Web Apps](https://www.smashingmagazine.com/2015/03/harnessing-flexbox-for-todays-web-apps/). Please kindly rephrase. 😊
/cc @2024-SANDHYA

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
@subhradwip01  It's okay but has a lot of grammatical errors like "properties" , "Summery" and so on. Also, you have not added an image source, and reference link. Add them.

**Comment by subhradwip01** [comment]
@2024-SANDHYA Ok I am working on it. I have a doubt image source means do you want me to provide links from which I have took those images...

**Comment by 2024-SANDHYA** [comment]
> 
> 
> I have done the required changes can you please check it. If any issue is found, tell me I will definitely solve the issue.

Like it's given at the bottom of this image, the same way. Mention the URL too as you can see 
image

**Comment by subhradwip01** [comment]
@2024-SANDHYA I need to do that for each photo or I need to add links "reference links"(which I will make for references)

**Comment by subhradwip01** [comment]
Sorry, @2024-SANDHYA for asking again and again...Actually I am new to this field...So I am learning and doing. 😅

**Comment by subhradwip01** [comment]
@2024-SANDHYA please once you tell me..it is my first documentation...from next time I hope I will not get any difficulty

**Comment by subhradwip01** [comment]
@2024-SANDHYA I have done the required changes. Hope it is right.

**Review by 2024-SANDHYA — APPROVED** [review]

**Review by praveenscience — APPROVED** [review]
Nice one. 👍

**Pull request merged**
