### PR TITLE
Introduction to Numpy

### LINKED ISSUE #434: Data Science with Python : Introduction to Numpy
Welcome to 'DSWP' Team, good to see you here

This issue will help in gaining clarity of how numpy is used in various ways. Tutorial to Numpy and how it's applied using its relevant sample codes with brief examples.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Jivitesh Jain / Arya Patel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by tavneetgill**
<hr>

## Description 📜

Numpy(numeric python) is a library that consists of multidimensional array objects and a set of routines for processing them. This documentation walks you through the fundamentals of NumPy, including its design and architecture. It also covers array features, creating,indexing , and other topics.
Fixes #434 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by tavneetgill** [comment]
@prathimacode-hub mam do review this and let me know if it needs any changes or adding more info

**Comment by tavneetgill** [comment]
@Jivitesh Jain @Arya Patel do review this

**Comment by AryaPatel1111** [comment]
@tavneetgill I went through the file and you have put great efforts in compiling the resources for explanation of the Numpy but somethings here and there need to be fixed such as the first cell where you are explaining the installation of Numpy. For example, you could have instead given !pip install numpy --upgrade just in case the user has the library installed then it will check for the update as well. Once make the change I mentioned and figure out rest.

**Comment by tavneetgill** [comment]
@prathimacode-hub @AryaPatel1111 Please close this pull request as it has lot of conflicts. I have created a new PR #1678 hich contains updated file.

**Pull request closed without merging**
