### PR TITLE
OpenSource : 3.7 The Pros and Cons of Open Source Software Development

### LINKED ISSUE #234: OpenSource : 3.7 The Pros and Cons of Open Source Software Development
includes 
Sense of value
Community recognition
Personal benefits
What Is Great About Developing Open Source Software?
What Is Open Source?

can @Aryamanz29 you assign me to these?

### PR DESCRIPTION
**Pull request by Kavindra-Mohan-Dwivedi**
### Description 📜
Added information about Free Software Foundation (FSF) Internship Program and how to apply for the same
Fixes #234  

### Type of change 📝
 Documentation (Content Creation in the form of codes or tutorials)

### Domain of Contribution 📊
 Open Source

### Checklist ✅
- [x]  I follow Contributing Guidelines & Code of conduct of this project.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
-  `Update your fork` repo
-  `Rename your file` and put your to `respective section` See this 👇
https://github.com/girlscript/winter-of-contributing/tree/Opensource/Open_Source
- `Change your PR description`, Follow other PR descriptions, See this👇
https://github.com/girlscript/winter-of-contributing/pull/398
- Change your `doc` from `google colab` to `markdown .md`

**Comment by HassanRahim26** [comment]
Hey @Aryamanz29, I would like to work on this issue. Can you please assign me this issue?

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
@Kavindra-Mohan-Dwivedi Covert your doc to `markdown` file

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
- Images not embedded properly to the doc 👇👇
Screenshot from 2021-09-18 14-31-08
- Squash your commits (merge all commits into a single commit) I don't want 14 commits to add to my domain branch
- Remove space in doc  name `3.7_Pros _and_Cons_of_Open_Source_Software_Development.md`

**Review by Aryamanz29 — APPROVED** [review]
LGTM
Thanks for Contributing 🎉🎉

**Comment by Kavindra-Mohan-Dwivedi** [comment]
Thank You so much for helping

**Pull request merged**
