### PR TITLE
Data Science with Python : Naive Bayes Classifier

### LINKED ISSUE #396: Data Science with Python : Naive Bayes Classifier
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about Naive Bayes Classifier. Tutorial to Naive Bayes Classifier and how it's implied effectively.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Kareem Negm / Peehu Saxena

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by GouriRajesh**
<hr>

## Description 📜

Included content on Naïve Bayes Classifier and updated the README.md file accordingly. Also uploaded an .ipynb file containing python code for Iris Flower Classification using Naïve Bayes Classifier as an example.
Fixes #396 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by GouriRajesh** [comment]
Hey @prathimacode-hub please review this PR and let me know if any changes are required. 
Thanks!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The project file name should be in snake case : naive_bayes_classifier.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Naive Bayes Classifier"
In .ipynb file you had come straight to the code implementation instead give short intro, whatis it used for and why have used it, it's workflow and let it flow into coding part, add sub headings of the process you're working on and final outcome gained at the end. 
Your README file is explained well good. At the end, make sure to add the conclusion and overall summary of the issue.

Kindly work on it. @GouriRajesh

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The project file name should be in snake case : naive_bayes_classifier.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Naive Bayes Classifier"
In .ipynb file you had come straight to the code implementation instead give short intro, whatis it used for and why have used it, it's workflow and let it flow into coding part, add sub headings of the process you're working on and final outcome gained at the end. 
Your README file is explained well good. At the end, make sure to add the conclusion and overall summary of the issue.
Add up the respective datasets used in "DS Datasets" in "Machine Learning" folder and resources referred in "DS Resources" in "Machine Learning" folder

Kindly work on it. @GouriRajesh

**Comment by GouriRajesh** [comment]
Yes, thankyou. I will work on the same and get back to you.

**Comment by prathimacode-hub** [comment]
Update here when it's done. @GouriRajesh

**Comment by GouriRajesh** [comment]
@prathimacode-hub Sorry for the delay. I have made the necessary changes, please have a look at them. 
Thankyou.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your PR is approved. Congrats on your PR. Great work. Keep going. 👌🎉@GouriRajesh

**Comment by GouriRajesh** [comment]
@prathimacode-hub Thank you for your support! 😄

**Pull request merged**
