### PR TITLE
Vectors in cpp

### LINKED ISSUE #3530: Vectors in Cpp
<hr>
vectors, its functions and examples in C++
<hr>

<hr>
-[x]C/CPP
<hr>

### PR DESCRIPTION
**Pull request by Kjp04**
<hr>

## Description 📜

I have included what are vectors, what is the syntax, when should we use a vector, its advantages and disadvantages and lastly the functions of vectors. 
Fixes #3530 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by deeqakkk** [comment]
@Suvraneel plz look into this

**Comment by Kjp04** [comment]
> @Kjp04 Remember to fetch and merge with the C_CPP branch before making a pull request.

Should I do it again?

**Comment by vasu-1** [comment]
> > @Kjp04 Remember to fetch and merge with the C_CPP branch before making a pull request.
> 
> Should I do it again?

Yes Please !!
- Take backup of your code
- Close this Pr
- Make Another Pr
- Fetch your upstream or your git repo.
- Make Saperate Branch for your work
- Put your content only in Apropriate Directory

**Comment by Saviour1001** [comment]
Closing this PR as discussed above. Update your Repo and make a fresh PR again !

**Pull request closed without merging**
