### PR TITLE
C cpp : Virtual Function in CPP

### LINKED ISSUE #1817: [Virtual Function in CPP]:
### Description

Description of virtual function in CPP with a code example.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by anirudh09041**
<hr>

## Description 📜
I created a issue for "Virtual_Function in CPP" which i have completed .
It includes Documentation with a code example.

Fixes #1817  

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)
 

<hr>

## Domain of Contribution 📊

- [X] C/CPP

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by anirudh09041** [comment]
@Suvraneel  please have a look at my PR

**Comment by richach** [comment]
I want to work on this issue. please assign me this task

**Comment by anirudh09041** [comment]
Let them first merge it then if you want you can create a new issue and work on it.

**Review by apeksha235 — APPROVED** [review]
Good work @anirudh09041 
Please merge this @Suvraneel

**Comment by Suvraneel** [comment]
Yes, by far one of the cleanest work I've seen
@anirudh09041  :octocat:

**Pull request merged**
