### PR TITLE
Added Python: 1.5 Brief History of Python

### PR DESCRIPTION
**Pull request by amitrakshar01**
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by adityabisoi** [comment]
Make your contribution as mentioned in discord channel.

**Comment by amitrakshar01** [comment]
> Make your contribution as mentioned in discord channel.
I have followed all the checkpoints. Can u please tell what more to add?

**Comment by adityabisoi** [comment]
Add your file in proper folder & update index in readme

**Comment by amitrakshar01** [comment]
> Add your file in proper folder & update index in readme

Done. Check and merge @adityabisoi

**Comment by adityabisoi** [comment]
There are two files with the same content and the index in README hasn't been updated. Double-check your commits before pushing.

**Pull request closed without merging**
