### PR TITLE
C_CPP: Decision Making Statements(Documentation)

### LINKED ISSUE #934: C_CPP: Decision Making
<hr>

## Description 📜

This will be documentation.
It will explain all the decision making statement used in the language so far. 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by AS8420**
<hr>

## Description 📜

This documentation comprises of concise details regard Decision Making Statements. 
Fixes #934 issue.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Looks cool  !!!
But make some formatting !! 
see this [link](https://www.markdownguide.org/basic-syntax/) for markdown formatting !!

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Also your file should go in this directory ` C_CPP/Fundamentals/Decision Making & Branching Structure/ `
- name your file as ` Decision_making_statements.md `

you don't have to create any directories !!
please remove the directory that you have created !! ` DECISION MAKING STATEMENTS `

**Comment by AS8420** [comment]
Sorry for that.  It was done by mistake.  It will be really helpful for me
if you please tell me how to remove that.

**Comment by ChetasShree** [comment]
Amazing work @AS8420 
@Saviour1001 @Suvraneel pls review this PR and merge it :)
Thank you!!

**Comment by AS8420** [comment]
Thanks mentor. 🙂

**Pull request merged**
