### PR TITLE
Create  04.0 Overview of Android-Manifest file.md

### LINKED ISSUE #516: Android-Kotlin : 04.0 Overview of Android-Manifest file
## Description :
* Give a brief overview of **AndroidManifest.xml** file.
*  Required documentation or video.

* Changes should be made in **Android_Development/Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
> Supervisor @rahulsain

### PR DESCRIPTION
**Pull request by Parth-001-git**
<hr>

## Description 📜

In this repository, you will get to know about the android manifest.
Fixes #516

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [x] Android Dev (Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by rahulsain** [comment]
Add this 2 line of code in the last line of this file `Android_Development_with_Kotlin/04. Android Studio IDE Overview/04.0 Overview of Android-Manifest file.md`

**Comment by Parth-001-git** [comment]
@rahulsain  I guess you are asking me to have proper folder structure right?

**Comment by rahulsain** [comment]
image
You can add your audio drive link , in this preexisting file

**Comment by Parth-001-git** [comment]
I am not getting you! @rahulsain I have made the commit after seeing previous prs.

**Comment by Parth-001-git** [comment]
@rahulsain  still same issue?

**Comment by rahulsain** [comment]
edit [this ](https://github.com/girlscript/winter-of-contributing/blob/Android_Development_With_Kotlin/Android_Development_with_Kotlin/04.%20Android%20Studio%20IDE%20Overview/04.0%20Overview%20of%20Android-Manifest%20file.md)file and put your audio file here at the bottom

**Comment by sitamadex11** [comment]
@Parth-001-git as you give a PR you should close this PR

**Pull request closed without merging**
