### PR TITLE
Opensource : M.15 Alternative of Jenkins in Open Source.md

### LINKED ISSUE #6401: Opensource : M.15 Alternative of Jenkins in Open Source.md
### Description

<hr>

## Description 📜
Alternative of Jenkins in Open Source
Fixes #6401

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
 

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by nikki-priyaHIT**
<hr>

## Description 📜

Alternative of Jenkins in Open Source.md
Fixes #6401

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by nikki-priyaHIT** [comment]
@Aryamanz29 please preview this issue and kindly merge it if possible.

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Hey @nikki-priyaHIT  Nice work 🎉, Could you please change your doc  name to `M.15_Alternative_of_Jenkins.md` and put it inside `Miscellaneous/` directory

**Review by Aryamanz29 — COMMENTED** [review]
Any updates on this @nikki-priyaHIT ?

**Comment by nikki-priyaHIT** [comment]
@Aryamanz29 Please preview this PR

**Review by Aryamanz29 — APPROVED** [review]
Thanks for contributing @nikki-priyaHIT 🎉

**Pull request merged**
