### PR TITLE
Added Bottom Navigation in Android (Kotlin)

### LINKED ISSUE #1426: Android-Kotlin : 09.11 Bottom Navigation in Android (Kotlin)
<hr>

## Description 📜

* Give a step-by-step tutorial of Nested RecyclerView in Android (Kotlin).
*  Required Documentation or Video or Audio.

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

<hr>

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in **Android_Development_With_Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* Inside **Android_Development_With_Kotlin/** directory creates a directory and names it according to the topic ( for this issue **09. Dynamic User Interface**)
* Inside **09. Dynamic User Interface/** directory add your task with subtopic number and name and make changes accordingly.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
* Will assign you on a first come first serve basis.
* Please try to complete your assigned task within 7 days. If you need some more time then, please inform mentors and supervisors.
* If you have two previously assigned issues on **Android-Kotlin** pending then please first complete them.
> Supervisor @rahulsain

## Happy Contributing. Best of Luck.💖

### PR DESCRIPTION
**Pull request by eshan1925**
<hr>

## Description 📜
In this documentation I have added everything related to Bottom Navigation in Android (Kotlin) with this I also have also beautified my code and also allowed users to directly copy the code directly from the docs.
THANK YOU

Fixes #1426 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by rahulsain** [comment]
You have added a single space after `filename .md,` it should be `filename.md`
Again in the several bold words you have added space **like this ** fix this too. it should be **like this**

**Comment by eshan1925** [comment]
Done the changes @rahulsain .
Thankyou

**Comment by sitamadex11** [comment]
@eshan1925 you have done a great job. Though here java code is not required, as a separate domain is working on java related works. I think no need to any change. But you don't need to do in both languages for your further PRs. BTW nice work.

**Review by sitamadex11 — APPROVED** [review]
Great Work.@rahulsain please check it once.

**Comment by eshan1925** [comment]
> @eshan1925 you have done a great job. Though here java code is not required, as a separate domain is working on java related works. I think no need to any change. But you don't need to do in both languages for your further PRs. BTW nice work.

Thanks so much @sitamadex11 I will definitely keep your points in mind in the future.😁

**Pull request merged**
