### PR TITLE
ML 8.19: GAN(D)

### LINKED ISSUE #7519: ML 8.19: GAN(D)
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_GAN_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Seqential_Data_&_Visual_Data` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Yugal41735**
<hr>

## Description 📜

Documentation of GAN.
Fixes #7519 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@Yugal41735 follow the template for the documentation. Small changes to be done.

**Comment by Yugal41735** [comment]
@abhisheks008  Sorry, I am unable to get you, could you elaborate more what changes are to be done. Thank you

**Comment by abhisheks008** [comment]
As per the recommendation of the GWoC Team, we have created a generalized template for all the contributions (Audio, Video and Documentations) to maintain the professionalism of this event and the contributors. In your case, you have done the documentation of a topic and for that you need to maintain the documentation template, check out here, https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md

Hope you get it!
@Yugal41735

**Comment by Yugal41735** [comment]
Sorry for pinging u again, but it would be great if u could point out the
errors as I am unable to point out my errors

**Comment by Yugal41735** [comment]
@abhisheks008  Sorry for pinging u again, but it would be great if u could point out the
errors as I am unable to point out errors in the documentation

**Comment by abhisheks008** [comment]
```
## Title : Name of the Topic
🔴 Type of Content : Documentation
🔴 Domain : Machine Learning
🔴 Module : Name of the module for every week
```

Add these points before starting your documentation. This is called following any template, there is no rocket science behind it!
@Yugal41735

**Comment by Yugal41735** [comment]
@abhisheks008 ohh, I dont know because in previous documentation that I made in Ml does not ask me do something like this and I also have seen other documentation in the ml but no one added has added anything that u have mentioned above. Thanku for letting me know.

**Comment by abhisheks008** [comment]
@Yugal41735 If someone is not following the guidelines, that doesn't mean that you also will not be following the same. The guidelines are guidelines, you've to follow them, otherwise nothing will happen, just your PR will not be merged. As simple as that.

**Review by abhisheks008 — APPROVED** [review]

**Comment by Yugal41735** [comment]
First of all, I haven't said anything like "why should I follow the guidelines". 
Secondly, since you said there is no rocket science, that why I told you since I have seen nobody added that.
Third, we learn things from other people's work.

And if any way I have offended you by asking questions, then I am sorry for that.

**Comment by abhisheks008** [comment]
Fine enough, complete your another assigned issue by EOD @Yugal41735

**Pull request merged**
