### PR TITLE
ML 2.3. Numpy Cheatsheet: Most Useful Functions and Methods (D)

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜
Numpy breif introduction , multiple functions and code snippets with proper snapshots
Fixes # <2788> 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine #Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
Tasks I have done:

-  Introduction
-  Usefulness
-  Installation
-  Multiple functions
-  References.

Let me know if any changes are needed .

@geeythree , @abhisheks008  👍

**Comment by abhisheks008** [comment]
Well done @ron352. PR Approved 🎉

**Comment by ron352** [comment]
Thanks ! Can I  comment on other issues if anything left ?

**Comment by abhisheks008** [comment]
Yeah sure. @ron352

**Pull request merged**
