### PR TITLE
Algorithmic approach to problem solving (Searching Algorithms) C++

### LINKED ISSUE #975: Searching algorithms (Linear Search and Binary Search) - C_CPP
<hr>

## Description 📜

<p> Searching algorithms (Linear Search and Binary Search)</p>
<p> Documentation format</p>
<p>I will be working on this issue, explaining linear search and binary search in a detailed format with code samples and animations. </p>

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by pratyaksh1610**
<hr>

## Description 📜

Successfully added documentation on Searching Algorithms (Linear Search and Binary Search) with animations for 
better understanding of the algorithm. 
Fixes #975 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP
- [x] DS#A

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by pratyaksh1610** [comment]
Please review my PR and revert in case of any changes need to be made.
Any Suggestions/Feedbacks or Scope for improvements are Welcomed !😊😊

**Comment by ChetasShree** [comment]
Amazing work @pratyaksh1610 
@Saviour1001 @Suvraneel pls review this PR and merge it :)
Thank you!!

**Comment by pratyaksh1610** [comment]
Thankyou !! @ChetasShree

**Comment by pratyaksh1610** [comment]
Thankyou !!

**Pull request merged**
