### PR TITLE
Data Science with Python : Reinforcement Learning

### PR DESCRIPTION
**Pull request by Anna-cod**
<hr>

## Description 📜

Reinforcement learning is briefly explained for aspirants in document as well as video form.
Fixes # [353](https://github.com/girlscript/winter-of-contributing/issues/353)

<hr>

## Type of change 📝

- [X] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilities etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Data science with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Anna-cod** [comment]
@jiviteshjain, @aishanii, @prathimacode-hub 
Kindly review my PR.

**Comment by Anna-cod** [comment]
@prathimacode-hub The changes as mentioned by you are accommodated in the video. Kindly review it again.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your link isn't viewable, it's asking for access. Keep it public and share the link in README file. @Anna-cod

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Excellent work. 👏🎆@Anna-cod

**Pull request merged**
