### PR TITLE
Kadanes Algorithm

### LINKED ISSUE #7811: Kadane’s Algorithm
### Description

Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers that has the largest sum. 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Mahi1901**
<hr>

## Description 📜

Kadane’s Algorithm is an iterative dynamic programming algorithm. It calculates the maximum sum subarray ending at a particular position by using the maximum sum subarray ending at the previous position.
Fixes #7811 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by vasu-1** [comment]
image

- Remove hash sign from documentation
- uncheck all except C/CPP
- also remove hash sign from C/CPP

**Comment by vasu-1** [comment]
image
- Remove hash sign from documentation
- Uncheck all except DSA
- Remove hash sign from DSA
- Send your PR link into your respective DSA Channel not in C/CPP group.

**Comment by Pragati1419** [comment]
"/assign"

**Comment by vasu-1** [comment]
> "/assign"

you can't do this here.!
Please go to issue section and create your unique issue on whateve topic which is remaining !

**Comment by vasu-1** [comment]
I guess your file should go  in `/C_CPP/Algorithmic Approaches/Dynamic/` directory

**Pull request closed without merging**
