### PR TITLE
Perfect Guess Game

### LINKED ISSUE #7243: Perfect Guess Game
### Description

This is a game that generates a random number and asks us to guess it. It takes input from the user and tells that the generated number is smaller or larger than the input number and records the number of guesses and stores it in a "highscore.txt" file till we get the correct answer.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by yashh18**
<hr>

## Description 📜

This is a game that generates a random number and asks us to guess it. It takes input from the user and tells that the generated number is smaller or larger than the input number and records the number of guesses and stores it in a "highscore.txt" file till we get the correct answer.

Fixes #7243 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by queenish001 — CHANGES_REQUESTED** [review]
- Try to elaborate the `README` a bit more
- Use snakecase to name your file i.e. `The_Perfect_Guess.py`
- Add comments in your code
- Inside this `Examples` folder add a folder `Perfect_Guess_Game` and add both your files there.

**Comment by yashh18** [comment]
@queenish001 actually our supervisor told us not to add readme with the contribution but still, I wrote a short description about the game.
I also made the required changes you asked me to do.
Please review it once again!

**Comment by queenish001** [comment]
Your changes looks good to me.
And about the README, It's a must for all Python domain contributions, 
So if your supervisor wasn't from Python Domain, then please Elaborate the README.

**Comment by yashh18** [comment]
@queenish001 Please review the README file now I made the required changes!

**Comment by yashh18** [comment]
@queenish001 please review now

**Review by queenish001 — CHANGES_REQUESTED** [review]
Please remove the Images Folder

**Comment by yashh18** [comment]
@queenish001 all the changes done!
edited readme, deleted the images folder

**Review by queenish001 — APPROVED** [review]
Kindly merge this @adityabisoi

**Pull request merged**
