### PR TITLE
Basic Widgets in Flutter

### LINKED ISSUE #2939: Flutter : Basic Widgets used - Documentation
### Description

Add documentation on basic widgets used-
-Text
-Row, Column
-Stack
-Container

Each should be explained with examples to distinctively explain the use of each widget.

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Safwan310**
<hr>

## Description 📜

This documentation explains in brief about the basic widgets used in Flutter
Fixes #2939

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ViAsmit** [comment]
@Safwan310 mention your mentor name, in the comment, so that he can verify the PR. if you don't know who is your mentor, just comment in you batch or in general channel in discord.

**Comment by Safwan310** [comment]
> @Safwan310 mention your mentor name, in the comment, so that he can verify the PR. if you don't know who is your mentor, just ask in your batch or in the general channel in discord, to verify.

Hey Asmit, I have already pinged my mentor @thisisamank via discord.

**Review by Procoder16 — CHANGES_REQUESTED** [review]
1. When you are demonstrating the column widget with the use of various widgets under it, just wrap those children by containers with distinct colors so that they look cleaner.
2. Remove the type under the description: "bried" to "brief"

**Comment by Safwan310** [comment]
> 1. When you are demonstrating the column widget with the use of various widgets under it, just wrap those children by containers with distinct colors so that they look cleaner.
> 2. Remove the type under the description: "bried" to "brief"

Alright!, I will implement these changes

**Comment by Safwan310** [comment]
@Procoder16 I have made the changes. Can you look at them?

**Review by Procoder16 — CHANGES_REQUESTED** [review]
Everything looks good to me... just a minor change. Bring that entire documentation for Container and Stack ahead of Row and Column widgets' documentation, the reason being that you have used Containers in that documentation of Row and Column that is before to that of Containers. My point is if someone is a newbie, then he won't know what a Container is.

**Comment by Safwan310** [comment]
> Everything looks good to me... just a minor change. Bring that entire documentation for Container and Stack ahead of Row and Column widgets' documentation, the reason being that you have used Containers in that documentation of Row and Column that is ahead of that of Containers. My point is if someone is a newbie, then he won't know what a Container is.

How about now?

**Review by Procoder16 — APPROVED** [review]
@ViAsmit I have reviewed the PR and the changes were made accordingly by Safwan.
You may merge the PR if you find it completely fine.

**Comment by ViAsmit** [comment]
Thans @Safwan310 and @Procoder16

**Pull request merged**
