### PR TITLE
Java 9.2 Method basics #1997

### LINKED ISSUE #1997: Java 9.2: Methods basics
### Description

Description Add audio, Documentation, and Video regarding the **Methods basics**.

____

### Location of File to be added

The files should be added inside the `Methods basics`  folder which is inside the `Classes and Methods`  folder present in the   `Java`  main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE` , so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by SoubhPrat17**
<hr>

## Description 📜

Documentation regarding the Java Method basics(return type, structure, etc.)
Fixes #1997 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by AkMo3 — CHANGES_REQUESTED** [review]
@SoubhPrat17 Please make corrections to the formatting, If you are not comfortable with the collab, use README.md. You can read [basic-writing-and-formatting-syntax for readme](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by SoubhPrat17** [comment]
Ok I will do that

**Comment by AkMo3** [comment]
@SoubhPrat17 Please take time, have a look at the material that has been shared. Right now you file is nothing more than a text file.

**Comment by SoubhPrat17** [comment]
Ok thank you. I will look into it

**Review by AkMo3 — APPROVED** [review]
There is some plag but that is basic norms we cannot change. @garvitraj Please take over.

**Comment by SoubhPrat17** [comment]
@garvitraj please check this PR

**Pull request merged**
