### PR TITLE
Added exercises on Strings

### LINKED ISSUE #152: Flutter: Exercises for Intro_To_Dart
Edit the exercise.md file present inside Flutter/Intrduction_To_Dart, to add questions related to dart programming, along with thier solution.

Reference: https://github.com/Asabeneh/30-Days-Of-JavaScript/blob/master/04_Day_Conditionals/04_day_conditionals.md#exercises-level-1

Anyone can do contribution, I am not assigning to anyone but comment before working on which topic you will be adding the question. (Max 3 questions per topic), so that other contributors should not add question related to that topic.

### PR DESCRIPTION
**Pull request by msbuddhu**
<hr>

## Description 📜

I have added 3 exercises well documented alongwith their explanation and solutions. Please have a look.
Fixes #152  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by msbuddhu** [comment]
Is there still any issue with my PR @ViAsmit?

**Comment by ViAsmit** [comment]
@msbuddhu actually after your PR.. you have to mention your mentor, so that he can validate your PR, before I merge it ..

**Comment by msbuddhu** [comment]
> @msbuddhu actually after your PR.. you have to mention your mentor, so that he can validate your PR, before I merge it .. 

Who is the mentor to Batch 10 ?

**Comment by thisisamank** [comment]
Hi @msbuddhu everything looks fine just go through your code once and use proper naming conventions. Although, it is not compulsory but this will set good standards.

**Comment by msbuddhu** [comment]
> Hi @msbuddhu everything looks fine just go through your code once and use proper naming conventions. Although, it is not compulsory but this will set good standards.

@thisisamank I will keep in mind from next time onwards.

**Pull request merged**
