### PR TITLE
Added 09.6 Nested RecyclerView (issue 1407)

### LINKED ISSUE #1407: Android-Kotlin : 09.6 Nested RecyclerView in Android (Kotlin)
<hr>

## Description 📜

* Give a step-by-step tutorial of Nested RecyclerView in Android (Kotlin).
*  Required Documentation or Video or Audio.

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

<hr>

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in **Android_Development_With_Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* Inside **Android_Development_With_Kotlin/** directory creates a directory and names it according to the topic ( for this issue **09. Dynamic User Interface**)
* Inside **09. Dynamic User Interface/** directory add your task with subtopic number and name and make changes accordingly.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
* Will assign you on a first come first serve basis.
* Please try to complete your assigned task within 7 days. If you need some more time then, please inform mentors and supervisors.
* If you have two previously assigned issues on **Android-Kotlin** pending then please first complete them.
> Supervisor @rahulsain

## Happy Contributing. Best of Luck.💖

### PR DESCRIPTION
**Pull request by ayush-sleeping**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1407

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by ayush-sleeping** [comment]
@rahulsain please review my PR and if any mistake is there kindly guide me.

**Comment by rahulsain** [comment]
See here

**Comment by ayush-sleeping** [comment]
> See here

Ok , I am going to make another PR and Deleting this PR

**Comment by rahulsain** [comment]
> > See here
> 
> Ok , I am going to make another PR and Deleting this PR

No need, your next commit will automatically show here

**Comment by rahulsain** [comment]
Dont put non code txt in code view

**Comment by ayush-sleeping** [comment]
> Dont put non code txt in code view

ooooo I get it , On the line 157 I have added non code txt in code view

**Comment by rahulsain** [comment]
> > Dont put non code txt in code view
> 
> ooooo I get it , On the line 157 I have added non code txt in code view

Exactly

**Pull request closed without merging**
