### PR TITLE
OpenSource : 5.1 Explain Deploying to Netlify

### LINKED ISSUE #317: OpenSource : 5.1 Explain `Deploying to Netlify`
### Description :

- **Explain everything related to `Deploying to Netlify`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by uditkatyal**
<hr>

## Description 📜
An issue of Deploying site on Netlify was assigned to me by @Aryamanz29
I have prepared documentation regarding deploying the site.

Deploying a site is just another crucial thing for a developer.
It gives the result of our coding on search engines running in the real-world and is quite tempting.
We can share our deployed site link with family and friends and showcase our work!

Fixes #317 

<hr>

## Type of change 📝

- [x ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ x] Open Source

<hr>
 
## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by uditkatyal** [comment]
@Aryamanz29  bhaiya any changes needed? I have included  images and update file name as well!

**Comment by uditkatyal** [comment]
is the documentation merged?

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
- Rename this file `5.1_Deploying_to_Netlify.md`
-  Put that in `section-5`

**Review by uditkatyal — COMMENTED** [review]
added  someone'e else file but updated to correct now!
5.1_Deploying_to_netlify.d

**Review by Aryamanz29 — APPROVED** [review]
LGTM
Thanks for contributing 🎉🎉

**Pull request merged**
