### PR TITLE
Python: Dictionary_Comprehension

### LINKED ISSUE #3200: Python: Dictionary_Comprehension
### Description

Description:
What is dictionary comprehension?
Why is dictionary comprehension is needed?
Utility of dictionary comprehension with examples
Some advantages

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by TishaJhabak1014**
<hr>

## Description 📜

Added the documentation for dictionary comprehension with important examples and insights.
Fixes #3200 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by TishaJhabak1014** [comment]
@queenish001 Mam, raised the PR. Thank you.

**Comment by PurviBhoyar21** [comment]
Hello Supervisors and Mentors, 
Please assign me this issue.
I am from Python batch 5
Thnak you

**Review by queenish001 — CHANGES_REQUESTED** [review]
Good work on the Notebook!
Changes to be done: 
1. Create a Subfolder by Name 'Dictionary_Comprehension', in that folder add this Notebook and add a README listing the topics that you're covering in the Notebook
2. Change your Notebook name from 'Python_Dictionary_Comprehension' to 'Dictionary_Comprehension'
2. Update the Index and Learning Path in Python Folder README, follow the right format.

**Comment by queenish001** [comment]
> Hello Supervisors and Mentors, Please assign me this issue. I am from Python batch 5 Thank you

You can't get issues assigned under a `Pull Request`, Go to the `Issues` section and select the issue of your choice, and ask for the supervisor's approval there.

**Comment by TishaJhabak1014** [comment]
@queenish001 Solved : )

**Review by queenish001 — APPROVED** [review]
Looks good to me!

@adityabisoi

**Pull request merged**
