### PR TITLE
OpenSource : 2. Getting Started With Open Source

### LINKED ISSUE #25: OpenSource : 2. Getting Started With Open Source
### Description :

-  **Getting Started With Open Source**
     -  **Build a good Tech-Related background**
         - Software products are built with different kinds of tech stacks and
also by following different architectural patterns. Therefore it is
better to study **_architectural patterns, design patterns, and
well-known technologies_** before you begin anything.

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by priyanshuc4423**
<hr>

## Description 📜

 Getting Started With Open Source  it tries to answer some basic queries Why should I contribute to open-source,How do I get started and also mentions some Open-Source Programs/Contests you can try
Fixes #25 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by Aryamanz29** [comment]
After Reviewing your PR Some Changes : 
- I have noticed that you didn't read the issue description
```
 Getting Started With Open Source:-

- Build a good Tech-Related background

Software products are built with different kinds of tech stacks and
also by following different architectural patterns. Therefore it is
better to study architectural patterns, design patterns, and
well-known technologies before you begin anything.
```
- You've to write about how to build a `tech-related background` before contributing to open source projects like if I wanted to contribute to `python-web  related projects` then I need to understand python and some python based web frameworks, You need to add those resources for various tech stacks and try to explain with `images, graphs, gif, charts etc` Don't write` text-heavy documentation`, No one gonna read those 
-  Ask first that you adding particular content before doing any work, You can put your thoughts on issue threads 
- `PR description` should have some text of what you've done, Correct those `[x]` checkboxes
-  Change `PR Description` to `OpenSource : 2. Getting Started With Open Source`
-  Change `commit message` to `OpenSource : 2. Getting Started With Open Source`

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
After Reviewing your PR Some Changes : 
- I have noticed that you didn't read the issue description
```
 Getting Started With Open Source:-

- Build a good Tech-Related background

Software products are built with different kinds of tech stacks and
also by following different architectural patterns. Therefore it is
better to study architectural patterns, design patterns, and
well-known technologies before you begin anything.
```
- You've to write about how to build a `tech-related background` before contributing to open source projects like if I wanted to contribute to `python-web  related projects` then I need to understand python and some python based web frameworks, You need to add those resources for various tech stacks and try to explain with `images, graphs, gif, charts etc` Don't write` text-heavy documentation`, No one gonna read those 
-  Ask first that you adding particular content before doing any work, You can put your thoughts on issue threads 
- `PR description` should have some text of what you've done, Correct those `[x]` checkboxes
-  Change `PR Description` to `OpenSource : 2. Getting Started With Open Source`
-  Change `commit message` to `OpenSource : 2. Getting Started With Open Source`

**Comment by priyanshuc4423** [comment]
Is it fine?

**Comment by Aryamanz29** [comment]
@priyanshuc4423   Amazing Work 🎉🎉🎉 
**One Suggestion -** 
- Please `squash` (merge all commits into one single commit) your commits, Since you've made 3 commits (In which two commits have the same commit message, We want clean commit history :)

Once you've done with the mention changes, I'll merge your PR, Once again thanks for working on this 🙌
Looking forward to more contributions from you 😉

**Comment by Aryamanz29** [comment]
@priyanshuc4423  For squashing commits refer : 
https://youtu.be/gXCkYkLQ3To
https://www.git-tower.com/learn/git/faq/git-squash/

**Review by Aryamanz29 — APPROVED** [review]

**Comment by priyanshuc4423** [comment]
I have commited directly from google colab, so how do I squash it?

**Comment by Aryamanz29** [comment]
> I have commited directly from google colab, so how do I squash it?

Try to use the command line for this

**Comment by priyanshuc4423** [comment]
> > I have commited directly from google colab, so how do I squash it?
> 
> Try to use the command line for this

I tried doing it through command line but I am not getting my commits there

**Comment by Aryamanz29** [comment]
> > > I have commited directly from google colab, so how do I squash it?
> > 
> > 
> > Try to use the command line for this
> 
> I tried doing it through command line but I am not getting my commits there

Join discord voice channel

**Pull request closed without merging**
