### PR TITLE
Refractor Files

### PR DESCRIPTION
**Pull request by priyanshu688**
## Added Documentation  📜

I have added the documentation of Android Java 1.0 Overview of Android # ISSUENUM<138> 

## Overview of Android added  📝
- [ ] Documentation (Content Creation in the form of codes or tutorials)

## Domain of Contribution 📊
- [ ] Android Dev ( Java)

### CODE REVIEW

**Comment by priyanshu688** [comment]
@VikasPandey121 can you please review this?

**Comment by gauravdas014** [comment]
Don't give PR to main

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` command before pushing commit it to the remote repository.
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Your Contributing file should be in this directory `Android_Development_With_Java/`.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

Tag your issue like #138

**Review by Rohit484 — COMMENTED** [review]
Android_Development_Java

**Comment by VikasPandey121** [comment]
I can't merge this PR because you have not followed the guidelines of contribution in this PR.
I request you to please create another PR following the key steps of contribution informed on the Discord server.

**Pull request closed without merging**
