### PR TITLE
Added the documentation

### PR DESCRIPTION
**Pull request by ANUSHKA-AARYA**
<hr>

## Description 📜

I have created a bar chart for comparing population in different countries using '*' and arrays in c language.
 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@ANUSHKA-AARYA 
- Please upload an md file using [markdown-formatting](https://www.markdownguide.org/basic-syntax/) 
- Explain what your documentation is about briefly
- Add comments to your code

**Comment by apeksha235** [comment]
@ANUSHKA-AARYA you don't seem to be active on this pr.. please make the above mentioned changes

**Comment by ANUSHKA-AARYA** [comment]
@apeksha235   Sry....I was busy with chhat puja and all.......I was about to make changes.

**Comment by ANUSHKA-AARYA** [comment]
@apeksha235 I have to open a new issue or forking then  cloning and adding files will work?

**Comment by apeksha235** [comment]
@ANUSHKA-AARYA 
- Open an issue that isn't already available on the files 
- Assign the issue to yourself by commenting '/assign' or asking a supervisor to assign it to you 
- Fork the repo and an ```md file``` for documentation in the appropriate folder 
- You can also add .py or .ipynb files as per your convenience

**Comment by ANUSHKA-AARYA** [comment]
@apeksha235 kindly preview this .

**Comment by apeksha235** [comment]
@ANUSHKA-AARYA Please don't add an .txt file... add it in .md file and use [this](https://www.markdownguide.org/basic-syntax/) for formatting your texts. 
Also add the link of your file to the readme of your folder

**Comment by apeksha235** [comment]
@ANUSHKA-AARYA if you have any doubts, you can ping me on discord- shady#3536

**Comment by ANUSHKA-AARYA** [comment]
@apeksha235 I have messaged you on discord please reply

**Comment by ANUSHKA-AARYA** [comment]
@apeksha235 I have made the changes....kindly preview it.

**Comment by apeksha235** [comment]
Perfect!! @ANUSHKA-AARYA 
@Saviour1001 please merge this

**Pull request merged**
