### PR TITLE
OpenSource : 5.1 Explain Deploying to Netlify

### LINKED ISSUE #317: OpenSource : 5.1 Explain `Deploying to Netlify`
### Description :

- **Explain everything related to `Deploying to Netlify`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by uditkatyal**
<hr>

## Description 📜

An issue of Deploying site on Netlify was assigned to me by @Aryamanz29 
I have prepared documentation regarding deploying the site.

Deploying a site is just another crucial thing for a developer. 
It gives the result of our coding on search engines running in real world and is quite tempting.
We can share our deployed site link with family and friends and showcase our work!

Fixes #317  

<hr>

## Type of change 📝

- [ x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x ] Open Source

<hr>
 
## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Aryamanz29** [comment]
@uditkatyal  I have redefined the `Branch structure`, So Please `Update your forks` & put your `doc` on the respective `sections`

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
@uditkatyal  I have redefined the `Branch structure`, So Please `Update your forks` & put your `doc` on the respective `sections`
- Add Images to your `doc`

**Comment by Varun270** [comment]
@uditkatyal  Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.

**Comment by Aryamanz29** [comment]
> @uditkatyal  Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.

Update your fork with `girlscript open source branch`

**Comment by Varun270** [comment]
> > @uditkatyal  Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.
> 
> Update your fork with `girlscript open source branch`

You want me to sync the fork?

**Comment by Aryamanz29** [comment]
> > > @uditkatyal  Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.
> > 
> > 
> > Update your fork with `girlscript open source branch`
> 
> You want me to sync the fork?

yes

**Comment by uditkatyal** [comment]
> @uditkatyal I have redefined the `Branch structure`, So Please `Update your forks` & put your `doc` on the respective `sections`
> 
> * Add Images to your `doc`
> * Rename your file acc to the convention that which we're following ie https://github.com/girlscript/winter-of-contributing/tree/Opensource/Open_Source/Section-4

okayy got it!

**Comment by Varun270** [comment]
> > > > @uditkatyal  Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.
> > > 
> > > 
> > > Update your fork with `girlscript open source branch`
> > 
> > 
> > You want me to sync the fork?
> 
> yes

Yeah But I am even with the master branch, then why should I fetch upstream. I checked it and it shows that I am even with main.

**Comment by uditkatyal** [comment]
> @uditkatyal Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.

do git branch -a 
it will show all the branches under the main and then checkout to opensource and contribute!
happy coding!

**Comment by Varun270** [comment]
> > @uditkatyal Hey, I am also working on a different issue in the Open Source domain only, Just wanted to ask is there any separate folder for Open source or do we have to create one. Since I have cloned this repo in my system but didn't found any folder named after Open Source. Asking you since you generated a PR.
> 
> do git branch -a
> it will show all the branches under the main and then checkout to opensource and contribute!
> happy coding!

It worked thank you so much mate, Best of luck for your further contributions!!!

**Comment by uditkatyal** [comment]
> @uditkatyal I have redefined the `Branch structure`, So Please `Update your forks` & put your `doc` on the respective `sections`
> 
> * Add Images to your `doc`
> * Rename your file acc to the convention that which we're following ie https://github.com/girlscript/winter-of-contributing/tree/Opensource/Open_Source/Section-4

I have genrated a new Pull request. There was some trouble regarding merging of upstream and origin 
pls consider that 
i have done all necessary changes as per mentioned

**Comment by uditkatyal** [comment]
> > @uditkatyal I have redefined the `Branch structure`, So Please `Update your forks` & put your `doc` on the respective `sections`
> > 
> > * Add Images to your `doc`
> > * Rename your file acc to the convention that which we're following ie https://github.com/girlscript/winter-of-contributing/tree/Opensource/Open_Source/Section-4
> 
> I have genrated a new Pull request. There was some trouble regarding merging of upstream and origin
> pls consider that
> i have done all necessary changes as per mentioned

bhaiya @Aryamanz29 ?

**Pull request closed without merging**
