### PR TITLE
Cyber security: Common ports and protocols issue:739

### PR DESCRIPTION
**Pull request by kar-cloud**
<hr>

## Description 📜

File added for Common Ports and Protocols
Fixes # 739

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials) 

<hr>

## Domain of Contribution 📊

- [x] Cyber Security

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Anant1711 — CHANGES_REQUESTED** [review]
Great Work!
Can you please add `Port number: 110 (POP3)` , `Port number: 143 (IMAP)` , `Port number: 443 (SSL)`

**Comment by Nupurksk** [comment]
@kar-cloud There is plag of more then 25% kindly look into this.

**Comment by kar-cloud** [comment]
> @kar-cloud There is plag of more then 25% kindly look into this.

Can you please tell me which software you are using for checking?? i want to see.

**Comment by Nupurksk** [comment]
> > @kar-cloud There is plag of more then 25% kindly look into this.
> 
> Can you please tell me which software you are using for checking?? i want to see.

Now it's 8% may be some error

Btw here's the link https://smallseotools.com/plagiarism-checker/

**Review by Anant1711 — APPROVED** [review]

**Comment by Anant1711** [comment]
@kar-cloud I review your PR, now its good but,
Your PR is conflicting!
Please make a new PR again, and drop your work there, this time please don't do anything with the `README.md` file. Just upload your work in the `.md` file in the cyber_security branch and in the cyber_secuirty directory!

**Pull request closed without merging**
