### PR TITLE
Data Science with Python : Outliers Detection

### PR DESCRIPTION
**Pull request by Vidit-Ostwal**
<hr>

## Description 📜

Complete Outliers Detection Explained, What are Outliers, different methods to detect, causes of outliers along with codes to describe how to remove the outliers #[381](https://github.com/girlscript/winter-of-contributing/issues/381)

<hr>

## Type of change 📝
- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Your PR is currently under reviewing process.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

You had created up your project in main repo instead it should go under 
/Data_Science_with_Python/Machine Learning/Tutorials/Outliers Detection repository.
And also follow the project structure mentioned in document
File name should be in snake case : outliers_detection.ipynb
And README.md should be elaborate and detailed. 

Kindly work on it. @Vidit-Ostwal

**Comment by Vidit-Ostwal** [comment]
What else should I do to change the target location ?
Changed the base to Datascience_with_Python.
@prathimacode-hub

**Comment by Vidit-Ostwal** [comment]
Please Close This PR.

**Comment by Vidit-Ostwal** [comment]
I have recloned and then made the PR, won't be possible to change in this particular PR, kindly close this PR

**Comment by prathimacode-hub** [comment]
Ok. Closing the PR. @Vidit-Ostwal

**Pull request closed without merging**
