### PR TITLE
C_CPP : Red Black Trees in C

### LINKED ISSUE #1764: C_CPP : Red Black Trees in C
### Description

Red Black Trees in C

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by a-rcane**
<hr>

## Description 📜

Issue #1764 : Made a easy to understand documentation of red black trees with a basic implementation.
Fixes #1764

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by a-rcane** [comment]
@Suvraneel tried to do some justice to this. Please check it out :)

**Comment by SouravKr2001** [comment]
assign it to me

**Comment by ChetasShree** [comment]
@a-rcane  amazing work !!!
@Saviour1001 @Suvraneel pls check this pr and merge it :)
Thank you

**Comment by a-rcane** [comment]
@ChetasShree Thank you :)

**Review by Suvraneel — CHANGES_REQUESTED** [review]
@a-rcane  Very cool...
But there are many kind of trees, so kindly make a sub-directory within tree for Red n black & put these inside...

Readme ye wala bhi rehne do...
aur trees folder ke andar aur ek bana dena linking red n black

**Comment by a-rcane** [comment]
@Suvraneel I sort of made a mistake. I will take down this PR and put up a new one with the changes, sorry. Thank you.

**Comment by a-rcane** [comment]
@Suvraneel I made a mistake while updating. I'll make a new PR. Sorry for the hassle.

**Comment by a-rcane** [comment]
@Suvraneel Sorry did a whole lot of mistakes while doing this. But finally done the requested changes. XD

**Comment by Suvraneel** [comment]
@a-rcane  Doesn't matter you made mistakes, nice that you learnt from it & fixed it successfully🚀  
Awesome ❤️ :octocat:

**Comment by a-rcane** [comment]
> @a-rcane Doesn't matter you made mistakes, nice that you learnt from it & fixed it successfully🚀
> Awesome ❤️ :octocat:

Thanks a lot. It's very encouraging. 😄

**Pull request merged**
