### PR TITLE
Python : Sets(documentation) [issue #554]

### PR DESCRIPTION
**Pull request by tejas342**
<hr>

## Description 📜

i had created the documentation for some more data structure > sets 
issue number #554

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You had represented well but code blocks aren't compiled. Kindly compile them and present it. @tejas342

**Comment by tejas342** [comment]
> You had represented well but code blocks aren't compiled. Kindly compile them and present it. @tejas342
i have to show their output also?

**Comment by tejas342** [comment]
@prathimacode-hub i had made the suggested changes, please review it

**Review by ankurg132 — APPROVED** [review]
Looks good now

**Comment by Randrita** [comment]
@tejas342 looks good

**Comment by tejas342** [comment]
@Randrita @ankurg132 @prathimacode-hub @adityabisoi please merge this

**Comment by ankurg132** [comment]
Please resolve the conflicts.

**Comment by tejas342** [comment]
@ankurg132 Done 👍

**Review by ankurg132 — APPROVED** [review]
Looks good now

**Comment by ankurg132** [comment]
@adityabisoi you can merge this one!

**Pull request merged**
