### PR TITLE
Python: Loops-break

### LINKED ISSUE #561: Python: Loops- break
### Description :
What is `break` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by achsahxavier**
<hr>

## Description 📜

This includes a detailed description about python's break statement in AUDIO format along with ppt containing relevant information and examples. 
Fixes #561 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
 

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by achsahxavier** [comment]
@kumarankm
As you said, I deleted the old PR and created a new one.
Please check this and let me know if any change is to be made.

**Comment by kumarankm** [comment]
And one more thing, while mentioning the issue don't leave space in between # and issue number.
It should be like this #561 not # 561
Then only this pr will get linked with your issue

**Comment by achsahxavier** [comment]
@kumarankm 
Is it done now?

**Comment by achsahxavier** [comment]
@kumarankm 
I am getting a conflict here. Please tell me how to resolve it.

**Comment by kumarankm** [comment]
> @kumarankm
> Is it done now?
> 
> @kumarankm

Yes it's perfect

**Comment by kumarankm** [comment]
> @kumarankm
> I am getting a conflict here. Please tell me how to resolve it.

Could you able to open that conflict file? @achsahxavier
If yes send me the screenshot here

**Comment by achsahxavier** [comment]
@kumarankm 

Screenshot (755)
Screenshot (756)

**Comment by kumarankm** [comment]
134222458-a0373045-d747-489e-88b2-bcfc43bd3710
Add that circled part on there

Remove those things like <<< python and ===



And remove that thing(line 20 to 28) and add a loop at last as I mentioned in the image

**Comment by kumarankm** [comment]
> Add that circled part on there
> 
> Remove those things like <<< python and ===
> 
> 
> And remove that thing(line 20 to 28) and add a loop at last as I mentioned in the image
134222458-a0373045-d747-489e-88b2-bcfc43bd3710
Like this @achsahxavier

**Comment by kumarankm** [comment]
> @kumarankm
> Please check this now.

You have deleted loops break at index section by mistake, add it
@achsahxavier

**Comment by kumarankm** [comment]
Untitled
 Your readme index section should be like this

**Comment by achsahxavier** [comment]
@kumarankm 

Check it now
Is it done?

**Comment by kumarankm** [comment]
> @kumarankm
> 
> Check it now
> Is it done?

Yes everything is fine @achsahxavier

**Comment by kumarankm** [comment]
@adityabisoi  You can merge this pr

**Comment by achsahxavier** [comment]
@kumarankm 
Thank you so much for your guidance.
:)

**Pull request merged**
