### PR TITLE
4. Participating in Open Source Communities

### LINKED ISSUE #285: OpenSource : 4. Participating in Open Source Communities
its include:

  1. What does it mean for an organization to contribute?
  2 .How did contributions work?
  3 . How open-source projects are managed?

Please note that: @LegendSumeet
- File `name, commit message and PR title` should be the same
- Doc should be less `text-heavy` , try to explain things with `gif, images, graphs` etc

@Aryamanz29

### PR DESCRIPTION
**Pull request by LegendSumeet**
<hr>

## Description 📜

Participating in Open Source Communities
Fixes #285 
<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [x] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by LegendSumeet** [comment]
@Aryamanz29 done with it

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
- Put doc inside `section-4`
- Rename doc `4._Participating_in_Open Source_Communities.md`

**Comment by LegendSumeet** [comment]
@Aryamanz29 review it sir

**Review by Aryamanz29 — APPROVED** [review]
Nice work, But next time make sure, Doc should have less text
Thanks for contributing 🎉🎉

**Pull request merged**
