### PR TITLE
Frontend with frameworks: Angular:Sharing data between parent and child components in Angular

### PR DESCRIPTION
**Pull request by RIYANSHGARG**
<hr>

## Description 📜

:Sharing data between parent and child components in Angular
Fixes # <729> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>
Screenshot (104)

### CODE REVIEW

**Review by anandhu720 — APPROVED** [review]
On primary analysis it is fine. @mukeshmjn will take final decision

**Comment by the-pro** [comment]
Please include some code examples

**Review by anandhu720 — CHANGES_REQUESTED** [review]
Please add changes as per @the-pro comment.

**Comment by RIYANSHGARG** [comment]
Ok I will add some examples of code

**Comment by mukeshmjn** [comment]
@RIYANSHGARG u explained it practically very well but it's of no use until u won't add code example so please add them as well :)

**Pull request closed without merging**
