### PR TITLE
Frontend Dev (HTML, CSS, JS): CSS Positionings

### PR DESCRIPTION
**Pull request by Subhrato20**
<hr>

## Description 📜
I would like to make documentation on CSS Static, Relative, and Absolute Positioning.
I would provide theory related to it along with some examples

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Hello @Subhrato20 👋 
You need to present the final content in **.md** file format.

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
You can remove this `CSS_Positioning.pdf` file now.
And kindly look into the Formatting of text.

If you are not familiar with Markdown (.md) syntaxes. I would suggest you to go through **https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf**

**Comment by Subhrato20** [comment]
@code-reaper08 sir can you please check whether it is correct or I do have to change something please

**Review by code-reaper08 — COMMENTED** [review]
@2024-SANDHYA Check this out please.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
1. Here you've mentioned "three", whereas it's 4 & you have explained 3 only. 
Screenshot 2021-09-21 at 22-04-03 Frontend Dev (HTML, CSS, JS) CSS Positionings by Subhrato20 · Pull Request #1667 · girlsc


2.  Don't use "I", "We", rather use "it" . eg : So it means.
Screenshot 2021-09-21 at 22-04-25 Frontend Dev (HTML, CSS, JS) CSS Positionings by Subhrato20 · Pull Request #1667 · girlsc

Rest is okay @Subhrato20

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Just a minor change here : four, instead of three

image

The rest looks good ! @Subhrato20

**Comment by Subhrato20** [comment]
@2024-SANDHYA ma'am done

**Review by 2024-SANDHYA — APPROVED** [review]
Good Job !! 🎉

**Review by code-reaper08 — APPROVED** [review]
Looks cool 🚀

**Pull request merged**
