### PR TITLE
Long Short-Term Memory tutorial [LSTM]

### LINKED ISSUE #5808: Data Science with Python : Long Short-Term Memory tutorial "LSTM"
### Description

Welcome to 'DSWP' Team, good to see you here

In this issue, you will make a tutorial and notebook  about LSTM 
`the notebooks one implement with TensorFlow and another one using Pytorch `

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow, and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : @Kareem-negm / @DhruvBajaj01

Start from: you can use this [notebook ](https://www.kaggle.com/kareem3egm/learn-machine-learning-faster-1)to give you a sample overview 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### Domain

Data science with Python

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by srini047**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #5808

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by srini047** [comment]
I have made the PR so that it gets counted towards the end. I will update the work within tomorrow.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

- It will get counted only if it's merged before the time. In your PR template, add what you have done and what is your issue title about in description. 
- Add aim, purpose, introduction, description, workflow, implementation, data visualizations, advantages, why its used or implied, outputs or results attained from your .ipynb file and conclusion in your README.md
- All images should be in "Images" folder
- Rename your project folder name as "Long Short Term Memory" and add it in "/Datascience_with_Python/Deep Learning/Tutorials" repo.
- Add short introduction on your issue topic, add data visualizations, textual description of your code blocks to get good understanding of the code blocks and overall summary at the end.

Kindly do the changes addressed. @srini047

**Comment by srini047** [comment]
I have done the necessary changes @prathimacode-hub.

**Comment by prathimacode-hub** [comment]
Changes aren't done completely. @srini047

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Well done. Good work. ✔👌@srini047

**Comment by srini047** [comment]
> PR approved. Well done. Good work. ✔👌@srini047

Thanks again @prathimacode-hub.

**Comment by prathimacode-hub** [comment]
Welcome. 🙂@srini047

**Pull request merged**
