### PR TITLE
[DataScience_with_Python]: Create CheatSheet for Matplotlib library of Python

### LINKED ISSUE #6908: [DataScience_with_Python]: Create CheatSheet for Matplotlib library of Python
### Description

**Description :** This issue deals with the documentation for cheat-sheet for matplotlib library of Python.
The readme.md will contain the codes and a .ipynb file will contains all the demonstration of all the codes.

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by singhmansi25**
<hr>

## Description 📜
This issue deals with the documentation for cheat-sheet for matplotlib library of Python.
The readme.md will contain the codes and a .ipynb file will contains all the demonstration of all the codes.
 
Fixes #6908  

<hr>

## Type of change 📝

-  Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

-  Datascience with Python

<hr>

## Checklist ✅

-  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
-  I have performed a self-review of my own code or work.
-  I have commented my code, particularly in hard-to-understand areas.
-  My changes generates no new warnings.
-  I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by singhmansi25** [comment]
**@prathimacode-hub** I have made PR, please have a look
Thanks

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Rename your .ipynb file name in snake case and readme file as README.md
Add "requirements.txt" file with list of libraries used in this issue
In README.md, it can be more elaborative as this is cheatsheet and it should cover all angles of the topic.
Since this being a library, add up the visualization images in "Images" folder and link those image files to README.md
In .ipynb file, at the end provide overall summary of the cheatsheet

Kindly do these changes. @singhmansi25

**Comment by singhmansi25** [comment]
@prathimacode-hub 
Please review my PR again

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive work. Keep going. 👌✔@singhmansi25

**Pull request merged**
