### PR TITLE
Machine learning

### PR DESCRIPTION
**Pull request by kishlayaug15**
<hr>

## Description 📜

Created audio on Different Types of Probability Distributions, which include
1) Normal Distribution
2) Standard Normal Distribution
3) Binomial Distribution
4) Poisson Distribution
5) Exponential Distribution
 
Fixes # <1963> 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by abhisheks008** [comment]
@kishlayaug15 you've not added any file.

**Comment by kishlayaug15** [comment]
@abhisheks008 Sorry for inconvenience, I am new to git & github. It's stated in contributing rules, I have to add gdrive link for audio part. I don't know how to add gdrive link in repository. If you can assist me in that.

I asked in my batch but there is no reply.

**Comment by abhisheks008** [comment]
@kishlayaug15 Go to Demo folder of the Machine Learning repository, there you'll get how to add audio file link using thumbnail.

**Comment by kishlayaug15** [comment]
@abhisheks008 I have committed some changes.

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
@kishlayaug15 The file name should be, `ML_1_15_Types of Distribution_(A).md`

Please update

**Comment by kishlayaug15** [comment]
@abhisheks008 Done!

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
PR approved 🎉

**Comment by kishlayaug15** [comment]
So that means my contribution is merged in GWOC for sure. And my first contribution is successful??

**Pull request merged**
