### PR TITLE
Python: Concepts-Generators #577

### PR DESCRIPTION
**Pull request by lohith1392**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [x] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by lohith1392** [comment]
@adityabisoi once can you check this

**Comment by adityabisoi** [comment]
You need to mention the PR in discord thread.

**Comment by lohith1392** [comment]
@lohith1392 what is discord thread

**Comment by adityabisoi** [comment]
> @adityabisoi what is discord thread

Discord channel

**Comment by lohith1392** [comment]
@adityabisoi yeah i mentioned it

**Comment by lohith1392** [comment]
@adityabisoi can you please check this and confirm so that I can do other question

**Comment by lohith1392** [comment]
@adityabisoi please can u do this quick because if u merge than I can do the other one

**Comment by lohith1392** [comment]
@Randrita can u please check this and merge

**Comment by Randrita** [comment]
can you please 1st resolve the merge conflicts?

**Comment by lohith1392** [comment]
@Randrita actually that conflict should be resolved by you as index keep changing on merging the last time also I got the same problem but my mentor only has resolved it

**Comment by lohith1392** [comment]
@Randrita now is it ok

**Comment by lohith1392** [comment]
@Randrita can u please merge it so that I can do other assigned works

**Comment by lohith1392** [comment]
@Randrita please why are you not merging it

**Comment by Randrita** [comment]
@lohith1392 wait I will check , I think I missed it earlier. You can always mention me in discord channel.

**Comment by lohith1392** [comment]
@Randrita thank you soo much 😊

**Review by Randrita — COMMENTED** [review]
@lohith1392 Content looks perfect! Will you please add references?

**Comment by lohith1392** [comment]
@Randrita actually these were from my notes which I made for python

**Comment by lohith1392** [comment]
So I don't have idea about references

**Comment by Randrita** [comment]
@lohith1392 how dear? it shows 50% plagiarism! if you copied the examples or lines from any site add them in another subtopic named "references/source". If you have written each and every line even an example on your own then it will never show 50% plag!

**Comment by lohith1392** [comment]
@Randrita ok I will check it and let you know

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
