### PR TITLE
Frontend web development react angular vue

### PR DESCRIPTION
**Pull request by RIYANSHGARG**
<hr>

## Description 📜

I have added Introduction to AngularJS
Fixes # <331> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr
Screenshot (88)
>

### CODE REVIEW

**Comment by mukeshmjn** [comment]
@RIYANSHGARG change AngularJS to Angular

**Review by mukeshmjn — COMMENTED** [review]
Whereever u are writing AngularJS please replace it with Angular

**Comment by the-pro** [comment]
Please Do not make PRs to the main branch

**Comment by mukeshmjn** [comment]
Content need to be written over Angular not AngularJS @RIYANSHGARG

**Comment by RIYANSHGARG** [comment]
> Please Do not make PRs to the main branch

Can you tell me what command i have to give to push to this branch ?

**Comment by RIYANSHGARG** [comment]
Can You Please reassign it to me.

**Pull request closed without merging**
