### PR TITLE
Opensource : 4.8 Linux kernel mentorship program

### LINKED ISSUE #300: OpenSource : 4.8 Explain everything related to`Linux Kernel Mentorship Program`
### Description :

- **Explain everything related to `Linux Kernel Mentorship Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title `

## Happy Contributing 🙌

### PR DESCRIPTION
**Pull request by RaghavvGupta**
4.8_Explain_everything_related_to_Linux_Kernel_Mentorship_Program
Branch-Open source

<hr>

## Description 📜

Corrected the branch to be merged in.
Fixes #300 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by RaghavvGupta** [comment]
Issue no #300

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Hey @RaghavvGupta  Could you please add one image of `Linux kernel program` in the doc, otherwise its looks good to me, I'll merge that once you done with changes

**Comment by RaghavvGupta** [comment]
> Hey @RaghavvGupta Could you please add one image of `Linux kernel program` in the doc, otherwise its looks good to me, I'll merge that once you done with the changes.

Done! :))

**Review by Aryamanz29 — APPROVED** [review]
LGTM, Thanks for contributing  🎉🎉

**Comment by RaghavvGupta** [comment]
Thanks mate, cheers!🎉✌

**Pull request merged**
