### PR TITLE
Added exercises for Conditional statements in dart

### PR DESCRIPTION
**Pull request by Niranjan5601**
<hr>

## Description 📜

Added exercises for Conditional statements in dart
Fixes # <152> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Niranjan5601** [comment]
@thisisamank

**Comment by thisisamank** [comment]
@Niranjan5601 whenever you add issue just use the #152 and not #<xyz> by that way the issue automatically get linked :))

**Comment by thisisamank** [comment]
Looks good to me

**Comment by Niranjan5601** [comment]
> @Niranjan5601 whenever you add issue just use the #152 and not #<xyz> by that way the issue automatically get linked :))

Thanks for the tip 👍🏻

**Pull request merged**
