### PR TITLE
Data Science with Python : Data Augmentation Techniques

### LINKED ISSUE #7359: Data Science with Python : Data Augmentation Techniques
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know on how to use and implement data augmentation using images.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Computer Vision

Mentors Assigned : Arya Patel | Ankit Kumar

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by vishvarana**
## Description 📜

Defined different data augmentation techniques for increment of training data when the data is imbalanced. The techniques defined are zooming, rotating, flipping & contrasting.

Fixes #7359 

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python
- [ ] 
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by vishvarana** [comment]
@prathimacode-hub Please review

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add README.md file with detailed elaboration on your issue topic. 
All images should be in "Images" folder
At the end of .ipynb file, add summary of the work.

@vishvarana

**Comment by vishvarana** [comment]
Changes done 
Please review @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive work. 🙌✨@vishvarana

**Pull request merged**
