### PR TITLE
Implementation Of String In Java

### LINKED ISSUE #3260: DSA 2.1 Implementation of Strings in Java - Documentation
## Description
How are strings implemented in Java? Discuss string class, string length.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by dhruti29**
<hr>

## Description 📜

Add Documentation 
Fixes #3260 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by dhruti29** [comment]
@nimisha-yadav please review...!!

**Comment by nimisha-yadav** [comment]
Please review @sneha-nitdgp @harshsri28

**Review by harshsri28 — CHANGES_REQUESTED** [review]
use some images for explanation

**Comment by dhruti29** [comment]
> use some images for explanation

Please check I added some images.

**Review by sneha-nitdgp — APPROVED** [review]
LGTM

**Review by nimisha-yadav — CHANGES_REQUESTED** [review]
Hey @dhruti29 please put your file in [here](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/2.1%20Strings/3.%20Implementation%20in%20Java%2C%20Python) and rename it 2.1.3.1_Java_Implementation_Of_Strings.md

**Comment by dhruti29** [comment]
@nimisha-yadav Thank you...🙂

**Pull request merged**
