### PR TITLE
How to install and setup Flutter

### LINKED ISSUE #66: How to Install and Setup Flutter for App Development
Description
Give a brief on how to download and install Flutter on a device (Mac, Windows, Linux).

### PR DESCRIPTION
**Pull request by aaryan078**
How to Install and Setup Flutter for App Development #66

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #66 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by aaryan078** [comment]
How to Install and Setup Flutter for App Development

**Comment by ViAsmit** [comment]
@aaryan078 Please contact your mentor to validate this PR.

**Comment by aaryan078** [comment]
I am not a Flutter domain contributor.

**Comment by ViAsmit** [comment]
@aaryan078 can you add this readme file and all images in a single folder inside Flutter Folder?

**Comment by aaryan078** [comment]
yes @ViAsmit

**Pull request merged**
