### PR TITLE
Flutter : Stateless Widget Documentation

### LINKED ISSUE #1008: Flutter : Stateless Widget Documentation
<hr>

## Description 📜

One is supposed to add documentation on-
1. What are stateless Widgets?
2. Use of Stateless Widgets.
3. Syntax of Stateless Widget.
4. Description of Keywords in the syntax with example.
<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter)

<hr>

### PR DESCRIPTION
**Pull request by msramesh2k1**
<hr>

## Description 📜

I had done documentation  on stateless widget
Fixes #1008  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ViAsmit** [comment]
@msramesh2k1 you have some plagiarised content from geeksforgeeks, please make your content unique, using online tools.

**Comment by msramesh2k1** [comment]
Okie will do

**Comment by msramesh2k1** [comment]
@ViAsmit can you please now

**Comment by ViAsmit** [comment]
@msramesh2k1 Thanks for the PR

**Pull request merged**
