### PR TITLE
J hoisting

### LINKED ISSUE #161: JS: Hoisting in Javascript
# Hoisting in JavaScript
Discuss the concept of hoisting in JavaScript.

## Directory
```
Topics/6.Hoisting
```
## Description

- Talk about What is Hoisting
- How javascript uses hoisting for declarations
- Effect Of Hoisting on different types of Declarations

### PR DESCRIPTION
**Pull request by anjalirai12**
<hr>

## Description 📜

Extended the current file and added some additional information about the topic.
Fixes  #161

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Suvraneel** [comment]
@anjalirai12 
Delete all other domains from your comment.. as per official GWOC PR template directives
Kindly follow the issue template from next time ... & preach this to your fellow contributors

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by anjalirai12** [comment]
@Suvraneel sorry sir , I will keep this in mind from next time . 

> @anjalirai12
> Delete all other domains from your comment.. as per official GWOC PR template directives
> Kindly follow the issue template from next time ... & preach this to your fellow contributors

**Comment by anjalirai12** [comment]
> Also, Resolve conflicts

Sir , I have resolved the conflicts , so please now kindly review my work.

**Pull request closed without merging**
