### PR TITLE
Python: OOP-class #564

### PR DESCRIPTION
**Pull request by ekesel**
Python: OOP-class #564

<hr>

## Description 📜

Add OOP-Class Documentation
Fixes # 564

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by kumarankm** [comment]
@ekesel Looks good
Now you need to do two things
First in the description of pr, to make it as a check box you have to give [x] not [ x]
And then solve merge conflict

**Comment by kumarankm** [comment]
> @ekesel Looks good
> Now you need to do two things
> First in the description of pr, to make it as a check box you have to give [x] not [ x]
> And then solve merge conflict

For solving conflicts send me your screen shot of conflicts file I will say you how to do if you dont know to solve

**Comment by ekesel** [comment]
okay @kumarankm i will just add the screenshot ---https://ibb.co/G5NC0dQ

**Comment by kumarankm** [comment]
@ekesel 
Screenshot-from-2021-09-22-11-46-59

Add those four to the exact location where I marked and remove those things like "<<<Python" and "===="

**Comment by kumarankm** [comment]
And then remove those code (from line number 22 to 31) as I mentioned in the image below
Then append that oop-class on learning path @ekesel 
Screenshot-from-2021-09-22-11-46-59

**Comment by ekesel** [comment]
@kumarankm Thanks i have resolved the issue

**Review by kumarankm — APPROVED** [review]
@ekesel Everything looks good. Good job 👍🏻 
You can merge this pr @adityabisoi

**Pull request merged**
