### PR TITLE
Issue #588 M 1.3: Central Limit Theorem(D)

### PR DESCRIPTION
**Pull request by prishita-s**
<hr>

## Description 📜

I have created a folder for CLT, added the .ipynb file and readme file for CLT in it.
Fixes # 588
<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by abhisheks008 — APPROVED** [review]

**Comment by abhisheks008** [comment]
Create a Fresh PR and add the PR to Machine Learning branch @prishita-s

**Review by abhisheks008 — CHANGES_REQUESTED** [review]
Put only file, either you provide the ipynb file or the markdown file. No need of other files. Check others contribution you'll get to know what we are expecting.

**Comment by prishita-s** [comment]
Okay. I'll make the changes and send the PR again

**Comment by prishita-s** [comment]
What about the .csv file that I've used? Do I have to upload that as well or should I leave it? @abhisheks008

**Pull request closed without merging**
