### PR TITLE
Issue #570 Solved

### LINKED ISSUE #570: Python: Advanced functions-zip
### Description :
What is `zip` in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

### PR DESCRIPTION
**Pull request by Ajinkyap331**
<hr>

## Description 📜

Solved Issue #570. I have created a tutorial and documentation for Advanced Python Function Zip
Fixes #570 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Ajinkyap331** [comment]
@kumarankm @adityabisoi what to do now

**Comment by kumarankm** [comment]
Looks fine! Good job 👍🏻 
@adityabisoi have a look at it
Close your previous pull request @Ajinkyap331

**Comment by Ajinkyap331** [comment]
Ok Thanks

**Comment by adityabisoi** [comment]
Can you update `## Learning path` in readme as well

**Comment by kumarankm** [comment]
> @adityabisoi what number should I give it

@Ajinkyap331 The continuous one in this case 9

**Comment by Ajinkyap331** [comment]
ok @kumarankm

**Comment by Ajinkyap331** [comment]
@kumarankm @adityabisoi  Done

**Comment by kumarankm** [comment]
> @kumarankm @adityabisoi Done

Solve the conflicts. Send me the screenshot of your conflict file @Ajinkyap331 
I will say how to

**Comment by Ajinkyap331** [comment]
@kumarankm The conflict is in Readme.md (index)

**Comment by kumarankm** [comment]
@Ajinkyap331 Watch this video you could come to know how to solve
https://youtu.be/vexdS7ubtvQ

**Comment by Ajinkyap331** [comment]
Done @kumarankm. And Thank You so much

**Comment by Ajinkyap331** [comment]
@adityabisoi  Please review it

**Review by kumarankm — APPROVED** [review]
@Ajinkyap331 Everything looks fine. Good job 👍🏻 
You can merge this pr @adityabisoi

**Comment by Ajinkyap331** [comment]
Thank you @kumarankm.

**Pull request merged**
