### PR TITLE
Interview preparation

### PR DESCRIPTION
**Pull request by singhnikhiljsr**
## Description 📜

Made a complete crash course of SQL, covering everything from basics to advanced with syntax.
Fixes girlscript#3240

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [x] Interview Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by singhnikhiljsr** [comment]
@syedareehaquasar Can you please review this PR, and kindly convey your thoughts otherwise my efforts will go in vain.

**Comment by syedareehaquasar** [comment]
I would suggest, take 1 small dummy data 3*3 maybe and show o/p of them all that helps support better. The rest looks good well done!

**Comment by singhnikhiljsr** [comment]
Hi, @syedareehaquasar 
I tried implementing your suggestion but complex queries can't be represented by 3*3 table as it considers many other factors.
Eg. I tried name, marks (for aggregation) and salary (order by), then for group by I need and org. name (column) and to show joins I need two tables, it contains around 50 queries, work was getting very hectic.
Anyways I have tried explaining each query in plain, simple language.
Would appreciate your comment.

**Comment by syedareehaquasar** [comment]
cool! I understand let's merge this for now!

**Comment by syedareehaquasar** [comment]
Good Job!

**Pull request merged**
