### PR TITLE
[JS] Topic: Graphics - WebGL

### LINKED ISSUE #6936: [JS]: Graphics - WebGL
### Description

# Description

Introducing the usage of 2-D and 3-D graphics in JavaScript and how WebGL can be used to create these graphics with some examples.

### Domain

JavaScript_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by subhendudash02**
<hr>

## Description 📜

Added the documentation of WebGL, HTML and JS file.
1. Introduction
2. How WebGL is executed
3. Getting Started with WebGL
4. Applications
5. References
 
Fixes #6936 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by subhendudash02** [comment]
@paramsiddharth @amino19 @dakshsethi @s4-2 @Creatoon Kindly review this PR.
I don't know why it is including every commit in each PR I am raising, from September.🤔

**Review by s4-2 — COMMENTED** [review]
Please mention the topic on the top of doc and it will good if you attach the output of the following code:-)

**Comment by subhendudash02** [comment]
@s4-2 I have mentioned the topic and I attached the output of the code already. Is it visible from your side?

**Comment by s4-2** [comment]
@subhendudash02 It's not showing in one file. I think this is due to multiple commits.

**Comment by subhendudash02** [comment]
Screenshot from 2021-11-08 08-45-47

@s4-2 It is showing even in incognito mode. I have cleaned the commit history too....

**Review by s4-2 — APPROVED** [review]
@subhendudash02 Great work. Looks good to me. Keep going, every contributors contribution means a lot🙂

**Comment by subhendudash02** [comment]
Thank you so much for your approval😊.

**Review by paramsiddharth — APPROVED** [review]
Amazing work, Subhendu!

@Creatoon @dakshsethi @amino19 Please review.

**Comment by subhendudash02** [comment]
Thank you for approval @paramsiddharth !

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Pull request merged**
