### PR TITLE
Updated README of Python folder for Lambda function.

### PR DESCRIPTION
**Pull request by mohansaitejatalari**
<hr>

## Description 📜

Updated README of Python main folder, included advanced_function_lambda.

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
@mohansaitejatalari everything looks perfect! but instead of the other "readme.md" file, you can directly add it in ipynb or in .md file add something like " to explore more about Lamba - then add the link of .ipynb" it will look well constructed then

**Comment by mohansaitejatalari** [comment]
@Randrita mam, modified it please check it now.

**Review by Randrita — APPROVED** [review]
looks good to me! indeed good job @mohansaitejatalari ! But there's already an existing folder for Lambda Function created by Bhaswati Roy! Try to push your .ipynb file in that folder! Then it will be ready to merge! if you are unable to see that "upstream and fetch" python branch

**Comment by mohansaitejatalari** [comment]
@Randrita Mam, Added to that folder ,shall I create a PR again?

**Comment by Randrita** [comment]
Nopes! Just change ta file name from Read_me.ipynb to documentation.ipynb :|

**Comment by Randrita** [comment]
@mohansaitejatalari can you please resolve the merge conflicts?

**Pull request closed without merging**
