### PR TITLE
Data Normalization #1857

### LINKED ISSUE #1857: Data Science with Python : Data Normalization
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Data Normalization. Tutorial to Data Normalization and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Kareem Negm / Dhruv Bajaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ELLIPSIS009**
<hr>

## Description 📜

I did an extensive documentation on Data Normalization, and how it's applied using sample code. Added one MD and one IPYNB files.
Fixed #1857 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by manthan89-py** [comment]
**Interested in working on this issue.**

**Comment by prathimacode-hub** [comment]
This is not an issue but a PR. @manthan89-py

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done

Instead of adding this in Libraries, you can add it up in Tutorials repo.
In README, add benefits, usage purpose, applications, why it's preferred.

Kindly work on it. @ELLIPSIS009

**Comment by ELLIPSIS009** [comment]
@prathimacode-hub please check, i have added the benifits, usage purpose and as for application and why its preferred i think its covered in Is Normalization helpful and importance if normalization, please check

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great job. 👍@ELLIPSIS009

**Pull request merged**
