### PR TITLE
[Frontend_Web_Development_HTML_CSS_JS]: Code Structure

### LINKED ISSUE #1711: [Frontend_Web_Development_HTML_CSS_JS] Topic: Code Structure
# Code Structure
The code structure of JavaScript
# Directory
```Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/3.Code_Structure```
## Description 📜
- Functionality and Readability
- Whitespace
- Semicolons
- Indentation
- Identifiers

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

# Format
- [x] Documentation

### PR DESCRIPTION
**Pull request by sushovanb02**
<hr>

## Description 📜

Created a document on the Code Structure of JavaScript 
Fixes #1711
PR no.- #1722 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS
- [x] Batch-14-FEWD 

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by sushovanb02** [comment]
@Knighthawk-Leo Please review this PR

**Comment by Knighthawk-Leo** [comment]
Please add your batch name in the PR

**Comment by sushovanb02** [comment]
@Knighthawk-Leo done as you said!

**Comment by Knighthawk-Leo** [comment]
> @Knighthawk-Leo done as you said!

No need to mention batch name in your code add batch name in the pull request only. This time I edited that next time please take care for that

**Comment by sushovanb02** [comment]
@Knighthawk-Leo so shall I take it out from the code?

**Comment by Knighthawk-Leo** [comment]
> @Knighthawk-Leo so shall I take it out from the code? And sir I'm from Batch-14 not batch-7

yes remove it from there

**Comment by sushovanb02** [comment]
> > @Knighthawk-Leo so shall I take it out from the code? And sir I'm from Batch-14 not batch-7
> 
> yes remove it from there
Sir done, now you can merge ig

**Comment by Knighthawk-Leo** [comment]
> > > @Knighthawk-Leo so shall I take it out from the code? And sir I'm from Batch-14 not batch-7
> > 
> > 
> > yes remove it from there
> > Sir done, now you can merge ig

I more thing Add the issue number associated with this PR

**Pull request merged**
