### PR TITLE
C_CPP : Deque in C++ Standard Template Library (STL) 

### LINKED ISSUE #1003: C_CPP : Deque in C++ Standard Template Library (STL)
<hr>

## Description 📜

This documentation will explain Double ended queue of STL in C++
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by ankushsingh24**
<hr>

## Description 📜

I've completed my issue work , I raised an issue on the topic "Deque" in C++.

This documentation will explain Double ended queue (Deque) of STL in C++ :
1. It is a beginner friendly documentation of Deque includes deque C++ code with proper comments ahead.
2. Used images to visualize deque very well. 
3. Explained functions involved in Deque.
Fixes #1003

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by ChetasShree** [comment]
Well done @ankushsingh24 ,  
@Suvraneel @Saviour1001 , pls review this PR and merge it :)
Thank you

**Comment by ankushsingh24** [comment]
> Well done @ankushsingh24 ,
> @Suvraneel @Saviour1001 , pls review this PR and merge it :)
> Thank you

Glad you liked it @ChetasShree. 
I would like to request @Suvraneel and @Saviour1001 to please review this 😇

**Comment by Saviour1001** [comment]
As you are using the inbuilt STL, place it in Data Structures Folder, else the content is remarkable !!

**Comment by Suvraneel** [comment]
@ankushsingh24 I'm not adding a plagiarised from here : https://www.geeksforgeeks.org/deque-cpp-stl/ yet
Kindly change the code

**Comment by ankushsingh24** [comment]
> @ankushsingh24 I'm not adding a plagiarised from here : https://www.geeksforgeeks.org/deque-cpp-stl/ yet
> Kindly change the code (other than ngquiz renamed to ngwoc)
> 
> My suggestion : Make this take dynamic input
> & this will be ready to merge

yes sir, I've take reference from there, but if I perform dynamic input in the code, I'll only able to show one function.
i.e only one of push_back() , pop_back(), push_front(), pop_front() , etc
So, will it be okay for merging?

**Comment by ankushsingh24** [comment]
Updated my Code and MarkDown as suggested.

Kindly review my documentation. @Suvraneel

**Comment by Suvraneel** [comment]
@ankushsingh24 One last thing,
 can you put the entire deque folder inside "Data Structures/Standard Template Library (Vectors, Maps etc)/" directory
 
 if I merge this now, it won't be organised

**Comment by ankushsingh24** [comment]
> @ankushsingh24 One last thing,
> can you put the entire deque folder inside "Data Structures/Standard Template Library (Vectors, Maps etc)/" directory
> 
> if I merge this now, it won't be organised

Finally, @Suvraneel , changed the location of Deque as suggested.
Now it's ready to go...😇

**Comment by Suvraneel** [comment]
@ankushsingh24 Awesome! ❤️  Have a good open-source journey :octocat:

**Pull request merged**
