### PR TITLE
Java Switch Blocks

### LINKED ISSUE #1808: Java 6.2: Switch Blocks
### Description

DescriptionAdd audio, documentation, and video regarding the **Switch Blocks**.

____

### Location of File to be added

The files should be added inside the `Switch Blocks`  folder which is inside the `Control Statements`  folder present in the   `Java`  main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ShikhaSwati60**
<hr>

## Description 📜
Explained Switch Blocks in Java 
Fixes #1808 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by ShikhaSwati60** [comment]
@AkMo3 please review my work

**Review by Sin-Sumit — APPROVED** [review]
Add References, if any, it will be a good practice.

**Comment by AkMo3** [comment]
@ShikhaSwati60 Will be review by @sakshamlamba109 first. @sakshamlamba109 Please complete the review and let me know

**Comment by AkMo3** [comment]
> Add References, if any, it will be a good practice.

Alt Text

**Comment by AkMo3** [comment]
@sumitaccess007 My bad, please complete the review

**Review by garvitraj — APPROVED** [review]

**Comment by Sin-Sumit** [comment]
Yes, it's good.

**Comment by ShikhaSwati60** [comment]
@AkMo3 Do I need to add anything else in my file or is it ready to get merged?

**Review by AkMo3 — APPROVED** [review]
GTG

**Pull request merged**
