### PR TITLE
ES6 Template Literals

### PR DESCRIPTION
**Pull request by SakshiMishra1**
<hr>

Week 1:- (Frontend development with ReactJs)
Added clear explanation of ES6 Template Literals.

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [x] Frontend Dev React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by SakshiMishra1** [comment]
Clear explanation of ES6 Template Literals.

**Comment by anandhu720** [comment]
@SakshiMishra1 can you please mention in which issue you worked

**Comment by SakshiMishra1** [comment]
@anandhu720 It was mentioned in week 1 under frontend dev with react.

**Comment by anandhu720** [comment]
@SakshiMishra1 Is this work assigned to you

**Comment by anandhu720** [comment]
this work has already assigned to someone else and already merged to repo.Please follow the rules he have provided it discord.

**Pull request closed without merging**
