### PR TITLE
Advanced_function_Reduce folder added

### PR DESCRIPTION
**Pull request by Ashi-00**
<hr>

## Description 📜

**Fixes Issue  # <573>** 
**PYTHON ADVANCED FUNCTION-reduce()**
As the name suggests, the function implements folding or reduction. It is useful when you need to apply a function to an iterable and reduce it to a single cumulative value.
It can be imported from the functools module of python.

Its a very useful function because it makes working with iterables easy in place of using explicit and comparatively slow for loops.
<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [x] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by Randrita — CHANGES_REQUESTED** [review]
hey @Ashi-00 , will you please check plagiarism? 23% plagiarism is found! either change the line or mention the site from where you copied with the proper date. The following stanza totally.  folder name can be "function" instead of "functions". 
"The left argument, x, is the accumulated value and the right argument, y, is the update value from the iterable. If the optional initializer is present, it is placed before the items of the iterable in the calculation, and serves as a default when the iterable is empty. If initializer is not given and iterable contains only one item, the first item is returned."

**Comment by Ashi-00** [comment]
Ma'am,
Actually this particular paragraph is from the official python documentation
(docs.python.org)
So, i copied this part as it is...

Also the other sites i took help from were:-
1)realpython.com
2)www.geeksforgeeks.com
3)www.w3schools.com (for some help on lamda)

Regards
Ashi Dubey
Python contributor

**Comment by Randrita** [comment]
Mention it in a reference section in your notebook and update it.. to avoid plagiarism.

**Comment by Ashi-00** [comment]
Ok ma'am will do that.!

**Review by Randrita — COMMENTED** [review]
Can you please change the file name, use "reduce()" instead of "Reduce"  as its defined in "functools" module @Ashi-00

**Review by Randrita — APPROVED** [review]
@adityabisoi looks good to me now. The merge request is approved from my end.

**Comment by Ashi-00** [comment]
Thankyou @adityabisoi  sir and @Randrita ma'am..!  :)

**Pull request merged**
