### PR TITLE
C_CPP: Why To Overload Operators Using Friend Functions

### LINKED ISSUE #7213: C_CPP: Why to Overload Operators Using Friend Functions?
### Description

Description

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by 124015001**
<hr>

## Description 📜

Explained the use of friend function in Operator Overloading. Also, performed a program on same.
Fixes #7213 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by deeqakkk — CHANGES_REQUESTED** [review]
Abhimanyu, your content is good and easy to understand as well.
But it shows a few % of plagiarism, to compensate that do add link to the websites in as a reference.

**Review by 124015001 — COMMENTED** [review]
updated file

**Comment by 124015001** [comment]
@deeqakkk Thanks for informing. I have changed the sentence. Can you check now?

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Can you resolve the conflicts first !!

**Comment by 124015001** [comment]
@vasu-1 Resolved.

**Review by vasu-1 — APPROVED** [review]
LGTM @124015001 

@Suvraneel

**Comment by Suvraneel** [comment]
@124015001  LGTM 🚀 Nice work ❤️  :octocat: 

Btw @vasu-1  You can tag me for resolving conflicts... Abhi here is pro 😄  But bohot log darr jaate hai

**Comment by vasu-1** [comment]
> @124015001 LGTM rocket Nice work heart :octocat:
> 
> Btw @vasu-1 You can tag me for resolving conflicts... Abhimanyu here is pro smile But bohot log darr jaate hai

okok Sure

**Pull request merged**
