### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by anmol20112000**
<hr>

## Description 📜

i updated the README.md file & create a Roadmap of Android Development using Java
Fixes # <85> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by anmol20112000** [comment]
please review this @VikasPandey121

**Review by Rohit-2602 — APPROVED** [review]

**Comment by VikasPandey121** [comment]
Awesome work @anmol20112000, just a minor change requested

- Change the file directory from `Android_Development/Java/README.md` to `Android_Development_With_Java/README.md`

**Comment by VikasPandey121** [comment]
> Awesome work @anmol20112000, just a minor change requested
> 
> * Change the file directory from `Android_Development/Java/README.md` to `Android_Development_With_Java/README.md`

@anmol20112000 please follow these steps to make PR and comment if you have found any trouble doing so.

**Comment by anmol20112000** [comment]
> > Awesome work @anmol20112000, just a minor change requested
> > 
> > * Change the file directory from `Android_Development/Java/README.md` to `Android_Development_With_Java/README.md`
> 
> @anmol20112000 please follow these steps to make PR and comment if you have found any trouble doing so.

@VikasPandey121  how i supposed to do this......???

**Comment by anmol20112000** [comment]
> > Awesome work @anmol20112000, just a minor change requested
> > 
> > * Change the file directory from `Android_Development/Java/README.md` to `Android_Development_With_Java/README.md`
> 
> @anmol20112000 please follow these steps to make PR and comment if you have found any trouble doing so.

Should i need to create new PR ?( i change what you told )

**Comment by VikasPandey121** [comment]
Change the folder/directory from ` Android_Development/Java/` and add your file to `Android_Development_With_Java/` folder.

**Comment by anmol20112000** [comment]
> Change the folder/directory from ` Android_Development/Java/` and add your file to `Android_Development_With_Java/` folder.

i done this commit plzz review that..... will i have to create PR again??

**Pull request closed without merging**
