### PR TITLE
2.4 Layouts in Android Development

### PR DESCRIPTION
**Pull request by Priyanshirathore**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # < 122> 
Briefly describes what is a layout. Discuss its different attributes. Briefly describe each type of layout with sample code and images of the output screen.

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev (Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>
@VikasPandey121  sir please review.

### CODE REVIEW

**Comment by VikasPandey121** [comment]
I can't merge your contribution because it also consists of commits from the main branch kindly do the needful changes and create a new PR for the assistant regarding it please use the general channel. 

1- Create a new branch `Android_Development_With_Java` using `git branch Android_Development_With_Java`.
2- Checkout to this new branch using  `git checkout Android_Development_With_Java`.
3- Now you add your file your files into this branch only using the command `git add .`
4- Commit your changes using the command `git commit -m "ENTER YOUR COMMENT HERE"`.
5- Push your changes using the command `git push origin Android_Development_With_Java`

**Comment by Priyanshirathore** [comment]
I didn't get it, sir, I made the new branch named patch2, and then I asked to merge that branch only with girlscript android java branch.

> I can't merge your contribution because it also consists of commits from the main branch kindly do the needful changes and create a new PR for the assistant regarding it please use the general channel.
> 
> 1- Create a new branch `Android_Development_With_Java` using `git branch Android_Development_With_Java`.
> 2- Checkout to this new branch using `git checkout Android_Development_With_Java`.
> 3- Now you add your file your files into this branch only using the command `git add .`
> 4- Commit your changes using the command `git commit -m "ENTER YOUR COMMENT HERE"`.
> 5- Push your changes using the command `git push origin Android_Development_With_Java`

**Comment by VikasPandey121** [comment]
You did not rebase your branch to the recent commit on `Android_Development_With_java` due to which you are having commit from the main branch. 
Please look into the general channel for the instructions on how to deal with it.

**Comment by Priyanshirathore** [comment]
> You did not rebase your branch to the recent commit on `Android_Development_With_java` due to which you are having commit from the main branch.
> Please look into the general channel for the instructions on how to deal with it.

yes sir, I understood that yesterday, I made a new PR and it got merged too. Thankyou!

**Comment by VikasPandey121** [comment]
Please always tag the issue number in your PR like #122.

**Comment by Priyanshirathore** [comment]
> Please always tag the issue number in your PR like #122.

yes sir, I did.

**Pull request closed without merging**
