### PR TITLE
Added Switch Expressions in JAVA

### LINKED ISSUE #1899: Java 6.3: Switch Expressions
### Description

Description Add audio, Documentation, and Video regarding the **Switch Expression**.

____

### Location of File to be added

The files should be added inside the `Switch Expression`  folder which is inside the `Control Statements`  folder present in the   `Java`  main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE` , so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by eshan1925**
<hr>

## Description 📜

I have included the detailed info about the switch case statements (both according to new and old versions of Java)
With this I also added a feature of giving User the choice to copy the code if he/she wants.
Fixes #1899 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by AkMo3** [comment]
https://smallseotools.com/view-report/092a24f5969df705fee46924e29292e3/

**Comment by AkMo3** [comment]
@eshan1925 Try to bring it below 20%

**Comment by eshan1925** [comment]
@AkMo3  whatever I have mentioned in the documentation is Important from the student point of view and I have combined my notes, official documentation and few other resources like blogs all together.
And then this is the resultant and the best form of docs on switch case statements according to me.
So please review the content i guess , still if their is an issue let me know.

**Comment by garvitraj** [comment]
Content plagiarism should not be more than a 10% Pls close this or and make new PR

**Comment by eshan1925** [comment]
Will try my best to reduce it, For the last time. :)

**Comment by eshan1925** [comment]
@AkMo3 and @garvitraj I have added new PR #2158 .Please have a look and merge it if there is no issue.
Thankyou

**Pull request closed without merging**
