### PR TITLE
DS-R: 1.2.DOC History - History of Data Science #140

### LINKED ISSUE #140: DS-R: 1.2 History of Data Science
## Description :
* History of Data Science

* Changes should be made in **DS-R/** directory under **Datascience_With_R** branch.
* You have to push your PR to the **Datascience_With_R** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

### PR DESCRIPTION
**Pull request by ashish-reddy-20-08**
<hr>

## Description 📜

Made a document on the topic of the History of data science.  
Fixes #140 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with R

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.

- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ashish-reddy-20-08** [comment]
@micepram, Kindly evaluate the PR.
Batch - 1
serial number: 12 
Name: M. Ashish Reddy

**Comment by ashish-reddy-20-08** [comment]
@micepram , Can you kindly merge this PR if everything is ok . So that i can work on other pr's.

**Comment by harshita2319** [comment]
> @micepram , Can you kindly merge this PR if everything is ok . So that i can work on other pr's.

Hey, the content seems to be plagiarized. You're free to rephrase the sentences but please don't copy.

**Comment by ashish-reddy-20-08** [comment]
@harshita2319 , can you please review it mam. I have changed the sentences.

**Comment by micepram** [comment]
[Check Plagiarism](https://www.check-plagiarism.com/)

After running your content through, I get 72% plagiarized. Please rephrase content and reference the sources @ashish-reddy-20-08 and bring it down to below 30% at a minimum.

**Review by micepram — CHANGES_REQUESTED** [review]
Make the changes as told in the issue thread.

**Comment by ashish-reddy-20-08** [comment]
@micepram, @harshita2319  , can you please evaluate , I have made the changes.

**Comment by ashish-reddy-20-08** [comment]
@micepram  , @harshita2319 , PLEASE REVIEW THE PR AND MERGE IT IF EVERYTHING IS FINE.

**Pull request merged**
