### PR TITLE
Create Answer to Tell me About yourself.md

### LINKED ISSUE #2855: Introductions/  About yourself in the Interviews
### Description

Important Aspects of what should be covered in your Introduction with exaples

### Domain

Interview Prep

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Nupurksk**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2855 #2854
<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations, and regular explanatory films are all possibilities, etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [x] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by syedareehaquasar** [comment]
Please add an example as well.
Audio, video, or text type and customize it with a role so you can create a file name UG Example/ Software Engineer Example or any other one.
Also, Mark the checklist with what apply (how to do it is [] -> [X]) Just put X in the square braces. Some spell mistakes are also in the comments do fix them as well. There are #

**Comment by syedareehaquasar** [comment]
Also add Fixes # <issue_number_here> this in place of <> add the issue you are fixing!

**Comment by Nupurksk** [comment]
> Please add an example as well.
> Audio, video, or text type and customize it with a role so you can create a file name UG Example/ Software Engineer Example or any other one.
> Also, Mark the checklist with what apply (how to do it is [] -> [X]) Just put X in the square braces. Some spell mistakes are also in the comments do fix them as well. There are #

I am unable to Find How to give answer to Tell me about your self in Readme

**Comment by syedareehaquasar** [comment]
It's the description I was talking about

**Comment by syedareehaquasar** [comment]
Also, separate behavioral and Introduction file commits make a new commit for the behavioral questions. Also as mentioned earlier give an example of self Introduction... It's not done yet!

**Comment by syedareehaquasar** [comment]
I am suggesting to separate as that will increase ur contributions as well and label that issue resolved in new PR

**Comment by Nupurksk** [comment]
> Also, separate behavioral and Introduction file commits make a new commit for the behavioral questions. Also as mentioned earlier give an example of self Introduction... It's not done yet!

I have already added an example at the End

**Comment by syedareehaquasar** [comment]
Got It I thought You will create a new file didn't notice that! Great Let's merge this one! Few edits I will Help do that after the merge!

**Comment by syedareehaquasar** [comment]
Few pointers for the future! There were grammatical errors, Markdown was not properly used for example for the bullet points!
Since this was your first commit I omitted those but please take care for future commits! :-)

**Comment by Nupurksk** [comment]
> Few pointers for the future! There were grammatical errors, Markdown was not properly used for example for the bullet points!
> Since this was your first commit I omitted those but please take care for future commits! :-)

For sure, Thank you.

**Pull request merged**
