### PR TITLE
OpenSource : Docker Hub Repository #3799

### LINKED ISSUE #3799: OpenSource : Docker Hub Repository
## Description
Docker Hub is a service provided by Docker for finding and sharing container images with your team. It is the world’s largest repository of container images with an array of content sources including container community developers, open source projects and independent software vendors (ISV) building and distributing their code in containers.

##  Checklist 
- Explain Docker Hub .
- Explain Role of Docker Hub in distributing and shipping opensource software .
- Using Docker Hub with example .
- Installing Docker and using images from docker hub .
- Advantages / Disadvantages of docker hub .
- Alternatives to Docker Hub .

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ELLIPSIS009**
<hr>

## Description 📜

Explain everything related to Docker, Docker Hub with example of how to create a Docker Hub Repository
Fixed #3799 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ELLIPSIS009** [comment]
@Aryamanz29 please check

**Review by Aryamanz29 — CHANGES_REQUESTED** [review]
Nice work @ELLIPSIS009  One thing I'll suggest you to do that move this `doc` content to `CNCF_Porjects/5.4_Docker.md` because there you see less content about docker.
Once you done with the changes we'll move forward with this PR 🚀

**Comment by ELLIPSIS009** [comment]
so i should replace that doc with my doc?

**Comment by Aryamanz29** [comment]
> so i should replace that doc with my doc?

Not completely replace that,  just make some modifications and add your content there :)

**Comment by ELLIPSIS009** [comment]
okay

**Comment by ELLIPSIS009** [comment]
so should i keep mu original doc as well named as 5.4_Docker_Hub_Repository.md and add a bit of my content of Docker in 5.4_Docker.md .......... is that correct?

**Comment by ELLIPSIS009** [comment]
@Aryamanz29 please check the changes

**Review by Aryamanz29 — APPROVED** [review]
LGTM 
Thanks for contributing @ELLIPSIS009 🎉

**Pull request merged**
