### PR TITLE
ML_1_7_Parzen_Windows_(D)_#592

### LINKED ISSUE #592: ML 1.7 : Parzen Windows (D)
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Parzen Windows**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Using Google Colab/Jupyter Notebook) [Upload the documented .ipynb file while making the PR]

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by ELLIPSIS009**
<hr>

## Description 📜

Here I have explained in brief about Parzen Windows along with examples and its uses.
Fixes #592

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by geeythree — CHANGES_REQUESTED** [review]
The equations as well as the graph are not legible. Please put those on white background. Also run your file through plagiarism checker. If plagiarism is over 20 to 25% please rewrite the content.

**Comment by abhisheks008** [comment]
@ELLIPSIS009 Do the needful changes otherwise we can not proceed.

**Comment by ELLIPSIS009** [comment]
okay i am working on it

**Comment by abhisheks008** [comment]
@ELLIPSIS009 Please update on this issue.

**Comment by ELLIPSIS009** [comment]
I am so sorry i couldnt work on it, i actually took covid vaccine on Friday and it took me 2 days to recover, I am working on it and would require 2 days max, I hope you understand

**Pull request closed without merging**
