### PR TITLE
Data science with python: Introduction to unsupervised learning

### PR DESCRIPTION
**Pull request by Robinrai2612**
<hr>

## Description 📜

I have worked on the issue "Introduction to Unsupervised learning" in which I have explained the detailed information about the unsupervised learning. Fixes issue #428

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Robinrai2612** [comment]
@prathimacode-hub Please review this PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to do :

You're in right track now.
Remove the README file from "images" folder
Title images folder as "Images"
The project file should be in snake case : introduction_to_unsupervised_learning.ipynb
In main README.md, at the end write the conclusion and overall summary of the topic and work you had done.
In .ipynb file you can add few code snippets to explain it well. Theory is good but some code needs to justify the theory.

You can do this. Once it's done. all good. @Robinrai2612

**Comment by Robinrai2612** [comment]
@prathimacode-hub I have committed the changes .Please review it.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats. You have an amazing edication and will ppower. Great start. And wonderfully explained. Keep up the good work. 👏🎉@Robinrai2612

**Pull request merged**
