### PR TITLE
What_is_pass_in_Python #562

### PR DESCRIPTION
**Pull request by acrocks1000**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by kalyanirb12** [comment]
I would like to contribute through documentation. please assign to me.

**Comment by SouravKr2001** [comment]
Plz assign it to me

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Remove the .md file from Python_Loops as it's repetitive with the .md file in "What_is_pass_in_Python". Also add more detailing in .md file with theoretical explanations.

That's it. @acrocks1000

**Comment by kumarankm** [comment]
@acrocks1000 Would you like to change the changes mentioned by a mentor or can I close this pr?

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
