### PR TITLE
ML 3.1 What is Clustering? Validate its necessity using real-world applications. (A)

### PR DESCRIPTION
**Pull request by ron352**
<hr>

## Description 📜
Audio content of clustering
Unsupervised learning
Clustering
Examples
Similarity Measurement
Types of clustering
Applications

Fixes # <4098> 

<hr>

## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by ron352** [comment]
Audio content of clustering:

Unsupervised learning
Clustering
validating in rea life
Similarity Measurement
Types of clustering
Applications

@geeythree @abhisheks008  please kindly review this 👍

**Review by kshitijshrivastava1903 — COMMENTED** [review]
Nice one. Kindly, increase your pace of speaking, and make it to the point, start directly with the explanation and use of Birch algorithm.

**Review by kshitijshrivastava1903 — COMMENTED** [review]
Kindly change the example of me and my friend using books, and describe a real life example elaborately, for explaining clustering, like Amazon and Netflix grouping customers, on the basis of their buy and watch history, for making recommendations, so that reader can relate.

**Comment by ron352** [comment]
please check it now.

**Review by geeythree — APPROVED** [review]

**Pull request merged**
