### PR TITLE
DSA 3.2.1 Greedy Algorithms - Introduction

### LINKED ISSUE #5918: DSA 3.2.1 Greedy Algorithms - Introduction
## Description
Give an introduction and discuss about the correctness and proof of greedy algorithms.
**Important: Do not use assign command for this issue.**
## Task
- [ ] Video

## Note
- After completion of your task, add your file in this [folder](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/01.%20Introduction%20To%20Greedy%20Algorithms) and name it 3.2.1_Greedy_Algorithms_Introduction_Video.md
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by Asmit2952**
<hr>

## Description 📜

Added info about greedy algorithms, also added correctness and proof of greedy algorithms.
Fixes #5918  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by nimisha-yadav — COMMENTED** [review]
Hey @Asmit2952 your assigned issue was a video contribution. You need to record a video on the topic. You can do either of these two things now.

You may record and add a video here in this file so as to count as a valid PR or you may wait for sometime. The documentation is part is already assigned to someone else, once they submit it, you may edit and suggest improvements in that file since your documentation is quite good.

**Comment by nimisha-yadav** [comment]
> 
> Oh okay, I'll wait for sometime then, and I'll suggest edits if necessary. And if everything's fine, I'll try to make a video.

Sounds good.

**Comment by Danish-Belal** [comment]
Assign this to me 
Danish Belal

**Comment by nimisha-yadav** [comment]
> Assign this to me Danish Belal

This is not an issue but a pull request, you may try for these [open issues.](https://github.com/girlscript/winter-of-contributing/issues?page=1&q=is%3Aopen+label%3AUp-For-Grabs+DSA)

**Review by nimisha-yadav — COMMENTED** [review]
Hey @Asmit2952, the documentation has been added, [refer here](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/3.2%20Greedy%20Algorithms/01.%20Introduction%20To%20Greedy%20Algorithms/readme.md) and you can add your extra content to it now :)
Do not omit any necessary content from the original file.

**Comment by Asmit2952** [comment]
> Hey @Asmit2952, the documentation has been added, [refer here](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/3.2%20Greedy%20Algorithms/01.%20Introduction%20To%20Greedy%20Algorithms/readme.md) and you can add your extra content to it now :)
> Do not omit any necessary content from the original file.

Okkk sure, I'll add some extra content if necessary

**Pull request closed without merging**
