### PR TITLE
C/C++ Introduction to Pointers - Fixes #953

### LINKED ISSUE #953: Introduction to Pointers
<hr>

### Introduction to Pointers
This will be a documentation on Introduction to Pointers in C/CPP
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by silicolicious**
<hr>

## Description 📜

Fixes #953  
I have made a new folder named *Introduction to Pointers* inside *winter-of-contributing/C_CPP/Pointer and its types/*  
Inside the folder I have included a document named *Introduction_to_Pointers.md* which contains the following things which are explained properly:-
* Memory
* What are Pointers
* Understanding Pointers with an Example
* How to Declare and Initialise Pointers
* How to Dereference a Pointer?  

and a *README.md* file is created which contains index like links for all the above mentioned topics inside the markdown file.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊
- [x] C/CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by silicolicious** [comment]
@Saviour1001 @Suvraneel 
I have made a PR here, pls review it.

**Comment by Saviour1001** [comment]
Hey great work @silicolicious with the documentation. You don't need to add the 2 readme files for now. Kindly delete them and just keep the documentation.

**Comment by silicolicious** [comment]
> Hey great work @silicolicious with the documentation. You don't need to add the 2 readme files for now. Kindly delete them and just keep the documentation.

Yeah ok 👍 
Thank you!

**Comment by silicolicious** [comment]
@Saviour1001 
Changes completed Harsh, removed both the readme.md files, anything else or is it ready to be merged?

**Comment by Saviour1001** [comment]
Perfect @silicolicious !

**Pull request merged**
