### PR TITLE
Priority queue

### LINKED ISSUE #1612: priority queue
<hr>

## Description 📜

- Explain about priority queue 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by Raghavshalu**
<hr>

## Description 📜

In the folder "Data Structure" I made one more folder called "Priority_Queue" in that I have an MD file that resolves an issue about **Priority Queue** by including some defining and pictures at last show a demo of program. On the basis:-
   - Main Priority Queues Operations
   - Implementation of a Priority Queue
   - Priority Queue Representation
Fixes #1612

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
App Screenshot
App Screenshot

<hr>

### CODE REVIEW

**Review by deeqakkk — APPROVED** [review]
Try to explain things in points, that looks more better and easy to understand as well.
For now its good.

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Delete your images...
I have embedded them for you... Have a look

**Comment by Raghavshalu** [comment]
> Delete your images...
> I have embedded them for you... Have a look

Done

**Comment by Suvraneel** [comment]
:octocat:

**Pull request merged**
