### PR TITLE
Cyber_Security: 1.9.7_Types_of_Hackers

### LINKED ISSUE #148: Cybersecurity: 1.9.7 Types of Hackers.
### Discuss 8 Types of Hackers:

 - White Hat Hackers.
 - Black Hat Hackers.
 - Gray Hat Hackers.
 - Script Kiddies.
 - Green Hat Hackers.
 - Blue Hat Hackers.
 - Red Hat Hackers.
 - State/Nation Sponsored Hackers.
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with Diagrams
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by 0shivamh**
<hr>

## Description 📜
It describes who is a hacker and what are the different types of hackers

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #148 
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Cyber Security

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Anant1711 — CHANGES_REQUESTED** [review]
@0shivamh You did great work!
But can you add some more content, you wrote very less just1-2 lines, like Blue-hat, Green-hat, Red-hat.

**Comment by 0shivamh** [comment]
> @0shivamh You did great work!
> But can you add some more content, you wrote very less just1-2 lines, like Blue-hat, Green-hat, Red-hat.

Okay, @Anant1711 , I'll do it

**Comment by 0shivamh** [comment]
> @0shivamh You did great work!
> But can you add some more content, you wrote very less just1-2 lines, like Blue-hat, Green-hat, Red-hat.

Okay, @Anant1711 , I'll do it

**Comment by 0shivamh** [comment]
Hey @Anant1711, it is fine now, or have to add more content.

**Review by Anant1711 — APPROVED** [review]

**Pull request merged**
