### PR TITLE
Java 9.3: Constructors and "this" key word #2090

### PR DESCRIPTION
**Pull request by JayashreeSadarhalli**
<hr>

## Description 📜

Audio Explanation about Constructor and this keyword #2090 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise , Low distortion)

<hr>

## Domain of Contribution 📊

- [x] Java_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by JayashreeSadarhalli** [comment]
Constructor and this keyword #2090 : Adding Constructor_and_this_keyword  audio in .mp3 format

**Comment by sumitaccess007** [comment]
Hello @garvitraj, @AkMo3,
Audio content for PR - #2235, is okay. Both topics are covered with correct explanation and audio quality is also good.

@JayashreeSadarhalli - Good Work and explanation, Keep Going :runner:

**Review by sumitaccess007 — COMMENTED** [review]
Hello @garvitraj, @AkMo3,
Audio content for PR - #2235, is okay. Both topics are covered with correct explanation and audio quality is also good.

@JayashreeSadarhalli - Good Work and explanation, Keep Going 🏃

**Review by AkMo3 — CHANGES_REQUESTED** [review]
0:52 - Constructor must be declared in public mode. Wrong! A constructor can have any of the access modifiers.

1:18 - Delete operator! I have never heard of it. Java doesn't provide the option to deallocate objects. To deallocate objects, either we assign it to null and then garbage collector does the job, else we call finalize() method and destroy the object.

**Pull request closed without merging**
