### PR TITLE
[JS] Topic: Iterables, sets and maps

### PR DESCRIPTION
**Pull request by SakshiMishra1**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Iterables, maps and sets
Fixes # <#1833> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [x] JavaScript
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 Please review.

**Review by paramsiddharth — CHANGES_REQUESTED** [review]
The document looks really great to me! With a few changes, it would be ready to merge.

Please use a markdown file and NOT an extensionless text file for the document contribution. Also, use syntax highlighting whenever possible. Please rename the file and go ahead with the update requested.

**Comment by SakshiMishra1** [comment]
@paramsiddharth thank you sir. Noting down the changes.

**Review by dakshsethi — CHANGES_REQUESTED** [review]
The content looks good but this is not well documented!!!
Use proper markdown styling techniques - https://guides.github.com/features/mastering-markdown/

**Comment by Creatoon** [comment]
@SakshiMishra1 will review once you complete your pr

**Review by SakshiMishra1 — COMMENTED** [review]
@paramsiddharth sir please review the changes. #1881

**Comment by paramsiddharth** [comment]
@SakshiMishra1 The PR was branched out of the `main` branch instead of the `Javascript`, which produces a huge diff. Hence, your PR cannot be merged. Don't worry, you can still contribute to the merged document by extending it or adding contributions in the form of audio and video.

**Pull request closed without merging**
