### PR TITLE
Fundamentals

### LINKED ISSUE #1198: Java 2.2: OPPs Principal
<hr>

## Description 📜

Add audio, documentation, and video regarding the **OPPs Principal**.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

## Location of File to be added

The files should be added inside the `OPPs Principal` folder which is inside the `Fundamental` present in the  `Java` main folder.  The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.

 **Note:**
 - You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 - Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 - You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 - Issues will be assigned on a first come first serve basis.

### PR DESCRIPTION
**Pull request by Binita-tech**
<hr>

## Description 📜

Added Audio part of OOP Principals under Fundamentals of Java
Fixes #1198

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [x] Java_Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by justdoit254** [comment]
Sir/Ma'am, I want to contribute to fundamentals in java.

**Review by sumitaccess007 — CHANGES_REQUESTED** [review]
@Binita-tech,
For the topic - Fundamentals
Why are you modifying other folders, please check below file
Java/History Of Java/Untitled0.ipynb
What it is for ?

**Comment by Binita-tech** [comment]
@sumitaccess007 ,
I haven't make any changes in this folder. I don't know why it is showing like this

**Comment by sumitaccess007** [comment]
> @sumitaccess007 , I haven't made any changes in this folder. I don't know why it is showing like this. what should i do next?

@Binita-tech - Delete this file and push again. After that there will be only 1 file under 'Files Changed section'
image

**Review by AkMo3 — CHANGES_REQUESTED** [review]
@Binita-tech Add the link (upload in a google drive) of audio in a readme file.

**Comment by Binita-tech** [comment]
I need help, Can anyone of you help me in VC. I am confused. It will take 5-6 min please
@sumitaccess007 , @AkMo3

**Comment by AkMo3** [comment]
Discord VC is banned in my college. Please reach out to @garvitraj at the appropriate time (Usually 9:30 AM).

**Comment by Binita-tech** [comment]
Added README file @AkMo3

**Pull request closed without merging**
