### PR TITLE
Dsa Merge Sort

### PR DESCRIPTION
**Pull request by uzma024**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # 3306

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot 2021-10-05 at 9 21 36 PM

<hr>

### CODE REVIEW

**Comment by uzma024** [comment]
Please add 'hacktoberfest-accepted' label to my PR.

**Review by nimisha-yadav — COMMENTED** [review]
The video is very well created, great work on that! There are just a couple of minor changes required. Compress your video and then upload it to drive, once the preview option shows then you can insert it in your md file. Best way is that you upload it to Youtube either unlisted or public. Also, use a better picture in your md file and give credits to the author.

Once you're done, tag @goelesha. She allotted you this issue so she'll give the final review and merge it.

**Comment by nimisha-yadav** [comment]
> 
> 
> Credits to author of the md file? Other sites have been included in video and resources.
> 
> > The video is very well created, great work on that! There are just a couple of minor changes required. Compress your video and then upload it to drive, once the preview option shows then you can insert it in your md file. Best way is that you upload it to Youtube either unlisted or public. Also, use a better picture in your md file and give credits to the author.
> > Once you're done, tag @goelesha. She allotted you this issue so she'll give the final review and merge it.

Credits to the author of image - the image of istock which you used.

**Comment by uzma024** [comment]
> > Credits to author of the md file? Other sites have been included in video and resources.
> > > The video is very well created, great work on that! There are just a couple of minor changes required. Compress your video and then upload it to drive, once the preview option shows then you can insert it in your md file. Best way is that you upload it to Youtube either unlisted or public. Also, use a better picture in your md file and give credits to the author.
> > > Once you're done, tag @goelesha. She allotted you this issue so she'll give the final review and merge it.
> 
> Credits to the author of image - the image of istock which you used.

Oh okay I will upload the one in the pr instead.

**Comment by uzma024** [comment]
@goelesha Kindly review my pull request. And please merge it.

**Comment by goelesha** [comment]
@uzma024 Looks good to me. Congrats on getting your PR merged.

**Comment by goelesha** [comment]
@uzma024 I will edit it. No worries

**Comment by uzma024** [comment]
> @uzma024 I will edit it. No worries

Thank you so much.

**Pull request merged**
