### PR TITLE
Flutter : Widgets documentation

### PR DESCRIPTION
**Pull request by supriya-045**
<hr>

## Description 📜

I had added about flutter widgets .
Fixes # 1007

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>
<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by WarMac4964** [comment]
@supriya-045 Please check the [markdown file](https://github.com/girlscript/winter-of-contributing/pull/1725/commits/9403d6d8912f1dc477a4cb9e2419bd7421317a51) as the images present in the file are not displayed correctly, Thanks

**Comment by supriya-045** [comment]
> @supriya-045 Please check the [markdown file](https://github.com/girlscript/winter-of-contributing/pull/1725/commits/9403d6d8912f1dc477a4cb9e2419bd7421317a51) as the images present in the file are not displayed correctly, Thanks

Actually it is not decoded by markup as it was .py file so i removed that part. Please check it  now .

**Comment by WarMac4964** [comment]
Looks good to me, One last question @supriya-045 do we need to include that jupyter nb? We'll only be needing the markdown file for the repo right?

**Comment by supriya-045** [comment]
> Looks good to me, One last question @supriya-045 do we need to include that jupyter nb? We'll only be needing the markdown file for the repo right?
> As I could not see that file being deleted

Deletd now .

**Comment by WarMac4964** [comment]
@Asmit2952 We are good to go with this PR

**Comment by Asmit2952** [comment]
> @Asmit2952 We are good to go with this PR

I think you tagged the wrong person?

**Pull request merged**
