### PR TITLE
1.1.5.7 Arrays: Standard Problems (Problem 7) 

### LINKED ISSUE #2241: DSA 1.1.5.7 Arrays: Standard Problems (Problem 7)
### Description

Given an array of N integers arr[] where each element represents the max number of steps that can be made forward from that element. Find the minimum number of jumps to reach the end of the array (starting from the first element). If an element is 0, then you cannot move through that element.
Note: Return -1 if you can't reach the end of the array.

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by siddhi-244**
<hr>

## Description 📜

1.1.5.7 Arrays: Standard Problems (Problem 7) 
Fixes #2241  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by siddhi-244** [comment]
> /assign

Dude it's my pr!

**Comment by siddhi-244** [comment]
@goelesha plzz see to this. Someone has assigned my pr to them .

**Comment by thatSophisticatedMess18** [comment]
Sorry, but it didn't show assigned to anyone , that is why used the assign tag here.

**Comment by siddhi-244** [comment]
> Sorry, but it didn't show assigned to anyone , that is why used the assign tag here.

But this is a pr! It's not a issue.

**Comment by thatSophisticatedMess18** [comment]
So sorry. I didn't know. It's okay, I will unassign this PR. Sorry for the issue.

**Comment by goelesha** [comment]
@siddhi-244 Plagiarised code !!
The entire code is copied from geek for geeks.

**Comment by siddhi-244** [comment]
> @siddhi-244 Plagiarised code !!
> The entire code is copied from geek for geeks.

No ma'am I took a reference

**Comment by siddhi-244** [comment]
> > @siddhi-244 Plagiarised code !!
> > The entire code is copied from geek for geeks.
> 
> No ma'am I took a reference

I wrote the whole document by my own.

**Pull request closed without merging**
