### PR TITLE
Create classes_and_objects.md

### LINKED ISSUE #901: C_CPP : documentation on classes and object
<hr>

## Description 📜

I will be creating a documentation on Classes and Object

<hr>

## Domain of Contribution 📊

- [ ] C/CPP

<hr>

### PR DESCRIPTION
**Pull request by jaissumi1402**
<hr>

## Description 📜

added documentation on classes and objects
Fixes #901

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Comment by jaissumi1402** [comment]
@Suvraneel sir please review my documentation.

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Contribution is perfect 
Add a line in readme of same folder
ie, in Adv C++ OOPs Prog/readme,md

**Comment by jaissumi1402** [comment]
@Suvraneel I have updated the readme file can you please review and merge it?

**Review by gunjan-g — CHANGES_REQUESTED** [review]
@jaissumi1402 Please place the files in the correct folder of Classes and Objects Programming

**Comment by jaissumi1402** [comment]
@gunjan-g I have changed the location of file can you please review and merge it?

**Comment by Suvraneel** [comment]
@jaissumi1402 Just 1 Index line in Classes and objects/readme.md

**Comment by jaissumi1402** [comment]
@Suvraneel that index line is already there. I think someone else has contributed this topic before me.

**Comment by jaissumi1402** [comment]
@Suvraneel now is it okay?

**Review by gunjan-g — APPROVED** [review]
Great work @jaissumi1402 
I guess it's fine @Suvraneel, we can merge this

**Comment by Suvraneel** [comment]
@jaissumi1402  Great work ❤️  :octocat:

**Comment by jaissumi1402** [comment]
Thankyou so much @Suvraneel @gunjan-g for your guidance :)

**Comment by gunjan-g** [comment]
> Thankyou so much @Suvraneel @gunjan-g for your guidance :)

😄

**Comment by amankumar11** [comment]
@jaissumi1402 @gunjan-g @Suvraneel my PR regarding these topics was already merged in the repo.

**Comment by amankumar11** [comment]
> @jaissumi1402 @gunjan-g @Suvraneel my PR regarding these topics was already merged in the repo.

https://github.com/girlscript/winter-of-contributing/pull/1157 link of the previous PR

**Pull request merged**
