### PR TITLE
Frontend Dev (HTML, CSS, JS): CSS background-repeat( CSS property to set how background images are repeated)

### PR DESCRIPTION
**Pull request by Subhrato20**
<hr>

## Description 📜

I would like to make documentation on CSS background-repeat ( CSS property to set how background images are repeated)
I would provide theory related to it along with some examples #3854 

<hr>

## Type of change 📝

- [X] Documentation (Content Creation in the form of codes or tutorials)
 

<hr>

## Domain of Contribution 📊

- [X] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by iam-sakshi** [comment]
please Assign this issue to me.

**Review by 2024-SANDHYA — CHANGES_REQUESTED** [review]
Plagiarized content, rephrase it.
@code-reaper08  Have a look 👀

**Comment by Subhrato20** [comment]
wait I am working on it

**Comment by Subhrato20** [comment]
@2024-SANDHYA ma'am can you check now.

**Review by code-reaper08 — CHANGES_REQUESTED** [review]
Now it's rephrased, But I would love to see at least a different example rather than the one from **MDN Docs**. In that way it would be more awesome.

**Comment by Subhrato20** [comment]
@code-reaper08 sit is it better?

**Comment by Subhrato20** [comment]
@code-reaper08 sir & @2024-SANDHYA ma'am can you check it now?

**Review by 2024-SANDHYA — APPROVED** [review]
LGTM ! 💯

**Review by code-reaper08 — APPROVED** [review]

**Pull request merged**
