### PR TITLE
Python: 1.5 Brief history of python

### PR DESCRIPTION
**Pull request by amitrakshar01**
<hr>

## Description 📜

Added Python: 1.5 Brief history of python.md and updated README index#784 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
 

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>
 
## Checklist ✅
- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by amitrakshar01** [comment]
@prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

The readme should be titled as a README.md file. You can add more topics, as python is an ocean like applications, features, how it's different from other languages, why one should choose python, how it's going to help developers, overall summary and conclusion in your words.
There should be an another file with file name and in snake case : brief_history_of_python.ipynb
In this file, show case python, few code snippets of how python works along with explanation of it and what all does python endorse with using visual representations.

Kindly work on it. @amitrakshar01

**Comment by prathimacode-hub** [comment]
Kindly work on this changes. @amitrakshar01

**Comment by kumarankm** [comment]
@adityabisoi Close this pr

**Pull request closed without merging**
