### PR TITLE
Data Science with Python : Exploratory Data Analysis using Python

### PR DESCRIPTION
**Pull request by nakshatra-garg**
<hr>

## Description 📜

Created Video on Exploratory Data Analysis using Superstore Dataset.
Issue Title: Data Science with Python: Exploratory Data Analysis using Python
Fixes: #348

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

Please review @prathimacode-hub

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure and don't do changes to other's work. This is a video so it should go under "Data_Science_with_Python/Data Analysis and Visualization/Videos/"
Add all file recordingly and create your own README.md file with all the details on your issue. @nakshatra-garg

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done.

Add .ipynb file in same place of your README file.
And project file name should be in snake case.

Kindly do the changes. @nakshatra-garg

**Comment by nakshatra-garg** [comment]
I've made the requested changes, Please review @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👍@nakshatra-garg

**Pull request merged**
