### PR TITLE
Node JS file added.

### LINKED ISSUE #2178: Frontend_Web_Development_HTML_CSS_JS: Node Js
### Description

Documentation on getting started with Node Js.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Piyushjar**
<hr>

## Description 📜
Documentation/Tutorial added for topic Node Js
Fixes #2178

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Added
<hr>

### CODE REVIEW

**Review by code-reaper08 — APPROVED** [review]
Looks awesome 😃

@2024-SANDHYA have a look

**Comment by ghulamyazdani** [comment]
You have to add some more details about node js

**Comment by Piyushjar** [comment]
Further than installation and getting started ?
Like should I add about npm ?

**Comment by code-reaper08** [comment]
> Further than installation and getting started ? Like should I add about npm ?

Yes I think, I'll make it more awesome!

**Review by code-reaper08 — APPROVED** [review]
LGTM now ✨

**Pull request merged**
