### PR TITLE
C_CPP : Enumerated Data Type

### PR DESCRIPTION
**Pull request by sonali-t**
<hr>

## Description 📜

I have added the Enum.md file explaining concepts about Enumerated Data Type in C/C++.
@Saviour1001 pls review the changes and do let me know if any other change is to be made.
Fixes # <3364> 
Added documentation on Enumerated Data Type
Name - Sonali Tomar
Batch - C_CPP Batch 5
This PR is with reference to the issue #3364

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

### CODE REVIEW

**Review by gunjan-g — CHANGES_REQUESTED** [review]
@sonali-t good work 👼🏻 
Just add this file name and relative link in the readme too

**Comment by sonali-t** [comment]
> @sonali-t good work 👼🏻 Just add this file name and relative link in the readme too

Hi @gunjan-g Thank You
Can you please explain me which readme I have to edit and how?

**Review by gunjan-g — CHANGES_REQUESTED** [review]
@sonali-t just remove the first line ## Index, we just need the second line and it's good to go

**Comment by sonali-t** [comment]
> @sonali-t just remove the first line ## Index, we just need the second line and it's good to go

I have made the changes, Please have a look

**Comment by gunjan-g** [comment]
@Suvraneel please merge this pr

**Comment by gunjan-g** [comment]
> > @sonali-t just remove the first line ## Index, we just need the second line and it's good to go
> 
> I have made the changes, Please have a look

Yes, it's fine now 😄

**Pull request merged**
