### PR TITLE
1.2.2.1_Algorithms:_Recurrence_Relations_(Introduction)

### LINKED ISSUE #482: DSA 1.2.2.1 Algorithms: Recurrence Relations (Introduction)
## Description
Explain recurrence relations and their properties.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### PR DESCRIPTION
**Pull request by Harshil-Jani**
Added Recurrence Relations Introduction and properties for it.

<hr>

## Description 📜

This PR includes an basic introduction to recurrence relations and the properties of it. 
Fixes #482 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Harshil-Jani — COMMENTED** [review]
Self Check Done!

**Comment by kunal-kumar-chaudhary** [comment]
hey! can i contribute in this through video?

**Comment by Harshil-Jani** [comment]
> hey! can i contribute in this through video?

Hey ! @kunal-kumar-chaudhary I am also contributor. You should ask supervisors to Assign you this for Video in #482 Issue section. Till now no one asked for video assigning so I hope you will surely be assigned this :v: Try asking there :smiley:

**Comment by nimisha-yadav** [comment]
Please review @harshsri28

**Review by harshsri28 — APPROVED** [review]
Look's good to me

**Review by nimisha-yadav — CHANGES_REQUESTED** [review]
Hey @Harshil-Jani, please use only md extension. 
Also, update fork
Put your file under Recurrence Relations in Analysis of Algorithms folder
Rename your file 1.2.2.1_Introduction.md

Rest looks fine.

**Comment by Harshil-Jani** [comment]
> Hey @Harshil-Jani, please use only md extension.
> Also, update fork
> Put your file under Recurrence Relations in Analysis of Algorithms folder
> Rename your file 1.2.2.1_Introduction.md
> 
> Rest looks fine.

Oh Okay ! I am doing it very soon. Thanks for reviewing.

**Review by Harshil-Jani — COMMENTED** [review]
Self Check on Requested changes.

**Comment by Harshil-Jani** [comment]
> Hey @Harshil-Jani, please use only md extension.
> Also, update fork
> Put your file under Recurrence Relations in Analysis of Algorithms folder
> Rename your file 1.2.2.1_Introduction.md
> 
> Rest looks fine.

Hey ! I am done with requested changes. Can you check it again ?

**Review by nimisha-yadav — APPROVED** [review]
LGTM. Congrats on getting your PR merged!

**Pull request merged**
