### PR TITLE
  History of C/C++

### PR DESCRIPTION
**Pull request by vishnu95075**
<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # #980 

<hr>

##History of C/C++ 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## C_CPP📊

- [x] C/CPP

<hr>

##C/CPP ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by SouravKr2001** [comment]
plz assign documentation part to me

**Comment by ChetasShree** [comment]
@vishnu95075 please try to add some images and a little bit more information

**Comment by Suvraneel** [comment]
@vishnu95075 Kindly don't make issues like History of C++/History of Java
Make a documentation for something useful (for other ppl)

Check out our roadmap or the directories under c_cpp branch for that

**Comment by vishnu95075** [comment]
@Suvraneel  thanks for feedback .

**Pull request closed without merging**
