### PR TITLE
Data Science with Python : Introduction to Pytorch

### LINKED ISSUE #730: Data Science with Python : Introduction to Pytorch
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Pytorch. Tutorial to Pytorch and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Arya Patel](https://www.github.com/AryaPatel1111) / [Aishani Singh](https://github.com/aishanii)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by KTK-5901**
<hr>

## Description 📜

I have added a Tutorial with related examples for Introduction to PyTorch which is easy for beginners to understand and get familiar with. 
Fixes #730  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Data Science with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
This PR is currently under reviewing process

**Comment by prathimacode-hub** [comment]
Changes to be done 👍

The issue contribution should be under "/Deep Learning/Libraries/Introduction to Pytorch
Elaborate your README file. It needs more detailing. You can find the things you can add up in Project structure document
The project file name should be in snake case : introduction_to_pytorch.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Introduction to Pytorch"

Your README file lacks detailing. And In .ipynb file you had come straight to the point whether it's tensor flow or pytorch. Go it in flow with basic intro and and explain your sample codes. It has no information of what pytorch is or what tensorflow is. Kindly work on it.

@KTK-5901

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍

The issue contribution should be under "/Deep Learning/Libraries/Introduction to Pytorch
Elaborate your README file. It needs more detailing. You can find the things you can add up in Project structure document
The project file name should be in snake case : introduction_to_pytorch.ipynb
If you would like to show any final outcomes or screenshots, you can put up in "Images" folder created under "Introduction to Pytorch"

Your README file lacks detailing. And In .ipynb file you had come straight to the point whether it's tensor flow or pytorch. Go it in flow with basic intro and and explain your sample codes. It has no information of what pytorch is or what tensorflow is. Kindly work on it.

@KTK-5901

**Comment by prathimacode-hub** [comment]
Update here when it's done. @KTK-5901

**Comment by KTK-5901** [comment]
Yes @prathimacode-hub , I will update the changes as soon as possible.

**Comment by KTK-5901** [comment]
@prathimacode-hub, Please review the changes I have made.

**Comment by prathimacode-hub** [comment]
Have you missed any changes to be addressed? @KTK-5901

**Comment by KTK-5901** [comment]
I think now I have addressed to all the changes. @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. Your PR is approved. Amazing start. Good choice of issue. 🎉✨@KTK-5901

**Pull request merged**
