### PR TITLE
Android development with flutter

### LINKED ISSUE #1686: Flutter: Dynamic Views (List View and GridView)
<hr>

## Description 📜

Add a README File, which explains dynamic views - GridView and ListView.,

Reference:
https://flutter.dev/docs
For the structure of folders and files, view previous commits by other contributors

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

### PR DESCRIPTION
**Pull request by Niranjan5601**
<hr>

## Description 📜

Added documentation on list and grid view.
Fixes #1686

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Flutter)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Niranjan5601** [comment]
@thisisamank

**Review by AshAman999 — CHANGES_REQUESTED** [review]
Kindly format the codes so it looks good,
 like have a look at the proper trailing commas,

**Review by AshAman999 — APPROVED** [review]
@ViAsmit  I have checked it, it's good to merge  ✔️

**Comment by ViAsmit** [comment]
Thank you @Niranjan5601 @AshAman999

**Pull request merged**
