### PR TITLE
OOPs CheatSheet-Notes

### LINKED ISSUE #7763: [Interview Preparation]: Add OOPs cheat sheet
### Description

Hi admin, i want to add OOPs cheat sheet under Interview preparation repository. Please assign it to me.

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by singhnikhiljsr**
<hr>

## Description 📜

It contains all concepts related to Object Oriented Programming. 
Fixes #7763 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [x] Interview Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by singhnikhiljsr** [comment]
@syedareehaquasar Please review this and give your suggestions.

**Comment by syedareehaquasar** [comment]
Can you please cover what all languages support OOP and what all doesn't as u mentioned java in a question there are more just mention a few...

**Comment by syedareehaquasar** [comment]
Can you please cover what all languages support OOP and what all doesn't as u mentioned java in a question there are more just mention a few...

**Comment by syedareehaquasar** [comment]
Code examples are not properly indent, Please fix those and in some code there are there box instead of semicolon please take care of that as well.

**Comment by singhnikhiljsr** [comment]
@syedareehaquasar Fixed the code indentation. Please let me know if anything else I need to do.

**Comment by syedareehaquasar** [comment]
Looks good!

**Pull request merged**
