### PR TITLE
C_CPP : LCM and GCD in C++

### LINKED ISSUE #4060: C_CPP : LCM and GCD in C++
### Description

This documentation will explain LCM and GCD by a problem in C++

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by ankushsingh24**
<hr>

## Description 📜
I've completed my issue work , I raised an issue on the LCM and GCD in C++.

This documentation will explain LCM and GCD in C++ :

- It is a beginner friendly documentation of LCM and GCD includes a problem and solution in C++ code with proper comments ahead.
- Explained functions involved in LCM and GCD in the C++ code.

Fixes #4060 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

### CODE REVIEW

**Comment by ankushsingh24** [comment]
@Suvraneel please review my PR. 🚀

**Review by apeksha235 — CHANGES_REQUESTED** [review]
@ankushsingh24 Good job! but plagiarism has been detected in the few parts of the algorithm. Would be better if you try to reframe it in your own words.

**Comment by ankushsingh24** [comment]
@apeksha235 made some changes as suggested, have a look.

**Comment by apeksha235** [comment]
@ankushsingh24 Amazing! 
@Suvraneel please merge this

**Pull request merged**
