### PR TITLE
Update Why Python README.md

### PR DESCRIPTION
**Pull request by httpanand**
<hr>

## Description 📜

Edited Why Python's README file .

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ x] Python_Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by httpanand** [comment]
Hello ! @syedareehaquasar . Could you please review my PR ? 🙏🏽

**Comment by httpanand** [comment]
Hello ! @syedareehaquasar . Could you please review my PR ? 🙏🏽

**Comment by httpanand** [comment]
Hello ! @syedareehaquasar . Could you please review my PR ? 🙏🏽

**Comment by Suvraneel** [comment]
@httpanand  Again, not in my jurisdiction... Can't help

**Comment by httpanand** [comment]
> @httpanand Again, not in my jurisdiction... Can't help

Sorry for the inconvenience .

**Comment by httpanand** [comment]
@adityabisoi Please review

**Comment by Suvraneel** [comment]
> > @httpanand Again, not in my jurisdiction... Can't help
> 
> Sorry for the inconvenience .

No issues... 😄  All the best

I'm not your super, but still here's a few suggestions/corrections :
1. Also, delete hashtag from `Python` domain too, to label it 👍🏻 
2. PR should be made to a branch (eg, Python) & not `main`

**Comment by httpanand** [comment]
> > > @httpanand Again, not in my jurisdiction... Can't help
> > 
> > 
> > Sorry for the inconvenience .
> 
> No issues... 😄 All the best
> 
> I'm not your supe, but still here's a few suggestions/corrections :
> 
> 1. Also, delete hashtag from `Python` domain too, to label it 👍🏻
> 2. PR should be made to a branch (eg, Python) & not `main`



> > > @httpanand Again, not in my jurisdiction... Can't help
> > 
> > 
> > Sorry for the inconvenience .
> 
> No issues... 😄 All the best
> 
> I'm not your supe, but still here's a few suggestions/corrections :
> 
> 1. Also, delete hashtag from `Python` domain too, to label it 👍🏻
> 2. PR should be made to a branch (eg, Python) & not `main`

Oh ok but i changed items in main branch ... so how should i ?

**Pull request closed without merging**
