### PR TITLE
Android-Kotlin-09.18-CardView-and-MaterialCardView-in-Android-…

### PR DESCRIPTION
**Pull request by amaan118921**
Android-Kotlin-09.18-CardView-and-MaterialCardView-in-Android-Kotlin [Fixes Issue #1448]md

<hr>

## Description 📜

Added documentation for CardView and MaterialCardView in Android (Kotlin)
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by amaan118921** [comment]
@rahulsain please review my PR

**Comment by rahulsain** [comment]
Please rename your file and place this file into the appropriate subfolder of the topic folder

**Comment by amaan118921** [comment]
@rahulsain Done Sir, please review

**Comment by amaan118921** [comment]
@rahulsain here

**Comment by sitamadex11** [comment]
@amaan118921 I think your file is a markdown file. Please change the name from `Added 09.18 CardView and MaterialCardView in Android (Kotlin)`  to `09.18 CardView and MaterialCardView in Android (Kotlin).md`

**Comment by rahulsain** [comment]
Please rename your filename as `Android_Development_with_Kotlin/09. Dynamic User Interface/09.18 CardView & MaterialCardView.md`

**Comment by amaan118921** [comment]
@rahulsain sir did it, my file is already placed inside Android_Development_with_Kotlin/09. Dynamic User Interface.
But I renamed the file as suggested by @sitamadex11

**Comment by rahulsain** [comment]
Rename your filename as `09.18 CardView & MaterialCardView.md` . Make sure to add .md after the filename

**Comment by amaan118921** [comment]
@rahulsain Done sir

**Comment by rahulsain** [comment]
Please attach a relevant screenshot of the app after the code (no links, direct image)

**Comment by amaan118921** [comment]
@rahulsain done sir.

**Pull request merged**
