### PR TITLE
Flutter: Installation and setup Android Studio

### LINKED ISSUE #158: Flutter: Installation & Setup Android Studio - Video
A video depicting installation and setup of Android Studio and Flutter on the local machine.

One should cover:
-Download and setup of Flutter
-Download and setup of Android Studio Code
-Change in environment variables, if needed
-Run the default source code of Flutter Project(button click) to check if the setup works flawlessly.

### PR DESCRIPTION
**Pull request by Janak2401**
<hr>

## Description 📜

Created a video that guides on how to install flutter and set up the android studio.
Fixes #158

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

### CODE REVIEW

**Comment by Janak2401** [comment]
Please validate this @thisisamank

**Comment by thisisamank** [comment]
Hi @Janak2401 please make it more elaborate. For example have a look at https://csspoint101.com/how-to-get-started-with-flutter/ this post i wrote a while back.

**Comment by thisisamank** [comment]
@Janak2401 Video looks good to me, clear explanation. Well done! 
Just a suggestion, don't use background music maybe because normally people watch it at different speeds and because the music doesn't sound that good. Even if you use it, use it in the intro and extro.

**Comment by Janak2401** [comment]
> 
> 
> @Janak2401 Video looks good to me, clear explanation. Well done!
> Just a suggestion, don't use background music maybe because normally people watch it at different speeds and because the music doesn't sound that good. Even if you use it, use it in the intro and extro.

Thanks for this advice! I'll keep this in mind.

**Pull request merged**
