### PR TITLE
2.5 Added Functions in Kotlin

### PR DESCRIPTION
**Pull request by eshan1925**
<hr>

## Description 📜
Added Function in Kotlin. All the functions and the documentation provided is genuine and also been taken from the sources mentioned. 
I have also added a feature to copy the code directly from the .md file.
 #1499 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Comment by rahulsain** [comment]
change your folder structure

**Comment by eshan1925** [comment]
Please tell in detail...what to do?

**Comment by rahulsain** [comment]
dont structure the file as `Android_Development_with_Kotlin/2.5 _Functions_in_Kotlin.md`

instead, follow this type of pattern `winter-of-contributing\Android_Development_with_Kotlin\02. Basics of Kotlin\02.5 Functions.md`

**Comment by sitamadex11** [comment]
@eshan1925 You have done great work. One more thing you can add is the extension function. And also change the structure of the file as Rahul(supervisor) mentioned.

**Comment by eshan1925** [comment]
@sitamadex11 I have added the extension function link at the end becuse the documentation was getting way too long, still if it is to be added then please reply me with a yes or no I will add it.  And also I am not able to get what do you mean by changing the structure of the file? Please guide me.

**Comment by sitamadex11** [comment]
ok, then one thing we can do for now is keeping the doc as it is only the file structure. We can make a separate issue for the extension function.

**Comment by sitamadex11** [comment]
Please change the file structure.

**Comment by eshan1925** [comment]
Please guide me what is the file structure ? is it the folder path
@sitamadex11

**Comment by sitamadex11** [comment]
> dont structure the file as `Android_Development_with_Kotlin/2.5 _Functions_in_Kotlin.md`
> 
> instead, follow this type of pattern `winter-of-contributing\Android_Development_with_Kotlin\02. Basics of Kotlin\02.5 Functions.md`

follow this

**Comment by eshan1925** [comment]
Ok thankyou generating another PR

**Comment by eshan1925** [comment]
@sitamadex11 and @rahulsain I have generated another PR #1846 .Please have a look and merge if there is no issue now.

**Pull request closed without merging**
