### PR TITLE
[JS] Other: added the JSON servers section

### PR DESCRIPTION
**Pull request by Surbhi-sinha**
<hr>

## Description 📜
I have added the section of JSON from web servers which are fetched directly in form of AJAX request using APIs.
Please review it and merge ASAP.

Fixes #3168 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by paramsiddharth — APPROVED** [review]
@Creatoon @dakshsethi @s4-2 Please review.

**Review by dakshsethi — APPROVED** [review]
Looks good to me!! 🔥🔥🔥

**Review by sushovanb02 — APPROVED** [review]

**Comment by paramsiddharth** [comment]
@Creatoon @dakshsethi @s4-2 Please review.

**Review by s4-2 — APPROVED** [review]
Looks good to me:)

**Pull request merged**
