### PR TITLE
Cybersecurity 4.5 Caesar Cipher #3645

### PR DESCRIPTION
**Pull request by SwarnaliBhunia**
Cybersecurity 4.5 Caesar Cipher done by Swarnali Bhunia #3645

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # 3645 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] Cyber #Security

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Anant1711 — APPROVED** [review]

**Comment by Anant1711** [comment]
@SwarnaliBhunia Nice work!✨

**Comment by SwarnaliBhunia** [comment]
thanks!

**Comment by sushma616** [comment]
> Cybersecurity 4.5 Caesar Cipher done by Swarnali Bhunia #3645
> 
> <hr>
> 
> ## Description 📜
> 
> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
> Fixes # 3645 
> 
> <hr>
> 
> ## Type of change 📝
> 
> 
> 
> 
> - [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
> 
> <hr>
> 
> ## Domain of Contribution 📊
> 
> 
> 
> 
> - [x] Cyber #Security
> 
> 
> 
> <hr>
> 
> ## Checklist ✅
> 
> 
> 
> - [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
> - [x] I have performed a self-review of my own code or work.
> - [x] I have commented my code, particularly in hard-to-understand areas.
> - [x] My changes generates no new warnings.
> - [x] I'm GWOC'21 contributor
> 
> <hr>
> 
> 
> 
> ## Screenshots / Gif (Optional) 📸
> 
> <hr>
> 

Can u send caesar cipher project in python

**Comment by Anant1711** [comment]
> > Cybersecurity 4.5 Caesar Cipher done by Swarnali Bhunia #3645
> > 
> > ## Description 📜
> > Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
> > Fixes # 3645
> > 
> > ## Type of change 📝
> > 
> > 
> > * [x]  Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
> > 
> > 
> > ## Domain of Contribution 📊
> > 
> > 
> > * [x]  Cyber #Security
> > 
> > 
> > ## Checklist ✅
> > 
> > 
> > * [x]  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
> > * [x]  I have performed a self-review of my own code or work.
> > * [x]  I have commented my code, particularly in hard-to-understand areas.
> > * [x]  My changes generates no new warnings.
> > * [x]  I'm GWOC'21 contributor
> > 
> > 
> > 
> > ## Screenshots / Gif (Optional) 📸
> 
> Can u send caesar cipher project in python

Refer this article for script: https://www.thecrazyprogrammer.com/2018/05/caesar-cipher-in-python.html

**Comment by sushma616** [comment]
Can u please send me a caesar cipher project on python

**Pull request merged**
